### ISSUE TITLE
indicate -if exist- synonym status in fuzzy search csv output  

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1018]
having the synonym status indicated in the csv output (as in the web page output) would help the user to differentiate how related are the matching names.
for more background infos, see previous issue #996

**Comment by nickmorales** [comment]
You mean show all synonyms that are in the database for the fuzzy matched terms?

**Comment by nickmorales** [comment]
83d8d1c9f155037d52911d357808e450237a7c1b

**Comment by bauchetg** [comment]
fixed by Nick
