### ISSUE TITLE
fuzzy search displays an incorrect fieldbook error message 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1019]
After confirming the addition of batch of new accessions, casava-test displays a fieldbook related error messages and keep processing:
![screen shot 2017-05-14 at 4 45 29 pm](https://cloud.githubusercontent.com/assets/12039071/26037644/578da110-38c5-11e7-8180-fbdf476dec6c.png)

**Comment by nickmorales** [comment]
you were logged out (probably auto logged out after some time limit), but there was a typo in the alert message. 
the message was fixed in #1020
