### ISSUE TITLE
Replace plot accession function is returning with an error

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1021]
From the yambase error log:
[error] CXGN::Trial::FieldMap::replace_plot_accession_fieldMap(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "stock_relationship_c1"
DETAIL:  Key (subject_id, object_id, type_id, rank)=(83678, 68724, 76542, 0) already exists. [for Statement "update stock_relationship set object_id =? where object_id=? and subject_id=?;" with ParamValues: 1='68724', 2='83798', 3='83678'] at lib/SGN/Controller/AJAX/TrialMetadata.pm line 513

**Comment by nickmorales** [comment]
this is probably just that the stock_relationship_id sequence needs to be reset in yambase... happens when manually editing values in the database

**Comment by nmenda** [comment]
this error does not come from the sequence , it's from the unique constraint. 
Need to add a check if the subject-object relationship already exists in stock_relationship before updating the stock_id in the database with something else that is already there

**Comment by aco46** [comment]
I couldn't replicate the error in my local database as well as sweetpotato and yam test database where we saw the error.

**Comment by aco46** [comment]
close via 15df42cc4bd16b71c4198583fa564ec3b3130b03
