### ISSUE TITLE
wizard phenotype download

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1029]
Both csv and excel for fast and complete options not working...
eg. 
https://cassavabase.org/breeders/trials/phenotype/download?trial_list=[%22143%22]&format=csv&trait_list=[]&trait_component_list=[]&accession_list=[]&plot_list=[]&plant_list=[]&location_list=[]&year_list=[]&dataLevel=plot&phenotype_min_value=&phenotype_max_value=&timestamp=0&trait_contains=[%22%22]&search_type=fast

**Comment by isaak** [comment]
also phenotype download from the trial page: 
e.g. https://cassavabase.org/breeders/trials/phenotype/download?trial_list=[%22143%22]&format=xls&timestamp=0&trait_contains=[%22%22]&trait_component_list=null&trait_list=null&dataLevel=plot&phenotype_min_value=&phenotype_max_value=&search_type=fast

**Comment by nickmorales** [comment]
Should be fixed in the topic/postcomposed_cass pull request. Just needs to
be checked out and approved
