### ISSUE TITLE
retrieving trial design

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1030]
For some trials on the trial search result page the design type is shown. And when you go to the trial detail page, you get: 
-- 'There is no design data for this trial', e.g. https://cassavabase.org/breeders/trial/135?format=

**Comment by bauchetg** [comment]
For information and follow up on that issue, I copy here the slack thread:

isaak [9:58 AM] 
a  bit confusing: this trial is augmented and has 1 block and 157 replicates for 158 entries...
https://cassavabase.org/breeders/trial/458?format=

naama [1:38 PM] 
@isaak this one has 157 plots, so must be a typo in the description. @aco46 ^^

isaak [4:05 PM] 
Hi @naama: it is also that there are 150 replicate entries for the trial
some how the replicate field is populated for some trials when there is no replication, I think, for the trials, e.g. RCBD trials (edited)
https://cassavabase.org/breeders/trial/657?format=

guillaume [4:15 PM] 
@isaak, replication is populated by default with block number. First I though that was a bug however Moshood said that it is fin
If a trial is uploaded manually it may or may not contain this information as it is not a compulsory field to inform in the current upload template

nickmorales [5:58 PM] 
hi @isaak we can try to do that tomorrow


----- Today May 25th, 2017 -----
aco46 [12:53 AM] 
@isaak the trial you mentioned with 1 block and 157 replicates should be a description issue with the user who uploaded the trial like @naama highlighted.
[12:56] 
@isaak @naama @guillaume IITA requested that for RCBD the block number and replication number should be the same. So, during trial creation and upload those two fields are populated with the same information.

**Comment by lukasmueller** [comment]
* make data compulsory in the trial layout upload
* check that replication is in a sane range, field size is not out of hand, etc.?
* related tickets: #762 #760

**Comment by bauchetg** [comment]
@nickmorales  plot standards for main trial stages:
[plot_size_cassava.xls.zip](https://github.com/solgenomics/sgn/files/1881785/plot_size_cassava.xls.zip)

**Comment by lukasmueller** [comment]
have these issues been fixed????

**Comment by bauchetg** [comment]
Hi Lukas, plot standards can be entered manually.  An improved way to do it would be to define a trial type and its associated plot dimensions and spacing parameters as a configuration key.
