### ISSUE TITLE
accession list validation and upload improvements 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1035]
While validating a large accession list (>1000), missing accession may identified and sent to the "manage" "add" section to be seamlessly added:
- instead of taking the subset of missing accessions, the entire array is sent to the fuzzy search process which slows down everything.
- when the missing accessions are identified from validation step an option to create a specific list with this subset can still be offered (as in previous version). It can be desirable to save the list independently without proceeding to the upload.

**Comment by nickmorales** [comment]
#1036
