### ISSUE TITLE
phenotype dataset metadata headers

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1040]
Suggestion: if  'locationDbId', 'locationName were prefixed with 'study' to be consistent with the studyYear, studyDesign, studyName etc.., it would be easier to filter/parse metadata columns while processing dataset for analyses...

**Comment by lukasmueller** [comment]
Make it whatever is in brAPI?

**Comment by nickmorales** [comment]
in brapi the identifier for locations are always locationDbId or locationName so i don't think we should change it to studyLocationName, etc...
