### ISSUE TITLE
plots phenotype data query

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1051]
check phenotype search with a list of plots (with ids, or uniquenames) only.

this query returns only the metadata headers (no traits and phenotype values)

my $phenotypes_search = CXGN::Phenotypes::PhenotypeMatrix->new(
bcs_schema  =>$self->schema,
data_level  => 'plot',
search_type =>'Native',
plot_list   => $plots_ids,
);

my @data = $phenotypes_search->get_phenotype_matrix();

**Comment by nickmorales** [comment]
hi @isaak i added an additional test for this specific case here:
https://github.com/solgenomics/sgn/commit/38bd31aa2a603b23e0ea98b7a2648eda1323ef49

but the search seem to return correct results.

**Comment by isaak** [comment]
Hi Nick,
Are you able to get the traits and phenotype values, then? 

The query returns only the headers for me (using list of plots I created in the fixture db): 
studyYear       studyDbId       studyName       studyDesign     locationDbId    locationName    germplasmDbId   germplasmName   germplasmSynonyms       observationLevel        observationUnitDbId     observationUnitName     replicate       blockNumber     plotNumber
