### ISSUE TITLE
IITA-TMS-IBA011412 (population) has 5 different stock_id numbers

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1069]

**Comment by bauchetg** [comment]
all populations were referring to themselves we deleted them.
 stock_id | dbxref_id | organism_id |    name     |     uniquename     | description | type_id | is_obsolete 
----------+-----------+-------------+-------------+--------------------+-------------+---------+-------------
     1281 |           |           5 | TMS-I011412 | IITA-TMS-IBA011412 |             |   76392 | f
