### ISSUE TITLE
Merged accessions end up with too many stock relationships

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1073]
For example, IITA-TMS-IBA30572 ended up with 3 different female parents yesterday. TMEB419 and TMS13F1106P0009 still have multiple female parents. These can be removed manually, but it would be better to prevent in the first place.

**Comment by bauchetg** [comment]
Could be part of improvements listed in #1061

**Comment by lukasmueller** [comment]
fixed in 5ce54eee72dd948e77e9296e52c2fc2018648ecd .
