### ISSUE TITLE
Incomplete phenotyping data during trials' download 

### ISSUE THREAD

**Issue by aafolabi** [solgenomics/sgn#1075]
Trial download through trial's detail page returns incomplete phenotyping data

**Comment by nickmorales** [comment]
The phentype download dialog has a section called "Data not showing?". There you can tell it to use the complete search instead of the materialized view. Did you try that?

**Comment by nickmorales** [comment]
This is most likely because the materialized view was not refreshed.
Maybe with postgres10 we can make "complete" as the default search_type instead of "fast".
