### ISSUE TITLE
More clarity on use of uniquename and stock names in detail page

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1079]
From a user perspective the display of uniquename and stock name on accession page  is very confusing. For a few accession there may be different but most of the time they are identical.
Also, it may be helpful to:
1- hide stock name from the stock details and leave only the uniquename for display.
2- As we have synonyms, can't stock name be part of them? In this case we need to be sure synonyms can be assign to a single uniquename.
3- Is there any specific use of stock name? From the stock table it doesnt show any relationship
http://jbrowse-test.sgn.cornell.edu/schemaspy/2016/public/tables/stock.html

**Comment by lukasmueller** [comment]
Remove one of them from the page...

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/1852
