### ISSUE TITLE
accession search: allow a longer output 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1081]
Can we increase the length of search output displayed ion a single page to a thousand?
So far the longest output is a hundred which is often too low to save a complete query in a list.

**Comment by bauchetg** [comment]
The best would be to allow saving the entire output in a single list whatever the length list.

**Comment by bauchetg** [comment]
@bellerbrock @titima15 Is it the same issue as the one solved in  #1091 ?

**Comment by titima15** [comment]
@bauchetg I don't think it is the same issue.

**Comment by bellerbrock** [comment]
hi @bauchetg, I just spoke to prasad about this and it is related. the copy to list function is added, but in some cases the max 100 results per page for the table isn't enough, and users may want to add more like 1,000 results at a time to a list. We are working on a simple fix by changing a datatables param to allow up to 1,000 results to be displayed at once
