### ISSUE TITLE
"Copy Results to a List" section on "Trial Search" page is not completed, missing click buttons 

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1091]

**Comment by bellerbrock** [comment]
Thanks for catching this, I've seen this error before in the accession page. It's caused when there is a blank name in the database. It looks like that was the problem in cassavabase, the trial with id = 161 had no name. I looked in the test site, and it was named 'GSseedlingsclonalevaluation', so i updated the name in the live site and the copy to list is working again.

I'll close this issue and open a new one about preventing trials and accessions from having blank names
