### ISSUE TITLE
load trial data from Tanzania 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1096]
[DATA CHAMBEZI SIX MONTH 201617 OG _GG.xlsx](https://github.com/solgenomics/sgn/files/1091502/DATA.CHAMBEZI.SIX.MONTH.201617.OG._GG.xlsx)

**Comment by bauchetg** [comment]
@lukasmueller this needs curation from Kasele will be done coming August

**Comment by lukasmueller** [comment]
These trials still seem to be missing.... need to contact Kasele.
