### ISSUE TITLE
Merging feature page into locus page

### ISSUE THREAD

**Issue by phosmani** [solgenomics/sgn#1100]
Integrate Feature page information complementary to locus page (mRNA sequence, Genomic sequence and Related features).
Add computation prediction along with user curated function
Remove link to genome features on SGN.

**Comment by lukasmueller** [comment]
I think it would be a good idea to have the protein, cds and mRNA sequence listed on the locus page, with a link to the feature page (to not overload the locus page)

**Comment by lukasmueller** [comment]
Closed because it is a duplicate of #1399
