### ISSUE TITLE
Modify dosage file format for GBS

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1102]
Generate dosage data including REF/ALT allele, chromosome and phasing infos

**Comment by isaak** [comment]
related #1107.

**Comment by bauchetg** [comment]
[041f225](https://github.com/solgenomics/gbs/commit/69c109a3ce42b11f6c7cf5775e4c1875faaf40e2)

**Comment by bauchetg** [comment]
I did not keep the imputed vcf files (only the dosage ones) for the last build (June16), re-running the pipeline today, expect new file  in outputs 4-5 days.

**Comment by bauchetg** [comment]
Include extra information field from imputed file GT field
GT:AD:DP:GQ:DS:PL
would be now:
GT:AD:DP:GQ:GT:DS:PL
to avoid confusion second GT could renamed PT (to check if this match with vcf format conventions):
GT:AD:DP:GQ:PT:DS:PL

**Comment by bauchetg** [comment]
@nickmorales Format change is done through vcfFormatChange.pl see commit above.
Effective upload of vcf will be done separately
