### ISSUE TITLE
Display more information on 2D barcode.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1113]
-add an option to generate plot 2D barcode with display of field information and plot id encoded in the barcode.

Requested by Margaret.

**Comment by bauchetg** [comment]
If we add more metadata to the 2D barcode will it interfere with the Fieldbook format to identify the plot ID you want to go to? (Like adding pedigree string , would it conflict with the PlotID string?)

**Comment by aco46** [comment]
We can display as much information users want to see but for a barcode to be used in field book app, plotName alone has to be encoded into the barcode.

**Comment by bauchetg** [comment]
@aco46 Thanks for clarifying Alex

**Comment by aco46** [comment]
close via #1135
