### ISSUE TITLE
Need for heterosis trials in Sweetpotatobase.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1159]
CIP Ghana are establishing a heterosis trial where the cross_name will be used as accessions for the creation of a trial.
-Nick, Bryan and I discussed extensively about this. These where suggestions we can up with.
  -we could allow crosses to be used in the same way accessions are used for heterosis trial type only.
  -a section that retrieves phenotypes associated with a cross will be added to the cross detail page.
  -the section will also include trait average values across rep and trial for a cross family.

**Comment by dauglyon** [comment]
Use seedlots as a layer of extraction for these types of trials

**Comment by lukasmueller** [comment]
This is implemented by Titima - crosses and family names can be used in trials.
