### ISSUE TITLE
add ability to associate introgressions to accessions

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1165]
what would be the best way to do this? using the marker tables? @lukasmueller @nmenda

**Comment by bauchetg** [comment]
@nickmorales diagnostic markers can be a solution an other option is haplotype definition using the hapmap and related origins of haplotypes

**Comment by nickmorales** [comment]
stock_feature table could do this

**Comment by nickmorales** [comment]
need an interface to query a specific start and stop position, return the accessions that have this region, return phenotypes for those accessions
