### ISSUE TITLE
Display pedigree infos in the trial layout file

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1175]
requested by Prasad
It would benefit the breeder to have the information displayed while making selection

**Comment by nickmorales** [comment]
@bauchetg so display pedigree when a layout is downloaded?

**Comment by bauchetg** [comment]
@nickmorales yes.
Idea is to have this available on the field book too as the breeder collect its data.
This may complement the pedigree information available on barcode label.
The pedigree field can be selected by the user as an information field displayed on the fieldbook phenotyping page
