### ISSUE TITLE
Include pedigree Purdy system notation for trial layouts

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1176]
This notation may be necessary to minimize string size in the fieldbook display.
Related #1175 and #225

**Comment by bauchetg** [comment]
Some documentation (based on usda wheat program) complementary to what is provided in #225 
[Template for Germplasm records.txt](https://github.com/solgenomics/sgn/files/1170108/Template.for.Germplasm.records.txt)

**Comment by nickmorales** [comment]
trial layout can include pedigree. now it is just a matter of implementing the purdy notation described in #225
