### ISSUE TITLE
pedigree doesnt alway show cross type when biparental

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1188]

**Comment by bauchetg** [comment]
ex: 
Accession | Female_Parent | Male_Parent | Cross_Type
IITA-TMS-IBA010046 | IITA-TMS-IBA920326 | CM8710-1

Are stock relationship missing from upload or is it purposely?

**Comment by titima15** [comment]
Some data are stored incorrectly, needed to be fixed.

**Comment by bauchetg** [comment]
Thanks @titima15 , I meant in the "Manage" "Download" section

**Comment by bellerbrock** [comment]
Hey @bauchetg , I think your right with the first explanation - those crosses are missing the relevant cross type in the stock relationship table. They are normally stored as the value in the maternal relationship row.
Can we assume that all accessions with a distinct mother and father result from a biparental cross? And that those with mother only come from open crosses, and those with the same accession as mother and father come from a self?
If so we could write a data fix patch that infers the correct cross type from the parent relationships and then stores it in stock_relationship. Or we could alter the code to infer the cross type on retrieval of each pedigree row.

**Comment by bauchetg** [comment]
@bellerbrock I also think it is a fair assumption. 
1- To keep data integrity a patch may be better we could ask @pvnsprasad to validate the list of cross lacking these info before proceeding and from now on it should not be a problem as the cross type is required while uploading.
2- The idea of inferring is great but it may be good to leave it to crosses we will infer from the DB rather than cross uploads made by users ( @zacherl008:  it may be good to differentiate/store original pedigree from corrected ones in the pedigree checker)
Let me know your opinion on -2-

**Comment by titima15** [comment]
If any data are not stored in the database, I think we shouldn't "manipulate" the data, even though it looks obvious.  If users want to infer anything, they should be the one who infer the missing data (outside the database).

**Comment by nickmorales** [comment]
adding parents from the stock detail page was not able to capture cross_type until #1160 .
