### ISSUE TITLE
storing GPS coordinates at trial plots level

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1192]
@bellerbrock some bullet points from discussion
-GPS coord could be added at a plot level (for ex for spatial analysis, by linking lat/long to row/cols data).
-Figure out if fieldbook can actually transfer such data.
-In this case infos could be linked to stockprops.

**Comment by lukasmueller** [comment]
plots are defined by corners of a quadrangle, so each plot needs stock props that define these 4 (or N) points. Maybe a JSON string containing the path of the circumference (each point defined by GPS coords)

**Comment by dauglyon** [comment]
Heres a quick proposal for the plot location format (this can obviously by minified to eliminate whitespace):  
```javascript   
{
    'p': [ [lat, long], [lat, long], [lat, long] ],
    'c': [lat,long]
}  
```

- where lat/long are floats
- where p is null or a list of lat/long pairs defining the outline of a polygon such that the first and last points form the last edge* in CW order (this becomes important for 3d/spherical analysis or modeling).
    - clockwise order can be determined as follows:
        - clockwise(a) implies sum[(ei.x2-ei.x1)*(ei.y2+ei.y1) for ei in edges in p] > 0
- where c is _by default_ the centroid of p
    - centroid can be determined as follows:
        - X = sum[(Xi + X(i+1)) * (Xi * Y(i+1) - X(i+1) * Yi)] / 6 / A
        - Y = sum[(Yi + Y(i+1)) * (Xi * Y(i+1) - X(i+1) * Yi)] / 6 / A
            - where A is the signed area of p:
                - sum[Xi*Y(i+1) - X(i+1)*Yi] / 2
                - where Xn <- X0, Yn <- Y0

* so [[0,0], [0,1], [1,0]] not [[0,0], [0,1], [1,0], [0,0]]

**Comment by c5sire** [comment]
You might want to look into this: http://geojson.org/ and  https://tools.ietf.org/html/rfc7946.

**Comment by c5sire** [comment]
Sorry, didn't mean to close this ...

**Comment by bellerbrock** [comment]
Thanks @c5sire, I'd second the geojson idea. Locations are retrieved now as geoJSON points on the manage locations page, and it makes mapping them much simpler. And @dauglyon, I'm guessing the system you described for storing plots should fit very well with geoJSON polygons.

**Comment by dauglyon** [comment]
@c5sire @bellerbrock geoJSON looks great! D3 also happens to handle it well (which is definitely an upside!) It might be good then to have a plot location defined either as null, a [geoJSON Point](https://tools.ietf.org/html/rfc7946#appendix-A.1), or [a geoJSON Polygon](https://tools.ietf.org/html/rfc7946#appendix-A.3). Also, on further investigation, the centroid probably isn't what we'd want as a default `c` point (especially if we want to populate a map of trial boundaries with name lables). There is a good method for finding a visual center of a polygon using quad-trees, which has been implemented [here](https://github.com/mapbox/polylabel). That might be good to use.

**Comment by nickmorales** [comment]
@dauglyon a sample csv file that CASS has given me has the following header columns "plot_name, accession_name, plot_number, row_number, col_number, blx, bly, brx, bry, trx, try, tlx, tly" where the last columns give the corner coordinates for each plot
