### ISSUE TITLE
Downloading "field_layout" on cassavabase return a wrong file

### ISSUE THREAD

**Issue by rachealmukisa** [solgenomics/sgn#1204]
Under the design tab on Cassavabase, clicking on "Download Layout" link returns the wrong field layout.  Example is at https://cassavabase.org/breeders/trial/2860?format= the layout downloading is different from the actual layout uploaded.

**Comment by nickmorales** [comment]
@rachealmukisa what was the layout that you had uploaded?

**Comment by aco46** [comment]
No réponse from the person that gave the bug feedback. We have not also heard from anyone else about this bug.
