### ISSUE TITLE
field map feeback and improvements

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1208]
From test with musabase:
-The field map display takes very long if the field > 100's plots
-The field map template download as png is good but users usually expect more something like and excel file format (like the field layout but ordered according to row/col infos, see enclosed ex.), something that can be used as a work document essentially.
- The "[Upload trial coordinates]" remains available when coordinates are already loaded, it could be switched to a click button like "View FieldMap"
![ex_display_field_map](https://user-images.githubusercontent.com/12039071/29043952-2eaf79ea-7b8b-11e7-8cac-cca178b19eb4.png)

**Comment by bauchetg** [comment]
As well, the "field layout download" from the trial page  doesn t display optional information fields like row/cols when they are actually available  (ex: https://musabase-test.sgn.cornell.edu/breeders/trial/398 )

**Comment by aco46** [comment]
@bauchetg thanks for the feedback. Fieldmap will be improved to capture these feedbacks.

**Comment by bauchetg** [comment]
Additional metadata could be shown when mousing over the plot (i.e: plot name)

**Comment by aco46** [comment]
Thanks @GBauchet. Will be working on this when I get back.

**Comment by aco46** [comment]
I'm also concern about the length of the plot names.

**Comment by aco46** [comment]
closed via #1719
