### ISSUE TITLE
Shared lists

### ISSUE THREAD

**Issue by jeremyde** [solgenomics/sgn#121]

**Comment by nickmorales** [comment]
Were you working on this issue @lukasmueller ? If not I can take it

**Comment by lukasmueller** [comment]
Hi Nick,

I think we should improve the lists with several new features. I think it would be nice if a user could:
* open several lists at once from the list dialog
* drag and drop list elements between lists
* combine lists (using AND or OR)
* publish public/shared lists

What do you think? Maybe we can indeed start with the public list.

cheers
Lukas

**Comment by nickmorales** [comment]
Hi Lukas,
Does this make sense for the public list feature?
There will be a button for each list that when clicked causes that list to be copied into a "public" user account. Then there will be a dialog where user's can view all the "public" user's lists.

Thanks,
Nick

**Comment by lukasmueller** [comment]
That’s how I imagined it more or less. Of course users will immediately want to control who can view the published lists, but this will be for later…
Will you just add a field (or maybe there already is one) to the list table that indicates whether it is public?
Anyway, if you make changes to the database structure, you should issue a so-called db-patch. I (or Naama, as I am in the meeting) can tell you more about db-patches.

cheers
Lukas

**Comment by nickmorales** [comment]
Ok. Well it seems like there is an unused "sent_by" field that could be used in the sgn_people.list table. That could indicate if the list was shared and by who. Or we could add a "public" boolean field. What do you think Naama or Lukas?

**Comment by lukasmueller** [comment]
shared_by would be better… if it is set, it is public. We could then easily extend to shared_to (but that would limit sharing to only one person)

cheers
Lukas

**Comment by lukasmueller** [comment]
OK, sorry, shared_by is not necessary, as the list is owned by an owner in addition to being public, so the is_public (boolean) column should suffice.
cheer
Lukas
