### ISSUE TITLE
accession upload file template

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1216]
Current accession upload gives ability to specify (optionally)  a population and an Institution to a batch of accession loaded in a list.
This is not always handy as  accessions need sometimes to be loaded in bulk with a lot of (optional ) metadata including:
-synonyms
-ploidy level (cvterm  76495) see #748
-germplasm group (cvterm 76496 genome structure)
-population see #1122 #1209 and #850 
-institution
-location (if conservation bank for example)

 a back-end loading script exist: "load_stock_banana.pl" in cxgn/sgn/bin and could maybe be adapted and  interfaced?

**Comment by bauchetg** [comment]
-location code (cvterm 76494)

**Comment by nickmorales** [comment]
@bauchetg can you give a brief description of what "genome_structure" and "location_code" are? For "ploidy_level" would it be okay to store it as a number (e.g. 2 for diploid)?

**Comment by bauchetg** [comment]
@nickmorales just saw your comment: 
-Genome structure as to do with genetic groups to which belong an accession it takes into account ploidy and ancestral genome info, ex: AAA, AB, AAB
-Ploidy level is ok as a number
