### ISSUE TITLE
loading Agronomy ontology for trial treatements application

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1234]
Terms from this ontology would be required to build up factorial experiments (split plot, strip plot, etc...)
https://github.com/AgriculturalSemantics/agro
http://www.obofoundry.org/ontology/agro.html
https://raw.githubusercontent.com/AgriculturalSemantics/agro/master/agro.owl
It is in a pre-release version at the moment.
@nmenda could we test this?

**Comment by lukasmueller** [comment]
Not sure what the status is of this, is it already done or do we want to move forward with this? Otherwise we can close the ticket?
