### ISSUE TITLE
wizard updates fails on musabase.org

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1241]
Updates doesnt reflect database content changes.
From the log:
Use of uninitialized value in string eq at lib/SGN/Controller/AJAX/HTMLSelect.pm line 125.
materialized views last updated 2016-08-03 16:49:02.987008-04
Starting get trials at time Wed Aug 23 16:24:29 2017
Finished get trials at time Wed Aug 23 16:24:29 2017

**Comment by bauchetg** [comment]
Validating criteria_list
Validating query types
Validating dataref ids
Use of uninitialized value $_ in pattern match (m//) at lib/SGN/Controller/AJAX/BreederSearch.pm line 65.
Use of uninitialized value $_ in pattern match (m//) at lib/SGN/Controller/AJAX/BreederSearch.pm line 65.
Use of uninitialized value $_ in pattern match (m//) at lib/SGN/Controller/AJAX/BreederSearch.pm line 65.
Use of uninitialized value $_ in pattern match (m//) at lib/SGN/Controller/AJAX/BreederSearch.pm line 65.

**Comment by bellerbrock** [comment]
Unfortunately the refresh functions don't give very informative errors, but finally when I tried running the update manually in the db I got this error:
``````cxgn_musabase_new=# select refresh_materialized_views_concurrently();
ERROR:  permission denied for relation cvprop```
It looked like the cvprop table was in the wrong schema, so I ran ```cxgn_musabase_new=# ALTER TABLE sgn.cvprop SET SCHEMA public;```, then the update worked.

The db patches in 00073 have a fix for this, so they must not have been run yet and should be run
