### ISSUE TITLE
stock search autocomplete to include synonyms

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1244]
Stock search autocomplete only include stock names and should also cover synonyms.
This is particularly needed when the unique name of a stock is not commonly used regarding its vernacular name (ex: ITC codes in banana regarding local names)

**Comment by bauchetg** [comment]
Could the stock search aucomplete ignores plot names? This is confusing and usually generates extremely long list

**Comment by nickmorales** [comment]
the stock search autocomplete could be changed to only show stocks of the
selected stock type

On Mon, Feb 19, 2018 at 3:24 PM, Guillaume Bauchet <notifications@github.com

**Comment by nickmorales** [comment]
the stock search will search over synonyms
