### ISSUE TITLE
adapt image uploads to plot/trait based informations 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1260]
Follows previous #241 
Current images uploaded jointly with a field book file are allocated to the plot level but do not specify any trait information.
It also request to unselect the photo based trait used for collection from the trait file prior export 
We could use post-composing to load "photo based" trait types in field book.

Two additional feature would be need:
-1- A -relatively- fast images upload, considering one plot may have one or more than one image in a trial.
-2- An image visualization at the trial level? 

to be discussed...

**Comment by lukasmueller** [comment]
Hi Nick, is this implementation finished? If so, we could close this ticket?
