### ISSUE TITLE
Install DiGGer package on relevant servers.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1263]
It dependencies should be install as well.
- R.oo
- R.MethodsS3

**Comment by aco46** [comment]
Done for yam test and production.

**Comment by lukasmueller** [comment]
Isaak has fixed the package updates using the Build script. New R package dependencies need to be listed in special files (similar to the Build.PL file for Perl dependencies). Please check with Isaak how to do this, and the rest will be automatic! (if this is the non-open source package that you are using, then don't do this!!!)

**Comment by aco46** [comment]
DiGGer package and it dependences have been installed in all bases.
