### ISSUE TITLE
tool to easily "convert" a list of accessions to a list of seedlots

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1268]
could be integrated into the list tool

**Comment by nickmorales** [comment]
related to #1233

**Comment by dauglyon** [comment]
@bellerbrock Do you think this belongs in the wizard? It seems like it fits within the search pattern

**Comment by dauglyon** [comment]
Tool added in #1282. It might be good to also have it in the wizard, but the tool provides much more information than the wizard would.

**Comment by dauglyon** [comment]
fixed the last known bug to this tool in #1339
