### ISSUE TITLE
trial folders show up as trial in wizard search

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1281]
@bellerbrock: in cassavabase, while querying "trials", trial folder names such as "00_ibadan", "01_mokwa" up to "05_ubiaja" are displayed

**Comment by lukasmueller** [comment]
should probably be filtered out?

**Comment by bellerbrock** [comment]
this was fixed in db patch 00074, but the fixed version had not been run on all dbs. Ran it on all dbs and refreshed their mat views.
