### ISSUE TITLE
Brapi trials call

### ISSUE THREAD

**Issue by c5sire** [solgenomics/sgn#1289]
On sweetpotatobase it seems the brapi callL https://sweetpotatobase.org/brapi/v1/trials?active=true&sortOrder=asc

always returns 126 studies under each trial.

**Comment by lukasmueller** [comment]
should return a list of folders?

**Comment by c5sire** [comment]
It seems to me like a bug: the format is compliant with the definition but there is always the same number of study entries under individual trials. Also, the same study entries (at least the first few ones checked) under different trial ids.

**Comment by nickmorales** [comment]
@c5sire yes there was a bug. thanks
