### ISSUE TITLE
cvterm.name "crossing_trial" is associated with two different cvterm_ids

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1294]

**Comment by nmenda** [comment]
need to merge cvterms under 'trial_type' cv (generated by this patch https://github.com/solgenomics/sgn/blob/master/db/00032/AddTrialTypes.pm#L63 ) 

with terms generated under the 'project_type' cv 
https://github.com/solgenomics/sgn/blob/master/db/00079/AddGraftingCvterms.pm#L79

**Comment by nmenda** [comment]
cv.name = project_type 

cvterms to update= 
phenotyping_trial
genotyping_trial

remove crossing_trial with cv trial_type

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/1340
