### ISSUE TITLE
progeny/cross search shows different outputs 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1295]
In "search progenies" section:
When querying TMEB419 for "all progenies", we get 1,056 outputs. If we look at TMEB419 stock detail page in the progeny section, 1,835 outputs.
@titima15 Does this reflect a different information type? In which way? Or is it just a bug in the postgres query?

In search crosses section:
-a dding the number of progenies available for each crosses displayed would be useful.

**Comment by titima15** [comment]
On stock detail page, progenies of that accession are from crosses that used the accession for  female or male parent.  However, on the search progeny page, when using "all progenies", the progenies are from female parent.  I will modify the progeny search page so that it will be clearer.

**Comment by bauchetg** [comment]
@titima15 for the "search progeny" page, when using "all progenies", instead of changing the current query may we can just specify that the "all the progenies" is based on female parent?

**Comment by titima15** [comment]
@bauchetg yes, that's what Lukas suggested. I'm not going to change the query. Because it is a minor change, I am going to include that in a branch that I'm working on another issue.

**Comment by titima15** [comment]
Add more info in the titles for clarification. Closed via e4c96ef
