### ISSUE TITLE
Loading physical trial layout fails for some large trials

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1304]
Error from log when trying to load physical trial layout for DCPop Caswell Summer 2017 trial in sweetpotatobase: 

Caught exception in SGN::Controller::AJAX::TrialMetadata->get_spatial_layout "Modification of non-creatable array value attempted, subscript -1 at lib/CXGN/Trial/FieldMap.pm line 131.

**Comment by aco46** [comment]
@bellerbrock : Could you send me the file and the trial name, so I could replicate the error from here and work on it.

**Comment by aco46** [comment]
column numbers where not uploaded for the plots. It only has row numbers.
- trial is been fixed.
