### ISSUE TITLE
"Manage" -> "Download" -> "Phenotypes" query doesnt work

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1313]
from Prasad.
It returns:
DBD::Pg::st execute failed: ERROR:  invalid input syntax for integer: "" at lib/CXGN/List.pm line 199.
[error] Caught exception in SGN::Controller::BreedersToolbox::Download->download_pedigree_action "DBD::Pg::st execute failed: ERROR:  invalid input syntax for integer: "" at lib/CXGN/List.pm line 199.

Actually this download functionality is largely underused and redundant with the Wizard except that it can take different list types at once. Maybe the wizard could take more that one list as input?
In this case it may no longer be needed.

**Comment by nickmorales** [comment]
I think this is still a useful interface especially with the available public lists shown. when datasets become available those could be used here as well

**Comment by nickmorales** [comment]
#1315
