### ISSUE TITLE
Cross detail page can't be opened.

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1314]
The message indicated that  “The requested id does not correspond to a cross and cannot be displayed by this page.”

**Comment by bellerbrock** [comment]
Hey @titima15, I'm not sure why you were getting that message specifically, but I just made a pull request that better handles errors those types of errors in general. When you get a chance please review it and see if it fixes your problem!

**Comment by bellerbrock** [comment]
Ok @titima15, I see what was still causing problems for cross links on cassavabase. Commit 7dd8c12e4d2298135e116388cca18ea8a212d471 fixes it. The branch should be ready to merge pending your review!
