### ISSUE TITLE
accession uplaoding/validation seems very slow in the new version release

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1334]
"Manage" -> "Add accessions" -> "validate" validation process is long lasting (did not work for Prasad and almost 10 min for me) for a list of 100 accessions using the public list "1_12" (these accessions are now stored)

**Comment by bauchetg** [comment]
Similarly, pedigree upload are a lot slower. Could all this be connected with recent changes in the seed lot based information management?

**Comment by nickmorales** [comment]
No i dont think its related because those things have not been changed. It
seems to be running fine now. The database may have been in a transaction
because of the uploads causing a queue of queries to pile up.

**Comment by nickmorales** [comment]
#1338 increases speed of pedigree upload, which should prevent freezing of database for long periods of time.
