### ISSUE TITLE
locationName entry for some Ugandan trials

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1348]
Trials that seem conducted in different locations have the same location name entry. 
E.g.
TCC_Namulonge_2013
TCC_Namulonge_2014
TCC_Bulindi_2013
TCC_Bulindi_2014
TCC_abi_2013
TCC_abi_2014

They all have 'NaCRRI, Central Uganda'.  If they are indeed done in different locations, this same locationName entry breaks GXE interaction analysis (until you detect it and do the correction during analysis).

**Comment by bauchetg** [comment]
@rachealmukisa could you review the location infromation for these trial s?
It seems the location name included in the trial doesnt exist in the database yet, we could easily create these but we need your confirmation.
