### ISSUE TITLE
Option to re-randomize trial design if checks are clustered together

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1360]
Expected Behavior 
--------------------------------------------------------------------------
Another suggestion from yesterday's discussion with Josh from IRRI. Randomization during trial creation sometimes places checks too unevenly. When this goes uncorrected the data from the trial become less useful. One way to solve this would be to view the design with checks highlighted before saving the trial, and giving users the option to re-run just the randomization step if necessary.

For Bugs:
---------

**Comment by lukasmueller** [comment]
There is an option to not save a trial. This could be clicked and then the randomization done again?
