### ISSUE TITLE
Design a barcode type for genotyping facility

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1367]
Expected Behavior 
--------------------------------------------------------------------------
@aco46 A barcode format which can be tagged on 96 well plates.
It could work in combination with the genotyping trial tool as it does now for trial.
This may be a major asset for the next genotyping season data identification.
@pvnsprasad could you specify exact dimension of current label used if any?

For Bugs:
---------

**Comment by lukasmueller** [comment]
Genotyping trial name from genotyping facility should be on the barcode.

**Comment by aco46** [comment]
closed via #1528
