### ISSUE TITLE
Manage Locations http Error

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1369]
Expected Behavior 
--------------------------------------------------------------------------

When trying to click on the map to add a new location:

jquery.js:586 Mixed Content: The page at 'https://yambase.org/breeders/locations' was loaded over HTTPS, but requested an insecure script 'http://www.datasciencetoolkit.org/info?callback=jQuery110209280744096126035_1508176038430&_=1508176038431'. This request has been blocked; the content must be served over HTTPS.

For Bugs:
---------

#### Steps to Reproduce

Click on the map to add a new location

**Comment by bellerbrock** [comment]
Unfortunately the datascience toolkit api isn't available over https. Seems like the best solution then is to stop using it, at least temporarily. Locations can still be added without auto-filling country and elevation.

The toolkit is open source and available as a vagrant machine, so when we get a chance it may be worth setting up our own instance locally. That could cut response time and avoid this mixed content error.
