### ISSUE TITLE
Stock search test fails

### ISSUE THREAD

**Issue by dauglyon** [solgenomics/sgn#1381]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

Test in [t/unit_fixture/AJAX/Search/Stock.t](/t/unit_fixture/AJAX/Search/Stock.t) fails. I'm unclear on which test as the STDERR is a big ol' mess.

#### Steps to Reproduce

run `$ perl t/test_fixture.pl t/unit_fixture/AJAX/Search`

**Comment by nickmorales** [comment]
works for me. do you have the latest fixture?

**Comment by dauglyon** [comment]
Whoops! This is likely the issue. relevant to #1349

**Comment by dauglyon** [comment]
Yep, it runs with the latest fixture.
