### ISSUE TITLE
Design New Multi-location Trial fails at save step

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1382]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Enviroment 

sweetpotatobase-test
#### Steps to Reproduce

Manage-> Trials -> Design New Multi-location Trial

Process fails at save step. Error in error log reads: 
[error] Attribute (trial_has_plant_entries) does not pass the type constraint because: Validation failed for 'Int' with value "trial_has_subplot_entries" at /usr/local/share/website/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Exception.pm line 37

**Comment by bellerbrock** [comment]
@nickmorales Got it, just made a pull request with a fix. 

I see a lot of duplicated code between design a trail and design multilocation trial. What do you think about unifying the two tools? Maybe it's more complicated than I'm thinking, but it seems like the sort of change that would make future development and maintenance a lot easier.

**Comment by nickmorales** [comment]
Would definitely be better to consolidate that duplicated js files. Would be good to move some of that logic into controller, out of js
