### ISSUE TITLE
Selected list functions in the list manager are broken on the Manage Trials page

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1383]
Expected Behavior 
--------------------------------------------------------------------------
For Bugs:
---------
### Enviroment 

cassava-test
#### Steps to Reproduce

The list manager works fine on most pages, but specifically on the manage trials page the Delete, Make Public, Make Private don't work. And an error is visible in the javascript console:

Uncaught ReferenceError: on is not defined
    at <anonymous>:1:26

**Comment by nickmorales** [comment]
It is not showing this error for me. What environment is this and what browser

**Comment by bellerbrock** [comment]
This was originally reported by Prasad, though I'm not sure what browser he was using. I'm seeing it In Chrome, and in Iceweasel in my VM with the cache disabled.

I haven't had a chance to look at it in depth, but I do see that the batch functions call an onclick javascript function, and that the difference on the Manage Trial page is that for some reason this includes an array that starts with 'on' rather than a list id,

 `javascript:deleteSelectedListGroup([on,1295,1002])`

**Comment by bellerbrock** [comment]
Ok, i see the problem. The on click function for the list_select checkboxes is retrieving the values for every checkbox element in the dom. On the manage trials page this now also includes a 'new_trial_add_treatments_apply_to_plants' checkbox.

A fix that explictly retrieves just the values of the list_select checkboxes is ready for review and merge in above branch.
