### ISSUE TITLE
Trait submission page

### ISSUE THREAD

**Issue by dauglyon** [solgenomics/sgn#1385]
Expected Behavior 
--------------------------------------------------------------------------

A page should exist on the dbs which links (or embeds) the following Google form, which automatically creates issues in the appropriate repositories.

[https://goo.gl/forms/wR0ypdHgilPNiHpv2](https://goo.gl/forms/wR0ypdHgilPNiHpv2)

**Comment by nickmorales** [comment]
Maybe better to just make a small form in a mason file and submit it to issue using github api (like contact form)

**Comment by dauglyon** [comment]
True, I would prefer that actually, we just made the form during our
meeting. It is nice to have a spreadsheet of the requests as well though,
(not that we couldn't also generate that). There are a few options really.
I think a custom form might be best.

**Comment by bellerbrock** [comment]
A mason form would probably be better if it's just us using it. An advantage to the google form though is that it could be used more broadly - the crop ontology.org , IBP, and anyone else using these ontologies could link to it or embed it. If that's possible, it would help ensure that all new trait requests are submitted to the same issue tracker in the same way.

**Comment by dauglyon** [comment]
I just realized another reason to use the Google form is so that we can
just use a single GitHub access token for everyone and not have to worry
about teaching people to set it up if they want to add it to their own
sites.

**Comment by nickmorales** [comment]
I would vote against using a google form as a middle man. It is not hard to
set up a call to post issues to github (or they can just link to our form
instead of google's).

**Comment by bellerbrock** [comment]
Nick, are you thinking there's a security or license concern with using google forms and/or sheets as a middleman? Don't get me wrong, I like the idea of implementing our own form in mason. For one, that would make it easier to implement checks on each field to ensure that a user's newly submitted trait doesn't already exist. 

But I bet other groups using the ontology might not be comfortable simply linking to a form on one of our sites. Maybe a good compromise would be to each build our own forms, but then submit the form data to a single google sheet [like this?](https://medium.com/@dmccoy/how-to-submit-an-html-form-to-google-sheets-without-google-forms-b833952cc175)

That would ensure everyone is still populating the same fields and using the same access token. And it would preserve the google sheet itself, which could be a nice way to see all new submissions at once.

**Comment by dauglyon** [comment]
I put together a simple flask/gevent python server script that serves the form and creates the issues on github. The repo is here: [Planteome/variable-issue-submission](https://github.com/Planteome/variable-issue-submission). Currently this is running on the rtbbase VM at [submit.rtbbase.org](http://submit.rtbbase.org). We can link to this page from our sites. Other people could also host this repo (with their own github token) if they _really_ dont want to link to our sites.
