### ISSUE TITLE
Cross Wishlist error.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1387]
Expected Behavior 
--------------------------------------------------------------------------

There was an error submitting cross wishlist to ONA. Please try again.There was an error submitting germplasm info file to ONA. Please try again.

For Bugs:
---------

**Comment by nickmorales** [comment]
Only works from musabase currently. Each website will need its own form on ona to sync media files with

**Comment by lukasmueller** [comment]
Maybe a sgn_local.conf setting to disable the functionality when it is not available?
