### ISSUE TITLE
Traits list validation 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1393]
Trait list validation test seems to fail. This happens when creating field book traits file and also when trying to validate the list from the list menu. E.g. 'Ukiriguru trial traits' (public list, on cassava-test)

**Comment by nickmorales** [comment]
You should use the correct ID which now are CO_334

**Comment by isaak** [comment]
I created the traits list from the search wizard. How do you do that?

**Comment by nickmorales** [comment]
I guess the views for wizard are out of sync with the database and need to
be refreshed. You can edit your list and change the CO to CO_334

**Comment by isaak** [comment]
This is happening also on the live site.

**Comment by nickmorales** [comment]
The views need to be refreshed for the cassava databases (you can initiate
it from the wizard). it will take some time for cassavabase to complete

**Comment by nickmorales** [comment]
@isaak did you try refreshing the materialized views?
@lukasmueller also a patch could rewrite all list items that have CO: to CO_334: but this might be too intrusive

**Comment by isaak** [comment]
The materialized views was old. Refreshing it seems to fix it.
