### ISSUE TITLE
downloading genotypes fails in cassavabase and solgenomics

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#1405]
Expected Behavior 
--------------------------------------------------------------------------
seems to be ok in sgn-test
e.g. 
https://solgenomics.net/stock/647/genotypes

For Bugs:
---------

**Comment by nickmorales** [comment]
@nmenda should there be genotype data for that stock? there are some stocks in sgn with this genotype data different from in cassavabase (not in genotypeprop json) https://solgenomics.net/stock/6590/view
