### ISSUE TITLE
Pedigrees are not always completely shown

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#1406]
Expected Behavior 
--------------------------------------------------------------------------
In the current implementation, all pedigrees should be drawn completely. Certain pedigrees are truncated, such as :
https://cassavabase.org/stock/609389/view
The female parent also has a large pedigree, but is not shown. This may happen because the pedigree on the female side contains parents that are also on the male side, and there may be some code limiting the number of occurrences of accessions in the same pedigree (to avoid cycles).

For Bugs:
---------

### Enviroment 

https://cassavabase.org/stock/609389/view

**Comment by dauglyon** [comment]
Is this more urgent or can it be resolved with #1274 ? It's still in the works, but chugging along smoothly.

**Comment by bellerbrock** [comment]
Closed in #1486
