### ISSUE TITLE
Load Gerard's layer specific RNAseq data to jbrowse

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/sgn#141]
Loaded on sgn-test for user review. Waiting on feedback. Gerard wants to chnge the display but Alessandra has no experience with jbrowse.

**Comment by lukasmueller** [comment]
How is this ticket going?

**Comment by suryasaha** [comment]
Sent reminder on Jan 7. Final reminder sent on Feb 3 2015

**Comment by suryasaha** [comment]
The problem is that the SNP locations are all stored in 1 file (Peri_SNPs.gff3) and the tissues (leaf,D30,fruit) are encoded in the last field. I have spent some time trying to reverse engineer the codes but we need Gerard or Alessandra to split up the GFF file into the 3 tissue types. I can then display each SNP type in a separate track.

**Comment by suryasaha** [comment]
The SNP locations are same for all the samples, i.e. the SNPs are derived from the pooled libraries. No good way to display 3 genotypes for a SNP location on jbrowse.
sftp://surya@192.168.1.12/home/surya/work/workspace8/data/Gerard_L1/poster_Traini_SOL2013%20gb%20edit.pdf

**Comment by suryasaha** [comment]
The SNP locations are same for all the samples, i.e. the SNPs are derived from the pooled libraries. No good way to display on jbrowse. See gbrowse example
![selection_001_screenshot](https://cloud.githubusercontent.com/assets/1084749/6067093/0e025562-ad40-11e4-8dcd-53ea4b05272d.png)
