### ISSUE TITLE
selection index shows seedlots along with checks for normalizing values

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1410]
Expected Behavior 
--------------------------------------------------------------------------

If a trial has seedlots associated, they show up in the selection index tool in the "Normalize with a control" dropdown select.

For Bugs:
---------

### Enviroment 

You can see it on yambase-test with the trial "17UAC28aytBohicon"

**Comment by dauglyon** [comment]
Wait, is that the expected behavior or is that a bug?

**Comment by nickmorales** [comment]
i think it should only show control accessions there
