### ISSUE TITLE
trial phenotype deletion is very slow

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1414]
Expected Behavior 
--------------------------------------------------------------------------
Even though deletion of all phenotypes in a trial is not common, it is very slow ~1 second/phenotype to delete on cassavabase. Would be more user friendly to speed this up.

For Bugs:
---------

**Comment by isaak** [comment]
wondering if this feature is working...trying to delete one trait... 45 min later still spinning 'working'.

**Comment by bauchetg** [comment]
Recentely broken it seems, deletion does not proceed.
Something is broken, error log doesn t display progress.

**Comment by isaak** [comment]
Well, it is working. A trial data got deleted eventually. It must be very slow....
https://cassavabase.org/breeders/trial/1644?format=

**Comment by aco46** [comment]
@isaak will take a look at it. Used to be fast though. Guess something went wrong lately.

**Comment by bauchetg** [comment]
@aco46 the log do not display information on the deletion process anymore. It is hard to track whats is exactly happening.

**Comment by aco46** [comment]
@bauchetg I would work on it tonight.

**Comment by bauchetg** [comment]
Hey @aco46 you could check 14.GS.C2.CE.IK
https://cassavabase.org/breeders/trial/1644?format=
Could not get it deleted when I tried (it even takes a long time to load the page)

**Comment by isaak** [comment]
Please check with @pvnsprasad first. That trial has a new data now (re-uploaded).

**Comment by pvnsprasad** [comment]
Hi @aco46 
I have already reuploaded the data for the trial 14.GS.C2.CE.IK

**Comment by aco46** [comment]
Were you able to delete the previous assayed traits? Do you intend making any deletion?

**Comment by pvnsprasad** [comment]
I took Guillaume and Isaak Help to delete the previous assayed traits, i tried it for whole day but was not able to delete them it gave me error all the time.
Actually i am doing a quality check on the trials on cassavabase for each trait

**Comment by aco46** [comment]
Sounds good @pvnsprasad

**Comment by aco46** [comment]
Closed!

**Comment by nickmorales** [comment]
we could speed up phenotype deletion by moving the slow step: the deletion of nd_experiment entries into an asynchronous process. that way from the web it would be fast to delete the actual phenotype entries, and deletion of the nd_experiment entries can happen in the background while the user does other things. @lukasmueller does that sound reasonable?
