### ISSUE TITLE
trial comparison comments

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1419]
Expected Behavior 
--------------------------------------------------------------------------
labels are often going out of bounds in charts.
request to add non-linear fits for equation

For Bugs:
---------

**Comment by lukasmueller** [comment]
One half of the trial comparison tool has disappeared. This may have to do with the BrAPI 2.0 transition.

**Comment by MFlores2021** [comment]
Closed since is same as #4999
