### ISSUE TITLE
Changes to fieldbook photo file naming causes photo upload to fail

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1420]
Expected Behavior 
--------------------------------------------------------------------------
The fieldbook app now saves a trait name and number as part of the photo file names, for example `17PPTS24SCTT_6013_4_NCP12-0233_RootPhoto1_1_2017-11-02-12-15-00.jpg` This change is causing the photo upload to fail.

Right now the upload gets the plot name with a substring of the filename that removes the last 20 timestamp characters. Maybe a regex that grabs everything before the 3rd to last underscore will work better for the new file name format?

For Bugs:
---------

### Enviroment 

sweetpotatobase.org

**Comment by nickmorales** [comment]
maybe similar to #1260 in that uploaded images should be tied to a specific trait, and not just a generic "photo" trait

**Comment by bellerbrock** [comment]
True, at least some of the ontologies have photo traits. For the short term though I can add the quick fix.

@nickmorales it also looks the photo zipfile is being uploaded twice, in both the verify and store step. Is that expected? It takes long enough to upload these large files that if possible it'd be good to do just once.

**Comment by nickmorales** [comment]
@bellerbrock it archives the uploaded zipfile both during the verify and store step, but it only saves the individual pictures during the store step. It needs to save the zipfile during the verify step because that is when it checks the filenames match plot names in the database

**Comment by trife** [comment]
What would you suggest as a better separator?

**Comment by nickmorales** [comment]
thanks @trife. maybe you could preface each part of the name with the thing following, like OBSERVATIONUNITNAME__, __OBSERVATIONVARIABLENAME__, and __TIMESTAMP__ or if the name becomes too long that way maybe use abbreviations like OUN__ and __OVN__ and __TS__ (notice the double underscore). i don't know, i'm open to suggestions

**Comment by lukasmueller** [comment]
Is this completed?

**Comment by bellerbrock** [comment]
Yes, this is [completed(https://github.com/solgenomics/sgn/blob/master/js/source/legacy/CXGN/BreedersToolbox/UploadImages.js#L179). Image uploads now grab everything before the 3rd to last underscore to get the observationUnit name, then validate it.

The only limitation with this is that it fails if anyone puts an underscore in their trait name. It hasn't been a big issue yet, but I'll see if I can make it extra-clear in the Fieldbook docs to avoid underscores in trait names . . .
