### ISSUE TITLE
many cross property cvterms are missing from yambase-test

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1423]
Expected Behavior 
--------------------------------------------------------------------------

On yambase-test, if you go to cross detail page and try to add props, many say that term does not exist in database. Possibly could be happening in yambase as well

For Bugs:
---------

**Comment by nmenda** [comment]
these were removed by a db patch
https://github.com/solgenomics/sgn/blob/master/db/00087/UpdateNdExperimentProperty.pm

We should remove these props from the cross detail page

**Comment by aco46** [comment]
Fixed in the new crossing improvement.
