### ISSUE TITLE
Cross search should include the properties of the cross

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1428]
Expected Behavior 
--------------------------------------------------------------------------
In cross search the datatable should include all the cross properties as columns 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Needs more discussion with Nick

**Comment by lukasmueller** [comment]
I assume this is already implemented?

**Comment by lukasmueller** [comment]
As this seems already implemented, I am closing this ticket. Please re-open if needed.
