### ISSUE TITLE
Trait search add to list adds just the ID and not the trait name or '|'

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1433]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

Users and tools like the trt file creator need the name , or at least the '|', to be in the list along with the ID

**Comment by bauchetg** [comment]
@bellerbrock: this is a duplicate of #1412 i believe

**Comment by bellerbrock** [comment]
Ah, good catch. Sorry I didn't see that, I'll close this one
