### ISSUE TITLE
Add latest potato genome v4.03 to SGN

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/sgn#144]
* FTP site (done)
* JBrowse
* Blast
* Locus pages?
* Feature table

**Comment by lukasmueller** [comment]
Notes from the labmeeting: rename the chromosomes (and genes?) in the potato dataset (chromosome names are crazy).

**Comment by suryasaha** [comment]
Potato PGSC_DMv3_219_ch?? chromosomes not present in featureloc. Lots of features with corrupted uniquenames (uniquename-feature_id) and some features are also loaded multiple times. Removing v3 entirely from the DB and loading v4.03 using [bio-chado-loader](https://github.com/solgenomics/bio-chado-loader). Testing on cxgn dump first.

**Comment by suryasaha** [comment]
This issue was moved to solgenomics/issue_tracker#3
