### ISSUE TITLE
store crop cycle IDs in cross app

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1444]
Expected Behavior 
--------------------------------------------------------------------------
step1:
crop cycle IDs should be hardcoded in ODK app:
TIME: 0000073 (cycle1)
TIME: 0000074 (cycle2)
TIME: 0000075 (cycle3)

step2: 
include information update in musabase from TracT script
@mkaranja: the above IDs will be appended to the related trait scored using ODK data collection: like:
"CO_325:0000169 Bunch weight | TIME: 0000075 cycle3", although current postcomposing displays this format "Bunch weight |cycle3" .
This late format not be desirable as IDs would be needed to assign data from TracT back to musabase. To be discussed with @nickmorales 

step3:
Once musabase will be updated, the wishlist would need to contain the latest update to reflect changes in cross app (ex: cycle 1 was pollinated, cycle 1 was harvested, etc..)
So that no ambiguity would remain regarding which cycle is  currently growing in the field

to be discussed:
possibility of having multiple cycles simultaneously in the field in a pollination block (does it really occur? ?)

For Bugs:
---------

**Comment by bauchetg** [comment]
trait that may be involved from the crossing app:
number_of_flowers 
date_of_pollination 
date_of_harvest 
number_of_seeds_harvested 
days_to_maturity 
date_of_seed_extraction 
number_of_seeds_extracted 
number_of_viable_seeds 
number_of_nonviable_seeds 
days_from_harvest_to_extraction 
date_of_embryo_rescue 
number_of_embryos_rescued 
days_from_extraction_to_embryo_rescue 
number_of_embryos_germinated 
number_of_embryos_contaminated 
number_of_seeds_planted 
number_of_seeds_germinated 
number_of_progeny

**Comment by bauchetg** [comment]
should them be a cvterm/prop/syst. cvterm? Discussion from previous ticket meeting to be re-open?

**Comment by bauchetg** [comment]
-different cross names would be used (one for each cycle)
-data collected here is "not biologically" relevant to the cross, it is a property. 
these are NOT phenotypes but only props from crossing activity.
=> the json string storage (instead of cvterm) decision is the valid one

-male cycle (for pollen ) could be an other aspect, although it is not needed currently

**Comment by nickmorales** [comment]
this has been taken care of as far as i can tell. the OD cross app will name crosses like:
BT201803_(124343C1/124219) where the C1 can be C2 etx to indicate cycle.
