### ISSUE TITLE
link between seedlot creation from crosses to seedling nursery trial

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1449]
Expected Behavior 
--------------------------------------------------------------------------

1. seedlot needs to be able to have contents of cross_name OR accession_name. currently implemented only for accession_name. COMPLETED
2. from cross detail OR accession detail page, should have button to "create seedlot" with X number of seed in it. COMPLETED
3. the existing nursery/greenhouse trial creation needs to be able to accept a list of accessions OR a list of cross_names. here user can give a list of seedlots to design the trial with as well. need to be able to upload seedling nursery trials as well.
4. in seedling nursery trial user can upload phenotypes to the trial as usual. from seedling nursery some plants are chosen to continue to propagation. that is when progeny accessions should be saved in database. naming of these progeny uses cross_name001, cross_name002 etc.

For Bugs:
---------

**Comment by lukasmueller** [comment]
It seems that these things are already implemented. Closing the ticket.
