### ISSUE TITLE
graphical filtering improvements

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1455]
Expected Behavior 
--------------------------------------------------------------------------
do graphical filtering on means instead of at plot level.
allow user to export the filtered dataset (possibly save that dataset in the database somewhere).

For Bugs:
---------

**Comment by dauglyon** [comment]
The filtered dataset can currently be saved as a list. I'm going to start looking at ways to speed up the loading of the data as well by using resultsets instead of the phenotypematrix.

**Comment by dauglyon** [comment]
Switching to means also shouldnt be too difficult.
