### ISSUE TITLE
selection index

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1456]
Expected Behavior 
--------------------------------------------------------------------------

Can allow user to specify what goes into formula e.g.:
For each accession: SI = Xi * Xcoeff + Yi * Ycoeff + ... + Zi * Zcoeff
OR
For each accession: SI = ( (Xi - Xavg) / Xsd ) * Xcoeff + ( (Yi - Yavg) / Ysd ) * Ycoeff + ... + ( (Zi - Zavg) / Zsd) * Zcoeff
OR some other formula

For Bugs:
---------

**Comment by lukasmueller** [comment]
This ticket may predate the selection index tool, and may be closed.

**Comment by lukasmueller** [comment]
Let me know if this should be reopened, closing this for now as it seems already implemented in the Selection Index tool
