### ISSUE TITLE
XML sitemap

### ISSUE THREAD

**Issue by dauglyon** [solgenomics/sgn#1467]
Expected Behavior 
--------------------------------------------------------------------------

We should have an XML sitemap with update frequency information to cut down on bot traffic.

For Bugs:
---------

**Comment by dauglyon** [comment]
It looks like we will need to manually create a sitemap generator for each controller function which can resolve multiple URLs, so thats a wrench in the gears

**Comment by lukasmueller** [comment]
closing this ticket as it may be more effort than expected
