### ISSUE TITLE
Batch upload for stock synonyms. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1474]
Expected Behavior 
--------------------------------------------------------------------------
Violet and Brigitte has highlighted the fact that their progenies are renamed before planting them out in the field. This new name can be captured as synonyms to the already existing name for that progeny. Currently, we can add synonyms manually in the database. It would be helpful to have a link on the upload page for stock synonyms batch upload.

An Example;
CrossName (family name): 102575S
CrossProgenies: 10257S-1, 10257S-2, 10257S-5, etc.
NewNames: F1MK-1, F1MK-2, F1MK-5, etc. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Link on Manage Accession page and on the centralized upload page.

**Comment by bauchetg** [comment]
see #1425
