### ISSUE TITLE
Make YamTrait Ontology the default ontology on Yambase ontology browser page.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1476]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bauchetg** [comment]
@aco46 @aafolabi 
"CO_343" yam ontology is set on yam-test, on production a "CO" ontology is set and seem to be slightly different in its variable content.
Shall we update production with CO_343? What is the current reference obo file? Is it:
https://github.com/Planteome/ibp-yam-traits/blob/master/yam-trait-ontology.obo

**Comment by aco46** [comment]
Done for production and test.
