### ISSUE TITLE
Musabase Trait search page returns dataTable error.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1477]
![picture1](https://user-images.githubusercontent.com/10618260/33313026-9deef346-d43a-11e7-9b8b-476e1dab88b5.png)
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bauchetg** [comment]
@aco46 this is due to absence of a valid ontology on production, it should work on test site.
Rhainnon is here and we are working out the new version

**Comment by bauchetg** [comment]
closed via #1478
