### ISSUE TITLE
Search Wizard doesn't return list of Trait variables on Musabase test and production database. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1478]
Expected Behavior 
--------------------------------------------------------------------------
Even when the materialized view was updated.

For Bugs:
---------

**Comment by bauchetg** [comment]
same reason as for #1477

**Comment by bauchetg** [comment]
[2d14590](https://github.com/solgenomics/sgn/commit/2d14590707408ac7ccd588ab3fbac4bd5d8bd21a)
[b90d4fb](https://github.com/solgenomics/sgn/commit/b90d4fb13fa07e13fef8b4c643d1cea8b37665b2
)
[b884445](https://github.com/solgenomics/sgn/commit/b884445023770a678b7e0bbeeda3b2cbadae83cc)
[393b1ce](https://github.com/solgenomics/sgn/commit/393b1ceab995491aea606676a736b9240561abef)
