### ISSUE TITLE
Genbank sequence import does not work on SGN locus page

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#1508]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

#### Steps to Reproduce

 Tried to associate gen bank accession AY497475 with locus Solyc01g081060
 https://solgenomics.net/locus/110982/view

Errors out "Genbank is not available"  but I am pretty sure it is...

**Comment by nmenda** [comment]
EUtils seems to work intermittently 
eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=$GBaccession&rettype=xml&retmode=text

trying to find a more stable solution for fetching GenBank records

**Comment by nmenda** [comment]
next site update should have the fix in cxgn-corelibs , but only works when the NCBI server works properly
