### ISSUE TITLE
Creating phenotyping spreadsheet returns an error on Cassavabase.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1532]
Expected Behavior 
--------------------------------------------------------------------------
Error returned is "An error occurred creating a phenotype file."

For Bugs:
---------

**Comment by isaak** [comment]
[error] Caught exception in SGN::Controller::AJAX::PhenotypesDownload->create_phenotype_spreadsheet_POST "malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/SGN/Controller/AJAX/PhenotypesDownload.pm line 66."

**Comment by aco46** [comment]
phenotype download controller
$VAR_DUMP1 = [
               3393
             ];
[error] Caught exception in SGN::Controller::AJAX::PhenotypesDownload->create_phenotype_spreadsheet_POST "malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/SGN/Controller/AJAX/PhenotypesDownload.pm line 66."

**Comment by aco46** [comment]
Resolved. Missing a patch.
