### ISSUE TITLE
upload/update PMID/DOI through accession batch upload

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1535]
from previous pull request on  #1514 

Expected Behavior 
--------------------------------------------------------------------------
We could add "publication DOI" (ex: DOI: 10.1038/ng.3845) and/or  "PubMed ID" ( ex: PMID: 28416819) as optional columns to reference a stock to an existing publication in the database.
These IDs are used in add_publication.pl when adding new publications to the DB(data being stored in pub, pub_dbxref pubabstract and pub_author tables)
This will be very handy to update stocks with associated literature and loci metadata (ie: introgressions).
If you want to check an example, I loaded the DOI and PMID examples to cxgn_cassava (hapmap data).

For Bugs:
---------

**Comment by nickmorales** [comment]
@bauchetg you mean the publications here https://cassavabase.org/search/pub_search.pl ?
Maybe this search should be linked from the Search tab instead of via the Profile page?

Uploading DOI or PubMed for an accession would probably link via table stock_pub

**Comment by bauchetg** [comment]
@nickmorales yes adding it to the search table can be handy.
Regarding DOI/Pubmed I meant adding a related column field to the accession batch upload

**Comment by lukasmueller** [comment]
I think this can be added to the additional fields in the accession upload. Please re-open if I am wrong :-)
