### ISSUE TITLE
add option to suppress the phenotypes of multiple plots at a time. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1540]
Expected Behavior 
--------------------------------------------------------------------------
HeatMap additional option.

For Bugs:
---------

**Comment by nickmorales** [comment]
also i think that the entry in phenotype_prop should capture more info. in the value field you could include a timestamp and a username

**Comment by aco46** [comment]
@nickmorales I agree with you. It makes sense to include timestamp and username.

**Comment by aco46** [comment]
also add an optional comment field.

**Comment by lukasmueller** [comment]
Outlier management will be implemented on the dataset level.
