### ISSUE TITLE
add option to exclude suppressed plot phenotypes during phenotype download.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1542]
Expected Behavior 
--------------------------------------------------------------------------
It would be necessary to add an option for suppressed plot phenotypes to be excluded during phenotype downloads and in most analysis pages. 

For Bugs:
---------

**Comment by nickmorales** [comment]
@bellerbrock can you update the materializedview to join to phenotypeprop for type_id of "phenotype_outlier"? If you're fullview can include a column for this field with the value in phenotypeprop that would be great.

**Comment by bauchetg** [comment]
@aco46 @nickmorales 
If I understand correctly, we the implementation leaves ability to users to perform targeted deletions in datasets?
If so, this ability of removing phenotypes outliers should be associated to a relevant statistical filtering (i.e 95% confidence interval) and not be based on someone's arbitray decision.
The subsequent output could be stored as a filtered data set but this should not affect the raw data.
In general, outliers should be prevented through Filedbook trait definition (min, max, trait type, etc...) and verification step when uploading.
If there is really deep need for this "manual editing" we may want to restrict it to curators.

**Comment by bauchetg** [comment]
Related issue: #1361

**Comment by aco46** [comment]
@bauchetg : The idea according to request was to flag some plot values as outliers if the values are wrong or higher than what was expected (only the breeder decides to suppress). This does not delete or remove the phenotype value. One can not assign minimum and maximum values to all traits via the fieldbook. Trait like root or tuber weight, will be difficult to assign a range within the fieldbook and if in any case it is defined, it should be done by the user. In that case it's not general, and may not be applied to all materials or trials. 

One thing that might be confusing though, is the fact that I called them outliers! We could look for something more general to reflect general use cases. 

We should probably restrict it to the owner (curator) of the trial if not already done. There was an option provided for the user, should he/she decides to download the trial phenotypes with or without the suppressed values.

The suppressed phenotype is tracked along with the timestamp and the user that suppressed it. We could also add an optional description input box for users.

I'm sure in the future, analysis pipeline will detect possible outliers after doing some descriptive analysis and give users the option to exclude them before proceeding with the main analysis.
