### ISSUE TITLE
we should have a patch that add row and column numbers to already existing trials in the database.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1544]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bauchetg** [comment]
Hello Alex, good idea, just to check:
Do you mean that would be applied to all trials that are without coordinates?
Or is it regarding a given list of them for which coords. can be somehow recollected?
In the first case I would avoid to had defaults coords to trials without any relevant infos that can be misleading for further interpretation.

**Comment by nickmorales** [comment]
@bauchetg i think Alex meant applying it to all trials without row and column info. the necessity for doing this is to enable use of the heatmap tool for visualizing and curating phenotype values. users can always overwrite the "default" row and column info with the real info if it is available.

**Comment by bauchetg** [comment]
@nickmorales make sense, however I would flag/document all trials with defaults coordinates as it can be totally misleading for other purposes (ie: spatial analysis in a single or multi-environment).

**Comment by nickmorales** [comment]
maybe it is a safer approach to not actually save the "default" row and column numbers with a patch, but to generate them on the fly for these tools for trials without row and column info (enabling the tools to work) and indicate to the user that they should upload the real info.

**Comment by bauchetg** [comment]
That s a great idea that would prevent corrupting original data.

**Comment by aco46** [comment]
@nickmorales : it looks good and even more convenient to just generate the row and column number on the fly while viewing tools that uses it. we also have an implementation that allow users delete and reupload row and column number for any trial. But on the long run, we want breeders to see how relevant rows and columns numbers had become. I think it would be confusing for a user if row and column is generated on the fly while clicking on the fieldmap or heatmap. It has become important for breeders to include that information to trials in the database. Generating and saving a default row and column numbers using the block information, will be a step in the right direction.

**Comment by aco46** [comment]
@bauchetg : the row and column numbers by default, are usually generated using the block number of the trials. Each block becomes and a row and the number of plots in that block becomes the number of column. We can only do this for trials with block numbers.

**Comment by bauchetg** [comment]
@aco46 make sense. Just be sure this is common practice across the different institutes. It is risky to make such assumption (again, adding false info would just generated noise in a spatial analysis context). Sorry for being so picky :-).

**Comment by aco46** [comment]
@bauchetg I wasn't thinking of the generated row and column numbers to be used for analysis purposes (since the breeders did not provide it themselves) but for the purpose of viewing those tools that uses row and column numbers. Definitely, if used for analysis, it may not represent the true laying of the plots in the field. In this case, it would be safer to go by @nickmorales suggestion.

**Comment by bauchetg** [comment]
All clear then! 👍

**Comment by aco46** [comment]
This wouldn't be necessary. Row and column numbers now generated on the fly while viewing heatmap.
Addressed via PR #1564
