### ISSUE TITLE
Better handle clonal generations in database

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1547]
Expected Behavior 
--------------------------------------------------------------------------
Sweet potato breeders keep close track of a material's 'generation', or the number of seasons the material has been used out in the field since it was grown from seed or last cleaned of virus. This is important in order to account for reduced yield in higher generations due to greater virus load.

We don't have a great way of tracking different generations in the database yet. So far the NCSU program has entered many accessions by both their absolute name (ex. 'Beauregard'), as well the different generations of the accession they've used in each trial (ex. 'Beauregard_G2','Beauregard_G10'). This has the advantage of maintaining the distinction between generations, but it then makes it harder to retrieve all data regardless of generation and breaks all the links to important stock relationships and properties. For example even if 'Beauregard" has a pedigree in the database, it won't be possible to retrieve that pedigree for 'Beauregard_G2'

Assuming this is an issue for other breeding programs too it would be good to find a solution that maintains the distinction between the phenotypic measurements without needing to create separate accessions. Maybe generations could somehow be handled with seedlots?

For Bugs:
---------

**Comment by nickmorales** [comment]
Seedlots would definitely work for this. You would have a single accession called Beauregard and then create seedlots called Beauregard_G2, Beauregard_G10 that are linked to the accession.
Then when you create a trial, the accession for the plot would be Beauregard, but the seedlot for the plot would be Beauregard_G2.
Then all the pedigree and phenotyping and genotyping info is maintained to what is happening.

**Comment by bellerbrock** [comment]
Thanks Nick! That makes a lot of sense. I'll suggest they handle generations this way and see how it goes

**Comment by nickmorales** [comment]
Alright keep us posted. Better to fix this before any new accession names
are added to the db.
