### ISSUE TITLE
brapi maps position call does not filter by linkageGroups 

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#1552]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
brapi/v1/maps/34/positions?linkageGroup=5 lists all the linkageGroups

Note there is also a problem with the page size; the call only lists the first ten or so, instead of pageSize number.

**Comment by nickmorales** [comment]
Can you try linkageGroupId. Not sure if it is implemented
