### ISSUE TITLE
Manual link in About section should point to new manual

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1555]
Expected Behavior 
--------------------------------------------------------------------------
By moving the manual documentation into the git repo, we now have a better manual available at http://solgenomics.github.io/sgn/
Should the old Manual link be replaced with this one

This just means adding the link in each of the sites mason repos

For Bugs:
---------

**Comment by dauglyon** [comment]
Changed in:
cassava solgenomics/cassava#27
yambase (already correct)
musabase solgenomics/musabase#7
sweetpotatobase solgenomics/sweetpotatobase@aa0b5aea6645f679ea3abc7528edc3cfa4b675db
cassbase solgenomics/cassbase@fd4a432f5f3abcc1af5daf31076bd2e55e03ce17
template solgenomics/template#1
