### ISSUE TITLE
trial creation pop up display can be confusing

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1581]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

"Number of replicates (required): " and "Block size (required):" are misplaced, they should be just below "Design Type: "

Additionally, if they are very much needed, the simultaneous presence of "accession", "seedlot" and "field map" sections lower the readability.
Maybe having some kind of "click on" sub menus would simplify the first view?

### Environment 
"Manage" -> "Field trials"

#### Steps to Reproduce

![screen shot 2018-01-24 at 11 24 21 pm](https://user-images.githubusercontent.com/12039071/35370866-96da5766-015e-11e8-9e0e-ad6595babf8a.png)

**Comment by aco46** [comment]
change trial design popup menu to tabs?

**Comment by bellerbrock** [comment]
I stumbled on [this design advice](https://medium.com/commonux/how-to-design-a-form-wizard-b85fe1cc665a) while looking for inspiration for improvements to the search wizard, but ti might be more applicable here. 

In particular, I liked the idea of separating long forms into logical groupings and then presenting them in a stepper. Each step would include a back button and a visual track of previous and upcoming steps, but only present the input fields for one step at a time.

 For trial creation steps could be `Description` (Name, location, dates, etc.) -> `Basic Layout` (Design type, accession list, control list, block #) -> `Advanced Layout` (seedlots, treatments, custom plot names)  -> `Review and Save` (Randomization, etc)

**Comment by bauchetg** [comment]
see #420 and #1199 as well

**Comment by bauchetg** [comment]
to avoid confusion we need to  add in the design type dropdown menu  acronyms for "complete random block" (CRD) and "complete block" (RCBD)

**Comment by isaak** [comment]
Since there is no space issue, why not spell out the entire names 'completely randomized design'  for CRD and 'completely randomized block design' or 'randomized complete block design'  for RCBD and remove any ambiguity.

**Comment by nickmorales** [comment]
has anyone started working on this?
