### ISSUE TITLE
analyzed results upload

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1586]
Expected Behavior 
--------------------------------------------------------------------------

there needs to be a way to upload processed results like BLUPS/LSmeans. these results could come from analysis of various trials, so these relationships should be maintained.

For Bugs:
---------

**Comment by aco46** [comment]
we can have a small analyzed ontology for BLUP and BLUE that can be combined with an ontology variable to form a new composable traits. These willl then be used in uploading analyzed trial result.

**Comment by bauchetg** [comment]
Statistical outputs are rich, in this regard the stato ontology project is a promising solution: http://stato-ontology.org/:
It covers most model parameters estimates and test types. Issue being stato releases (1.3) are in owl format and thus require a convertion to .obo
<img width="1018" alt="screen shot 2018-02-09 at 10 15 18 am" src="https://user-images.githubusercontent.com/12039071/36020245-509d9e4a-0d82-11e8-8fcb-2a5c287a0690.png">
see #1613 as well

**Comment by bauchetg** [comment]
See ongoing discussion and addition to stato here:
https://github.com/ISA-tools/stato/issues/63

**Comment by nickmorales** [comment]
there are tools to convert OWL to OBO apparently:
robot convert --input foo.owl --output foo.obo
https://github.com/ontodev/robot/

**Comment by nickmorales** [comment]
could we use a small subset from that stato ontology? at least to get things moving a little bit

**Comment by proccaserra** [comment]
@nickmorales conversion to OBO using robot tool fails (tried by both  @bauchetg and myself). I have contacted the developers of the tools for their help. @bauchetg @nickmorales  If this turns out to be blocker, what information do you need for loading into the system? would a csv file with stato ID, stato class name, stato definition, be  enough ?  best.

**Comment by proccaserra** [comment]
@nickmorales @bauchetg update:
conversion problem resolved but some post processing of the file is needed.
best

**Comment by lukasmueller** [comment]
This is implemented in the Analysis Framework. Closing the ticket.
