### ISSUE TITLE
trial page unified graph/scatter/heatmap display?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1596]
Expected Behavior 
-------------------------------------------------------------------------
How is phenotype data sourced? It seem to be different between the graph/heatmap.
Could heatmap source the same way as graph/scatter (#1587)?
In general it would be of interest to visualize the same trait in different ways using a single menu.

For Bugs:
---------
@aco46: for example heatmap display is quite slow
usually it seems to take time to retrieve the trial data

**Comment by aco46** [comment]
-It now uses the same source as other tools.
-it also generates on the fly row and column number.
I'm currently working on a Branch that has these fixes.

**Comment by bauchetg** [comment]
thanks Alex!

**Comment by aco46** [comment]
Addressed in #1574

**Comment by aco46** [comment]
closed via #1609
