### ISSUE TITLE
Wizard search showing accession count discrepancies

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1598]
Expected Behavior 
--------------------------------------------------------------------------
For Bugs:
---------

From Prasad: 
If you select the iita as the breeding program,then select the year say 2014, then trial type say AYT,
you will get the number of accession as 882
But if you select the trails instead and make them as list, and then again try to start the search with list of trials and pick the accessions then you will get only 219 accessions

**Comment by bauchetg** [comment]
see as well #1457

**Comment by bellerbrock** [comment]
After looking at this more closely it is expected behavior. 

The smaller number **219** in the second query is the number of accessions planted in IITA's 2014 Advanced Yield Trials. The larger number **882** in the first result is because that query is asking a subtly different question. It's asking "What is the set of accessions that have been used by IITA **AND** have been used in 2014 **AND** have been used in at least one Advanced Yield Trial?" 

The accession **50395**, for example, is returned in the first query but not the second because it has been used in many IITA trials **AND** was used in twice in 2014 (14geneticgainUB and 14geneticgainIB) AND has been used in Advanced yield trials (18.CMSSurveyVarieties.AYT33.IB, 18.CMSSurveyVarieties.AYT33.IK, 92AYT19NpDA, 94AYT19NpST, 95ayt79grIB, 96ayt15ictKU, 97ayt70colchiIB, 97impgermpIB, 99ayt101colchiIB, 99ayt67dpIB). But it did not appear in any IITA 2014 Advanced Yield Trials.

Creating the list of 2014 IITA Advanced Yield Trials first, then using it to retrieve accessions is the better approach. In the future perhaps we could remove the need for the list step by adding more panels to the wizard.
