### ISSUE TITLE
move solGS to use site tmp dir because of potential clobbering problem

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#161]

**Comment by lukasmueller** [comment]
there is a function for that in the codebase, you can use something like:
$c->path_to($c->tempfiles_subdir("solgs"))
which will create the path to the tempdir, with a solgs dir inside it.

**Comment by isaak** [comment]
fixed in https://github.com/solgenomics/sgn/commit/31285b1466203603fdebaef3c5c7a2946eb7c0e5
