### ISSUE TITLE
Additional ANOVA output feature.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1613]
Expected Behavior 
--------------------------------------------------------------------------
Agre has requested a similar histogram on the trial detail page to be generated using the BLUP mean values from the ANOVA analysis.

For Bugs:
---------

**Comment by bauchetg** [comment]
@aco46 I would suggest the BLUE/BLUP values to be on the same histogram.

**Comment by isaak** [comment]
When trial design allows, BLUEs (as opposed to just averages) should be an option in trial comparison and selection index.

I working on functions to retrieve the BLUEs to plugin in any tool.
