### ISSUE TITLE
Yambase login is broken in live and test site.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1620]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
CGI invocation failed: DBI connect('dbname=sandbox_yambase;host=db3.sgn.cornell.edu','web_usr',...) failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections at /usr/local/share/website/cxgn-corelibs/lib/CXGN/DB/Connection.pm line 370.
 at /usr/local/share/website/sgn/cgi-bin/solpeople/login.pl line 10.

**Comment by aco46** [comment]
increased max_connections to 200 in postgresql.conf

**Comment by dauglyon** [comment]
This is probably my fault as I'm doing many simultaneous BrAPI calls against yambase
