### ISSUE TITLE
calendar features

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1627]
-- In discussions today, people requested: (1) reminder emails of upcoming events (not sure if this already exists); (2) In case of a series of events with definite interval (in a pipeline), if time table of an event changes, to shift downstream events automatically. Or at least be asked if downstream events should be shifted.

**Comment by bauchetg** [comment]
see #876

**Comment by wolfemd** [comment]
![screen shot 2018-03-07 at 12 08 51 pm](https://user-images.githubusercontent.com/17029153/37106793-b3dc2480-2200-11e8-9373-a46237b91b54.png)

Something like this? A Gantt chart!

As in https://www.teamgantt.com/, for example.

**Comment by lukasmueller** [comment]
Duplicate of #876
