### ISSUE TITLE
Barcode handling for crosses using Fielbook 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1628]
Expected Behavior 
--------------------------------------------------------------------------
IITA uses Fieldbook   for crossing blocks (see #970).
Current use has limitations to generate adhoc crosse barcodes for the pollinated flower (same use case as btract for musabase)
Request: Is there a possible way of dealing with the same label printing approach as in btract  using field book?

->  A trick for short term is to use the multicat trait category in Fieldbook to collect male and female plot information when performing a cross within accesion clusters (group of accessions) 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Fieldbook will be able print barcode labels soon. The tool that should be used for crossing purposes will be the new Intercross app.

**Comment by titima15** [comment]
Done
