### ISSUE TITLE
Implementing seed inventory upload

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1630]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Make this compatible with the verify app from the field book group

**Comment by bauchetg** [comment]
see #973 as well

**Comment by titima15** [comment]
Right now the one who logs in is automatically assigned as the operator for that seed lot transaction.  Need to store additional inventory personnel who actually checked the inventory.

**Comment by titima15** [comment]
@nickmorales I checked with Trevor, they just use seed_id as identifier.  When they check inventory, they don't have accession or cross info.

**Comment by nickmorales** [comment]
ok i'm using this as the template for what come from "verify" app

![image](https://user-images.githubusercontent.com/7028512/37298523-e440d1c6-25f6-11e8-937a-8434b0cb15d8.png)

**Comment by nickmorales** [comment]
ok i'm using this as the template for what comes from the "verify" app
![image](https://user-images.githubusercontent.com/7028512/37298563-04666ea2-25f7-11e8-95f2-aaab18799497.png)

**Comment by titima15** [comment]
Are you going to implement for csv format for now?

**Comment by nickmorales** [comment]
yes i'll do csv for this one since it appears the format comes out of the app as csv
