### ISSUE TITLE
Trial detailed page missing pheno data percentage summary shows outliers

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1645]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Missing data percentage displays negative percentage when dataset is nearly complete.
@pvnsprasad in https://cassavabase.org/breeders/trial/3165?format=
Is the RCBD design correctly assigned? it looks like an augmented design
#### Steps to Reproduce

https://cassavabase.org/breeders/trial/3165?format=
<img width="741" alt="screen shot 2018-02-26 at 7 44 03 pm" src="https://user-images.githubusercontent.com/12039071/36683244-242afc72-1b2e-11e8-97bb-6124e6fba92f.png">

**Comment by lukasmueller** [comment]
This seems to have been fixed.
