### ISSUE TITLE
ANOVA does not output when pheno data is available

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1656]
Expected Behavior 
--------------------------------------------------------------------------
https://musabase-test.sgn.cornell.edu/breeders/trial/409?format=

For Bugs:
---------

**Comment by isaak** [comment]
installed R package phenoAnalysis.

**Comment by nickmorales** [comment]
there is some issue... https://musabase-test.sgn.cornell.edu/breeders/trial/409

**Comment by isaak** [comment]
the problem is related to job queuing: https://gist.github.com/isaak/9acae8911d2827c949943ca6b50e8e53

**Comment by bauchetg** [comment]
seems to affect the correlation calculation too:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/12039071/36943721-f55fda46-1f9e-11e8-9061-919bb66b6fea.png">

**Comment by bauchetg** [comment]
fixed, was a torque configuration issue on musabase-test
