### ISSUE TITLE
cassava sites: genotype data dependent tools broken

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1663]
e.g. genotype search/download from the Wizard, PCA, solGS

Error:
QUERY: SELECT trial_id, trial_name FROM public.genotyping_protocolsxtrials JOIN public.trials USING(trial_id) WHERE genotyping_protocol_id IN ('3') GROUP BY trial_id, trial_name  ORDER BY 2
DBD::Pg::st execute failed: ERROR:  relation "public.genotyping_protocolsxtrials" does not exist
LINE 1: SELECT trial_id, trial_name FROM public.genotyping_protocols...
                                         ^ at lib/CXGN/BreederSearch.pm line 153.
[error] Caught exception in SGN::Controller::AJAX::BreederSearch->get_data "DBD::Pg::st execute failed: ERROR:  relation "public.genotyping_protocolsxtrials" does not exist
LINE 1: SELECT trial_id, trial_name FROM public.genotyping_protocols...
^ at lib/CXGN/BreederSearch.pm line 153."

**Comment by lukasmueller** [comment]
Is this related with the changes that Bryan made (and has rolled back for the moment, I think?)

**Comment by isaak** [comment]
Yes. Is the roll back supposed to have fixed the problem? The problem persists, anyway.

**Comment by bellerbrock** [comment]
@lukasmueller An easy fix to this is to remove the jsonb genotype values from the materialized_genoview, then rebuild them. Unfortunately that solution will then limit what will be possible for the genotype search feature, unless we curate and cast the genotypeprop values themselves to jsonb. What do you think is the best solution?
