### ISSUE TITLE
Increase readbility of the "Manage" menu

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1669]
Expected Behavior 
--------------------------------------------------------------------------
From the workshop: options in "manage" section can be overwhelming, maybe we could collapse a few of them which are largely overlapping.
Example:
-**> Regarding data collection/uploads:**
In "Manage" -> "Phenotyping" we have:
[Upload Fieldbook Database File] [Upload Spreadsheet]
[Create Fieldbook Layout File] [Create Fieldbook Trait File]
[Create Spreadsheet] 
In "Manage" -> "Fieldbook":
Field Layout Files | [New]
Trait Files | [New]
In "Manage" -> "Upload":

**-> Regarding barcode generation:**
In "Manage" -> "barcodes" we have:
-list based input 
-pre-templated barcodes formats
In "Manage" -> "labels" we have:
-list based input
- design section
 @aco46 do you think we could migrate the preset design you created into the dataset object? 
This way we could have a single "Barcode/label design" section

-> User roles:
This section could be only displayed to curators as most of it s content overlapps with sgn people in the search

For Bugs:
---------

**Comment by aco46** [comment]
@bauchetg I would work on migrating those preset design into a dataset object that can be sourced and used on the label designer page.

**Comment by bauchetg** [comment]
-Regarding the "Generate barcode labels for plots or plants or accessions in this trial." on trial detail page: This interface can be simplified and be "fool proof" by:
- Setting "Enable 2D Barcode For FieldBook" as a default  (so many errors made!)
- Source the "Printing Format (Optional)" in the same list as for the label designer
- Minimize the "printer settings" section

**Comment by lukasmueller** [comment]
I tweaked the manage menu in Cassavabase. Resolves some of these issues but not all.
