### ISSUE TITLE
trial detail page phenotype correlation

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1675]
Expected Behavior 
--------------------------------------------------------------------------
-Specify which correlation calculation is implemented (Spearman?)
-Get correlation values overlay in the matrix display
-Download the correlation matrix as picture
+Trait names could use current synonyms from ontology

For Bugs:
---------

**Comment by isaak** [comment]
7206887

**Comment by isaak** [comment]
#1692
