### ISSUE TITLE
Display improvements for data sharing 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1676]
Expected Behavior 
--------------------------------------------------------------------------
To ease data sharing among community of users, several actions can be taken:
-For transparency, as we have a log display for uploads, there should be one for data downloads
-At the account registration, user should at least provide their affiliation
-When downloading any data a pop up could remind user that data is under the Toronto agreement for prepublication.

For Bugs:
---------

**Comment by bauchetg** [comment]
upload logs should show to logged in user only

**Comment by bellerbrock** [comment]
Agree that this is important. I just went to show a user that we at least have trial download logs working and realized they are not set up for some sites and appear broken for those that have them.

To fix the existing logging we should set a value for `trial_download_logfile` in all conf files. 
Then specify values for  `user_id` and `trial_download_logfile` on creation of a new CXGN::Trial::Download object and run `$self->trial_download_log()` in the build method.

In a new and improved system with a public display there is interest in seeing not just the username but also the user roles / affiliation and contact info for the downloading user. And in tracking not just trial downloads, but also detail page views, and downloads of accession, cross, and pedigree data.

**Comment by nickmorales** [comment]
related to #1522 
i think we decided on a table in sgn_people schema to track user views, downloads, uploads.
there should be an object like CXGN::People::Activity with functions to easily read and write activities into that table.

**Comment by nickmorales** [comment]
before download, they should select what the data is being used for and maybe provide a description

**Comment by lukasmueller** [comment]
downloads are logged I think.
