### ISSUE TITLE
Cross tree page crashes when refreshing it

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1678]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
The refresh function randomly crashes on cross tree page
### Environment 

cassava-test
#### Steps to Reproduce
"Manage" "Crosses" "refresh"

![screen shot 2018-03-06 at 12 45 33 pm](https://user-images.githubusercontent.com/12039071/37075969-65be4e56-21e5-11e8-963a-2e12ceed2af3.png)

**Comment by titima15** [comment]
I couldn't reproduce the problem. Have you tried to refresh the tree again?

**Comment by titima15** [comment]
closed via bf1c7b2
