### ISSUE TITLE
Adding progenies from a cross doesnt generate subsequent pedigree

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1681]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
When adding progenies to a specific cross it does not not add automatically the subsequent pedigree
### Environment 

"Manage", "Cross"
https://cassava-test.sgn.cornell.edu/cross/772826
Looking at "TZ-101", one of the parent of the above cross:
https://cassava-test.sgn.cornell.edu/stock/771925/view
@titima15 progenies are not showing accordingly, is it a bug or a feature?

There is an error displayed about datatables:
<img width="848" alt="screen shot 2018-03-07 at 8 03 46 am" src="https://user-images.githubusercontent.com/12039071/37074590-a1d5350a-21de-11e8-8fad-95fc1c5def1e.png">

**Comment by titima15** [comment]
It should add to the pedigree as well because no change in the stockprop table.  I will take a look.

**Comment by titima15** [comment]
@bauchetg found the problem.  It is a bug that exists since the old version and I did't see it.  Thanks for reporting the issue.  I will fix the problem.

**Comment by titima15** [comment]
Fixed, closed via 34af338
