### ISSUE TITLE
ability link tissue sample level to plot level without plant level

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1684]
Expected Behavior 
--------------------------------------------------------------------------
While collecting the CBSD necrosis on roots, breeders can collect up to 100 (!) data points per plot, bulking the harvest roots.
To collect data they usually  create traits like:
CBSD root necrosis-root1, CBSD root-necrosis-root2,...CBSD root-necrosis-root100 which usually ends up saturating the fieldbook  trait file (max. 64 columns).
An alternative could be to have the ability of associating tissue samples directly to the plot and compute average from that.
This approach may be of interest for other traits.

For Bugs:
---------

**Comment by wolfemd** [comment]
This is part of the reason their datasets don't go straight from field book to DB. They don't know in advance how many roots there will be to score. For now, they score all roots... so you couldn't plan how many tissue samples. Could that be accommodated without a field book mod?

**Comment by nickmorales** [comment]
The fieldbook does not allow observation units to be created on the fly, but it would be nice if this was possible. Certainly the "direct database phenotyping" that we have could let you create tissue samples on the fly and have them directly linked to plot,plant, accession, etc. Requires internet access for the direct phenotyping.

**Comment by nickmorales** [comment]
To "skip" the plant level you could just make 1 plant per plot, and then
make the tissue samples. Would that work?

**Comment by bauchetg** [comment]
@nickmorales thanks but could not we just associate the tissue prop directly to the plot id like we do with plant entries? This would generate a standard number of tissue entries per plot which may not exactly the same from plot to plot but breeders said they would be ok with that

**Comment by bauchetg** [comment]
@nickmorales  having a single plant would be very confusing. Or may be we can have that single plant and hide it to the user. Proportion of data points vary according to trial stage but as long the can set the number themself to its max (say 150 root per plot) they dont mind leaving empty rows in the file if it it less

**Comment by nickmorales** [comment]
We could maybe streamline the interface so that they could easily create
tissue samples for plots, but on the backend it is a pretty complicated web
of relationships and it might be easier to maintain the plot to plant to
tissue sample order. Any ideas for how that interface would look and where
it would be?

**Comment by bauchetg** [comment]
So far I was thinking to have it next to the current tissue option on the trial page.
Interface could be similar current tissue one but without the need to specify the tissue type for each element. Something similar to "Add plant" and specify the amount.
The risk being to be too specific.

**Comment by wolfemd** [comment]
I'll just add: currently, they don't keep track of which plant roots come
from. However, for analysis, this would be *very *beneficial as we can
treat roots/tissue samples as properly nested within plants (they belonged
to same root system and thus should be correlated). So maintaining the
Plot-->Plant-->Tissue hierarchy would be ideal!

**Comment by nickmorales** [comment]
@bauchetg can we close this?

**Comment by bauchetg** [comment]
Agree with @wolfemd  tissue hierarchy is ideal.  Breeder's reality is however different. 
They usually don t keep track of which plant are roots coming from due to the intense work load. 
Discussing with them a target study could include plant level but probably not in all cases.

**Comment by bauchetg** [comment]
@nickmorales  the 1 plant per plot, and then make the tissue samples is convenient solution
