### ISSUE TITLE
Plot/Phenotype-DNA matching

### ISSUE THREAD

**Issue by wolfemd** [solgenomics/sgn#1686]
Expected Behavior 
--------------------------------------------------------------------------

After downloading trial data, inevitably I need to match plots/clones whose names come as the cassava base consensus name, with DNA (GBS) samples whose names do not use the same conventions. 

Curation is certainly a work in progress. Will continue to be.

Need access via DB to the currently available or "official" matches to use. This will help us curate.

**Comment by bauchetg** [comment]
For future sample this will be covered by #973
For previously sampled data:
[correspondance_db_igd_numbers_syns_genoprop.zip](https://github.com/solgenomics/sgn/files/1790337/correspondance_db_igd_numbers_syns_genoprop.zip)
Need more curation

**Comment by wolfemd** [comment]
Right! Sorry, you had shared that to me before. Needs a lot more curation. Will this eventually become an "official" list either downloadable from the DB or used internally?

**Comment by bauchetg** [comment]
@wolfemd could you share here the file you mention in the QC meeting?

**Comment by wolfemd** [comment]
This one is for IITA: https://drive.google.com/open?id=1CU0AIMmqMDBAXSq8bcwGhlDBKaKz9fJL
This one for NRCRI: https://drive.google.com/open?id=1m1Y7nBzOkA_Sp3gI0teEh0vtSjlwZB_9

Haven't made one for NaCRRI as their names are pretty easy. I will eventually. Somo is in charge of TARI, so I also haven't done theirs.

I can share a simpler, CSV format if you prefer, but this R data.frame has more info.
