### ISSUE TITLE
Additional use case to Calendar tool.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1695]
Expected Behavior 
--------------------------------------------------------------------------
Breeders would want an optional ability for the Calendar tool to directly display the harvest date of a trial when given the number of days a trial would be in the field.

For Bugs:
---------

**Comment by bauchetg** [comment]
@aco46 this is a duplicate of #876 where harvest date is one of the requested props

**Comment by aco46** [comment]
@bauchetg thanks.
