### ISSUE TITLE
Handling of NIRS data and spectrum.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1696]
Expected Behavior 
--------------------------------------------------------------------------
Breeding programs generating NIRS data and spectrum, would want those spectrum associated to their samples in the database. The idea would be be to have the individual spectra saved in the database as meta-data and a link provided on the stock detail page for the individual stocks.  

For Bugs:
---------

**Comment by bellerbrock** [comment]
The plan from the 'NIRS Hackathon' on Feb 15th is to store NIRS spectra in a new table called md_json. Then link them to a single nd_experiment through a linking table and nd_experimentprop. Then all phenotypes in the pheontype table that are derived from the spectra can be linked to the single nd_experiment.
Proposed columns for the new md_json table are md_json_id, type_id, and value (jsonb)

**Comment by bellerbrock** [comment]
Example file from NCSU program, using WInISI and ISIscan: https://drive.google.com/file/d/18rKxPXfdaG1HZCzaT4zPOS4iSKf1t9Xu/view?usp=sharing

**Comment by jmh579** [comment]
Example file from SCiO, in format of direct download from the SCiO server:
https://drive.google.com/file/d/1znSNNAbEVBphf62TQmSH3e1h0fESOxjW/view?usp=sharing

In this example, the user input the trial name ("SCiO_test_2019"; top left next to "name") and sample names ("User_input_id" column). The name of this column can change based on user preferences and additional columns of user information can be added during data collection. 

Columns starting with "spectrum_" are used for analysis, while those starting with "wr_raw_" and "sample_raw_" are discarded (used for the calculation of the values in the "spectrum_" columns). Wavelength of each column can be calculated by adding the number directly after "spectrum_" to 740 (for example, first column of spectra, "spectrum_0 + 740" is 740nm, "spectrum_1 + 740" is 741, etc) for a range of 740-1070nm in 1nm increments. 

Each row represents a separate scan, in this case three per sample. I've been recommending 3+ scans per sample but the number can vary, as each scan is the result of a separate button push by the user.

I've been encouraging users to scan Cassavabase-generated plot barcodes in the user input column for easy sample identification and matching, but can change my recommendation based on what would be best on the Cassavabase side. 

Please let me know if you have any questions or need more examples.

**Comment by bellerbrock** [comment]
Thanks Jenna! It will be very helpful to have this example.

And yes, the plot name is the best identifer to use as long as the SCiO software can handle it.

**Comment by bellerbrock** [comment]
Addtions to the plan after yesterday's discussion:

Make specific SCIO parsing plugin based on the standard download format, also one for ISIscan.

Include spectroscopy protocol (device model) selector in the upload workflow.

When storing key:value pairs in json put all the spectral values in their own nested object for simple retrieval. For the SCIO format ignore all columns that come after the spectra, and process spectra column names into simple numeric keys. For example '741' in place of 'spectrum_1+740'.

There is significant overlap/similarities between NIRS data and genotyping data. It could make a lot of sense to model new nirs tools on exisiting geno tools.

**Comment by bellerbrock** [comment]
Add download option to accession page using accession list

**Comment by bellerbrock** [comment]
Notes from 2nd meeting
- Integrate [Jenna's R code](https://github.com/jmh579/SCiOAnalysis), perhaps using[ mixed model R code](https://github.com/solgenomics/sgn/compare/topic/modern_mixedmodels2#diff-6c912737cbbcd359138bc4f33da41f32) as a model
- Run filter and aggregate measurements on upload. File archived, aggregated measurements stored. 
- Produce a file based on accession/ plot names, ground truth/ lab mesurements, to feed into the prediction tool
- Ontology distinguish between lab measurements and predictions (different methods). Finer grained differences between predictions (model parameters used) stored within metadata of analysis trial? Document software version as a part of this

**Comment by bellerbrock** [comment]
Note re. RTBfoods - they will have nirs data in [JCAMP-DX format](http://cedadocs.ceda.ac.uk/999/1/JCAMP-DX_format.html)

**Comment by bellerbrock** [comment]
Here is the [proposed NIRS upload format](https://docs.google.com/spreadsheets/d/1Qkd3ZmPI2SxBzV2byj9hNYP36bPonj1k7-zchxmWGE0/edit?usp=sharing) for tabletop machines, based on the SCiO format but with some modifications based on RTBFoods discussion. NOt finalized yet, the relevant project leaders in RTBFoods are reviewing it.

**Comment by bellerbrock** [comment]
Notes from meeting 7/10
Add search / aggregate by trial or accession for spectral data
Add download option in winisi format
Add way to plot curves / visualize uploaded data.
