### ISSUE TITLE
More specific seedlot transactions

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1699]
Expected Behavior 
--------------------------------------------------------------------------

we need more specific seedlot transactions to keep track of the complete history of the seedlot:
moving between locations
sprouting
rotting
seed increase
seed viability
virus sterilization

For Bugs:
---------

**Comment by dauglyon** [comment]
Is there a "trash" seedlot, or would rotting just be transfered to a null seedlot?

**Comment by dauglyon** [comment]
also seed increase seems like a trial type and not a transaction edge type

**Comment by nickmorales** [comment]
yes maybe it should be a different name so that it doesn't get confused
with the seed increase trial type. something like seed addition

**Comment by nickmorales** [comment]
seedlot transactions have a description associated with them. the description is specific to the action being done.
