### ISSUE TITLE
label designer zebra output .zpl format alternative for genotyping trials

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1702]
Expected Behavior 
--------------------------------------------------------------------------
Through the new EIB initative, IITA and other national programs get supplied zebra-like printers:
TSC printer type TSC 310, see details here: http://www.tscprinters.com/index.php?cmsid=32&pro_id=20092
After testing it doesnt seem to take the .zpl format from Zebra.
Good news is we can get by using the custom format from the label design and generate a .pdf
In addition to this, project provides for lab work sticky labels in small formats (2in x 1 in) side by side like this:
![20180313_155204](https://user-images.githubusercontent.com/12039071/37349393-99948f06-26d6-11e8-8348-15189f8554f6.jpg)

@bellerbrock is it feasible to have  the label designer defining such printing areas so that it prints plate label in a zigzag manner?

For more information I include links to the corresponding printer documentation:
http://www.tscprinters.com/cms/upload/download_en/TA200_user_manual_E.pdf
http://www.tscprinters.com/cms/upload/download_en/TSPL_TSPL2_Programming.pdf

For Bugs:
---------

**Comment by bauchetg** [comment]
In addition to existing human readable customizable fields
"genotyping project name"
"plate ID" 
"genotyping plate ID"
"user name" 
would be needed. 
This is all linked to the recent PR #1637 for the genotyping plate submission

**Comment by bauchetg** [comment]
Hello @bellerbrock plate barcode printing looks good, enclosed a test:
[iita-mas-ng-me-0001-WTIG5.pdf](https://github.com/solgenomics/sgn/files/1824726/iita-mas-ng-me-0001-WTIG5.pdf)
Only missing fields seem to be:
"Genotyping Project name" (and possibly "Genotyping Facility")

**Comment by bellerbrock** [comment]
Ok, thanks for the feedback! "Genotyping Project Name" and "Genotyping Facility" aren't showing up by default because they are being stored in projectprop and nd_experimentprop, separate from the layout. But I'll should be able to add them on as additional design options.

**Comment by bauchetg** [comment]
Right, that would be great, thanks Bryan.
