### ISSUE TITLE
stock barcode images seem to not work for names with slashes

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1705]
Expected Behavior 
--------------------------------------------------------------------------

http://nelsonlab.sgn.cornell.edu/barcode/trial/NEL+stock+132639+(18AN_18AN+Ear+Rot%2FTraits_rep2_10NN0753_2016)/stock_qrcode

For Bugs:
---------

**Comment by aco46** [comment]
fixed via #1985 
Requires URI::Encode module.
