### ISSUE TITLE
adding plant entries throw an error on yambase.org

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1715]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
While adding plant to plots process stops on a particular plot (1033)

### Environment 

yambase.org
#### Steps to Reproduce

From trial:
https://yambase.org/breeders/trial/252?format=

<img width="876" alt="screen shot 2018-03-15 at 4 38 08 pm" src="https://user-images.githubusercontent.com/12039071/37473863-5b09291e-286f-11e8-9911-b9fc1ba85203.png">

From log:
An error occurred creating the plant entities. {UNKNOWN}: Can't call method "cvterm_id" on an undefined value at lib/CXGN/Trial/TrialLayout.pm line 381. at lib/CXGN/Trial.pm line 1801:

From Trial.pm line 1801:

    eval {
        $self->bcs_schema()->txn_do($create_plant_entities_txn);
    };
    if ($@) {
        print STDERR "An error occurred creating the plant entities. $@\n";
        return 0;
    }

    print STDERR "Plant entities created.\n";
    return 1;

**Comment by nickmorales** [comment]
some patches were not run. when you update a site and you do a git pull make sure to check if there are new patches being pulled in. if there are just run them so that these kind of errors dont happen

**Comment by bauchetg** [comment]
patch update solved it, thanks @nickmorales
