### ISSUE TITLE
Seedlot current count remains 0 after seedlot is added.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1730]
Expected Behavior 
--------------------------------------------------------------------------
Not sure if this is a feature or a bug. 
-Breeders would want to see the current count of a seedlot reflect  the seed transaction number. 
-the current count field is only updated when a transaction is added to the seedlot.

For Bugs:
---------

**Comment by nickmorales** [comment]
When I create a new seedlot it shows the count and weight that was entered
as current count and current weight. Not sure why it is not doing that for
you?

**Comment by aco46** [comment]
This was actually reported by the sweetpotato program in Ghana. I also view that particular seedlot and the current count wasn't reflecting the number of seeds in the seedlot. Maybe something is wrong that I can't debug for now. See example link: https://sweetpotatobase.org/breeders/seedlot/125293

**Comment by nickmorales** [comment]
i would ask them to try again, because i just tried it there and it works

**Comment by aco46** [comment]
Okay @nickmorales I would ask them to try again.

**Comment by aco46** [comment]
Ticket closed. Works fine!
