### ISSUE TITLE
Add the ability to change a seedlot content when it has not been used in a transaction.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1731]
Expected Behavior 
--------------------------------------------------------------------------
Breeders would love to change the content of a seedlot immediately after creation, if the wrong stock was used by error.

For Bugs:
---------

**Comment by nickmorales** [comment]
it is possible to change (i think it should work) the seedlot contents from the seedlot detail page -> click edit seedlot details. it will not let them change the seedlot contents if the seedlot has more than just the initial transaction.

**Comment by nickmorales** [comment]
@aco46 this is implemented already i think

**Comment by aco46** [comment]
Thanks @nickmorales should have checked if that was already associated to any transaction. Will close the issue.
