### ISSUE TITLE
seedlot deletion needs to delete stock owner first

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1732]
Expected Behavior 
--------------------------------------------------------------------------

prevents seedlot deletion from working

For Bugs:
---------

**Comment by aco46** [comment]
@nickmorales we observed that if a seedlot is uploaded without an en_experiment (breeding program and location), it makes some features that depend on retrieving any of those not to work.

**Comment by aco46** [comment]
To delete a seedlot, I had to delete the row from phoneme.stock_owner before deleting from stock table.

**Comment by nickmorales** [comment]
Oh i thought it was impossible to add or upload a seedlot without a
breeding program and location?

**Comment by aco46** [comment]
They added a seedlot without the program and location. I had to delete from the backend. I'm not sure how that happened.
