### ISSUE TITLE
set barcode printing ability from genotyping trial page

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1737]
Expected Behavior 
--------------------------------------------------------------------------
Hello @aco46 can we give the same printing ability as what we have for the field trial detail page
<img width="880" alt="screen shot 2018-03-20 at 1 30 28 pm" src="https://user-images.githubusercontent.com/12039071/37655570-ff83a742-2c45-11e8-8f18-6af8f7de5858.png">
but for genotyping trial?
https://cassava-test.sgn.cornell.edu/breeders/trial/3839
where 
plate id (= trial id)
plot id (= plot name, this can be used when collection is done using individual eppendorf tubes for ex.)

For Bugs:
---------

**Comment by aco46** [comment]
Sure @bauchetg we can have it on that page.

**Comment by bauchetg** [comment]
closed through #1875 
Maye require some additional formatting option later
