### ISSUE TITLE
genotyping trial creation page: plot list and plate view

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1738]
Expected Behavior 
--------------------------------------------------------------------------
Current trial genotyping trial creation setting only takes accessions as input list
plot/plant are needed as possible input sources.

When going to field, it is desirable to have a printable plate view format (could be used similarly as a fieldmap).

For Bugs:
---------

**Comment by nickmorales** [comment]
Hi guillaume, the genotyping trial design where you select a list should
accept lists of type "tissue_samples", "plots", "plants", or "accessions"

On Tue, Mar 20, 2018 at 8:57 AM, Guillaume Bauchet <notifications@github.com

**Comment by bauchetg** [comment]
@nickmorales correct. It did take it on my local but could not take old plot list i had, created a new one and it worked as well.

**Comment by aco46** [comment]
@bauchetg we could make the plate view downloadable or have it display like the field map with an option to download the spreadsheet format

**Comment by bauchetg** [comment]
@aco46 an option to download the spreadsheet format would be great. Current plate view is good as it offers hyperlinks to original content for each sample

**Comment by bauchetg** [comment]
closed with #1875 #1949 #1841 #1782
