### ISSUE TITLE
label designer/barcode crash with very large trials

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1742]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
from @rachealmukisa 
With a trial containing about 6000 plots both "manage"  -> "label design" and "manage" -> "barcode" show some issues.
This is a common uses cases as for seedling nursery (can contain > 25 000 entries!)

### Environment 

cassavabase
#### Steps to Reproduce

https://cassavabase.org/breeders/trial/3697?format=
-1- label designer seem to time out:
![screen shot 2018-03-21 at 8 51 52 am](https://user-images.githubusercontent.com/12039071/37701591-dfb0d3f4-2cef-11e8-9ad5-409b24e5c490.png)
-2- barcode generation from trial page times out too

Solution: splitting the large plot set into subsets of 1000 each
-1- When feeding label designer with a plot list of a 1000 (see public list : "PVitA_plots_1-1000")
it gives:
![screen shot 2018-03-21 at 10 03 50 am](https://user-images.githubusercontent.com/12039071/37701739-6a529376-2cf0-11e8-91fd-9076070902c3.png)
-2- barcode page handles it well

Additional issue is that plot list are not numerically sorted, this request users to do it in excel
this is mentioned in #1710

**Comment by bellerbrock** [comment]
@bauchetg  Woah, those are crazy numbers! Do they ever group plants in a seedling nursery by cross name, then give accession names only to the small number that end up selected? Naming 25000 new accession each year could get out of hand fast . . .

I don't think there's much room to speed up the pdf generation, at least not for 100+ page files. But I'll take a look at the error - it should be possible to use the 1000 plots at a time solution.

**Comment by nickmorales** [comment]
@bellerbrock they would not create named accessions for these seedling nursery trials. they would create plots that are linked to a cross name (not named accessions). related to #1449

**Comment by bauchetg** [comment]
@nickmorales good point @bellerbrock it wont be implemented for that trial size, but for GS trial it is surely going to be. The current one we have is 5600 accessions.

**Comment by bellerbrock** [comment]
@nickmorales That makes more sense to me. In fact in an ideal world a seedling nursery wouldn't involve accessions at all. Ideally it could just be designed with crosses - one plot per cross (or cross seedlot), containing all the seedlings from that cross. 

@bauchetg I'll see what I can do for huge trials like that, but I don't envy whoever has to print and use 5600 labels. Even at 30 per page that would mean 187 pages!

**Comment by bauchetg** [comment]
@bellerbrock you are absolutely right. This is current solution for NextGen GS trials at Nacrri using available labels. Give your support to @rachealmukisa !
Hopefully new solutions will come soon with different  label types.

**Comment by nickmorales** [comment]
generating pdf causes the VM to run out of memory for large pdfs. would it be possible to limit a pdf to 1000 labels and create many pdfs?

**Comment by bellerbrock** [comment]
@nickmorales implemented your idea in https://github.com/solgenomics/sgn/pull/2638/commits/7daa4573f3e58fa0347bdf4cd9db850929ea4ef4
