### ISSUE TITLE
Uniqueness is not enforced for population names

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1745]
Expected Behavior 
--------------------------------------------------------------------------

Duplicate populations have been accidentally added to sweetpotatobase because it is not enforcing uniqueness.

For Bugs:
---------

### Environment 

sweetpotatobase.org
#### Steps to Reproduce

[17ELIT](https://sweetpotatobase.org/stock/127981/view) and [17ELIT](https://sweetpotatobase.org/stock/127980/view)

There is also a duplicate population [17 Elite Nursery](https://sweetpotatobase.org/stock/127982/view) (same members) with a different name. Might also be useful to enforce unique membership as well to prevent this sort of duplication.

**Comment by lukasmueller** [comment]
I can't see this in the live site... Did you fix it? The issue is that we should probably work with the uniquename here, not the name, which is not enforced for uniqueness.
