### ISSUE TITLE
Genotyping trials show in the Field trial tree

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1751]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
https://cassavabase.org/breeders/trials/
![screen shot 2018-03-22 at 1 16 34 pm](https://user-images.githubusercontent.com/12039071/37770244-108d121e-2dd4-11e8-9b6e-8d1b570c3bdd.png)

**Comment by nickmorales** [comment]
Do we want to use the same tree on the manage genotyping page? (instead of the accordian thing?) of course it would only show genotyping trials on the manage genotyping page.

**Comment by bauchetg** [comment]
That would be great! we can replace the leaf logo by something like:
![erlenmeyer-flask_318-40674](https://user-images.githubusercontent.com/12039071/37777262-63fb0af6-2de7-11e8-845b-86e7eb4ce273.jpg)

**Comment by bauchetg** [comment]
well, smaller...

**Comment by nickmorales** [comment]
ok i would really prefer to use one of these icons https://getbootstrap.com/docs/3.3/components/#glyphicons

**Comment by bauchetg** [comment]
sure it was just an example!
