### ISSUE TITLE
plate layout should include wells set a "blank"

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1759]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

cassava-test
#### Steps to Reproduce

When generating plate template from cassavabase and specifying which wells should be included as blanks in "Well information"
These are not included while downloading the layout, ex:
https://cassava-test.sgn.cornell.edu/breeders/trial/3882?format=

**Comment by nickmorales** [comment]
hmm it should show like in this test i just made
https://cassava-test.sgn.cornell.edu/breeders/trial/3884?format=
that was with a list of 38 accessions and i set A02 as the blank in the
form.

On Fri, Mar 23, 2018 at 8:31 AM, Guillaume Bauchet <notifications@github.com

**Comment by bauchetg** [comment]
@nickmorales I see your point, Blank should in the list.
Then when you download theplate layout excel file it only keeps informed well (see screenshot below), I though the other would be set as empty rows and keep all 96 rows. But maybe a feature more than a bug.

Actual main issue is when you use a list of plots (the solution id your field is not barcoded...) it does not remain numerically sorted (see #1710), thus you end with a plate layout that may be very hard to use in the field (plots are not ordered), see example here:
https://cassava-test.sgn.cornell.edu/breeders/trial/3886?format=

![screen shot 2018-03-23 at 5 20 43 pm](https://user-images.githubusercontent.com/12039071/37841026-eb30554e-2ebe-11e8-9de4-2072f4652cf1.png)

**Comment by nickmorales** [comment]
BLANK was not in the list, the list had 38 elements but not BLANK. notice that the layout it generated has 39 elements because i specified A2 as a blank well.

good point about the order between the list and what is generated not being maintained.
