### ISSUE TITLE
login error on cassavabase and multiple display bugs

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1762]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Login on cassavabase was showing a 501 error this morning with the following log:
error] Caught exception in SGN::Controller::CGI->CGI_search_2fmarkers_2fmarkerinfo_2epl “Can’t flush stdout: No space left on device at /usr/local/share/website/local-lib/lib/perl5/Catalyst/Controller/WrapCGI.pm line 233.”
[error] Caught exception in SGN::Controller::CGI->CGI_forum_2freturn_comments_2epl “Can’t flush stdout: No space left on device at /usr/local/share/website/local-lib/lib/perl5/Catalyst/Controller/WrapCGI.pm line 233.”

Did not know exactly  which dir may need to be cleaned up... 
We fixed it after restarting several times

In addition:
-Field trial tree doesnt display (it does run on the same tag on test site)
-Genotyping trial upload fails silently

**Comment by bauchetg** [comment]
Seem that production disk space is full...
<img width="346" alt="screen shot 2018-03-26 at 11 24 02 am" src="https://user-images.githubusercontent.com/12039071/37901608-ad347e46-30e9-11e8-9c9d-1b6fb75e08b1.png">
@suryasaha @lukasmueller 
Any advices on dirs to clean up?

**Comment by bauchetg** [comment]
It seems that production disk space is full @suryasaha @lukasmueller 
<img width="346" alt="screen shot 2018-03-26 at 11 24 02 am" src="https://user-images.githubusercontent.com/12039071/37901664-dc37f434-30e9-11e8-9e0e-b953297b2383.png">

**Comment by nickmorales** [comment]
@bauchetg maybe clear out the log files in /var/log/sgn/

**Comment by bauchetg** [comment]
@nickmorales  
remove error.log and access.log: >100G indeed!
It fixed it, thanks!

**Comment by nickmorales** [comment]
there was a debug statement turned on that may have caused the huge logs. i commented it out in #1763 if you can merge that @bauchetg
