### ISSUE TITLE
SOP for sites update

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1781]
-- to ensure all dependencies (Perl, R,...) are installed in the systems during site updates. 
-- for a start: https://github.com/solgenomics/sgn-devtools/blob/master/git/sgn_update (this updates all git repos, installs Perl and R dependecies)

**Comment by lukasmueller** [comment]
see https://bugs.sgn.cornell.edu/trac/cxgn/wiki/SiteUpdates
