### ISSUE TITLE
customize plot number doesnt reflect in plot name structure.

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1787]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
While using custom plot numbering these do not reflect in the plot name structure
### Environment 
cassavabase

#### Steps to Reproduce

Ex: in RCBD  “101 in plot number but “1001” in plot name
Ex2: in Augmented design, plot number is fine in new plot name but is not at the end (change variable space)

**Comment by aco46** [comment]
closes via #2082
