### ISSUE TITLE
ANOVA fails with generic error on sweetpotatobase.org

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1793]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by isaak** [comment]
Hi Bryan,

Fixed with installation of the latest phenoAnalysis R package.  

E.g., trial: https://sweetpotatobase.org/breeders/trial/161?format=, trait: weight of vines.

If you encounter more errors, please add the link to the trial and mention the trait.

**Comment by bellerbrock** [comment]
@isaak Looks good, and will do!
