### ISSUE TITLE
there should be an option to upload crosses and create seedlot at the same time

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1795]
Expected Behavior 
--------------------------------------------------------------------------

currently these two activities are implemented as completely separate steps (first upload crosses and their crossing information, then upload the seedlots that come from the crosses).
@aafolabi recommends to allow a combined upload

For Bugs:
---------

**Comment by titima15** [comment]
After discussion in the meeting, we concluded that it would be cleaner to upload new crosses first, then use those cross unique ids to upload seedlots.
