### ISSUE TITLE
Z-scores for evaluating accession performance

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1806]
Expected Behavior 
--------------------------------------------------------------------------

Potato breeders involved in the National Chip Processors Trials use 
 this fairly advanced database for analytics https://potatoesusa.mediusag.com/programs/ncpt/analytics

One nice feature it has that could be useful in our databases is the use of z-scores in heat maps, to visualize deviations from the population mean.

For Bugs:
---------

**Comment by isaak** [comment]
Hi Bryan,

This JS library has a method for z-score calc: statistics/simple_statistics

I have an implementation of it here: https://github.com/solgenomics/sgn/blob/master/js/solGS/normalDistribution.js. May be you can use it or modify it suit your purpose as well.

**Comment by isaak** [comment]
Perhaps this is addressed through the mixed model tool (BLUP, BLUE estimates) and GS breeding value predictions.
