### ISSUE TITLE
Faster pedigree retrieval and/or show working animation while loading

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1807]
Expected Behavior 
--------------------------------------------------------------------------

Lots of pedigree data have been loaded into sweetpotatobase recently. The new pedigree viewer is a big hit, but users have been confused when it takes a long time to show up after the accession detail page has loaded. Can we speed up the pedigree retrieval, maybe using the same method as the download?
 And/or show a working animation while its loading?

For Bugs:
---------

**Comment by dauglyon** [comment]
Can you give me an example stock where this is happening?

**Comment by nickmorales** [comment]
this one takes a few seconds https://sweetpotatobase.org/stock/54156/view

**Comment by dauglyon** [comment]
@nickmorales @bellerbrock It looks like I forgot to set the pageSize >10 so it is making too many calls one after another. It's a quick fix: #1828
