### ISSUE TITLE
Strange Errors in Trial Upload Process 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1822]
Expected Behavior 
--------------------------------------------------------------------------

Jeremy at NCSU has run into an issue when uploading existing trials. If there is an error in his file, the workflow does not allow him to go back. When he then reloads the whole page and tries again with a fixed file the trial name is no longer available - the (incomplete) trial has already been created. Then, when he goes to delete the incomplete trial it doesn't disappear, but the link to the trial detail page returns an error.

For Bugs:
---------

### Environment 

sweetpotatobase.org
#### Steps to Reproduce

Happens with 17OFYT00080WLM / https://sweetpotatobase.org/breeders/trial/1196?format=

will attach the upload file when I receive it.

**Comment by nickmorales** [comment]
if you can update the sweetpotatobase sites it might solve it. also tell
him to try clearing his browser cache if it happens again (after you've
updated)

**Comment by bellerbrock** [comment]
@nickmorales ok, I manually deleted the extra trial entry and it looks like recent merges have solved the remaining problems.
