### ISSUE TITLE
trial page breaks for specific trial(s)

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1823]
At least for a trial:
https://cassavabase.org/breeders/trial/135?format=
[error] Caught exception in SGN::Controller::BreedersToolbox::Trial->trial_info "Can't use string ("Something went wrong retrieving "...) as a HASH ref while "strict refs" in use at lib/CXGN/Trial/TrialLayout.pm line 288."
TRIAL ID = 135
TRIAL INIT...

**Comment by nickmorales** [comment]
I think it would be ideal if these trials were reloaded into the database.
Their layouts are not right in the database.

**Comment by nickmorales** [comment]
maybe to give more info about this: the "correct" way to save layouts in the database is to link the plots all to the same nd_experiment entry. there was an old loading script that apparently loaded the plots to different nd_experiment entries for every plot.

**Comment by lukasmueller** [comment]
How many trials are loaded the wrong way?
