### ISSUE TITLE
Additional cross properties for SPBase.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1824]
Expected Behavior 
--------------------------------------------------------------------------
Number of seed germinated and Number of Seed Sown.
-requested by CIP Ghana. 

For Bugs:
---------

**Comment by bauchetg** [comment]
@titima @aco46: I would rather see these as ontology terms no? easier to retrieve and analyze?

**Comment by titima15** [comment]
@bauchetg I think it should not have any problem to store values in json. It can be easily retrieved for the downstream analysis.
@nickmorales Do you have any opinion on this?

**Comment by aco46** [comment]
@bauchetg : they are measured at cross level just once and not associated to the cross progenies.

**Comment by bauchetg** [comment]
Thanks @aco46 , @titima15 sold me the concept!

**Comment by aco46** [comment]
Done for live and test database.
