### ISSUE TITLE
label designer returns pdf blank page 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1830]
Expected Behavior 
--------------------------------------------------------------------------
Using any trial, but as ex:
https://cassava-test.sgn.cornell.edu/tools/label_designer
trial: 14ayt15SK
format US letter pdf
Optional: "Prasad2" (public list)
Label format: custom
Returns a single,  blank pdf page
<img width="1111" alt="screen shot 2018-04-16 at 5 28 11 pm" src="https://user-images.githubusercontent.com/12039071/38833426-dac500ca-419b-11e8-9051-069a011abdf1.png">

Cleaned the cache and tried to see if it is a acrobat viewer config issue, not clear so far...

For Bugs:
---------

**Comment by bellerbrock** [comment]
@bauchetg I'm seeing it too, it's fine in the last release so must be related to a recent merge. I'm taking a look

**Comment by bauchetg** [comment]
thanks a lot Bryan! we are labeling a seedling nursery tomorrow.

**Comment by bellerbrock** [comment]
Hey @bauchetg, no problem. There is somthing strange going on where the default of 'All plots' under the new plot filter (in edit additional settings) is being set to blank when a saved design is loaded. For the time being you can fix this by clicking on addtional settings and re-selecting 'All plots'. It also doesn't seem to be an issue with labels designed from scratch.
I'll look into resolving the behavior with saved designs and make a pull request with the fix.

**Comment by bauchetg** [comment]
thaks for the tip, it rolls now
