### ISSUE TITLE
 large trial uploading fails in cassavabase

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1833]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
trials with >+10K plots upload fail in cassavabase.
checked:
-file format is correct
-accessions are in the database
-large files (+20Kplot) were tested before on smaller databases
-this current file did load on a local, smaller db (@aco46 's)
-> seems the database size has to do with the lengthy upload which doesn't end.
Enclosed the file

[Trial_file_PVA_Seedlings_NaCRRI.xls.zip](https://github.com/solgenomics/sgn/files/1919202/Trial_file_PVA_Seedlings_NaCRRI.xls.zip)

**Comment by nickmorales** [comment]
nginx conf was not allowing files greater than 1MB to be uploaded. needed to be set in the http context
