### ISSUE TITLE
Barcode designer printing for plants

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1838]
Expected Behavior 
--------------------------------------------------------------------------

Printing of plant labels is not possible right now on barcode designer.
Also, this needs to be more streamlined from the trial detail page (like it was before) meaning that the pre-set label designs that we had before need to be available to use.
From the trial detail page there should really only be two things: dropdown to pick a label design (plots or plants and label type e.g. cass) and a download button.
related to #1714 

For Bugs:
---------

**Comment by aco46** [comment]
@nickmorales: I would make the migration issue a priority.

**Comment by bauchetg** [comment]
thanks @nickmorales 
@aco46 the preset interface (plot/plant/accession) from the trial page was really convenient

**Comment by bauchetg** [comment]
@aco46 fully agree this is the best option
