### ISSUE TITLE
Options to handle data that needs to be kept private

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1848]
Expected Behavior 
--------------------------------------------------------------------------
Some breeders from the sweetpotato project would like to see the database better handle the problem of data privacy for a couple reasons
 - They have seen substantial reluctance on the part of national program breeders in SSA to share data, out of concern that it will be stolen. 
- The program at NC State is worried about how to track data from it's ornamental and processing breeding programs - both are funded by industry partnerships, in which both the germplasm and data generated are supposed to be private and owned by the industry partners.

There is no clear solution I can think of, but the general request is for a way to make specific trials and accessions (and all the data associated with them) invisible to users outside the given program. I don't love the idea, but it's certainly popular with users.

The ornamental breeding program is so different that it uses completely separate germplasm and will require a completely different ontology. Because of this I suggested the best solution for privacy may be to set up a new stand-alone database instance. Not sure how straightforward that would be yet.

![img_20160315_171955](https://user-images.githubusercontent.com/11297346/39140923-141fbf42-46f4-11e8-8102-0ebef8ea5b38.jpg)

For Bugs:
---------

**Comment by bellerbrock** [comment]
Some additional thoughts from discussions today - 
It would provide additional reassurance to users if they can see when and by whom their data is downloaded.
It would be helpful to be able to view / verify who is using the database. Maybe by making the user role table downloadable

**Comment by nickmorales** [comment]
a separate database instance that can only be accessed by the ornamental breeders would be the easiest solution

**Comment by bellerbrock** [comment]
Thanks Nick. I'll follow up on the separate database solution for commercial data. And it looks like the other potential improvements are being tracked here #1676
