### ISSUE TITLE
Seedling Nursery trial type does not accept crosses

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1850]
Expected Behavior 
--------------------------------------------------------------------------

No option exists to use crosses rather than accessions. The description for 'greenhouse/nursery' design type says this is possible, but crosses are rejected by both the new trial design and the trial upload tools.

This is critical for tracking seedling nurseries in sweetpotato! By way of example, NCSU's seedling nursery trial consists of ~60,000 seedlings, grouped and planted by the ~150 different crosses they come from. Everything is tracked at the cross level, including selection percentages, major defects, and cross-level performance that can help determine which parents get used again. Accession names are only assigned at the very end of the season to the roughly 2% of seedlings that get selected. 

For Bugs:
---------

**Comment by nickmorales** [comment]
related #1449

**Comment by lukasmueller** [comment]
I think Titima implemented this so this could be closed?

**Comment by titima15** [comment]
@lukasmueller yes, it's done.
