### ISSUE TITLE
Cassavabase trial tree doesn't show and crashes the page on refresh.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1855]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by aco46** [comment]
![picture11](https://user-images.githubusercontent.com/10618260/39367846-ee5c96ee-4a05-11e8-99a1-4f2be8db1cb3.png)

These bunch of trials are breaking the manage trial tree in cassavabase.

**Comment by bellerbrock** [comment]
hey @aco46 , what happens if you set all the missing years to a specific number, like 2000? It looks like that log error comes from a non-numeric value for year being used in a numeric sort

**Comment by nickmorales** [comment]
the times i've seen the filesystem get full is because of the sgn logs, so the solution is to just clear those files. 
the trial tree seems to be working https://cassavabase.org/breeders/trials/ for me
