### ISSUE TITLE
Implement a cross search

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#186]

**Comment by nickmorales** [comment]
by cross search do you mean a simple 'cross name' search? if so, the new folder tree will take care of this

**Comment by lukasmueller** [comment]
I thought about selecting a female parent, which would list all the male parents used in crosses; selecting the male parent would give you all the crosses between these two.

**Comment by titima15** [comment]
Closed via commit c93edeb131edda45c068ab55a25dde76f495935b

**Comment by titima15** [comment]
Closed via commit acbb8303386d3567fe302e8185f2daf7c22bae93
