### ISSUE TITLE
Label Designer: add plant entry as an option for barcode designing.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1860]
Expected Behavior 
--------------------------------------------------------------------------
Requested by Prasad;
- add plant name
- add plant number

For Bugs:
---------

**Comment by bellerbrock** [comment]
Also saw the request from Nick #1838. Working on it this afternoon. Alex if I can ask for your review once I have a branch ready maybe we can add the links and migrated pre-designed options as well?

**Comment by bauchetg** [comment]
Hello @bellerbrock @aco46  there is a similar request to have the ability for genotyping trial to print for plate ID (96 plates).

**Comment by bauchetg** [comment]
see #1737

**Comment by bellerbrock** [comment]
Implemented in #1869 . Addtional tweaks needed before closing:

Plant list as data source
Plant number field that is separate from plant name
Rid of duplicate plant_names and plant_ids fields
