### ISSUE TITLE
Need additionnal custom template upload from Coordinates

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1865]
Expected Behavior 
--------------------------------------------------------------------------
Coordinate PhenoApp offers preset template such as "DNA Plate" (already handled in cassavabase) with this format: date | plate_id | plate_name | sample_id | well_A01 | well_01A | tissue_id | dna_person | notes | tissue_type | extraction
It can be accessed using "I am uploading a Default Coordinate Android app plate design"

However the template  "DNA plate" sets randomly the control well which can be a problem for some genotyping vendor. This can be overcome by setting a custom template using "New template", where the default format is:
Value | Column | Row | Identification | Person | Date
Where fields are:
-Value: store the barcode content (here "plot name")
-Column: column number (integer)
-Row: row number (integer, not letter)
-Person: same as "dna_person"
-Date:  same as date in "DNA Plate" format (YYYY-MM-DD)

We would need to add this format under a second option like: "I am uploading a Custom Coordinate Android app plate design".
Additional options are offered (adding optional field, exclude field, or custom naming) but these would add more complexity.

Hello @trife is there any major changes planned in Coordinates output formats  we should keep in mind for further compatibility with cassavabase?
From https://github.com/PhenoApps/Coordinate it seems that some multiple plate could be exported in a single file, is that correct?

For Bugs:
---------

**Comment by nickmorales** [comment]
for consistency in column naming:

Coordinate Default "DNA Plate" Format:
date | plate_id | plate_name | sample_id | well_A01 | well_01A | tissue_id | dna_person | notes | tissue_type | extraction

Coordinate Default "New Template" Format:
sample_id | column | row |  dna_person | date

**Comment by bauchetg** [comment]
new template example:
<img width="1027" alt="screen shot 2018-05-23 at 8 22 02 pm" src="https://user-images.githubusercontent.com/12039071/40443840-d24d6574-5ec7-11e8-8cc3-2164a3909762.png">
Yellow fields are default, grey ones are custom one (order and names can differ...)
So implementation should only cover yellows
For a comparison below the dataset from above screenshot converted into the the current Coordinate format we use:
<img width="1073" alt="screen shot 2018-05-23 at 8 22 12 pm" src="https://user-images.githubusercontent.com/12039071/40443925-1bc6554e-5ec8-11e8-86bb-981c43881280.png">
Respective corresponding default columns are highlighted in  yellow and optional in grey.

**Comment by trife** [comment]
I think I cleared up most everything over email. Integer being used instead of letter in column/row should be modifiable within the custom template but is currently not and I will have our dev fix that before the new version is released. The "Value" field will be able to be changed within the template file in v2 and the user will be able to manually toggle excluded cells.

I would recommend developing a NextGen template that users can access if you want everything to be completely standardized.
