### ISSUE TITLE
Genotyping trial tree: folder deletion

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1866]
Expected Behavior 
--------------------------------------------------------------------------
For Bugs:
---------
Folders from phenotyping trials are displayed in the Genotyping trial tree, but empty.
When opening an empty folder to delete it,  it still display content (ie: phenotyping trials) and cannot be deleted.
https://cassavabase.org/breeders/genotyping/
Ex:
2006 NRCRI -> 2006_Umudike -> "06cetEarlyBulkingUM" and "06SeedlingsEarlyBulkingUM"

**Comment by aco46** [comment]
@bauchetg we may need to add an option to enable or disable a folder for genotyping trial, just like we have for field trial and cross trial.

**Comment by bauchetg** [comment]
closed with #1961
