### ISSUE TITLE
BrAPI: Study observation unit detail returns one assayed trait within a plot.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1868]
Expected Behavior 
--------------------------------------------------------------------------
Current implementation, returns one trait at random for each plot. Should return all the assayed traits within a an observation unit (plot).

For Bugs:
---------

**Comment by dauglyon** [comment]
It looks like the issue would be coming from here: https://github.com/solgenomics/sgn/blob/master/lib/CXGN/BrAPI/v1/Studies.pm#L476-L522

But, I cant see what is wrong from first glance. I will do some debugging later on. @nickmorales, do you have insight on this?
