### ISSUE TITLE
Add uploaded file section to genotyping trial page

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1873]
Expected Behavior 
--------------------------------------------------------------------------
Genotyping trial would need to display uploaded files as in he field trial detail page.

For Bugs:
---------

**Comment by nickmorales** [comment]
what files would you show?

**Comment by bauchetg** [comment]
@nickmorales same as for trial, the uploaded file log would show the file and user would did it

**Comment by nickmorales** [comment]
Right but on the trial detail page it shows uploaded phenotype files. Do
you mean the additional files section?

**Comment by lukasmueller** [comment]
maybe uploaded vcf files could be added to the list. If that doesn't seem useful, this issue can be closed?

**Comment by titima15** [comment]
This implementation is a part of #4536
