### ISSUE TITLE
update solQTL to slurm

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1899]
run_cluster in cgi-bin/phenome/qtl_analysis.pl and cgi-bin/phenome/population.pl

**Comment by nickmorales** [comment]
is this done on the topic/slurm_backend2 branch?

**Comment by isaak** [comment]
this is on separate branch and will merge it to master once  topic/slurm_backend2 is merged to master. Fixing the three way merge conflict was cumbersome....

**Comment by isaak** [comment]
#1996
