### ISSUE TITLE
upgrade systems to jessie and slurm

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#1903]
-- CXGN::Tools::Run is broken for all statistical tools: solGS, PCA, Correlation, ANOVA.

"Can't use string ("CXGN::Tools::Run") as a HASH ref while "strict refs" in use at accessor CXGN::Tools::Run::temp_base (defined at /home/isaak/cxgn/cxgn-corelibs/lib/CXGN/Tools/Run.pm line 114) line 6.

**Comment by isaak** [comment]
Or reverse topic/slurm_backend merge on cxgn-corelibs

**Comment by isaak** [comment]
The Slurm coding is done! I guess upgrade to Jessie still on going??

**Comment by nickmorales** [comment]
vms are now using a template based on jessie
