### ISSUE TITLE
Improve account creation and management options

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1906]
Expected Behavior 
--------------------------------------------------------------------------

Some problems that we've encountered this week while working with the sweetpotato program at NaCRRI:

- Manual account creation (https://sweetpotatobase.org/solpeople/admin/quick_create_account.pl) is not working anymore because it does not encrypt passwords. And it does not seem to save email addresses.

- There are 3 different fields that store a user's email address. Password retrieval only works with the 'private_email' field, but many older accounts only have the pending or contact email field populated.

- Account creation on test-sites doesn't work because emails are not sent.

- There is no way for a user to retrieve forgotten username.

- There is no way for a user to delete or merge duplicate accounts.
- check if email already exists

- User details are stored in a case-sensitive manner in the database, but the check for username uniqueness is case-insensitive. 

- It is not clear what the field 'Organization:' means in the account creation form. If it is for breeding program, an autocomplete field or dropdown list of existing programs would be helpful.

- Breeding program roles are not added on account creation.

- Adding user roles does not check for to see if the user id -  role combination already exists, resulting in duplications.

For Bugs:
---------

**Comment by bauchetg** [comment]
For user account default settings see as well #1015 
For User role management see as well: #1870 and #484
For user reigstration mandatory fields see as well: #1676
For duplicates on cassavabase see: #892

**Comment by bellerbrock** [comment]
An idea discussed at ticket meeting for handling the problem with synching between live and test site:

Store both production_dbname and test_dbname (and server). in sgn_conf. Disable All account management, except for changing privilleges, in sites where is_production conf variable is false. Then refactor code so that all other create and manage new account changes are executed in both dbs at the same time.

**Comment by lukasmueller** [comment]
Sometimes it is useful for trainings etc. to open submitter accounts for students on a test machine, but not on a production site. So having both databases be synched is not always desirable.

**Comment by lukasmueller** [comment]
Most of these issues have been resolved.
