### ISSUE TITLE
Phenotyping Graphical Viewer

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#1907]
Expected Behavior 
--------------------------------------------------------------------------
Use  a Dataset (or integrate into Wizard) a tool that displays phenotypes in different formats, such as box plots, according to user selectable categories.

For Bugs:
---------

**Comment by dauglyon** [comment]
Using (vega-lite) Some potential graphs are:
histogram
grid of histograms split by some other variable (maybe trial, location)
scatterplot // grid of scatterplots
box/violin plots

**Comment by lukasmueller** [comment]
This has been implemented in the BoxPlotter.
