### ISSUE TITLE
Graphical Filtering and Trial Comparison Tools are broken

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1908]
Expected Behavior 
--------------------------------------------------------------------------

After selecting a list, spinner spins endlessly. 

For Bugs:
---------

### Environment 

sweetpotatobase.org and yambase.org

**Comment by aco46** [comment]
It actually took some time and ended up retrieving all plot assayed traits in the database.

**Comment by dauglyon** [comment]
Looking into this

**Comment by nickmorales** [comment]
sorry i think what happened is the brapi arguments because studyDbId, germplasmDbId, observationVariableDbId, observationLevel, locationDbId. i think before we had them incorrectly implemented in the plural forms

**Comment by nickmorales** [comment]
maybe the sever should just accept both, either studyDbId or studyDbIds etc

**Comment by dauglyon** [comment]
That looks to be the issue, the BrAPI spec says DbId for single (GET) and DbIds for multiple (POST), is this a necessary distinction?

**Comment by nickmorales** [comment]
brapi params for:
phenotype-search GET and POST
phenotype-search/table
phenotype-search/csv
phenotype-search/tsv
fixed in here https://github.com/solgenomics/sgn/pull/1904/commits/b499fb5ce460f8a699418ed3d6d55538561cd560
its in the brapi_improvement pull request

**Comment by dauglyon** [comment]
@nickmorales that seems to do it. I thought I needed to change some BrAPI.js stuff, but thats more related to https://github.com/solgenomics/BrAPI-Pedigree-Viewer/issues/3.
