### ISSUE TITLE
redundant 'trait_property' and 'cvterm_property' cvs

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1909]
Expected Behavior 
--------------------------------------------------------------------------

Cvtermprop values had historically been stored under the cv called 'trait_property' for the cvterm names 'trait_categories', 'trait_default_value', 'trait_details', 'trait_format', 'trait_maximum', 'trait_minimum'.
Historically these values could only be added through backend scripts.

Recent changes to the cvterm page allow user to store cvtermprop values, but under a different cv called 'cvterm_property' for the same cvterm names listed above.

A patch should be written to pick one over the other, so that we can consistently store data

For Bugs:
---------

**Comment by nmenda** [comment]
need to add here param cv_name
https://github.com/solgenomics/sgn/blob/master/lib/SGN/Controller/AJAX/Cvterm.pm#L365

https://github.com/solgenomics/sgn/blob/master/mason/chado/cvtermprops.mas#L157
