### ISSUE TITLE
Include downloadable template with all upload format explanations

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1912]
Expected Behavior 
--------------------------------------------------------------------------

This is a request from the CIP sweetpotato breeding team in Uganda after having a particularly tough time with cross uploads. They often run into formatting issues while uploading data, even after they've copied and pasted the expected header. Often this is due to extra whitespace or other mistakes that can be tricky to identify from the error messages.

Their suggestion is that it would be much easier for them if each upload tool including the option to download a blank file with the exact template and file type that is needed. Then they can just paste in their data. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
format explanations are given on the website, probably good enough?
