### ISSUE TITLE
Enforce same plotname restictions in add trial as in upload trial

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1913]
Expected Behavior 
--------------------------------------------------------------------------
The add trial tool can end up including spaces and forward slashes in plot names if those characters are present in accession names. The upload tool is more strict, forcing users to remove the characters before upload. 

Since these characters can cause problems when scanning barcodes or using the fieldbook, it would be helpful to remove them from plot names in the add trial tool too. Or, fix the root of the problem by forbidding their use in accession names.

For Bugs:
---------

**Comment by nickmorales** [comment]
the '/' and '-' characters are no longer problems for the barcodes and some databases require that accessions have these characters
