### ISSUE TITLE
Trait search sometimes shows same trait multiple times in results

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1923]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

sweetpotatobase.org
#### Steps to Reproduce

![duplicatetraits](https://user-images.githubusercontent.com/11297346/40974137-5230680c-68cf-11e8-9d6d-a0b46e0cd5b0.png)

**Comment by nickmorales** [comment]
this should not be happening anymore. what are you searching?

**Comment by bellerbrock** [comment]
Ok, just rechecked. It's not happening on the live site, just the test site. It's happening when I select the variables ontology and then search 'alternaria'. No obvious reasons or javascript errors. Maybe sweetpotatobase-test is missing an update?

**Comment by bellerbrock** [comment]
hmm, test site was on sgn-225.4, live site on the master branch. Just updated the test site and the issue seems to be resolved
