### ISSUE TITLE
Option to delete crossing trials and edit their details

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1930]
Expected Behavior 
--------------------------------------------------------------------------

A Ghana user accidentally added a crossing trial to the Uganda program in sweetpotatobase. When attempting to fix the error it looks like there is no way to edit trial metadata, specifically the breeding program. And no way to delete the mistake trial.

For Bugs:
---------

**Comment by titima15** [comment]
Done. Closed via d85324f
