### ISSUE TITLE
Error prevents seedlot deletion

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1932]
Expected Behavior 
--------------------------------------------------------------------------
From log:
[error] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  permission denied for relation stock_owner [for Statement "DELETE FROM stock_owner WHERE ( stock_owner_id = ? )" with ParamValues: 1='191923'] at lib/CXGN/Stock/Seedlot.pm line 1090

For Bugs:
---------

### Environment 

sweetpotatobase.org
#### Steps to Reproduce

clicking delete option in search result table on manage seedlot page

**Comment by bellerbrock** [comment]
Looks like the problem might be that web_usr doesn't have delete permission on phenome.stock_owner

```cxgn_batatabase=# \z phenome.stock_owner
                                  Access privileges
 Schema  |    Name     | Type  |     Access privileges     | Column access privileges 
---------+-------------+-------+---------------------------+--------------------------
 phenome | stock_owner | table | postgres=arwdDxt/postgres+| 
         |             |       | web_usr=arw/postgres      | 
(1 row)
```

**Comment by nickmorales** [comment]
granted permission to web_usr
