### ISSUE TITLE
releasing database update/changes/upload within a Slack instance

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1941]
Expected Behavior 
--------------------------------------------------------------------------
Seems there would be an (easy?) way to release informations updates (ie: data upload, download, new release,etc...) from a database instance to a slack instance:
https://zapier.com/apps/slack/integrations/wachete/9770/send-slack-messages-for-wachete-changes
Or may a similar tool does that task?
Since the entire NextGen project is on Slack that would be easy to keep everyone informed by notifications and would get us close to the dropbox notification system breeders like.
Any suggestion?

For Bugs:
---------

**Comment by bauchetg** [comment]
Stream a log file to slack: 
http://blog.getpostman.com/2015/12/23/stream-any-log-file-to-slack-using-curl/
Would be cool for file upload/download no?

**Comment by nickmorales** [comment]
@bauchetg we show the latest PR on the homepage. can we close this issue?

**Comment by bauchetg** [comment]
yes
