### ISSUE TITLE
Allow multiple trial selection during creation of cross whichlist.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#1944]
Expected Behavior 
--------------------------------------------------------------------------
In some cases Breeders could use accessions from different trials to create cross whichlist. It would be nice to add an option to select one or more trials while creating cross whichlist.
Requested by IITA Abuja.

For Bugs:
---------

**Comment by aco46** [comment]
Nike from IITA said they usually separate male crossing block from female crossing. In these case while creating a cross wishlist, they would want to combine two crossing block trials or use list of male and female accessions from two different crossing blocks to create a cross wishlist.

**Comment by nickmorales** [comment]
it is now possible to select a female trial and a male trial
