### ISSUE TITLE
alpha lattice bugs and improvments

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1950]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
creation of custom plot name:
-> plot numbering doesn t include blocking level while using custom (works in default mode):
This happen even without setting info 
-> use block number within plot naming
-> row/col doesn t display when default mode (even if row info is optional

**Comment by bauchetg** [comment]
Bug found!  Alpha lattice need to use the number of accessions per block  for column coordinates instead of the block number

**Comment by aco46** [comment]
FieldMap display for Alpha Lattice fixed in #2062

**Comment by aco46** [comment]
There's another ticket addressing plot numbering.
