### ISSUE TITLE
add a info field to pedigree upload with free text (for example, “female is a half sib”).

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#197]

**Comment by bauchetg** [comment]
2cb6127  allow populations as male parents in pedigrees to represent open / half-sib crosses. - Lukas Mueller
78c8fba  add to pedigree unit_fixture test (needs more work). - Lukas Mueller
e3acb70  change the description of the pedigree upload format to correspond to the new format. - Lukas Mueller
