### ISSUE TITLE
"Public list" management and deletion

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1974]
Expected Behavior 
--------------------------------------------------------------------------
-Public list are managed by their owners, when they get many, one may be hard to track.
Adding the owner list to the display would ease this.
-Curators permission to delete them may help too.

For Bugs:
---------

**Comment by dauglyon** [comment]
@bauchetg Can I suggest the curator is given permission to un-public the list but not remove it? That reduces the chance of accidental data loss but still has the benefit of uncluttering.

**Comment by bauchetg** [comment]
@dauglyon thanks, that s a much better solution
