### ISSUE TITLE
Upload phenotype file fails in confusing way when csv file header values are not double quoted

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1977]
Expected Behavior 
--------------------------------------------------------------------------

Sometimes users get the error message ' First column in header must be plot_id, plot_name, plant_name, or subplot_name.' despite their header appearing to be correct. Looking at the ParseUpload Fieldbook plugin, it seems this is because it is checking header values like ```plot_name``` and ```'plot_name'``` against the string ```"plot_name"```.

Would be good to make the upload check more flexible to handle these different variations.

For Bugs:
---------

**Comment by nickmorales** [comment]
Use Text::CSV to parse csv so that this isn't an issue
