### ISSUE TITLE
centralized manage->tissue samples page

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1978]
Expected Behavior 
--------------------------------------------------------------------------
Currently tissue samples can only be found by going into a field trial detail page or a genotyping trial detail page. It would be better if there was a central management page for handling tissue sampling 

For Bugs:
---------

**Comment by bauchetg** [comment]
Could that be integrated to the Genotyping trial interface?

**Comment by nickmorales** [comment]
It could be to a degree, but its should also be separate because a field
trial can produce tissue samples that don't necessarily go into a
genotyping trial 96 well plate

On Mon, Jun 25, 2018 at 4:36 PM, Guillaume Bauchet <notifications@github.com
