### ISSUE TITLE
Additional feature for "Find synonym" function in accession list  

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#1979]
Expected Behavior 
--------------------------------------------------------------------------
Current "find synonym" feature tells user if queried name is a uniquename or a synonym.
Ability to retrieve all additional synonyms/uniquename according to input string would help curators to identify mismatches. 
Something like:
SELECT uniquename, stockprop.value FROM stock JOIN stockprop USING(stock_id) WHERE uniquename in ('TMEB419','TMEB204') AND stockprop.type_id = (SELECT cvterm_id FROM cvterm WHERE cvterm.name = 'stock_synonym');

For Bugs:
---------

**Comment by bauchetg** [comment]
Having that function in the list validator is good but having the ability of downloading the synonyms from the "Search" -> "Accession" would be better. Since the list only allows arrays, erhaps it could be saved/downloaded (with other selected stockprops) as a dataset?

**Comment by bauchetg** [comment]
Current accession search does not include synonym field, which is desirable

**Comment by nickmorales** [comment]
the accession search searches over synonyms and uniquenames already e.g. type 'tme' on cassavabase and you'll see that
