### ISSUE TITLE
Allow users to add a description when adding new list name

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#1982]
Note: just need to add an input box in the dialog and js.  AJAX/List and CXGN/List are ready for storing description.

For Bugs:
---------

**Comment by bauchetg** [comment]
@titima15 I take the opportunity of this issue to list up a couple other points on list:
- request for a list "intersect" option in addition to the existing "combine"
- the batch deletion of list doesn t not work if you increase the datable display above 10 entries
- list name and deletion #1974

**Comment by bauchetg** [comment]
moved remaining point to a separate issue #2230
