### ISSUE TITLE
histogram scale is not readable when counts are in the thousands

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#1988]
Expected Behavior 
--------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/7028512/42007786-e8c4727c-7a4f-11e8-8eff-364191f136f3.png)

For Bugs:
---------

### Environment 

On breeding program page on cassavabase

**Comment by dauglyon** [comment]
What is the largest count one would expect to see on the y-axis?

**Comment by dauglyon** [comment]
(by order of magnitude)?

**Comment by dauglyon** [comment]
maybe 9,999 or 99,999?
