### ISSUE TITLE
add link to associated stocks on publication page 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#1995]
Expected Behavior 
--------------------------------------------------------------------------

https://solgenomics.net/publication/18521/view

For Bugs:
---------

**Comment by bauchetg** [comment]
@nmenda Could we have a similar reciprocal link for trials ?
I mean, when a trial is used in a published study to have on the trial detail page have a publication link? (same as what exist for the stock detail page)

**Comment by bauchetg** [comment]
oops sorry I closed by mistake...

**Comment by bauchetg** [comment]
Thanks @nmenda
For information:
Cassava hapmapII
https://cassavabase.org/publication/1/view
Cassava hapmapI
https://cassavabase.org/publication/2/view

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/1998

**Comment by nmenda** [comment]
link to publications from trial pages needs a new ticket
