### ISSUE TITLE
problem printing barcodes for subplots 

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2005]
Expected Behavior 
--------------------------------------------------------------------------
problem printing barcodes for subplots
![image](https://user-images.githubusercontent.com/7028512/42325463-57ace6e4-8034-11e8-80c8-78e04256d8ff.png)

For Bugs:
---------

**Comment by aco46** [comment]
@nickmorales this came from the label designer page.  plots contains two or more subplots which are returned in an array data structure. We should probably capture the use case that iterate through the returned array to print the barcodes for each of the subplot in a plot.
