### ISSUE TITLE
Add cross property file with the same format as trait file for intercross app

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#2030]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bauchetg** [comment]
Fieldbook trait file format includes: 
**trait:** trait name ex: apical pubescence|CO:0000026 or it synonym
**format:** variable type ex: "qualitative" (Fieldbook includes type like "numeric/categorical/percent/date/boolean/text/photo/counter/multicat/rust/rating/audio/location"
-defaultValue: "" or "FALSE"
**minimum:** integer ex "0"
**maximum:** integer ex "100"
**details:** "Visual qualitative rating of the young leaves pubescence / usually scored on a scale 0/ 3/ 5/ and 7"
**categories:** if qualitative trait ex "0/3/5/7"
**isVisible:** "TRUE" or "FALSE"
**realPosition:** integer to rank traits in the file

**Comment by titima15** [comment]
This ticket is obsoleted.
