### ISSUE TITLE
Plant based trial plant name sorting

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2036]
Expected Behavior 
--------------------------------------------------------------------------
When generating plant level from plots, a plant number is appended to the existing plot name and does not include a standard number of digits (i.e: _0001, _0010, _0100), this results in an inexact name sorting in a plant name list:
https://cassavabase.org/breeders/trial/4009?format=
![screen shot 2018-07-23 at 2 12 04 am](https://user-images.githubusercontent.com/12039071/43060192-dcdebc56-8e1d-11e8-898d-e268ca7b0d3d.png)

For Bugs:
---------

**Comment by nickmorales** [comment]
also check if plant index number is being saved in the correct order

**Comment by nickmorales** [comment]
when you download the layout, the plant_index_number provides a reliable column for sorting plants

**Comment by bauchetg** [comment]
@nickmorales just drop here the comments from testing:
-  double sort of plot number first and then plant index number: requesting user to manually sort the layout prior loading in FieldBook is too error prone
- Think this may affect the plant barcode printing as it source the same table the barcodes get printed unordered (If I use the "sort by option" in the label designer it does not solve it
