### ISSUE TITLE
Inconsistent hover behavior on field map

### ISSUE THREAD

**Issue by dauglyon** [solgenomics/sgn#2039]
Expected Behavior 
--------------------------------------------------------------------------
I'm unsure of the expected behavior here, but there is something strange happening with hovering and the field map. @aco46, any ideas?
![2018-07-23 14_40_00](https://user-images.githubusercontent.com/5115845/43096223-65fe8f8a-8e86-11e8-9f5b-18d81692bf96.gif)

For Bugs:
---------

### Environment 

Mac Chrome Version 67.0.3396.99 (Official Build) (64-bit)
#### Steps to Reproduce
https://cassavabase.org/breeders/trial/4009?format=

**Comment by aco46** [comment]
@dauglyon if you're fast in your hover then the popups might not be displaying as well as the inconsistencies in plot highlight. 

I could come seat with you to review that chunk of code. Perhaps your knowledge of D3 would be helpful in resolving it.
