### ISSUE TITLE
Probelm with displaying Pedigree in Label designer download using Create Custom Field 

### ISSUE THREAD

**Issue by pvnsprasad** [solgenomics/sgn#2043]
Expected Behavior 
--------------------------------------------------------------------------

Pedigree doesn't display in the downloaded pdf when generated through "Create Custom Field" in label designer

For Bugs:
---------

### Environment 

Cassavabase main site

#### Steps to Reproduce

[15ayt16highTCIK-zvVBu.pdf](https://github.com/solgenomics/sgn/files/2224085/15ayt16highTCIK-zvVBu.pdf)

**Comment by dauglyon** [comment]
@bellerbrock I took a look at it with Prasad and it looks like its a problem with loading the pedigree information. When a pedigree field is used in conjunction with a custom field "Pedigree:{pedigree_string}", the data shows in both fields, but when the pedigree field is absent the custom field renders just as "Pedigree:" with no data.
