### ISSUE TITLE
add ability to upload subplot entries in the same way as plant entries

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2048]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Hi Nick, I am under the impression this is already implemented? Could the ticket be closed?

**Comment by dwaring87** [comment]
@lukasmueller I don't think this is implemented.  From the trial detail page, there are options to create plant entries but no options to create subplots.  This is something that would be really useful for the kelp project.  @nickmorales are you working on this?  If not, I can try implementing it.

**Comment by nickmorales** [comment]
hi @dwaring87 i'm not currently working on it, so please feel free to work on it

**Comment by dwaring87** [comment]
@nickmorales I'm almost done adding the subplot functions.  One thing I noticed with the existing plant functions, is that each dialog to create plant entries has a checked and disabled option to inherit management factors from plots.  Is this supposed to be disabled?  Or should the user be allowed to not have this enabled?

**Comment by nickmorales** [comment]
Hi good point. I think this was mainly a reminder that this is the behavior
that was implemented. It may make sense to not show the disabled checkbox
on the display.
