### ISSUE TITLE
Brapi response in sweetpotatobase to call: germplasm/id/pedigree

### ISSUE THREAD

**Issue by c5sire** [solgenomics/sgn#2052]
Expected Behavior 
--------------------------------------------------------------------------

When pedigree is 'unknown' or parents id is 'null' then no siblings should be returned.

For Bugs:
---------

### Environment 

web and R client

#### Steps to Reproduce

 https://sweetpotatobase.org/brapi/v1/germplasm/103412/pedigree

**Comment by nickmorales** [comment]
this is also causing the pedigree call to be extremely slow @dauglyon
