### ISSUE TITLE
BrAPI response to allelematrices-search

### ISSUE THREAD

**Issue by c5sire** [solgenomics/sgn#2053]
Expected Behavior 
--------------------------------------------------------------------------

If the call returns no results, the data object should be just empty - not a list 'null' values as long as the pageSize parameter.

For Bugs:
---------

### Environment 

web and R client
#### Steps to Reproduce

https://sweetpotatobase.org/brapi/v1/allelematrices-search/

https://sweetpotatobase.org/brapi/v1/allelematrices-search/?pageSize=100&page=0

**Comment by nickmorales** [comment]
thanks for pointing this out. it is addressed in #2069
