### ISSUE TITLE
plot number is not reflecting the block number  in custom generation

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2058]
Expected Behavior 
--------------------------------------------------------------------------
change the plotID generation when selecting custom plot naming
<img width="861" alt="screen shot 2018-07-26 at 11 29 19 am" src="https://user-images.githubusercontent.com/12039071/43276435-ab56d904-90d2-11e8-8876-6a0e37b12d44.png">

For Bugs:
---------
-> Block number doesnt reflect in plot number (here should shift from 115 to 201)

**Comment by aco46** [comment]
closes via #2082
