### ISSUE TITLE
hardcoded jbrowse link  on stock page 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2072]
Expected Behavior 
--------------------------------------------------------------------------
This is cassavabase specific

https://github.com/solgenomics/sgn/blob/0bf671cd8ba0f1a3b8622c0a432af59935318274/mason/stock/index.mas#L188

Need to construct a link using 
1. dataset name 
2. track name/s

This means we need to load an xref in the database if we want to link accessions to all the jbrowse datasets that have SNP data associated , something similar to the sgn blast db table 

For Bugs:
---------

**Comment by nmenda** [comment]
Same for the trial detail page 
Remove the hardcoded jbrowse link
https://github.com/solgenomics/sgn/blob/master/mason/breeders_toolbox/trial/jbrowse_instance.mas#L13

**Comment by lukasmueller** [comment]
This may already have been fixed... ?
