### ISSUE TITLE
Label Designer: ability to print a list of trials 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2088]
Expected Behavior 
--------------------------------------------------------------------------

Requested by Prasad. To send plates to genotyping services he has to print the plate names (trial names) of a list of genotyping trials and attach them to the plates.

For Bugs:
---------

**Comment by bauchetg** [comment]
Requested by prasad for upcoming project

**Comment by pvnsprasad** [comment]
This is mainly when we need to print the Genotyping plate names (Genotyping trial names) to send the samples
