### ISSUE TITLE
Add pheno descriptors to ontology whenever it is still missing

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2094]
Expected Behavior 
--------------------------------------------------------------------------

ref doc:
https://cassavabase.org/static_content/Fukuda_et_al_2010.pdf

For Bugs:
---------

**Comment by nmenda** [comment]
@bauchetg do you mean to add a description to terms? We have to do this directly on the OBO file. Can't update the database and then import edits to the ontology file

**Comment by bauchetg** [comment]
Hello @nmenda, I am not sure if you meant "can or can't"
But yes I would like to add descriptors  to traits whenever they are still missing
Ultimately this should allow the user to export or not these visual scale to FieldBook 
This as to do with an important feature development on trait file customization, see #1641

**Comment by bauchetg** [comment]
done with @pvnsprasad
