### ISSUE TITLE
Provide option to update accession contained in plot name when editing a trial layout

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2097]
Expected Behavior 
--------------------------------------------------------------------------

Request from Jeremy at NCSU. Now that planting season has finished he is making edits to trial layouts to reflect the changes that had to be made during planting for lack of planting material. 

He said the "replace accession" tool on the trial detail page is handy, but it does not update the plot names. For example when he fixed 18CHIP0028HCR by replacing NC16-0748 with MC14-0363 it did not update plot 18CHIP0028HCR_309_3_NC16-0748 to 18CHIP0028HCR_309_3_MC14-0363. In many offline applications the plot name is used to tell the accession name, so the option to update it is important!

For Bugs:
---------

**Comment by aco46** [comment]
closes via #2130
