### ISSUE TITLE
Plant level layout with plot barcoding: print subset of plant based barcodes

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2119]
Expected Behavior 
--------------------------------------------------------------------------
On the trial detail page "barcoding" and "label designer" give an option to print a barcode subset which contains only the first plant of each plot.

Reasoning:
-1- East African program are focused on plant based data collection during growing season (biotic stress) 
-2- Barcoding is being implemented on a plot basis. (Barcoding on a plant basis is not needed in most cases and has a higher cost)
-3- Using Fieldbook + barcode for data collection requires a unique ID which can be plot name or plant name (in the case of plant based phenotyping).
-4- Therefore there is a need to combine plant based layout with plot based barcoding. Using plot based barcode is no longer possible in a plant based layout (plot name no longer unique)
-5- A solution is to print a subset of plant based barcodes  by selecting the first plant of each plot.
This allow to keep plot based labeling using plant based layout for data collection although it is more of a patch than a perfect solution. @pvnsprasad @aafolabi Would this feature be useful for West Africa?

For Bugs:
---------

**Comment by bauchetg** [comment]
This is required for Banana too

**Comment by bauchetg** [comment]
@bellerbrock that might come particularly useful for the NIRS data collection

**Comment by bauchetg** [comment]
To detail more:
The current NIRS devices have a GPS ability but which is phone based, so inaccurate. Bring RTK GPS to the field would improve greatly acuracy and as we can host geojson data we could match up the Scan ID generated to the plot coordinates. However this is still much theoritical.
AN off the shelf solution we can think of is to associate the NIRS data collection to a fieldbook layout based scoring of the scan to the plot/plant. Not the most practical but available immediately.
Following that idea, 
we would need to navigate the field on a plant basis without as systematic labeling of plant but solely of the labeling of the first plant of each plot.
In that regard the label generation option described above would help.

**Comment by aafolabi** [comment]
Hi @bauchetg This is not an option for West Africa. The cost implication will be very high ( it's like having individual pegs for each plant in a plot. Just wondering what will happen in a plot of 42 plants???). I quite understand the need most especially for plant level phenotyping. The singular barcode label will always be at the beginning of the plot instead of the middle of the plot.

**Comment by bauchetg** [comment]
@aafolabi i may not have explained clearly, this option is to keep plot based label but use plant based fiedl layouts

**Comment by aafolabi** [comment]
Oh I see. I understand better now. Thanks

**Comment by lukasmueller** [comment]
Make a custom list of plant names and choose it in the data source drop down.
