### ISSUE TITLE
Improvements to trait value viewing in fieldbook layout files

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2123]
Expected Behavior 
--------------------------------------------------------------------------

NCSU is starting their harvest and creating fieldbook layout files including trait averages from the past few years. It's very helpful feature, but still has limitations. Suggested improvements include:

Use trait abbreviation instead of trait name (names are too long)
option to include notes from previous plots of the accession
option to express trait as percent of a specified check

For Bugs:
---------

**Comment by lukasmueller** [comment]
I think these have been mostly implemented (maybe not # 3)
