### ISSUE TITLE
creating cross-wish list

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2126]
On cassavabase:
--Clicking 'Add cross wish list' returns 'Cross wishlist is not enabled for this database. Please contact us.'. 

-- Then when you click 'OK', it returns more error message:
<img width="1335" alt="cross-wishlist" src="https://user-images.githubusercontent.com/163702/44521274-cb5cce00-a6d2-11e8-9eff-94400e06ea3e.png">

**Comment by nickmorales** [comment]
Cross wishlist is currently only working with ONA ODK that is setup for Musabase and Yambase. 
Potentially the cross wishlist could just be downloaded into csv files, so that it could be used in other ways.
