### ISSUE TITLE
Creating multi-locations Trials

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2127]
On cassavabase:
-- After filling all the required fields and clicking the 'Add Multi-locations trial', a blank dialog box pops up. When you click 'OK', the submission proceeds successfully.
<img width="1161" alt="multi-locs-trials-creation" src="https://user-images.githubusercontent.com/163702/44522925-6ad08f80-a6d8-11e8-9b18-20c1e6865351.png">

-- Unlike when you are creating a single trial, the description of the chosen trial design does not show during the multi locations trial design.

-- Also it would be easy and intuitive for the user if all the dialog box (forms) close, when it is confirmed the trial design submission to the database is successfully done.

**Comment by nickmorales** [comment]
Maybe the multi-location trial should be incorporated into the "Add trial"
workflow, so that it is not this separate thing.

**Comment by aco46** [comment]
closed via #2129
