### ISSUE TITLE
On Cassavabase main website I could not access the 2013 and 2014 GBS Maps

### ISSUE THREAD

**Issue by pvnsprasad** [solgenomics/sgn#213]

**Comment by bauchetg** [comment]
Hi Prasad,
Cache file has been reset and map display is again available.
Although page display remains a bit slow.
Website update should come soon

Guillaume

**Comment by pvnsprasad** [comment]
Thanks Guillaume,  It is working fine now. Next week I am going to demonstrate Cassavabase in WACCI, Ghana.
