### ISSUE TITLE
Graphical Filtering

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2141]
On cassavabase, when I make filtering for a single trait and have selection:

Save results as list is not creating a list. When I give a name and click 'save', it just reloads the filtering page. When I go to my list of lists, I don't see the list.

This happens on both Firefox and Safari.

**Comment by dauglyon** [comment]
Is this on the graphical filtering page or on the accession search?

**Comment by isaak** [comment]
On the graphical filtering page.

**Comment by nickmorales** [comment]
related #2194
