### ISSUE TITLE
sweetpotatobase HTTPS not working

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2146]
Expected Behavior 
--------------------------------------------------------------------------
the certificate for sweetpotatobase.org https is not valid

For Bugs:
---------

**Comment by lukasmueller** [comment]
Fixed by creating the correct certificate file (cat sweetpotatobase_org.crt ssl-bundle.crt  > sweetpotatobase_org.ca-bundle - it needs to be in that order, the reverse order doesn't work).
