### ISSUE TITLE
SeedLot current count doesn't reflect the number of seeds in a seedLot.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2150]
Expected Behavior 
--------------------------------------------------------------------------
I'm not sure if this is a feature but it shows "NA"

For Bugs:
---------

**Comment by nickmorales** [comment]
it will show NA if a count was not provided, but either a count or a weight must be provided

**Comment by nickmorales** [comment]
where is this happening?

**Comment by nickmorales** [comment]
@aco46  you mean it is showing NA instead of showing 0? If the count was given as actually 0 then it should show 0, but if the count was never given then it should be NA.

**Comment by aco46** [comment]
@nickmorales I think you've fixed these. I should have closed the ticket before now.
