### ISSUE TITLE
Allow "Additional Info" properties to be added through the "Add synonym" dialog on stock page

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#216]

**Comment by nmenda** [comment]
need to move this list of props to the server conf file 
https://github.com/solgenomics/sgn/blob/bc1b0bf4fedae68b03f253b1a901e7aaff8b4dfb/mason/stock/index.mas#L102

and add it as an arrayref here 
https://github.com/solgenomics/sgn/blob/bc1b0bf4fedae68b03f253b1a901e7aaff8b4dfb/mason/stock/index.mas#L242

**Comment by jeremyde** [comment]
I ran into this issue today.  I did an ugly hack and just added the "Additional Info" types that I needed to the array.  I'll see if I can fix it properly later.
commit 8f622bf285f7ad06f9ea241bb7317a9303c70818

**Comment by lukasmueller** [comment]
They way the additional info parameters are specified have changed. I think they are now read from a sgn_local.conf file key, as they are different for every database. Naama should confirm.

cheers
Lukas

**Comment by nmenda** [comment]
hi Jeremy,

the stockprop types are now moved to the conf file
see this commit
https://github.com/solgenomics/sgn/commit/d102f769745170be14b93b0b60a14bd04f2e73b2#diff-0ad6a650600cf042ddf739578673e5b6L102

$metadata is no longer used (I just left it there for now )

You should move the new types you added to your sgn_local.conf file
the conf key is
https://github.com/solgenomics/sgn/commit/d102f769745170be14b93b0b60a14bd04f2e73b2#diff-5f8504a03ca74104c9447f5fe3f451b9R183


best,
-Naama



Naama Menda
Boyce Thompson Institute for Plant Research
Tower Rd
Ithaca NY 14853
USA

(607) 254 3569
Sol Genomics Network
http://solgenomics.net/
nm249@cornell.edu

On Wed, Nov 25, 2015 at 4:58 PM, Jeremy D. Edwards <notifications@github.com

**Comment by nmenda** [comment]
need to add the stockprops we want to make editable to sgn_local.conf in cassavabase, yambase, sweetpotatobase, musabase, ricebase , and anywhere else if needed
