### ISSUE TITLE
trials locations mapping

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2160]
-- Trials counts shown mapping to a location on the map don't agree with the trials counts on the pop ups for respective locations. 

-- clicking a trials count on the pop  up of a location shows the list of all trials in the database, instead of only the trials from that location.

-- the pop up is not displaying the breeding programs trials in a location belong to.

https://cassavabase.org/breeders/locations

![image](https://user-images.githubusercontent.com/163702/45283686-d9865900-b4de-11e8-8ae7-7d31e267c4ad.png)

**Comment by bauchetg** [comment]
@isaak from your comments:
-1- "trials counts shown mapping to a location on the map don't agree with the trials counts on the pop ups for respective locations." => The number displayed is the location ID, not the number of trial associated
-2- => correct
-3- => This is probably true for location uploaded before the leaflet interface. Current location creation require a breeding program (curation needed)

Additional observations: 
-4- The location deletion process does not work. 
![screen shot 2018-09-23 at 5 31 40 pm](https://user-images.githubusercontent.com/12039071/45933240-f7c86c00-bf56-11e8-9845-53ba2f7c553b.png)

**Comment by bauchetg** [comment]
-4- was fixed doing grant delete on nd_geolocation to web_usr

**Comment by bauchetg** [comment]
@pvnsprasad I fixed most of GPS/country/location enlisted here.

[Location_Breedingprogram_GB.xlsx](https://github.com/solgenomics/sgn/files/2801476/Location_Breedingprogram_GB.xlsx)
There are several pending, some locations  do not include some nd_geolocation props, to be inserted.
Hello @bellerbrock could you help me to fix the location specific trial list sql query? (problem 2 enlisted by Isaak above)

**Comment by bauchetg** [comment]
Map looks better now:
<img width="933" alt="screen shot 2019-01-27 at 11 42 06 pm" src="https://user-images.githubusercontent.com/12039071/51815672-a1669380-2290-11e9-9991-f6e07e41d6f2.png">

**Comment by bellerbrock** [comment]
No problem @bauchetg . Recent changes to the location object broke the original implementation of the location specific trial list filter. It's fixed now in topic/location-fixes, I just made a pull request if you can review and merge it.
I'm also looking at making a database patch to fix all the old locations that aren't expliticly linked to a breeding program. It should be possible to infer th correct breeding program from many of them based on any trials that have been held at the location.
