### ISSUE TITLE
stackedObservationPhenotypeHistogram.js has issue with notes being returned in result

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2170]
Expected Behavior 
--------------------------------------------------------------------------
The data is being returned to the js, but there is something blocking the data reaching the histogram display. Can be seen on trial detail page where stacked histogram is used.

For Bugs:
---------

**Comment by dauglyon** [comment]
Is this on every instance?

**Comment by dauglyon** [comment]
Nvm, I did a full refresh and it isn't working anymore. I'll check this out
