### ISSUE TITLE
login: email and password update errors

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2184]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
email: 
not all email addresses work. Several cases where ".edu", ".de", ".me" addresses do not get account validation (remain "disabled") in sp_person table. Unclear if this is from the email client or from our side. 

password update: 
with a "valid" email (ex: ".com") and active account, the pwd change function gives a " successful change" message but is not effective. This is true for wheatbase at least. Moreover the process is confusing (see screenshots below) and the user is not rerouted to homepage. 

![screen shot 2018-09-23 at 4 54 07 pm](https://user-images.githubusercontent.com/12039071/45932919-0c563580-bf52-11e8-88dd-45baf365c8dc.png)
![screen shot 2018-09-23 at 4 54 12 pm](https://user-images.githubusercontent.com/12039071/45932921-124c1680-bf52-11e8-875c-529e0b231281.png)
![screen shot 2018-09-23 at 4 54 20 pm](https://user-images.githubusercontent.com/12039071/45932922-1415da00-bf52-11e8-8ceb-233a57f20215.png)

**Comment by bauchetg** [comment]
related to #1906

**Comment by lukasmueller** [comment]
I think this may have been fixed?
