### ISSUE TITLE
Slurm error on Yambase while running Blast.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2205]
Expected Behavior 
--------------------------------------------------------------------------

![picture1](https://user-images.githubusercontent.com/10618260/46485752-551bb300-c7ca-11e8-8730-8f24eceb0216.png)

For Bugs:
---------

**Comment by nickmorales** [comment]
fixed on yambase by:
sudo apt-get install libslurm-perl

had to reinstall munged for some reason also

**Comment by aco46** [comment]
Thanks @nickmorales 
I installed on yambase test as well.
