### ISSUE TITLE
Ability to assign phenotypic values to tissue samples

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2207]
Expected Behavior 
--------------------------------------------------------------------------
Example of trial using tissue sample with phenotypic data 
https://cassava-test.sgn.cornell.edu/breeders/trial/1953?format= 
and https://cassava-test.sgn.cornell.edu/breeders/trial/1954?format=
complement of #2183

For Bugs:
---------

**Comment by nickmorales** [comment]
@bauchetg this should work already, just use the tissue sample name instead of the plot name or other name

**Comment by bauchetg** [comment]
The data might be stored already but not visible on the trial page 
![Screen Shot 2019-04-01 at 9 44 12 AM](https://user-images.githubusercontent.com/12039071/55332130-c0390000-5462-11e9-8e96-c8edcb22fb6d.png)
or available for download
![Screen Shot 2019-04-01 at 9 44 00 AM](https://user-images.githubusercontent.com/12039071/55332138-c8913b00-5462-11e9-96fc-a2279a5a9013.png)
