### ISSUE TITLE
"treatment" cvterm appears in wizard "trial design" menu

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2208]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
"treatment term appears in Wizard trial design type drop down:
![screen shot 2018-10-07 at 11 05 12 am](https://user-images.githubusercontent.com/12039071/46583226-319e7580-ca21-11e8-8330-b82004d160ef.png)

**Comment by nickmorales** [comment]
the materialized views were updated and now should not show treatment as an option
aa42be45cfc7af87bd1469e722a9c3035a4dcc73
