### ISSUE TITLE
Fieldbook "NA" functionality is not handle if a trait is define as "numeric"

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2209]
Expected Behavior 
--------------------------------------------------------------------------
Perhaps we should add "NA" as an exception to be uploaded regardless the trait type.
This call (again?) for a clarification in the db of "NA" vs " "... or maybe not...

For Bugs:
---------

**Comment by trife** [comment]
I would recommend that NA become an exception as " " is ambiguous about intention and "null" has a reserved meaning. If not NA doesn't make the most sense to reference missing data, I'd be open to other values.

**Comment by lukasmueller** [comment]
I don't understand what the conclusion of this discussion is and how and if it has been resolved?

**Comment by bauchetg** [comment]
Database stores " " if the data is not scored and NA if stored is not handled specifically:
NA stands for not available to be scored
" " should be available but not scored.

Differentiating the two cases can be important when computing missing data:
User may purposely decide to score data on a subset (ie: a single rep of an RCBD or in subset of plants within a plot).
This is quite different than if the plants are missing or got removed/killed by a pathogen (ie: CBSD)

**Comment by lukasmueller** [comment]
Does the system/fieldbook handle it correctly? Then we can close the issue?

cheers
Lukas

**Comment by bauchetg** [comment]
this not a fieldbook issue, it can set NA or "" (see below)
![Screenshot_20191028-231748](https://user-images.githubusercontent.com/12039071/67722411-70e29000-f9af-11e9-842f-19af99bd9f43.png)

This is on how breedbase could processes distinctly NA vs "" while analyzing data.

**Comment by lukasmueller** [comment]
So users have to enter it correctly, I guess? 

If so, we can close the issue, but it must be mentioned in training etc.

cheers
Lukas

**Comment by bauchetg** [comment]
breedbase could not handle NA while loading traits including these.
But perhaps it was fixed since?
