### ISSUE TITLE
Fieldbook image upload crashes (parsing issue at upload?) 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2210]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Seems that upload of image name from fieldbook doesnt work with the fieldbook file upload, ex:
NGCGOBII_trial1_rep1_IITA-TMS-IBA920326_1001_PlotPic_1_2018-10-08-12-05-44
Concatenate plot_traitname_timestamp
If we simplify the pics ID as:
NGCGOBII_trial1_rep1_IITA-TMS-IBA920326_1001
It still throw an error (see below) even if the plot exist: https://cassava-test.sgn.cornell.edu/stock/898281/view
![screen shot 2018-10-08 at 12 24 22 am](https://user-images.githubusercontent.com/12039071/46592867-98a94200-ca94-11e8-8691-8e6cf869d47a.png)
This has been previously investigated in #1513 #241 and more #1260

**Comment by trife** [comment]
I'm not sure if this is directly related to a parsing issue, but I had talked with Nick about including a label for each of the photo name components so that they could be more consistently parsed. Would an OU.<id>_OV.<trait>.R.<rep>.TS.<timestamp> be a starting place?

**Comment by lukasmueller** [comment]
Has this been resolved? I hope so...???

**Comment by bellerbrock** [comment]
The attached error messages are related to incorrect trait values, rather than the image names. But yes the image upload parses fieldbook file names correctly, after the update described in this issue: #1420
