### ISSUE TITLE
Plot width and length should also include intervals of 0.3

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2227]
Expected Behavior 
--------------------------------------------------------------------------
Requested by CIP team.

Breeders would want an option of 0.3 intervals to be added to plot width and length. 
An example from their trial is having 3-plants plot with plot width of 0.9

For Bugs:
---------

**Comment by bellerbrock** [comment]
More details from Raul at CIP:

`For the plot width and length, the scale goes in steps of 0.5m, would be better if this field could be open so you can type any number. Here in Peru we use 0.25m between plants and 0.9m between rows, and the folks in Africa I think use 0.3m between plants. So for a 3-plants plot (preliminary or observational trial) the plot size in Peru is 0.75 x 0.9.`

**Comment by aco46** [comment]
@bellerbrock we should make it more open to allow the breeders use the width and length that fit what is done in their breeding programs. Looks like in the initial implementation @nickmorales considered use cases within cassava programs.

**Comment by nickmorales** [comment]
@bellerbrock maybe avoid leaving it open as a text field. we can add 0.1 increments from 0 to 10 meters in the dropdown select and also include 0.25 and 0.75 because those are probably most common.

**Comment by aco46** [comment]
@nickmorales is there a reason why we can't make both option more flexible for the users to just enter their plot width and length. Will it break anything in the backend? The list may end up becoming too long.

**Comment by bellerbrock** [comment]
@nickmorales @aco46 A text field would be dangerous because there'd be lots of room for user error. But I agree a dropdown could get unwieldy. How about a text field that does not accept anything that isn't a 0.1 increment between 0-10?

**Comment by aco46** [comment]
@nickmorales @bellerbrock I definitely agree with you guys.  @bellerbrock I'm not sure if you restrict the field to numeric values, it would take values like '0.1'

**Comment by aco46** [comment]
closed via #2244
