### ISSUE TITLE
System fails running R for the calculation of Alpha design. If the block size is the square root of the number of treatments, the design adds an extra block to each rep.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#223]

**Comment by bauchetg** [comment]
I guess that one is for me
Thanks

Guillaume

**Comment by suryasaha** [comment]
Hi Guillaume, Simplest way to do that is to just assign it to yourself.

**Comment by bauchetg** [comment]
Hey Surya,

Ok, maybe I will ask you a quick brief on the ticket management tomorrow, making sure I am doing things correctly.
Thanks

Guillaume




On Aug 30, 2015, at 10:23 PM, Surya Saha <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Guillaume, Simplest way to do that is to just assign it to yourself.

**Comment by isaak** [comment]
Hi Alex, if you could add a snippet of the error message and code where you see the error, it may help.

**Comment by aco46** [comment]
![screenshot from 2015-08-31 10 46 49](https://cloud.githubusercontent.com/assets/10618260/9581469/ac1f22fe-4fcd-11e5-951c-738982ab3021.png)

**Comment by jeremyde** [comment]
Be sure to check the version of the R package Agricolae.  Was there a recent update?  Updates have broken the input and/or output parsing in the past resulting in a similar message.

Jeremy

**Comment by isaak** [comment]
On cassavabase and cassava-test, we update R to 3.2 and all packages have been updated to their latest versions,  3 - 4 months ago. The R packages versions in use on the live and test sites are here: https://github.com/solgenomics/sgn/blob/master/R_files/DESCRIPTION

**Comment by aco46** [comment]
I updated the R in my VM and everything works fine now.
