### ISSUE TITLE
Multilocation trial creation leaves spaces in plot name

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2237]
Expected Behavior 
--------------------------------------------------------------------------
Multilocation trial creation adds spaces in plot name. Also uses location full names rather than abbreviation, which sometimes have characters like ',' in them. Both spaces and commas then throw off tools like the Fieldbook that try to name saved image files with the plot name.

For Bugs:
---------

**Comment by nickmorales** [comment]
the multi-location trial creation should probably be merged into the workflow for trial creation

**Comment by nickmorales** [comment]
@bellerbrock do you want to work on that larger refactoring?

**Comment by bellerbrock** [comment]
Sure I'd be interested
