### ISSUE TITLE
anova bug:  runs without outputting any results

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2241]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
While running an anova on test database it runs forever with no output, ex:
https://cassavabase.org/breeders/trial/340?format=
While clicking the new spinning wheel displays for the pca and correlation without request

<img width="769" alt="screen shot 2018-10-24 at 10 29 02 pm" src="https://user-images.githubusercontent.com/12039071/47474355-319dc400-d7dc-11e8-9c90-c877ebc2b303.png">

**Comment by isaak** [comment]
fixed:   #2243
