### ISSUE TITLE
Show the pedigree also as a pedigree string on stock detail pages

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#225]

**Comment by lukasmueller** [comment]
From "Rules for Maize pedigrees.pdf" sent by Prasad (note that only a subset of these rules, to be determined, will be implemented in cassavabase). 

34.1 Nomenclature For Writing Maize Pedigrees At CIMMYT
General rules of pedigree writing
1) English is the official pedigree writing language at CIMMYT. For e.g. FS will stand for full sibs and not HC (hermano completo in Spanish). This would also apply to naming synthetics and populations (e.g. EY will stand for early yellow and not AP (amarillo precoz in Spanish)).
2) Do not use a period “.” anywhere in the pedigree.
3) Do not use spaces anywhere in the pedigree
4) To make words distinguishable in a pedigree use alternating upper case and lower case (sentence case) to make the pedigree more readable e.g. ObatanpaSR or EarlyWhiteSynthetic. This is more readable than writing EARLYWHITESYNTHETIC or earlywhitesynthetic.
5) Writing a pedigree is like writing a mathematical formula. The number of open brackets must equal the number of close brackets. The bracket types must oppose each other for instance, a round open bracket “(“ must be complemented only with a close round bracket. It is wrong to write (CML505/CML509]. Also, only round “()” brackets are allowed in a pedigree (see point 7).
6) Hyphens, “-“, should only be used to indicate a generation advance (e.g. by selfing or sibbing). Obatanpa-SR is confusing to the computer as it would mean that Obatanpa was selfed one generation.
7) Never use flower “{}”, square “[]” or triangular “<>” brackets anywhere in the pedigree.
Writing Inbred Pedigrees
8) For a selfing generation derived by selfing and retaining the identity of individual cobs, indicate the ear selected by the suffix “-“ and ear number e.g. ZM401F2-1, ZM401F2-2 etc.
9) For a selfing generation derived by selfing and bulking the cobs, indicate the bulked generation by the suffix “-B“, e.g. ZM401F2-B. DO NOT use lower case “b” to indicate this.
10) When you begin selfing a pedigree cross e.g. CML505/CML509 you need to put round brackets around the hybrid before making your stocklist for the selfed generation e.g. (CML505/CML509)-1. (This is done automatically in fieldbook by clicking the option of putting brackets when making the stocklist). Failing to put brackets before indicating the selfing generations could result in a pedigree CML505/CML509-1 which indicates that this is a hybrid between CML505 and CML509-1 (the first ear selected by selfing CML509) and not the first ear selection from the self of the hybrid CML505/CML509.
￼￼117
11) For an F2 population developed by selfing an F1 and bulking cobs use the suffix F2 (ZM401F2) and NOT the suffix “-B” (ZM401-B).
12) If you maintain an inbred line by sib mating use the suffix “-#” eg. ZM401F2-1-#.
13) If you need to indicate a certain type of selection during inbreeding keep it brief and enclose it within round brackets e.g. ZM401F2-2(Mod2)-1 indicates that ear number 2 of the S1 generation was selected for QPM modification 2 and selfed to give ear number 1. ZM401F2-2(GLS2)-2 indicates that a plant with GLS score of 2 in the S1 generation was selfed to and ear number 2 was retained. Such description is usually not required except when you are doing special studies and you are differentiating plants for specific scores of traits. In the normal case one would select the best plants and self them. The pedigree of the harvested ear would be written as ZM401F2-2-1.
14) Do not use Sn to indicate that the germplasm has been selfed “n” times and is a fixed line.
15) When an inbred line (e.g. ZM401-4-2-1-B) is selfed and bulked repeatedly follow the procedure below:
a) If repeatedly bulked two generations the pedigree would read ZM401-4-2-1- BB
b) If repeatedly bulked three generations the pedigree would read ZM401-4-2-1- BBB
c) If repeatedly bulked four generations the pedigree would read ZM401-4-2-1- B*4. This would apply to any repeated bulking of 4 generations or more i.e. if it is bulked six generation the pedigree would read ZM401-4-2-1-B*6.
16) When an inbred line (e.g. ZM401-4-2-1-#) is maintained by sib mating repeatedly follow the procedure below:
a) If repeatedly sib mated two generations the pedigree would read ZM401-4-2- 1-##
b) If repeatedly sib mated three generations the pedigree would read ZM401-4-2- 1-###
c) If repeatedly sib mated four generations the pedigree would read ZM401-4-2- 1-#*4. This would apply to any repeated sib mating of 4 generations or more i.e. if it is sib mated six generations the pedigree would read ZM401-4-2-1- #*6.
(Note: for points (15) and (16) above the Fieldbook would generate a stocklist with pedigree having “-B” or “-#”. Once you have made the stocklist, highlight the pedigrees and run Fieldbook/Clean Pedigree. This will format the pedigree as per the two points above).
17) If you have selfed an inbred line and wish to bulk the harvest from one plot into two or more separate bulks to represent separate selections (e.g. separation of the better looking cobs into a Breeder’s bulk and the remainder into another bulk) then use the pedigree extensions “-B1”, “-B2” etc. This would read as follows: ZM401-4-2-1-B1, ZM401-4-2-1-B2, etc.
18) Always separate the generation described in (17) above with a “-“ before and after the generation. E.g. write the pedigree as ZM401-4-2-1-B-B1 and NOT as ZM401-4-2-1- BB1; write the pedigree as ZM401-4-2-1-B-B1-B and NOT ZM401-4-2-1-B-B1B.
Writing Hybrid Pedigrees
19) Use the delimiter single forward slash “/” to indicate the first cross (e.g. CML505/CML509).
￼118
20) Use the delimiter double forward slash “//” to indicate the second cross (e.g. CML505/CML509//CML508).
21) Use the delimiter triple forward slash “///” to indicate the third cross (e.g. CML505/CML509//CML509///CML509).
22) Do not use “x” or “X” or “*” as a delimiter.
Writing pedigrees to indicate recombinations
Generally there are three types of recombinations:
• half sibs (HS) where pollen from a group of entries is bulked and female entries
whose identity is retained at harvest are pollinated;
• full sibs (FS) where cross between two parents and made and identities of both
parents are retained at harvest; and
• complete recombination where pollen from a group of entries is bulked and the same
group pollinated or seed from a group of lines crossed in a diallel are bulked. By doing this, the identity of the male and female is not retained in the pedigree.
Writing pedigrees to describe a recombination:
23) For half sibs indicate each ear as follows: ZM401HS1, ZM401HS2 etc.
24) For full sibs indicate each ear harvested as follows: ZM401FS1, ZM401FS2 etc.
25) Use small case “c” to indicate cycles c1, c2 etc.
26) A physical mix of full or half sibs or a first complete recombination as ZM401F1 (This is not your final OPV).
27) A further recombination of ZM401F1 should be indicated as ZM401F2.
28) For any further increase of ZM401F2 indicate it as ZM401 without any suffix after the name of the OPV. Just the name of the OPV would indicate that it is sufficiently recombined to be considered as the final product.
￼119

**Comment by bellerbrock** [comment]
Ensure pedigree strings are working on stock detail pages, and add ability to search for them on manage accessions page

**Comment by bauchetg** [comment]
covered with #1148
