### ISSUE TITLE
Trim accession names during upload.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2255]
Expected Behavior 
--------------------------------------------------------------------------
spaces before and after the accession name should be removed.

For Bugs:
---------

**Comment by bauchetg** [comment]
Pretty sure this was implemented no?  #1677 #1672

**Comment by titima15** [comment]
Yes, this was already implemented.

**Comment by nickmorales** [comment]
pretty sure this has been implemented. maybe knowing where this happened would help, e.g. it was a very out of date server

**Comment by aco46** [comment]
I thought as much. But Qi told me that he tried it yesterday.

**Comment by aco46** [comment]
I just checked, it works well. Will close this ticket.
