### ISSUE TITLE
scale phenotype data before selection index

### ISSUE THREAD

**Issue by pvnsprasad** [solgenomics/sgn#2261]
Expected Behavior 
--------------------------------------------------------------------------
Formula for selection index needs the data to be scaled (e.g. subtract the mean value for the trait and divide by its standard deviation). Otherwise the index is useless. 

For Bugs:
---------

**Comment by isaak** [comment]
related #1456

**Comment by lukasmueller** [comment]
Use an analysis to precompute the mean etc.?

**Comment by bellerbrock** [comment]
@lukasmueller from our discussion, we can accomplish this by enabling analysis trials as selection index input

**Comment by lukasmueller** [comment]
I think this is basically solved with the storage of analysis results, so I am closing this ticekt.
