### ISSUE TITLE
Musabase: ability to create a list of cultured embryos to EET trial

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2269]
Expected Behavior 
--------------------------------------------------------------------------
Once embryos have reached hardening, the subsequent of IDs are transferred to be planted in EET trials. Having an option to create an accession list from a cross page based on the list of embryos reaching hardening (some terminology may change) would be very useful

For Bugs:
---------

**Comment by lukasmueller** [comment]
I think this is solved with the btract system.
