### ISSUE TITLE
Intercross beta evaluation at IITA

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2276]
Expected Behavior 
--------------------------------------------------------------------------

This is a testing conducted at IITA Ibadan with the pollination team of the Intercross PhenoApp
[Intercross beta](https://www.dropbox.com/s/uiqakkw39lp7mlh/intercross-cbase.pdf?dl=0)
@titima15 @aafolabi please feel free to elaborate on that first draft

For Bugs:
---------

**Comment by titima15** [comment]
This ticket is obsoleted.
