### ISSUE TITLE
harvested seed and terminology changes for musa

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2282]
Expected Behavior 
--------------------------------------------------------------------------
-> seeds harvested and embryo rescued terminology and ID storage:
"Embryo rescue" term is incorrect and should be replace by "Embryo culture"
-Only "Good Seeds" ( and not "Embryo rescue good seeds") can be used for "Embryo culture"
-Practically each seed harvested go through embryo rescue (=<50 seeds) or to the nursery (50+).
-Each seed requires a unique ID no matter what will work or not.
-Several other terms required edits @mkaranja can you provide these?
original issue #2268 

For Bugs:
---------

**Comment by titima15** [comment]
This ticket is obsoleted.
