### ISSUE TITLE
organism detail page does not work with organism id

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#230]

**Comment by noefp** [comment]
Naama already fixed it. The problem was that sgn-test was not pull from cxgn-corelibs in a long time.

I got another query joining one time less than the older code:

      my $query = "SELECT COUNT
       (phenome.locus.locus_id)
       FROM phenome.locus
       JOIN sgn.common_name using (common_name_id)
       JOIN sgn.organismgroup  on (common_name.common_name = organismgroup.name )
       JOIN sgn.organismgroup_member USING (organismgroup_id)
       WHERE locus.obsolete = 'f' AND sgn.organismgroup_member.organism_id=?";
