### ISSUE TITLE
Issue on stock merging: cvterm undefined?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2312]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
While running the merging script:
perl bin/merge_stocks.pl -H db4.sgn.cornell.edu -D sandbox_cassava -x /home/production/Set_8.txt | tee -a ~/Set_8.log
I getan error:
: Can't call method "cvterm_id" on an undefined value at /usr/local/share/website/cxgn-corelibs/lib/CXGN/Chado/Stock.pm line 970,
Which corresponds to:
my $female_parent_id = SGN::Model::Cvterm->get_cvterm_row($self->get_schema, 'stock_relationship', 'female_parent')->cvterm_id();
Corresponding cvterm is defined under stock relationship:  76437 |    37 | female_parent
Am I misunderstanding the error? any idea of what may block?

**Comment by titima15** [comment]
It should be.......get_cvterm_row($schema, 'female_parent', 'stock_relationship')->cvterm_id();

**Comment by nmenda** [comment]
this is a bug in CXGN::Chado::Stock (in cxgn-corelibs) but it is deprecated and we need to use instead 
CXGN::Stock which replaces the above. It is in the sgn repo.

**Comment by bauchetg** [comment]
Thanks
Following comments I could get it fixed and running on my local
 but when moved to test it did not do, with or without the CXGN::Chado::Stock to CXGN::Stock
changes:  [f1650b0](https://github.com/solgenomics/sgn/commit/c7e50a3b1df13de3f82eec263f15aecc63871232) and  [aab8f8f](https://github.com/solgenomics/cxgn-corelibs/commit/aab8f8f185e3440e9e0beed58884dce43345e187)
https://github.com/solgenomics/sgn/commit/c7e50a3b1df13de3f82eec263f15aecc63871232
@nickmorales the commit appears on your name I just installed a new vm and your key was still there, sorry :-(

**Comment by nmenda** [comment]
@bauchetg CXGN::Stock replaces CXGN::Chado::Stock, so should avoid using the latter.
If something is missing from CXGN::Stock then it should be added 

Do you mean get_cvterm_row for female_parent and male_parent? That is not necessary because the merge function updates all stock_relationships regardless of the type_id, so no need to explicitly state the relationship type

**Comment by bauchetg** [comment]
Thanks Naama, we fixed it with Lukas' help.
[639a4628](https://github.com/solgenomics/sgn/commit/639a462830b753f77da7ded08b22cbad7424386b)
