### ISSUE TITLE
trial creation broken: Yapri bug

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2313]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
When running a Alpha lattice trial design error shows up (28 entries, block 7, rep 4) and asking for 7 rows) which points to:
`/usr/local/share/website/local-lib/lib/perl5/R/YapRI/Block.pm line 500`
The run_block routine crashes on $self->get_blockname() it seems :
sub run_block {
    my $self = shift;

    my $rbase = $self->get_rbase();
    $rbase->run_commands($self->get_blockname());
}

**Comment by lukasmueller** [comment]
Was this fixed? Does anybody know?

**Comment by bellerbrock** [comment]
This is still an issue! at least on some databases. Jolien reported that creation of wescott design trials on sweetpotatobase fails with the error: 
![error](https://user-images.githubusercontent.com/11297346/53745131-6d245b00-3e6c-11e9-8aa6-9e7f44b4cb2e.png)

**Comment by bellerbrock** [comment]
additional output from the error:
`Error in array(dim = c(nr, nc)) : negative length vectors are not allowed
Calls: cr.w -> array
In addition: Warning message:
In array(dim = c(nr, nc)) : NAs introduced by coercion to integer range
`

Based on this and some more testing it looks like wescott trial creation is only broken under certain conditions - when the user input for number of columns is less then the number of columns between checks (which defaults to 10).

Maybe making it a requirement that total # of columns be greater than # of columns between check rows is all that is needed?

**Comment by aco46** [comment]
Fixed
