### ISSUE TITLE
Website crashes when utf8 or latin encoded strings are present in location prop data

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2320]
Expected Behavior 
--------------------------------------------------------------------------

get_location_json() is called in SGN::Controller::Root; when it returns utf8 encoded strings, the website crashes. The easiest fix for now is that the output of get_location_json is to be forced to non-utf8 before it is returned.

For Bugs:
---------

**Comment by nickmorales** [comment]
closed by #2321
