### ISSUE TITLE
Boxplotter tool is showing negative values in place of actual minimums

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2334]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

Sweepotatobase.org, working with the LW_actives dataset. Saw the same issue with erroneous negatives for many of the dataset's yield traits. For example, the minimum measurement for 'Total number of root counting per plot' in the dataset is 15, but the boxplottter tool shows a minimum of -8.

Also all the real measurements should be integers, as you can't have fractional roots, but when filtering by germplasm the tool shows many negative and non-integer values. 

![boxplotter_negative_minimum](https://user-images.githubusercontent.com/11297346/51857925-79fbdf00-2301-11e9-9332-834cd0d9cc6d.png)
![boxplotter_actual_minimum](https://user-images.githubusercontent.com/11297346/51857918-76685800-2301-11e9-879b-7255735551f1.png)

**Comment by dauglyon** [comment]
Ah, I just realized whats causing this. The boxplotter uses the Tukey style (what I learned) so the whisker is Q_n +/- 1.5*IQR but I forgot to min that with the true lowest/highest value
