### ISSUE TITLE
Upgrade R to 3.2 in all servers that implement solQTL and solGS

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#235]
Steps:
http://www.r-bloggers.com/upgrade-and-update-r-2-15-to-r-3-0-in-debian-wheezy/
After the last step, you may need to do this :  
-- dist-upgrade 
-- or manually install whatever packages might be held back from upgrading

**Comment by isaak** [comment]
Aimin, could you also do it on zeabase?

**Comment by aiminy** [comment]
ok,
I will do it.
Aimin

**Comment by lukasmueller** [comment]
I think this was done.

**Comment by isaak** [comment]
sweetpotatobase, yambase, musabase still running R 2.15.

**Comment by aiminy** [comment]
Thank you for letting me know.
Aimin

**Comment by lukasmueller** [comment]
R upgraded for Sweetpotatobase.org

**Comment by lukasmueller** [comment]
also upgraded for sweetpotatobase-test...

**Comment by lukasmueller** [comment]
upgraded musabase.org

**Comment by lukasmueller** [comment]
upgraded musabase-test

**Comment by lukasmueller** [comment]
upgraded yam base...

**Comment by lukasmueller** [comment]
upgraded yambase-test
