### ISSUE TITLE
Allow a seedlot transaction that resets the value in the seedlot to the given value (transaction is calculated to adjust to the given value)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2359]
Expected Behavior 
--------------------------------------------------------------------------

Maybe this feature already exists when you upload the count/weight data using the verify app, it should generate a transactions that will result in the correct number in the seedlot

As requested by Jolien

For Bugs:
---------

**Comment by nickmorales** [comment]
this should be implemented already. the database will create a transaction to reflect the uploaded "current weight" and "current count"

![image](https://user-images.githubusercontent.com/7028512/53249365-ed390c80-3685-11e9-948b-20639cec7b22.png)

**Comment by lukasmueller** [comment]
Great, that's what I vaguely remembered... Super, I am closing the ticket.
