### ISSUE TITLE
add planting and harvest date inputs to existing trial upload workflow

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2363]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
There seem to be duplicate tickets for this issue

**Comment by bellerbrock** [comment]
What's the status of this feature? Edie Paul, the consultant working on loading historical sweetpotato data, said this morning that this is crucial to her work.

**Comment by bauchetg** [comment]
Hi @bellerbrock , I made a changes in mason and in the controlle and a patch implemented here: ﻿﻿﻿https://github.com/solgenomics/sgn/tree/topic/trial_metadata.
Some more work required
