### ISSUE TITLE
musa and sweetpotato sites not Slurm ready

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2367]
-- Analysis tools nor working.

An error occurred! Failed to load role: CXGN::Tools::Run::Plugin::Slurm Can't locate Slurm.pm in @INC (@INC contains: /usr/local/share/website/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/share/website/local-lib/lib/perl5 lib /usr/local/share/website/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/share/website/local-lib/lib/perl5 /usr/local/share/website/biosource/lib /usr/local/share/website/sgn/lib /usr/local/share/website/cxgn-corelibs/lib /usr/local/share/website/tomato_genome/lib /usr/local/share/website/ITAG/lib /usr/local/share/website/Cview/lib /usr/local/share/website/Phenome/lib /usr/local/share/website/local-lib/lib /usr/local/share/website/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi /usr/local/share/website/local-lib/lib/perl5 /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/local/share/website/cxgn-corelibs/lib/CXGN/Tools/Run/Plugin/Slurm.pm line 13.
BEGIN failed--compilation aborted at /usr/local/share/website/cxgn-corelibs/lib/CXGN/Tools/Run/Plugin/Slurm.pm line 13.
Compilation failed in require at /usr/local/share/website/local-lib/lib/perl5/Module/Runtime.pm line 317.

**Comment by lukasmueller** [comment]
fixed.
