### ISSUE TITLE
import data from btract ONA server  to musabase is broken

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2369]
Expected Behavior 
--------------------------------------------------------------------------
`Writing to /export/prod/tmp/musabase.org/ODK_ONA_cross_info/entire_odk_cross_progress_html_390.txt
$VAR_DUMP1 = {};
Arusha
Check 4.1:Fri Mar  1 12:47:56 2019cross_wishlist /export/prod/sgn_archive/1367/cross_wishlist_MusaBase_0/cross_wishlist_Arusha.csv
Number ODK Cross Submissions: 1
Writing to /export/prod/tmp/musabase.org/ODK_ONA_cross_info/entire_odk_cross_progress_html_390.txt
$VAR_DUMP1 = {};
Arusha
Generate login button for logged in user...
Retstring is <select class=“form-control” id=“cross_wishlist_location_id”    name=“cross_wishlist_location_id”>
Opening /export/prod/tmp/musabase.org/ODK_ONA_cross_info/entire_odk_cross_progress_html_390.txt
[error] Caught exception in SGN::Controller::AJAX::ODK->get_odk_cross_summary_cached “malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before “(end of string)“) at lib/SGN/Controller/AJAX/ODK.pm line 449, <$fh> chunk 1.”
Opening /export/prod/tmp/musabase.org/ODK_ONA_cross_info/entire_odk_cross_progress_html_390.txt
Retstring is <select class=“form-control” id=“cross_wishlist_male_trial_id”    name=“cross_wishlist_male_trial_id”>
Retstring is <select class=“form-control” id=“cross_wishlist_female_trial_id”    name=“cross_wishlist_female_trial_id”>
Retstring is <select class=“form-control” id=“cross_wishlist_list_male_trial_id”    name=“cross_wishlist_list_male_trial_id”>
Retstring is <select class=“form-control” id=“cross_wishlist_list_female_trial_id”    name=“cross_wishlist_list_female_trial_id”>
[error] Caught exception in SGN::Controller::AJAX::ODK->get_odk_cross_progress_cached “malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before “(end of string)“) at lib/SGN/Controller/AJAX/ODK.pm line 387, <$fh> chunk 1.

Suggestion from Nick: ODK form ids are out of sync between musabase and ona (if the forms were recreated or something on ona) or the odk forms (and the identifiers in those forms) have changed or the files in general are out of sync between musabase and ona

For Bugs:
---------

**Comment by titima15** [comment]
Fixed
