### ISSUE TITLE
list transform2Id is slow

### ISSUE THREAD

**Issue by dauglyon** [solgenomics/sgn#2397]
Expected Behavior 
--------------------------------------------------------------------------

Transformation is taking a surprising amount of time. Is there a more efficient way of doing this transform? Slowness may be coming from this loop:

[/lib/CXGN/List/Transform/Plugin/Accessions2AccessionIds.pm#L38-L57](https://github.com/solgenomics/sgn/blob/a2290ccbd709b5f6502e10fdefb8aeec23e07b47/lib/CXGN/List/Transform/Plugin/Accessions2AccessionIds.pm#L38-L57)

@bellerbrock you're git-blamed on this code, any insights?

For Bugs:
---------

**Comment by bellerbrock** [comment]
@dauglyon hmm, yeah, I can see how that probably doesn't scale well. I imagine for hu it would be much faster to handle the entire list at once in a single query. Something like ```my $rs = $schema->resultset("Stock::Stock")->search( { uniquename => { -in => @list  } , type_id    => $type_id });```

**Comment by bauchetg** [comment]
for info: 
300 accessions list = <3s.
2000 accessions list > 20 s. which is too long

**Comment by bellerbrock** [comment]
Whoops, didn't mean to close it. Also would be go to handle synonyms more efficiently too, though I doubt they're a significant factor in the speed.
