### ISSUE TITLE
add Yam to the submit.rtbbase.org list of crops

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2403]
Expected Behavior 
--------------------------------------------------------------------------

only cassava, banana and sweet potato appear in the list. Yam should appear as well.

For Bugs:
---------

**Comment by dauglyon** [comment]
Someone with admin privileges to the @Planteome org needs to update which repos the app can manage via the GitHub organization app settings page

@marieALaporte @cooperl09

**Comment by cooperl09** [comment]
Hi @dauglyon, I added the Yam repo to the list.  
I got shunted to this page, but perhaps you have to update that?
https://submit.rtbbase.org/deploy?installation_id=513295&setup_action=update

**Comment by dauglyon** [comment]
@cooperl09 Once it is added to the app access list, it _should_ update the page you were sent to, and YamBase should appear on that page. Unfortunately, I can’t debug it as I don't have access to the app settings for Planteome, and the issue isn't occurring in my test instance. I think it may possibly be related to the expired certificate on rtbbase. @lukasmueller are you able to fix that?

**Comment by cooperl09** [comment]
From here: https://submit.rtbbase.org/
When I try to add another repository to the list, I get a 404 page not found erorr 

https://github.com/apps/ontology-variable-submission-bot

**Comment by dauglyon** [comment]
So, the GitHub App page is restricted to those who have Planteome access, so I don't know if that is the correct link or not, because I no longer have access. I would need permissions to see the Planteome Organization app settings to debug this issue.

**Comment by cooperl09** [comment]
@dauglyon I gave you admin access to  https://github.com/Planteome/Ontology-Variable-Request-App.  Looks like there is an issue with the dependencies?

**Comment by dauglyon** [comment]
Issue was an expired HTTPS certificate
