### ISSUE TITLE
give description of different cross types

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2411]
Expected Behavior 
--------------------------------------------------------------------------
There are many cross types listed when adding new crosses to the database, but they are not defined.
A description for what each of the cross types means would help.

For Bugs:
---------

**Comment by lukasmueller** [comment]
In the crossing workflow, maybe implement a popup that shows more info...

**Comment by bauchetg** [comment]
available here:
https://cassavabase.org/breeders/crosses/

Just need to be moved form "Add a cross " to "upload crosses"

<img width="1105" alt="Screen Shot 2019-07-29 at 12 14 07 PM" src="https://user-images.githubusercontent.com/12039071/62064283-86062200-b1fa-11e9-9da8-0d3f5103aeae.png">

**Comment by titima15** [comment]
I already added the description, but not yet merged.
