### ISSUE TITLE
include intercross upload format

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2415]
Expected Behavior 
--------------------------------------------------------------------------
@titima15 this is the expected upload format
[intercross_upload_format.csv.zip](https://github.com/solgenomics/sgn/files/3065791/intercross_upload_format.csv.zip)
It is a .csv for now but we request an .xls format output to Phenoapps folks
related to #2030 

For Bugs:
---------

**Comment by trife** [comment]
What is the advantage of an xls format output or why would that be preferred?

**Comment by bauchetg** [comment]
Hello @trife, Coordinate and  Intercross come as .csv where Fieldbook is .xls I believe.
Not a particular technical reason but harmonizing the different input types we currently have (.xls, .csv, .txt) would be nice.

**Comment by trife** [comment]
Field Book exports to csv as well. It has the option of importing xls but that's the only use of the format in any of our apps. File format should be a moot point as we begin to incorporate BrAPI compatibility.

**Comment by titima15** [comment]
Done via 1f4301a
