### ISSUE TITLE
Product profile management

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2419]
Expected Behavior 
--------------------------------------------------------------------------

Enable product profiles to be defined in the database, specific for each breeding program, possibly in a section on the  Breeding Program Detail page (which would become a "manage breeding program" page). 

Should allow configuring traits, reference values, and checks.

Search the database for stocks that match or exceed the product profile.

Show a comparison of the specific catalog entry and the check in a bar chart displaying the differences to the check.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Could be implemented as a project prop for breeding programs. Configuration on the Breeding Program detail page.

**Comment by lukasmueller** [comment]
Can this ticket be closed? I think we should probably add a different ticket for the searching and the future features.

**Comment by titima15** [comment]
Close via 9f815b0
