### ISSUE TITLE
Accession upload gives an error during upload.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#2428]
Expected Behavior 
--------------------------------------------------------------------------
Reported by Adenike (IITA Abuja).

I checked the error.log file, but couldn't see any error I can identify as the problem.
The list she was uploading is in Yambase.org public list with list name as TDrSCG2019.

For Bugs:
---------

**Comment by titima15** [comment]
@aco46 As soon as I saw the contact form that she reported about the problem, I asked if there was any error message that popped up during uploading. She didn't reply back.

**Comment by aco46** [comment]
I guess she may not have received the email. The error message is not informative. It might be a minor bug. Looks like this is specific to Yambase.org.
![image](https://user-images.githubusercontent.com/10618260/56667694-4a4c4100-667c-11e9-93d1-b62104f550c5.png)

**Comment by lukasmueller** [comment]
This may have been due to a slow connection.
