### ISSUE TITLE
brapi remote query gives 502 error

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2438]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Querying musabase stock from mgis brapi gives a sporadic error nginx 502 error for specific stocks. This error can be reproduce accessing the stock page directly from musabase.
Stocks producing the 502 error have associated GBS data. ex, calcutta 4: https://musabase.org/stock/123380/view

### Environment 

Musabase.org
#### Steps to Reproduce

From the error log, query hangs on:
JOIN nd_experiment_projChild process 3253 exited with status 0 - signal was 9
NGINX time out is set on default cong using: keepalive_timeout 65; types_hash_max_size 2048;
worker_connections 768;
I restarted nginx, this did not change the issue
Is there an other system conf which may stop/prevent the request?

**Comment by nickmorales** [comment]
genotype search should be moved to asynchronous request and does not need to return actual markers and genotype info to populate genotype table on stock page.

502 errors caused because the VM ran out of memory from all the marker info being returned on load of stock detail page.
