### ISSUE TITLE
Wrong link and process in accession uploading for cassava-test (bootstrap version)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#244]
https://cassava-test.sgn.cornell.edu/breeders/accessions/

1/ option names displayed are wrong:
[Add Pedigree] [Upload Pedigree File] 
We expect:
[Add] [Upload Pedigree File] 
2/ When a list of accessions is submitted (using "Add pedigree"), if there are accessions already in the DB it wont upload the new accessions remaining (see screenshots).

![screen shot 2015-10-01 at 9 34 46 am](https://cloud.githubusercontent.com/assets/12039071/10222143/6049b3ba-6820-11e5-9330-5f47b869bf68.png)
![screen shot 2015-10-01 at 9 34 59 am](https://cloud.githubusercontent.com/assets/12039071/10222146/6532571a-6820-11e5-9c88-46cba4696f91.png)

**Comment by nickmorales** [comment]
This is not a bootstrap issue. It is some issue with the data that accessions.pm is returning to accessions.js, when Fuzzy search is not checked

**Comment by nickmorales** [comment]
fixed in 1215bfc3fbd9ef906d53638aacb7ce57635eb0e6
