### ISSUE TITLE
Update wizard function doesn't work particularly with accessions associated with new genotyping protocols

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#2445]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
The new genotyping protocol that you should check is GBS ApeK1_18

**Comment by nickmorales** [comment]
there are new type_ids that the materialized view should should use

**Comment by bellerbrock** [comment]
Views hadn't refreshed. Fixed by manually running the psql function `SELECT refresh_materialized_views();`
