### ISSUE TITLE
Effective genotype data transfer from breedbase to dart services

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2454]
Expected Behavior 
--------------------------------------------------------------------------
Dart has implemented vendor calls in their system during brapi meeting and have a testing interface:
https://ordering-testing.diversityarrays.com/brapi/v1/calls
This would allows possible genotyping trial transfer from breedbase

For Bugs:
---------

**Comment by lukasmueller** [comment]
Needs to be coordinated with Peter Selby.

**Comment by lukasmueller** [comment]
This ticket should implement a brapi-based submission system for genotyping services in general (not just Intertek)
