### ISSUE TITLE
Dartseq export format issues

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2455]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Dartseq download format is no longer  compliant with Dart website upload requirements
For example: https://cassavabase.org/breeders/trial/5724?format=
-> File download format should be .csv and not .xls
-> The rows corresponding to "BLANK" (G12 and H12) should not be included in the output file

Here are identified issues on each info fields of the file: 
Plate ID: header for this column should be "PlateID" (instead of "Plate ID")
Row: OK
Column: OK
Organism: current is Manihot esculenta should be Cassava
Species: OK (Manihot esculenta)
Genotype: OK
Tissue: some plate show "NA", other "Leaf", tissue sample should always be specified, preferably lower case (ie: "leaf"). This info is populated by user in the work
Comments: OK

Dart as posted a detailed guideline on this:
https://www.diversityarrays.com/orderservices/samplefileformat/

**Comment by bauchetg** [comment]
Some edits done on: topic/update_dartseq_layout branch (file header change, Organism). 
Organism is harcoded has "Cassava", not ideal for other crops.

Additional changes required: 
-> Row: currently numbered (1 to 8)  should be letter (A to H) as for Intertek plugin, using the letter only
-> Tissue: this info is provided through the upload dialog (free text) an should lower case constrained

**Comment by nickmorales** [comment]
does it really need to say "Cassava" instead of "Manihot esculenta"?

**Comment by bauchetg** [comment]
Yes @nickmorales . The Organism column includes the vernacular name where the species column includes taxonomical info (genus and specie).
