### ISSUE TITLE
trials tree cache is in tmp folder and should be moved to more permanent location

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2456]
Expected Behavior 
--------------------------------------------------------------------------
The trial tree that is drawn on manage->trials/crosses/genotyping plates is cached in tmp, but now that /tmp will be deleted periodically by cron job, this needs to be a more stable directory.

For Bugs:
---------

**Comment by isaak** [comment]
@nickmorales, how often does this happen. The same issue applies for the solGS data.

**Comment by nickmorales** [comment]
Surya is setting it to be every 2 days i think. Actually it might make more sense to keep the:
cluster_shared_tempdir sgn_local key on the mounted drive instead of /tmp given that in theory it is supposed to be shared across machines.
The tempfiles_base key could stay on /tmp so that mason, cgibin, etc can use the local /tmp
