### ISSUE TITLE
Cross experiment page interface changes: cross plan (=wishlist) 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2476]
Expected Behavior 
--------------------------------------------------------------------------
After discussion with Peter, seems beneficial to split the page into three chronological sections including: (1) Cross plan, (2) Cross performed, (3) Cross data collected (phenotypes/seeds).

(1) Cross plan section should cover aspects such as: 
-parental lines
-breeding objective/targeted trait for this cross (ie improving caroteinoid content)
-crossing block design
-number of seeds targeted.

For Bugs:
---------

**Comment by lukasmueller** [comment]
This is part of the new cross implementation by Titima. Fixed in #2545
