### ISSUE TITLE
In the wizard, list creation works only for first selection box, not for selection box 2-4.

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2478]
Expected Behavior 
--------------------------------------------------------------------------

Storing selected items in lists from selection boxes 2-4 does not work. There is no error message. The Add to list function behaves similarly I think.

(This was observed on Sweetpotatobase.org, must confirm for other sites)

For Bugs:
---------

**Comment by bauchetg** [comment]
interesting I though we solved that with @dauglyon . David was it pushed to master?

**Comment by lukasmueller** [comment]
Maybe we need to update Sweetpotatobase and we are done?

**Comment by dauglyon** [comment]
We did this hot on cassava-test then pushed to master. What is the last release sweet potato was updated to?

**Comment by dauglyon** [comment]
Could be a different bug, but unlikely. I can check when I'm out of work.

**Comment by lukasmueller** [comment]
I just updated Sweetpotatobase and the saving now works! Closing the ticket. Thanks and cheers!
