### ISSUE TITLE
fix warnings when server starts

### ISSUE THREAD

**Issue by noefp** [solgenomics/sgn#249]

**Comment by lukasmueller** [comment]
one fix in c4acc27c25e48fff0e0c84ee9ba58cbcd8737416

**Comment by lukasmueller** [comment]
Struggling with this one on localhost: Does anyone else see this followed by a huge stack backtrace after server startup  (all involved packages seem up to date):
Passing a list of values to enum is deprecated. Enum values should be wrapped in an arrayref. at /home/mueller/cxgn
/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util/TypeConstraints.pm line 437.
        Moose::Util::TypeConstraints::enum("LineCap", "butt", "round", "square") called at /home/mueller/cxgn/local
-lib/lib/perl5/Graphics/Primitive/Brush.pm line 9

**Comment by lukasmueller** [comment]
Emailed maintainer of Graphics::Primitive, which seems to be at the core of this problem,
Cory Watson, "<gphat@cpan.org>"

Hi Cory,

when I run libraries that use Graphics::Primitive libraries, I get the following warning:

Passing a list of values to enum is deprecated. Enum values should be wrapped in an arrayref. at /home/mueller/cxgn
/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util/TypeConstraints.pm line 437.
Moose::Util::TypeConstraints::enum("LineCap", "butt", "round", "square") called at /home/mueller/cxgn/local
-lib/lib/perl5/Graphics/Primitive/Brush.pm line 9

It seems that the version of Graphics::Primitive I have is the most recent. Are there any plans to update the code to the adhere to the more recent format of the enum call in TypeConstraints? (The stack backtraces are an issue in our server logs!!!)

Thanks and cheers
Lukas

**Comment by lukasmueller** [comment]
The version in cpan is fixed, but was not pulled in because cpanm could not determine the version of the installed module. Had to do a:
cpanm -L ../local-lib --reinstall Graphics::Primitive::Brush
and also:
cpanm -L ../local-lib --reinstall Layout::Manager::Flow
(same problem).

**Comment by lukasmueller** [comment]
To remove UNIVERSAL::isa startup warnings, 4d7efd07054ca0ff60bb2b778ec83736de29c823

**Comment by lukasmueller** [comment]
A couple of deprecation warnings are still there. Leaving this for now.
