### ISSUE TITLE
Wrong intertek file format upload information

### ISSUE THREAD

**Issue by Muyi1st** [solgenomics/sgn#2490]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by Muyi1st** [comment]
intertek file format information seems to be interchanged. The the SNP result grid information was interchanged with the Intertek SNP information file.
![image](https://user-images.githubusercontent.com/18723083/58101310-5376f200-7bd7-11e9-8ed9-5916a4cde71f.png)

**Comment by nickmorales** [comment]
addressed in #2499
