### ISSUE TITLE
upload spatial layout error - does not support .xls 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2492]
Expected Behavior 
--------------------------------------------------------------------------

uploading a file with plot_name row_number col_number returns an error message 
![image](https://user-images.githubusercontent.com/126788/58111997-8e216000-7bc0-11e9-9bbb-b60ad0229c69.png)

For Bugs:
---------

**Comment by nmenda** [comment]
I missed the part where it says 'does not support .xls files' 
Do we want to let users upload xls files here?

**Comment by nickmorales** [comment]
I think that only accepts a tsv file

**Comment by nmenda** [comment]
uploading a tab-delimited file does not return an error, but the column and row numbers are not updated in the database
http://sgn-test.sgn.cornell.edu/breeders/trial/76
[76_layout_test.txt](https://github.com/solgenomics/sgn/files/3203546/76_layout_test.txt)
