### ISSUE TITLE
GUI hangs while deleting phenotype sheet

### ISSUE THREAD

**Issue by lynnjo** [solgenomics/sgn#2494]
Expected Behavior 
--------------------------------------------------------------------------

In Manage->Phenotyping.  I have a spreadsheet loaded for a trial.  The data is incorrect.  I would like to delete the spreadsheet (which I believe will delete the phenotypic data).  I expect to click "delete" next to the spreadsheet, and have some indication the delete is happening.  I expect this to happen in a timely fashion (not sure what "timely' should mean)

For Bugs:
---------

### Environment 

PanZeaBase at panzeabase.sgn.cornell.edu

#### Steps to Reproduce
At PanZeaBase:  go to Manage->Phenotyping.  Select the "delete" option for the uploaded file  2019-05-24_16:38:43_NAMjhBLUPS_phenotypeSheet.xls.  For over an hour, it shows "waiting for panzeabase.sgn.cornell.edu..."   I cannot tell if it is deleting data, or stuck trying to connect to the DB.  If I kill the window, the file still exists (has not been moved to obsolete list).  I refresh, try again - same behavior.

**Comment by lukasmueller** [comment]
The AJAX timeout interval probably has to be increased for this functionality?

**Comment by nickmorales** [comment]
@lynnjo we need to make the phenotype deletion faster (it is currently extremely slow and can take many hours depending on the number of phenotypes you need to delete). there are ways we can implement it faster.
