### ISSUE TITLE
Make solgenomics slideshare presentations downloadable

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2502]
Expected Behavior 
--------------------------------------------------------------------------

Request from Doreen at NaCRRI. At the moment download does not seem to be enabled

For Bugs:
---------

**Comment by bauchetg** [comment]
@bellerbrock 
I guess you are refering to https://www.slideshare.net/solgenomics
The current settings include download to users (see below). Users need to be logged in slideshare website.

<img width="518" alt="Screen Shot 2019-07-29 at 11 51 42 AM" src="https://user-images.githubusercontent.com/12039071/62062698-86e98480-b1f7-11e9-9c9e-4837f365aba5.png">
