### ISSUE TITLE
Downloadable pdf version of SGN Documentation

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2503]
Expected Behavior 
--------------------------------------------------------------------------

Requested by breeders at the sweetpotato speedbreeders meeting. 

For Bugs:
---------

**Comment by bellerbrock** [comment]
A more complex but related request - allow annotation of the manual by users. For example, so each program can make a publicly visible note on the trial creation workflow section to document a standard way for their program members to construct trial names

**Comment by trife** [comment]
What system does SGN use for documentation?

**Comment by bellerbrock** [comment]
Hey @trife, sgn uses the built in Git Pages feature that can publish markdown from a git repo into a static site using Jekyll. Just look in the [docs](https://github.com/solgenomics/sgn/tree/master/docs) directory, David did a nice job documenting how it works.

I just stumbled on https://readthedocs.org/ , which looks like a popular solution for open source projects. It can build automatically from a docs/ folder in a git repo, just like our current solution, but would also allow versioning and pdf download among other features.

**Comment by lukasmueller** [comment]
>A more complex but related request - allow annotation of the manual by users. For example, so each program can make a publicly visible note on the trial creation workflow section to document a standard way for their program members to construct trial names

That would be really cool... I don't think the GitHub system allows that currently, but what system would allow that?
I think for the PDF - we can just print it as PDF from the webpage?

**Comment by darekbienkowski** [comment]
I will do it in next days.

**Comment by lukasmueller** [comment]
via #4751
