### ISSUE TITLE
Genotyping plate/data upload UI changes

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2515]
Expected Behavior 
--------------------------------------------------------------------------
Genotyping plate/project and folders:
Clarify the genotyping project creation in relation to genotyping plate folders?
Folders content should remain flexible. However when user loads a genotyping plate, the dialog should offer the possibility to add the plate to an existing folder or create a new one.

Genotyping data upload Step 1 and 2:
Possibly shrunk the size of existing project and protocol description so it remains readable when many.

Genotyping data upload Step 3:
Selecting tissue samples vs accession as data upload types should be hidden to the user and replaced by some back-rend routine check if user loads either tissue or accession based data (with warning that no field experimental fiedl data will be linked if accession type is chosen)

note: If genotyping data was collected at plot/plant level without using the coordinate/trial plate  user 
would need to create a dummy tissue sample to fix this.

For Bugs:
---------

**Comment by lukasmueller** [comment]
I think these comments are essentially covered when you work with Coordinate app? Please re-open if this is not correct.
