### ISSUE TITLE
Set pedigree viewer to show only two generations by default

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#2523]
Expected Behavior: Pedigree viewer should show only two generations and have an option to retrieve all pedigree info.
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bauchetg** [comment]
@titima15 perhaps I missed something but why would you limit the pedigree depth to n = 2?

**Comment by titima15** [comment]
@bauchetg (requested by Fola) Because when there are so many generations, it becomes very slow and large. Most of the time, breeders would like to see only 2 generations (or should we set for three generations). However, users have an option to expand the view.

**Comment by aafolabi** [comment]
@bauchetg That is exactly what the problem is. Waiting time is about 1-2mins. Try and search "IBA070593". So if the default is set to 2 or maybe 3, the user can have an option to expand the view.
Thanks

**Comment by bauchetg** [comment]
I see, this is a question for @dauglyon

**Comment by titima15** [comment]
@bauchetg I assigned to Mirella because Lukas asked Mirella to handle d3 issue. It's a good idea that she consults David as well when needed.
