### ISSUE TITLE
Add Crossing activity table in crossing experiment detail page

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2525]
Expected Behavior 
--------------------------------------------------------------------------

@titima15 Requested by sweetpotato and potato breeders at CIP Hackathon. Would track the raw data submitted from Intercross that could then be summarized in the summary table. The crossing experiment page would end up with 3 tables total, looking something like the following. Imagine this is the detail page for 19RKN, a simple sweetpotato crossing block for root knot nematode resistance.

#### Design
Cross Name | Female | Male
---------------- | ------------ | ---------
19RKN_CovingtonXTanzania | Covington | Tanzania
19RKN_BeauregardXTanzania | Beauregard | Tanzania
19RKN_CovingtonXNewKawogo | Covington | NewKawogo
19RKN_BeauregardXNewKawogo | Beauregard | NewKawogo
19RKN_NewKawogoXBeauregard | NewKawogo | Beauregard

*simplest possible design here, could be more columns for male and female plot, family name, other design info

#### Raw Data
Cross Name | Event ID | Operator | Type | Value | Timestamp
---------------- | ------------ | --------- | --------| ---------------- | ----------
19RKN_CovingtonXTanzania | 19_000001 | Bryan | Number of Flowers | 5 |  2019-06-08T17:49:32+00:00
19RKN_CovingtonXNewKawogo | 19_000002 | Bryan | Number of Flowers | 3 |  2019-06-08T17:50:36+00:00
19RKN_NewKawogoXBeauregard | 19_000003 | Bryan | Number of Flowers | 6 |  2019-06-08T17:54:02+00:00
19RKN_NewKawogoXBeauregard | 19_000004 | Bryan | Number of Flowers | 2 |  2019-06-09T17:54:02+00:00
19RKN_NewKawogoXBeauregard | 19_000003 | Titima | Number of Fruit | 4 |  2019-07-08T17:56:34+00:00
19RKN_CovingtonXNewKawogo | 19_000002 | Titima | Number of Fruit | 2 |  2019-07-08T17:57:49+00:00
 
 *this tables tracks the data coming in from the hand-help crossing app. Event ID is the distinct id generated by intercross for each pollination event and would be optional. 
 
 #### Summary
Cross Name | Number of Flowers | Number of Fruit | Number of Seeds
---------------- | ------------ | --------- | --------
19RKN_CovingtonXTanzania | 5 | 0 | 0
19RKN_BeauregardXTanzania | 0 | 0 | 0
19RKN_CovingtonXNewKawogo | 3 | 2 | 0
19RKN_BeauregardXNewKawogo | 0 | 0 | 0
19RKN_NewKawogoXBeauregard | 8 | 4 | 0

*This table would provide a running summary of the raw data and provide crucial information for breeders as they prioritize crossing activities throughout the season. 

For Bugs:
---------

**Comment by titima15** [comment]
Done via 1f4301a
