### ISSUE TITLE
make standalone correlation analysis tool

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2533]
-- also modular enough so it can be integrated in the mixed modelling pipeline
-- make it work with Datasets

**Comment by lukasmueller** [comment]
Is this not completed? Can this ticket be closed?

**Comment by lukasmueller** [comment]
To my knowledge, this is completed, so closing this ticket. Please re-open if that's not the case.

**Comment by isaak** [comment]
This still  needs to be done. Will bump it up.

**Comment by isaak** [comment]
done #4523
