### ISSUE TITLE
Printing labels for desktop printer Zebra zt400 

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#2546]
Printing labels. Yam group has a desktop printer Zebra zt400 which they want to use in printing field plants labels. It will be good to provide a format compatible with this printer in yambase
 

For Bugs:
---------

**Comment by titima15** [comment]
@bellerbrock Hi, Bryan. Could you please help with this request? Yam breeders would like to use this Zebra zt400 printer to print labels for plant level.

**Comment by bauchetg** [comment]
@margaret we have a .zpl format on the label designer. Have you got a chance to test it ?
<img width="394" alt="Screen Shot 2019-07-23 at 3 41 21 PM" src="https://user-images.githubusercontent.com/12039071/61742109-5d94a880-ad60-11e9-9567-01f36cc294ea.png">

**Comment by bauchetg** [comment]
zt400 is a desktop printer, it seems to be using similar label formats as portable ones.
https://www.zebra.com/content/dam/zebra_new_ia/en-us/solutions-verticals/product/Printers/Industrial%20Printers/ZT400%20Series%20Industrial%20Printers/GENERAL/spec-sheet/zt400-series-spec-sheet-en-us.pdf
Some testing would be helpful

**Comment by bauchetg** [comment]
Feedback from Margaret: Yes, we designed labels using the 'zebra printer file' yambase format but we couldn't print. The printer is a zebra ZT 410 model and uses zebra designer pro software. The input file for zebra designer is a '.lbl' whereas the file downloaded from yambase is a .zpl which is not compatible with the software.
A new format with '.lbl' could be added to yambase since we have the printer. Will really make the process easier.
Alternatively, we will download data in excel files, generate labels using the zebra designer software and the print using this printer.

**Comment by bellerbrock** [comment]
Thanks for following up @bauchetg. Do you have access to an example .lbl file? That would be helpful to inform any necessary changes.

It's possible that there is little to no real difference in the formatting, in which case I'd be curious if just changing the extension in the filename is all the is necessary to get the .zpl files to work.

**Comment by bellerbrock** [comment]
@mkaranja Please let us know if you can share more details!

**Comment by mkaranja** [comment]
[demo.zip](https://github.com/solgenomics/sgn/files/3453543/demo.zip)
Attached is an example file

**Comment by bellerbrock** [comment]
Thanks Margaret. Looking at the example .lbl file and reading more about the format, I don't think it's feasible to support it in label designer. It's a complex file type based on a Microsoft format, so not unfortunately not similar to the existing .zpl format as I was hoping. And I don't see any perl packages out there that could be used to produce it.

I do see in the newer [ZT400 series documentation](https://www.bcpmedia.com.au/wp-content/uploads/2021/10/ZT410-ZT420-User-Guide.pdf#page=136) that it's possible to turn on ZPL mode to print zpl labels, at least in the 410 and 420 models. Or worst case just keep using the zebra designer pro software workaround.
