### ISSUE TITLE
Search: menu and button text is different

### ISSUE THREAD

**Issue by eawoods** [solgenomics/sgn#2550]
Expected Behavior 
--------------------------------------------------------------------------
Items in the "Search" pull down menu are the same as the buttons across the "Search" pages.

Actual: menu items "Organisms" and "Progenies and Crosses" are not present in the list of buttons across the top of search pages.
Some of the text is not exactly the same ("Genotyping Trials" vs "Genotyping Plates").

**Comment by nickmorales** [comment]
@eawoods this is a site specific issue because the menu across the top of the page is specific for each site

**Comment by eawoods** [comment]
Ah - good to know. I was reviewing on CassavaBase.
