### ISSUE TITLE
wizard genotyping protocol update for kaspar type id 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2556]
Expected Behavior 
--------------------------------------------------------------------------
Currently wizard query does not display related accessions to kaspar protocol

For Bugs:
---------

**Comment by nickmorales** [comment]
this is working from the wizard on my test machine (fixture with /t/data/genotype_data/test.vcf loaded from web-interface from manage->genotypingtrials->load VCF)

**Comment by nickmorales** [comment]
looks like this is the problem https://github.com/solgenomics/sgn/blob/master/db/00092/UpgradeGenotypeStorage.pm#L70 
should not limit to accessions
