### ISSUE TITLE
clustering job cause site to crash

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2570]
Expected Behavior 
--------------------------------------------------------------------------
Submitting a cluster job can overload the vm it seems  (although mem use still low).
@isaak This happen during the demo

<img width="1181" alt="Screen Shot 2019-08-07 at 12 00 58 PM" src="https://user-images.githubusercontent.com/12039071/62638587-c4db5c80-b90b-11e9-960b-2f384cbfcd7f.png">
ing job 

For Bugs:
---------

**Comment by lukasmueller** [comment]
possibly a duplicate with something that Adrian is already working on

**Comment by isaak** [comment]
this should be partly solved with the Cluster server solution....and merged branches...
https://github.com/solgenomics/sgn/pull/2666 and Adrian's branch

**Comment by afpowell** [comment]
Genotype Search issue should now be solved by #2690 
but may still depend on how run_cluster is being used in specific cases.

**Comment by lukasmueller** [comment]
Can this issue be closed? It looks like it... :-)

**Comment by lukasmueller** [comment]
Cassavabase analysis jobs are now farmed out to the cluster server with 768G of RAM, so this problem should be solved.
