### ISSUE TITLE
breedBase database

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2575]
-- For demo purposes (speed), using the fixture db would be good.

**Comment by lukasmueller** [comment]
We have a site called breedbase.org that can serve as a demo site. Is that what you were thinking?

**Comment by isaak** [comment]
Yes, but use a light database (like the fixure db) instead of a copy of production db.

**Comment by lukasmueller** [comment]
I can put a copy of the fixture there instead.

**Comment by lukasmueller** [comment]
Confirmed in ticket meeting: put fixture on Breedbase

**Comment by lukasmueller** [comment]
duplicate of #4306
