### ISSUE TITLE
Quick search output page could be more intuitive

### ISSUE THREAD

**Issue by noefp** [solgenomics/sgn#258]
the output sections could be renamed and reorganized to be more intuitive for the users.

![screen shot 2015-10-21 at 2 23 17 pm](https://cloud.githubusercontent.com/assets/2249273/10646100/4e7260da-77ff-11e5-9222-6823738c4266.png)

**Comment by nickmorales** [comment]
how would you reorganize this:

![github_issue_04](https://cloud.githubusercontent.com/assets/7028512/11074577/56cbd440-87be-11e5-9628-4d724cc66f2e.png)

**Comment by lukasmueller** [comment]
addressed in f449cf842c3a1c81d828088f50cd08a6bdb460b1 but maybe not completely fixed.
