### ISSUE TITLE
design trial row number setting crashes

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2590]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Crashes in every case a row number is submitted
In Manage > Design new trial > select complete block design

Could not calculate design: Undefined subroutine &CXGN::Trial::TrialDesign::Plugin::RCBD::_validate_field_colNumber called at lib/CXGN/Trial/TrialDesign/Plugin/RCBD.pm line 50.

<img width="955" alt="Screen Shot 2019-08-19 at 11 59 49 AM" src="https://user-images.githubusercontent.com/12039071/63276077-ad3b9680-c270-11e9-9bea-d6a82d2d8881.png">

Has to do with the validation of column number
@lukasmueller could it be related to the recent re-factoring of the trial object ?

**Comment by aco46** [comment]
Yes, it has to do with the recent refactoring.

**Comment by lukasmueller** [comment]
Hi Alex,

I think you had implemented a fix for it… Can we work on this together to get it back in?

thanks and cheers
Lukas

**Comment by aco46** [comment]
I will take a look at it @lukasmueller.

**Comment by aco46** [comment]
fixed via #2603
