### ISSUE TITLE
gmod_load_cvterms.pl does not persistently store data

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2621]
Expected Behavior 
--------------------------------------------------------------------------

Runs with gmod_load_cvterms.pl don't give an error, but any changes the program makes do not persist in the database.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Naama - could you take a look at this with high urgency? Maybe the issue is just on the server that I am working with, or maybe it is more widespread, I don't know.

**Comment by nmenda** [comment]
can you paste the command you are using with all the options?

**Comment by nmenda** [comment]
looks like the terms do get updated. The way to check if the script worked is by looking in the database or at the web page for that cvterm.
The log will always report that terms found in both the database and the obo file are 'updated'.
Terms found in the database only will be set to is_obsolete =1 
New terms in the file will be inserted into the database when using the -u option

Need to add the obo file to the dawsonlab github repo, and edit it with Protege for tracking changes better
