### ISSUE TITLE
stock page javascript error for sequencing_status.mas

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2633]
Expected Behavior 
--------------------------------------------------------------------------

Cannot read property 'sequenced_accessions' of undefined

https://github.com/solgenomics/sgn/blob/master/mason/stock/sequencing_status.mas#L10

Also the alert on the stock detail page is not necessary.

For Bugs:
---------

**Comment by titima15** [comment]
@nickmorales I already removed the alerts and already merged to master

**Comment by nickmorales** [comment]
@titima15 there was still am error in loading the javascript. can you take a look at #2634?
