### ISSUE TITLE
Search wizard dose not show the number of items selected from the select boxes.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#264]
NEW SEARCH WIZARD SELECT BOX
![screenshot from 2015-10-26 15 43 53](https://cloud.githubusercontent.com/assets/10618260/10740396/6c69ffce-7bf8-11e5-994f-6fcba3417e66.png)

OLD SEARCH WIZARD SELECT BOX
![screenshot from 2015-10-26 15 44 53](https://cloud.githubusercontent.com/assets/10618260/10740412/8652fa4e-7bf8-11e5-9514-336436d865a9.png)

**Comment by nickmorales** [comment]
fixed with 47fa955959ea35d4714937d2106177ec41f74120
