### ISSUE TITLE
toolbar sub-menu items do not appear on phone/tablet/narrow browser window 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2643]
Expected Behavior 
--------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/126788/66426170-42404d80-e9df-11e9-989d-ca0256b6b578.png)

For Bugs:
---------

**Comment by nickmorales** [comment]
the submenu is displayed (expanded) if you click on one of those tabs
