### ISSUE TITLE
Image analysis search and tools disconnected

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2662]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by solomonnsumba** [comment]
There was an issue on our side of the image analysis; it had to do with space and it has been resolved.

**Comment by solomonnsumba** [comment]
But the first issue raised "We are unable to retrieve the list of images associated to a trial which has plot based images stored, ie 17.GS.C1.PYT.20.IB" Is still there
