### ISSUE TITLE
cross wish list changes

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2663]
Expected Behavior 
--------------------------------------------------------------------------
Request for more than 10 possible male parents (currently 10 is the max), up to 20 males would be useful.
<img width="800" alt="Screen Shot 2019-10-17 at 10 24 23 AM" src="https://user-images.githubusercontent.com/12039071/66998876-af3d9c80-f0dd-11e9-8f1d-71302aec118e.png">

For Bugs:
---------

**Comment by bauchetg** [comment]
This was fixed I believe but I cannot find the corresponding commit to close the issue, @titima15 any idea?

**Comment by titima15** [comment]
@bauchetg I usually combine small ticket like this one with other major ticket (If it is not urgent), so it is not merged yet. I will close the ticket once the branch is merged.

**Comment by titima15** [comment]
Done. Closed via 5033849
