### ISSUE TITLE
Database patch error handling not working properly

### ISSUE THREAD

**Issue by nickpalladino** [solgenomics/sgn#2672]
I attempted to apply database patches using the command:
```
./run_all_patches.pl -u postgres -p postgres -h breedbase_docker_db -d vitisbase -e nickpalladino
```
Since the postgres_dockerfile didn't have a web_usr role defined for the database, some of the patches failed, of particular importance to me was AddPhenomeProjectMdImageTable. In this case, the table specified in the patch wasn't created but an entry in the metadata.md_dbversion table was created for AddPhenomeProjectMdImageTable. When you try to rerun the patch after adding the web_usr role, the patch is not applied because the AddPhenomeProjectMdImageTable in metadata.md_dbversion causes the software to skip over that patch. I had to remove that entry from the metadata.md_dbversion table to get the patch to run.

The run function in DbPatch.pm (https://github.com/solgenomics/cxgn-corelibs) is checking for an error but the patch (AddPhenomeProjectMdImageTable.pm in this case) does not set the error, just outputs text indicating there was an error and therefore the the patch name data is written to the metadata table and as a result will not be run again.

### Environment 
- sgn ffcc3182fd7a6c105f8db9825f8a67d776537284
- cxgn-corelibs 6440e7e1cf5c4924b75dfd60695e8f82474cda04
- breedbase_dockerfile cb11d0878b3f7d851a01b23cd7a1edb2279885a0
- postgres_dockerfile 7508ada3c19c347f99cd506984491abe63a2827b

**Comment by nickpalladino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BBase-15 - Saving images](https://trello.com/c/qc8PewRg/65-bbase-15-saving-images)

**Comment by nickmorales** [comment]
@nickpalladino the patches can be manually run one by one also using:
example: running /db/0001/PATCHNAME.pm

mx-run PATCHNAME -H host -D dbname -u nickpalladino 

an option -F will force the patch to be run, which is useful for rerunning a patch
