### ISSUE TITLE
wizard pheno download misses "is_a_control" column

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2673]
Expected Behavior 
--------------------------------------------------------------------------
The column would show on individual trial downloads.
This is of importance for augmented designs

For Bugs:
---------

**Comment by nickmorales** [comment]
The wizard download shows 'entryType' to indicate either 'test' or 'control'. I think entryType was used to match closer to BrAPI terms, instead of is_a_control

**Comment by bauchetg** [comment]
Hello @nickmorales , correct but the implemented solution it is not effective.
See this issue #3016 for more details
