### ISSUE TITLE
cassavabase genotype queries

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#2676]
Cassavabase is getting overwhelmed by genotype data query of  ~ >300 clones. From the wizard it throws ‘502 Bad Gateway' and for solGS submissions, it silently dies. Memory is filling up and swap space maxed out!

**Comment by lukasmueller** [comment]
Fixed by adding a next_genotype_info iterator to CXGN::Genotype::Search (#2690) but code needs to be adapted in the codebase especially for Wizard and solGS and maybe the download tool.

**Comment by isaak** [comment]
adapted in solGS, wizard, solgwas
