### ISSUE TITLE
Errors when trying to generate a new list

### ISSUE THREAD

**Issue by dlebauer** [solgenomics/sgn#2684]
I was pushing buttons to explore the application without reading the documentation, so my use case may be low priority!

But I ran into errors when trying to create a new list 

For Bugs:
---------

### Environment 

Brave Browser

#### Steps to Reproduce

* Log in to http://imagebreed.org/
* Click "Lists" in upper right corner
* Try to create a new list
*  When creating the list, I should be able to specify type, but it gives the following error after I select any value in the 'type' field
![image](https://user-images.githubusercontent.com/464871/68627231-7ef9db80-049a-11ea-9d53-1bb149819f1c.png)
* And after I add new items, it deletes the list name, description, and type:
![image](https://user-images.githubusercontent.com/464871/68627271-9d5fd700-049a-11ea-8c53-0d1963bcbd07.png)

**Comment by lukasmueller** [comment]
Hi David, great to hear from you and thank you for submitting a ticket! However, I couldn't reproduce this error on Cassavabase. Note that you cannot verify a list that has no type associated with it. Let me know if this error persists and we can look how to resolve it.

**Comment by nickmorales** [comment]
hi @dlebauer thank you for pointing out this issue though I cannot see this error on imagebreed.org. I've given you additional permissions on that website and if you would like to explore the main functionalities of imagebreed please see http://imagebreed.org/breeders/drone_imagery and for searching and downloading phenotypes see http://imagebreed.org/breeders/search

**Comment by dlebauer** [comment]
Thanks for giving me access to imagebreed. I’ll take a look next week. This
looks really cool, and great work!

Have you tried to reproduce the error on Imagebreed when you are signed in
with the same permissions I had when I first signed up?
-- 
David LeBauer
Director of Data Sciences
CALS Comm and Technologies
THE UNIVERSITY OF ARIZONA

BSRL, 207
1230 N Cherry Ave | Tucson, AZ 85721
Office: 520-621-4381 | Cell: 760-468-8621
dlebauer@arizona.edu

*datascience.cals.arizona.edu <https://datascience.cals.arizona.edu>*
orcid <https://orcid.org/0000-0001-7228-053X> | twitter
<https://twitter.com/dlebauer> | github <https://www.github.com/dlebauer> |
linkedin <https://www.linkedin.com/in/dlebauer/>
