### ISSUE TITLE
updating of wizard does not require login

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2695]
Expected Behavior 
--------------------------------------------------------------------------

The wizard update should only be possible for logged in users who have submitter status.

For Bugs:
---------

**Comment by bellerbrock** [comment]
[This](https://github.com/solgenomics/sgn/blob/284e1a0e0fd95f526a1399085b8aa7ac57dace3b/lib/SGN/Controller/AJAX/BreederSearch.pm#L135) is the perl code that handles the ajax requests to refresh the materialized views. Maybe the best place to check if the user is logged in, and return with an error if they aren't.

Something similar to the way the way create list requests from the wizard are rejected if no user is logged in 
```my $user_id = $self->get_user($c);
    if (!$user_id) {
	$c->stash->{rest} = { error => 'You must be logged in to use lists.', };
	return;
    }
``` 
In fact, maybe we should make the whole wizard page only accessible to logged in users . . . It's pretty frustrating when you get to the the 4th multiselect and try to create a list only to realize you aren't logged in.

**Comment by lukasmueller** [comment]
I think requiring login for Wizard is a good idea.

**Comment by lukasmueller** [comment]
I can work on this one if you don't have time... :-)
