### ISSUE TITLE
Accession list creation fails if an accession name contains a single quote

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2704]
Expected Behavior 
--------------------------------------------------------------------------
Creating a list of accessions failed because it contained a check called `Doebler's Organic Standard`
`DBD::Pg::db do failed: ERROR:  syntax error at or near "s"
LINE 1: ..., (33,126,'Doebler's Organic ...
                                                             ^ at lib/CXGN/List.pm line 573.`

probably low priority, but either accession names should not be allowed to contain quotes, or quotes and other special characters should be escaped while handling accession names.

For Bugs:
---------

**Comment by lukasmueller** [comment]
The current implementation has a couple of problems, the quotes being one of them. The other one is that it doesn't use placeholders, which may be not secure. Needs to be changed asap.
