### ISSUE TITLE
Problem uploading phenotype spreadsheet with 'notes'

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2708]
https://github.com/solgenomics/sgn/blob/c221aa3a5e33f890e199e8b271c6b9071757bb5f/lib/CXGN/Phenotypes/StorePhenotypes.pm#L208

@bellerbrock any idea why the notes are being left out now? this causes phenotype upload to not work when notes are present

**Comment by bellerbrock** [comment]
@nickmorales Skipping notes during trait name validation is intentional, but it looks like I introduced a couple other bugs when I added nirs storage. It should be fixed in this [branch](https://github.com/solgenomics/sgn/compare/topic/fix_store_phenotypes) if you can help review!
