### ISSUE TITLE
store phenotypes not working

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#2709]
https://github.com/solgenomics/sgn/blob/c221aa3a5e33f890e199e8b271c6b9071757bb5f/lib/CXGN/Phenotypes/StorePhenotypes.pm#L497

there seems to be something not working when i try to upload phenotypes... i've opted to revert to the old cxgn::phenotype::phenotypestore in my own project because its not working for me...

**Comment by bellerbrock** [comment]
I just encountered something similar . . .

**Comment by nickmorales** [comment]
closed by #2719
