### ISSUE TITLE
genotyping plate breedbase download format hangs

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2711]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
Seems the query is very slow or inoperant
example:  https://cassavabase.org/breeders/trial/5699?format=
The error log stalls TrialLayoutDownload retrieving steps

**Comment by lukasmueller** [comment]
Is this still a problem?

**Comment by bauchetg** [comment]
it's been fixed, thanks!
