### ISSUE TITLE
plot list input in label designer restricted to a single experiment?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2712]
Expected Behavior 
--------------------------------------------------------------------------
Reported by Prasad
When creating  a list of plots in from multiple experiments from the wizard, the label designer print only plot barcodes for plots coming from a first experiment set in the list.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Hey @bauchetg, this is expected for the current implementation, but I get why a user might expect or want different behavior.

In the first step, if the user is working with a plot list they have to chose a data level, either list items or plots. If they chose list items they can then make a label for everything in their list, but the only field available to put in the labels will be the plot name. If they choose plots then all the plot details are retrieved from the trial design using trial layout download. Trial layout download takes trial_id as an argument, so the trial id associated with the first plot in the list is the one used.

In theory it should be possible to improve this by identifying all the unique trial ids from all the plots in the list, using them to retrieve all the associated layouts, and then merging them into a single data structure. In practice it would get quite complex if the different trials had different treatments and traits measured though, and depending on the list size it could also get quite slow. Worth exploring for the next version of the designer though.

**Comment by pvnsprasad** [comment]
Hi Bryan, this was request from me. it is needed when i print barcodes for sticky labels, (40 labels per page). so in case if i have to print 15 plots from 1 trial and 25 plots from another trial. I was expecting that i can use plots from different trials and get them printed at once, which would save me label and effort.

**Comment by lukasmueller** [comment]
The data source pop up contains trials and lists.
