### ISSUE TITLE
default_genotyping_protocol

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#2716]
Update solGS and GWAS so that you can specify a genotyping protocol. The current setup uses a config variable to define the genotyping_protocol which is used in the analysis tools. In T3/Wheat we have 40 different phenotype experiments/projects that are independent of each other and can have a different genotype protocol. In T3/Wheat Classic we allow independent selection of phenotype and genotype trials. A better way might be to add metadata to the phenotyping trial to specify which genotype protocol it is associated with.

**Comment by lukasmueller** [comment]
Isaak is working on this. There must be another, duplicate ticket somewhere.

**Comment by isaak** [comment]
@ClayBirkett: could you check out this branch: https://github.com/solgenomics/sgn/tree/topic/solgs/genotype-protocol-options

Please let me know how it works for you...including if it is intuitive or not?

**Comment by isaak** [comment]
Done. #2863
