### ISSUE TITLE
Phenotype uploads fail in docker due to missing date and operator cvterms 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2721]
Expected Behavior 
--------------------------------------------------------------------------
Phenotype upload fails during store [when retrieving date and operator cvterm_ids from the local cv](https://github.com/solgenomics/sgn/blob/ea53455515b1e9fafeeb6c1b00867b35560ddfab/lib/CXGN/Phenotypes/StorePhenotypes.pm#L453-L454).

Turns out the terms were missing. I fixed this in my local docker db by manually adding them:
```
BEGIN;
INSERT INTO dbxref (db_id, accession) VALUES ((SELECT db_id FROM db WHERE name='local'), 'date');
INSERT INTO dbxref (db_id, accession) VALUES ((SELECT db_id FROM db WHERE name='local'), 'operator');
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((SELECT cv_id FROM cv WHERE name='local'),'date',(SELECT dbxref_id FROM dbxref WHERE accession='date'));
INSERT INTO cvterm (cv_id,name,dbxref_id) VALUES ((SELECT cv_id FROM cv WHERE name='local'),'operator',(SELECT dbxref_id FROM dbxref WHERE accession='operator'));
COMMIT;
```
but i'm not sure what the best permanent fix is . . .

For Bugs:
---------

**Comment by nickmorales** [comment]
Ive seen this also from cxgn_fixture.sql

**Comment by nickmorales** [comment]
i'll make a dbpatch to add these terms and will redump the t/data/fixture/cxgn_fixture.sql and empty_fixture.sql files.
hopefully the database docker is using the cxgn_fixture.sql or the empty_fixture.sql as a base to setup the database?
