### ISSUE TITLE
sgn/bin/merge_stock.pl script merges the PUI from the bad stock with the good stock PUI

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#2723]
Expected Behavior 
--------------------------------------------------------------------------
When merging 2 accessions using the sgn/bin/merge_stock.pl script, the bad stock PUI is merged with the good stock in a comma separated list.  So, if the bad stock is deleted after the merging (-x), the merged PUI isn't valid anymore. Also, will there be a reason the PUIs from the bad stock should be merged with the good stock, even if the bad stock isn't deleted?

For Bugs:
---------

**Comment by bellerbrock** [comment]
Addressed in https://github.com/solgenomics/sgn/pull/2724 by checking the type id of each stockprop during the merge and skipping stockprops of type PUI if the merged stock will be deleted.
