### ISSUE TITLE
Trial detail page phenotype heatmaps are broken

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2725]
Expected Behavior 
--------------------------------------------------------------------------
No obvious errors in the console or error log, but based in [phenotype_heatmap.mas](https://github.com/solgenomics/sgn/blob/master/mason/breeders_toolbox/trial/phenotype_heatmap.mas) it looks like the observationVariableDbId values returned from
`/brapi/v1/studies/` do not match the observationVariableDbIds expected by `/brapi/v1/phenotypes-search`

Specifically `/brapi/v1/studies/` returns values like "observationVariableDbId": "Test Weight (lbs/bu)|HFG:0000004" while `/brapi/v1/phenotypes-search` expects the cvterm id instead. I've fixed the heatmap locally by temporarily changing [this line](https://github.com/solgenomics/sgn/blob/master/lib/CXGN/BrAPI/v1/Studies.pm#L472) to `observationVariableDbId => $trait_id,`, but not sure what sde effects that has elsewhere.

For Bugs:
---------

**Comment by nickmorales** [comment]
Moving this back to how it was before where observationVariableDbId is the cvterm_id might make the most sense.
The 'name' field already has the 'cvterm_name|DB:0000001' info if that is something that is needed

**Comment by bauchetg** [comment]
Hello @bellerbrock, as a side note, now that brapi 1.3 is implemented you may use
https://solgenomics.github.io/BrAPI-HeatMap/example.html
example using cassavabase Study Id 4832 works

**Comment by bellerbrock** [comment]
Good points @nickmorales. And thanks @bauchetg, I forgot I could just access the standalone app!
