### ISSUE TITLE
adding 'Additional information' on stock detail page gives an Error

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#273]
![github_issue_03](https://cloud.githubusercontent.com/assets/7028512/10887974/b20f6c8a-8157-11e5-93dc-5d6418a6c3cb.png)

**Comment by nickmorales** [comment]
Was the dropdown intended to be populated with this metadata list on line 102 of mason/stock/index.mas?

my $metadata = ['variety', 'donor', 'donor institute', 'country', 'state' , 'adaptation' , 'notes'];

**Comment by lukasmueller** [comment]
I think this should have been moved to some sgn_local.conf entry, so that it can be configured on a database-specific basis. This was implemented by Naama I think.

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/commit/d102f769745170be14b93b0b60a14bd04f2e73b2
