### ISSUE TITLE
Update local.conf paths for docker environment

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2736]
Expected Behavior 
--------------------------------------------------------------------------

Right now it has a mix of [vagrant paths
](https://github.com/solgenomics/sgn/blob/master/sgn.conf#L13-L16) and [fileserver paths](https://github.com/solgenomics/sgn/blob/master/sgn.conf#L110-L111). I had to override these with `/home/production` while using docker; if we are switching to docker for both dev and production can we update the default paths?

For Bugs:
---------

**Comment by lukasmueller** [comment]
For the docker, use the docker specific sgn_local.conf what is given as a template in breedbase_dockerfile. Even better, use the docker-compose, I think everything is set up in there to work out of the box (or can be easily made to work)
