### ISSUE TITLE
Allow user to set smtp auth method

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2738]
Expected Behavior 
--------------------------------------------------------------------------

At the moment [it is harcoded to ssl](https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Contact.pm#L93), but some users may need to use tls.

For Bugs:
---------

**Comment by dwaring87** [comment]
@bellerbrock I was just looking at this for our server.  We also need to specify the auth method and from address in order for it to work with our STMP server.  If you haven't started working on this I can add those as optional conf variables.

**Comment by bellerbrock** [comment]
Hey david, i just made a pull request after adding and testing a layer/auth
variable. Is the from variable different then the login variable? If you
want to test it out and also add a from variable that would be great!

**Comment by dwaring87** [comment]
Yeah, we have a username for login and then the SMTP server enforces a whitelist of what we can use as the 'From' field (in this case it's using www-data@hostname, which we haven't whitelisted).  I'll add the variable to your PR.
