### ISSUE TITLE
Generate derived traits for each trial on Cassavabase thereby eliminating mechanical ways of calculating those traits.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#274]

**Comment by bauchetg** [comment]
This objective could  cover the creation of the  "performance index" using trial checks mentioned in the project review. Derived traits are general, here the calculation would need to include some specific accessions according to the trial experiment (genetic gain) and/or the trait (biotic/ yield)

Known checks:
-genetic gain: IBA30572 and TMEB1
-white root trial: TMEB419 and IBA980581
-yellow root trials: IBA011371, IBA011368 and IBA070593

Main traits to target: 
- abiotic stress traits (especially CMD, CBSD and CBB)
- yield components including dry matter (fresh yield, dry yield, dry matter content, root number)

**Comment by aco46** [comment]
Fresh root yield (FYLD) could be calculated or computed in two ways depending on the planting space used. It's just a way of standardizing the trait with respect to the planting space used. This is not clearly defined in the ontology. However to compute this trait within the database we'll need additional information like plot dimension, that way we can account for the spacing used for each trial. 

 **FYLD
    If 1m x 1m spacing is used, FYLD = root weight / 16*10
    If 1m x 0.8m spacing is used, FYLD = root weight / 12.8*10**

I talked about this with Guillaume. I'm not sure how often this is applied by breeders. We'll discuss with Peter to get more clarity on this.

**Comment by aco46** [comment]
The multiplication sign was not showing in the previous comment.

FYLD
If 1m x 1m spacing is used, FYLD = root weight / 16 * 10
If 1m x 0.8m spacing is used, FYLD = root weight / 12.8 * 10

**Comment by aafolabi** [comment]
Yield estimate in t/ha varies by breeding stages. The formula written above is NOT applicable to all trials. It is a function of the gross plot to be harvested.

**Comment by aco46** [comment]
FRY(t/h) = (Root Wt (kg) *10 / no of plts harvested)
The above is the third way of calculating FYLD. We need to know the different stages where each is used.

**Comment by aco46** [comment]
I would close this ticket for now. If there is need to add more yield traits for post computation, they can always be loaded using the loading script.
