### ISSUE TITLE
Add a number of seeds/gram stock prop for seedlots

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#2744]
Expected Behavior 
--------------------------------------------------------------------------
Important for Maize, Wheat, and other seed propagated crops. It is tedious to count seed for every transaction, but not every genotype, or even seedlot of the same genotype has the seed number of seeds per unit of weight.
It would be helpful to measure and record both the weight and count for at least one seed transaction when a seed lot is first used, derive the number of seeds/gram, and store it in the database. Could also set a default. Related to [this Inventory App issue](https://github.com/PhenoApps/Inventory/issues/4).

For Bugs:
---------

**Comment by bauchetg** [comment]
Hello @bellerbrock, I believe the inventory upload includes total seed weight column. Typically industry use [1000 kernel weight](https://www.seedtest.org/upload/cms/user/OGM18-06dISTA_Rules_2019_10_weight_v2.pdf), crop specific. Perhaps we need to add a parameter in the local.conf to inform which crop is involved?

**Comment by nickmorales** [comment]
@bellerbrock i thought this was already done because in the seedlot transactions it tracks both count and weight in grams. There are stockprops for current count and current weight in grams

**Comment by lukasmueller** [comment]
Should this be closed?
