### ISSUE TITLE
Submitting value of 0 (zero) via BrAPI causes error

### ISSUE THREAD

**Issue by timparsons** [solgenomics/sgn#2749]
Expected Behavior 

When PUTing observations to Breedbase via the BrAPI endpoint (/studies/{studyId}/observations), any observation that has a value of '0' should be accepted.  For example:

```
    {
        'observationTimeStamp': '2020-01-03T15:20:57-05:00',
        'value': '0',
        'collector': '',
        'observationUnitDbId': '84670',
        'observationVariableDbId': 'Breadstick deformity or damage|SNACK:0000040'
    }
```

--------------------------------------------------------------------------

Actual Behavior

Any observation with a value of '0' is rejected with the error being the observation does not have the value field populated.

For Bugs:
---------

#### Steps to Reproduce
Send a PUT request to `/studies/{studyId}/observations` with the payload:

```
{
  "observations": [
    {
      "observationTimeStamp": "2020-01-03T15:20:57-05:00'",
      "observationUnitDbId": "84670",
      "observationVariableDbId": "Breadstick deformity or damage|SNACK:0000040",
      "value": "0"
    }
  ]
}
```

Technical Notes

The error appears to be within `CXGN::Phenotypes::ParseUpload::Plugin::Observations` and function `validate` and is a side effect of checking if the "value" field is empty or not by executing:

```
if (!$obs->{'value'})
```

Because Perl is not a typed language, 0 (zero) is interpreted as `false` whenever used in a boolean context.  An appropriate fix would be for that if-statement to be:

```
if (!$obs->{'value'} && $obs->{'value'} != '0')
```

**Comment by MFlores2021** [comment]
merged
