### ISSUE TITLE
Legacy Javascript files not loading when Catalyst-View-Javascript-Minifier-XS is upgraded from 2.101001 to 2.102000

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#2752]
Expected Behavior 
--------------------------------------------------------------------------
Legacy Javascript files not loading when Catalyst-View-Javascript-Minifier-XS is upgraded from 2.101001 to 2.102000.  
After upgrading, the server can't find the javascript files in sgn/js/source/legacy/

Output from catalyst on the server:
[error] Caught exception in SGN::View::JavaScript""Legacy->process "Can't call method "file" on an undefined value at /usr/local/share/cassava-site/local-lib/lib/perl5/Catalyst/View/JavaScript/Minifier/XS.pm line 150."

Output on the browser (Chromium on Linux):
GET http://10.110.16.229:3000/js/legacy/moment_min.js net::ERR_ABORTED 500 (Internal Server Error)
trials:93 GET http://10.110.16.229:3000/js/legacy/daterangepicker.js net::ERR_ABORTED 500 (Internal Server Error)
trials:94 GET http://10.110.16.229:3000/js/legacy/workflow.js net::ERR_ABORTED 500 (Internal Server Error)
trials:95 GET http://10.110.16.229:3000/js/legacy/calendar/moment_min.js net::ERR_ABORTED 500 (Internal Server Error)
trials:96 GET http://10.110.16.229:3000/js/legacy/calendar/fullcalendar_min.js net::ERR_ABORTED 500 (Internal Server Error)
trials:97 GET http://10.110.16.229:3000/js/legacy/jquery/dataTables.js net::ERR_ABORTED 500 (Internal Server Error)
trials:98 GET http://10.110.16.229:3000/js/legacy/calendar/fullcalendar_gcal_min.js net::ERR_ABORTED 500 (Internal Server Error)
trials:99 GET http://10.110.16.229:3000/js/legacy/calendar/bootstrap_datepicker_min.js net::ERR_ABORTED 500 (Internal Server Error)
...
trials:3063 Uncaught ReferenceError: Workflow is not defined
    at trials:3063
(anonymous) @ trials:3063
trials:3256 Uncaught ReferenceError: jQuery is not defined
    at trials:3256
(anonymous) @ trials:3256
trials:3876 Uncaught ReferenceError: Workflow is not defined
    at trials:3876
(anonymous) @ trials:3876
trials:4012 Uncaught ReferenceError: jQuery is not defined
    at trials:4012
trials:4277 Uncaught ReferenceError: jQuery is not defined
    at trials:4277
(anonymous) @ trials:4277
trials:4410 Uncaught ReferenceError: jQuery is not defined
    at trials:4410
(anonymous) @ trials:4410
trials:4872 Uncaught ReferenceError: jQuery is not defined
    at trials:4872
(anonymous) @ trials:4872
trials:5132 Uncaught ReferenceError: jQuery is not defined
    at trials:5132
(anonymous) @ trials:5132
trials:5525 Uncaught ReferenceError: jQuery is not defined
...

For Bugs:
---------

**Comment by nickmorales** [comment]
thanks @laguem we have encountered this issue in the past and had opted to just install version 2.101001 from cpanm.

we think we have identified the issue https://github.com/frioux/Catalyst-View-JavaScript-Minifier-XS/issues/3

**Comment by nickmorales** [comment]
this is an issue in the Catalyst-View-Javascript-Minifier-XS. they should maintain legacy support and it is mentioned in their github. we will continue only using 2.101001 in the meantime
