### ISSUE TITLE
Error when trying to open home page

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#2753]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
<img width="1344" alt="Screen Shot 2020-01-10 at 3 34 07 PM" src="https://user-images.githubusercontent.com/17749882/72184715-10180080-33bf-11ea-9c98-014b2545dc53.png">

**Comment by nickmorales** [comment]
this should have been solved in https://github.com/solgenomics/sgn/pull/2750
