### ISSUE TITLE
Apostrophes (') are replaced by &#39 in the suggestion box on the Search Accessions page

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#2758]
Expected Behavior 
--------------------------------------------------------------------------
When searching for accessions with ' (apostrophe) in their name on the Search Accessions page, the apostrophe shows has &#39 in the suggestion box.  This makes it imposible to search that name using the apostrophe.  Ex: for RUBY PULSIVER'S BLUE NOSER, typing PULSIVER'S won't work but PULSIVER&#39S will.

For Bugs:
---------

**Comment by lukasmueller** [comment]
I couldn't reproduce this issue with a normal single quote character ('). I didn't try the backquote. I have tried the accession and plot search and it found a quote containing accession. 

I think you have added the quoted accessions a long time ago maybe? We had a different encoding strategy at some point. So the way to fix this would be to go to the detail page and delete the quote, add it again, and store it.
