### ISSUE TITLE
The accession bulk loading scripts load_stock_data.pl doesn't replace apostrophes (') with &#39 when loading accession names.

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#2759]
Expected Behavior 
--------------------------------------------------------------------------
The accession bulk loading script (sgn/bin/loading_scripts/load_stock_data.pl) doesn't replace apostrophes (') with &#39 when loading accession names.

For Bugs:
---------

**Comment by lukasmueller** [comment]
I think it shouldn't. Otherwise it is hard to search. The database stores the data as UTF-8 so it should work, although there are some problems with quoting strings in the code etc.
