### ISSUE TITLE
Implement trial consistency checker

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2772]
Expected Behavior 
--------------------------------------------------------------------------

The trial consistency checker will apply rules that are stored with traits as well as other rules that describe relationships between traits. R scripts are already available from CIP that can be used as a first draft implementation (see https://github.com/reyzaguirre/st4gi ).

If the consistency check succeeds, a visual feedback such as a checkmark, could be shown.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Chris, could you update this issue, as I know you have worked on this? Is it complete?

**Comment by chris263** [comment]
Hi Lukas,

It was solved and also another ticket mentioned that.
https://github.com/solgenomics/sgn/issues/2812

I’ll check again and then close it if it is ok.

Cheers,
Chris
