### ISSUE TITLE
In addition to synonyms, add a stock prop of type "released_variety_name" 

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2778]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
The released_variety_name should appear in the basic search and be prominently displayed on the detail page along the unique name. 

It should be added as an additional stock prop type int the database using a dbpatch.

Question: The current stock prop "variety" this same concept or is it something different?

**Comment by lukasmueller** [comment]
The search already supports displaying any stock prop field, and supports searching by stock prop. The only thing is it should be displayed more prominently in the title of the page.

**Comment by lukasmueller** [comment]
OK, after discussion it was decided that the released variety name goes into a new stockprop key called "released_variety_name" that will be also searched by the accession search, and displayed prominently on the detail page.

**Comment by nmenda** [comment]
'released variety' would be better than adding multiple synonyms with different types. Easier to lookup and curate

**Comment by lukasmueller** [comment]
Add a button under additional info that specifically allows to enter a released_varitey_name (will check for uniqueness)

**Comment by lukasmueller** [comment]
Naama - have you been working on this? Is this completed?

**Comment by chris263** [comment]
Bert asked me about this issue last week. Do we need more discussion about it? Also, he mentioned about include cip number. Does anyone already discussed about it?
Thanks

**Comment by bellerbrock** [comment]
@chris263 more discussion would help. This feature seems crucial for many programs.

One suggestion from NCSU team when they had problems this week was to add both a variety name property, and a release date. Then keep the original accession name in any experiments before the release date, but use the variety name in all experiments after the release date.

**Comment by nmenda** [comment]
#3270
