### ISSUE TITLE
Create a summary statistics table that is loaded on demand on the trial detail page.  (solution to Trait frequency distributions on trial detail pages are slow to load or never load)

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#279]

**Comment by bellerbrock** [comment]
[One example] (https://cassavabase.org/breeders/trial/645/trait/76877)

**Comment by isaak** [comment]
Not sure what was happening when you were loading the pages. But except the example trait, for the rest of the traits in the list, the histograms were plotting at reasonable speed when I tried. When I cleared the cached files for the example trait, and tried it again, then it showed a message that all the lines have the same value for the trait. 

One possible glitch is you tried to load the trait statistics page, before the trial page was completely loaded. When you try to do something on the sections of trial page, before the trial page loads fully, you are likely to see ajax error messages...

**Comment by lukasmueller** [comment]
Create a summary statistics table that is loaded on demand on the trial detail page.

**Comment by nickmorales** [comment]
also work on histograms

**Comment by nickmorales** [comment]
summary stats table includes average, min, max, and std dev 1799bff4238a3a600d578f5229a95557ab546604
