### ISSUE TITLE
Running Tests from Docker Image

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#2807]
When trying to run the tests from the breedbase web docker container (using the breedbase database docker container for the database) the `test_fixture.pl` script was unable to create the test database.

Running the following command from the `/home/production/cxgn/sgn` directory:
```
perl t/test_fixture.pl t/unit_fixture/
```

gives the following output:
```
####### /home/production/cxgn/sgn #######Using breedbase_db:5432
# Writing a .pgpass file... Done.
# Loading database fixture... t/data/fixture/cxgn_fixture.sql ... createdb: could not connect to database template1: fe_sendauth: no password supplied
Password for user postgres:
psql: FATAL:  database "test_db_2020_2_21_15_173894" does not exist
Done.
```

The script prompts for the postgres password after trying to create the database.  The correct password is in our `sgn_local.conf` file and gets properly copied to the `sgn_fixture.conf` file.  The `.pgpass` file gets created in `/home/production` and contains the proper passwords (for postgres user and web_usr).

However, since the docker container uses the root user, `createdb` does not find the `.pgpass` file since it is looking for one in the root user's home directory.  I found manually setting the location of the pgpass file using the `PGPASSFILE` env var allows the tests to run:
```
PGPASSFILE=/home/production/.pgpass perl t/test_fixture.pl t/unit_fixture/
```

Is this something anyone else has encountered?  Is there a better way of running the tests using Docker?  Should the `test_fixture.pl` set this env var so it doesn't have to be set manually?

**Comment by lukasmueller** [comment]
In the Dockerfile, we set $HOME to /home/production, maybe we shouldn't?

**Comment by nickmorales** [comment]
This seems to be fixed in the latest Docker image

**Comment by lukasmueller** [comment]
Just set:
export HOME=/root 
before running the tests.
