### ISSUE TITLE
phenotype data download for some trials gives server error

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#281]
For both xls and csv formats, download phenotype data does not work on some trials: it gives server error.

https://cassavabase.org/breeders/trial/123
https://cassavabase.org/breeders/trial/128

**Comment by bellerbrock** [comment]
—

**Comment by nmenda** [comment]
[error] Caught exception in SGN::Controller::BreedersToolbox::Trial->trial_download "Error in tempfile() using /usr/local/share/website/sgn/static/documents/tempfiles/download/Cassava%20Ibadan%202001/02_phenotypeXXXX: Parent directory (/usr/local/share/website/sgn/static/documents/tempfiles/download/Cassava%20Ibadan%202001/) does not exist at lib/SGN/Role/Site/Files.pm line 163."

**Comment by lukasmueller** [comment]
The trial names are used to construct a temp file, if the names contain a slash it breaks. Use trial id to construct name.

**Comment by nmenda** [comment]
closed
https://github.com/solgenomics/sgn/commit/c7cbe0534f4ba60db887b8c0006c0e99836eb0e9
