### ISSUE TITLE
add trial design checking procedure at trial upload step

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2812]
Expected Behavior 
--------------------------------------------------------------------------

The code base has trial qc procedure on trial design (ie: in SolGS).
Would be valuable is the procedure for trial design checking be part of the trial layout upload step (current code is in R, a perl code may be better in that case) 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Can you elaborate a bit on what you want to have checked? Thanks!

**Comment by bauchetg** [comment]
Checking trial design conformity at upload step rather than doing in later when the trial is already stored and needs to be analyzed by a tool (ie in SolGS).
ie: If you have a complete or an incomplete design, calculation of adjusted means would be done differently: in a complete design you can do it on rep value, in an incomplete design it is adjusted based on the checks value.

Prior analysis design assumptions have to be checked based on actual data and selected design type, ie: if I have rcbd I need an identical set of entries in each of my block, not in alpha. Rather than doing this prior analysis, it could be done upfront.

The checking procedures already exist in code base (ie in SolGS or maybe in mixed model tool). Idea is implementing them earlier on in the process

**Comment by bauchetg** [comment]
similar to #2772
