### ISSUE TITLE
Observations count mismatch

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#282]
The observations count for traits shown on some trial pages does not match the number of observations in the phenotype data file downloaded from the same page. 

Eg.  For the following trial; 208  vs 104, 
https://cassavabase.org/breeders/trial/645

**Comment by lukasmueller** [comment]
Loading script has to check whether data is already aviaalblea and query user what to do, overwrite or keep the old values.

**Comment by nickmorales** [comment]
when uploading phenotypes, if the file you are uploading has values for a given plot and trait combination that already exists in the database, the interface will give an option to 'overwrite' the existing values in the database. this prevents the same plot from having more than one value for the same trait.
