### ISSUE TITLE
TED iframe stop working because https

### ISSUE THREAD

**Issue by noefp** [solgenomics/sgn#283]
Https protocol is preventing to display the http TED iframe at:

https://solgenomics.net/ted

**Comment by suryasaha** [comment]
FYI: TED is visible on IE 11 if unsecured content is allowed

**Comment by lukasmueller** [comment]
Contacted Fei about the issue.

**Comment by lukasmueller** [comment]
Link is no longer provided. Maybe we should revisit this.
