### ISSUE TITLE
trait search should be limited to variables only

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2831]
Expected Behavior 
--------------------------------------------------------------------------
we let users create lists of 'traits' from the search, thus it should be limited to variables. 
If we want to let users search for other traits, methods, and scales, maybe the right thing to do is to create a separate too for such search

https://github.com/solgenomics/sgn/blob/master/lib/SGN/Controller/AJAX/Search/Trait.pm#L18

https://github.com/solgenomics/sgn/commit/09dec2bf7948630e1ae706c135271cd73728a10d#diff-90cf24936a2ceb2e44804b1c24cbf52fL155

For Bugs:
---------

**Comment by lukasmueller** [comment]
Only variables should have a checkmark next to them for selection (unless a config key tells you otherwise) to prevent people from collecting phenotypes using traits that don't work in the upload.
