### ISSUE TITLE
Upon accession upload with a file, error message does not report missing crops correctly

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2836]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Could not replicate this in the development environment

**Comment by nickmorales** [comment]
Ive encountered this when uploading accessions from a list. If the crop
species is not in the autocomplete and a person enters a species not
already in the database it will fail in a strange way.

**Comment by lukasmueller** [comment]
I have seen it fail on a production server when uploading a file with a non-existing species, where it just silently failed. But I couldn’t reproduce that behavior in my devel system….
