### ISSUE TITLE
Materialized traits table causes problems when it doesn't update to reflect code or trait changes

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#284]
Just had to drop the cxgn_cassava materialized trait table so it could be regenerated with the new traitname format. The wizard was still creating trait lists with the old format "CO:fresh root yield" instead of "fresh root yield|CO:0000013", and those lists were failing validation. 

To avoid this, could we routinely regenerate the materialized_traits table somehow, or allow users to refresh it? Also, the traitname change has broken old_lists; would it be possible to fix them en masse?

**Comment by lukasmueller** [comment]
implement a url that updates the table (only for curators)?

**Comment by bellerbrock** [comment]
Implement materialized views from postgres 9.3+, and functions and triggers to refresh them when the tables they are based on are updated.
Look into why some wizard queries including breeding programs time out, explore the possibility of using materialized views to speed up the wizard.

**Comment by bellerbrock** [comment]
one solution is ready in topic/regenerate_mttable, but the triggers that refresh these views may not be the best solution if they make changes to the phenotype/cvterm tables much slower.

**Comment by bellerbrock** [comment]
can be resolved with topic/regenerate_mttable branch, but will not be an issue once we implement postgres 9.4 and materialized views
