### ISSUE TITLE
submit.rtbbase.org is not working for banana

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2842]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by nmenda** [comment]
autocomplete also not working for cassava and yam. Only works for sweetpotato

**Comment by lukasmueller** [comment]
I think this has been resolved?

**Comment by nmenda** [comment]
Need to create a release tag for the repo in order for the variable submit app to work 
https://github.com/Planteome/Ontology-Variable-Request-App

e.g. https://github.com/Planteome/ibp-cassava-traits/releases

Note that with every update of the obo file we need to create a new release tag in order for the change to appear in submit.rtbbase.org

**Comment by lukasmueller** [comment]
So it this fixed?
