### ISSUE TITLE
Can't call method "cvterm_id" on an undefined value

### ISSUE THREAD

**Issue by yukai0228** [solgenomics/sgn#2844]
Expected Behavior 
--------------------------------------------------------------------------
When I use docker to build and run the breedbase program, Can't call method "cvterm_id" on an undefined value appears on the homepage, I don't know if this will affect the use of the function, or how should I solve this problem?

![image](https://user-images.githubusercontent.com/6037387/77144922-18c53b00-6ac2-11ea-9ad7-de4543c22efb.png)

For Bugs:
---------

**Comment by isaak** [comment]
@yukai0228: it means your db needs some db patching... you can individually run a dbpatch at a time, starting from the latest db patch and go backwards until solved or run all missing dbpatches at once using the script run_all_patches.pl:

https://github.com/solgenomics/sgn/tree/master/db
