### ISSUE TITLE
brapi v1.3 studies dates not formated

### ISSUE THREAD

**Issue by MFlores2021** [solgenomics/sgn#2850]
Expected Behavior 
--------------------------------------------------------------------------

Brapi v1.3 studies startDate and endDate need to be corrected with ISO timestamp. Details here 
https://github.com/PhenoApps/Field-Book/issues/121

For Bugs:
---------

**Comment by lukasmueller** [comment]
Hi Mirella, I think this can be closed with commit 27366b0?

**Comment by MFlores2021** [comment]
yes!
