### ISSUE TITLE
store raw phenotyping data of biological replicates 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#2858]
Expected Behavior 
--------------------------------------------------------------------------
when uploading phenotyping file our analysis tools can handle one phenotype value per trait per sample ID.
We need a way of storing raw data in case there are biological replicates such as multiple measurements of the same trait in the same sample.
One idea is to store the average value in the phenotype table, and store the replicate values as a JSON string. 

For Bugs:
---------

**Comment by bauchetg** [comment]
@nmenda if I understand correctly, this may be available already.
See for example: https://cassavabase.org/breeders/trial/4838?format=
Under tissue sample we have multiple values that were scored for the same trait on the same plot. The data may not be clearly accessible from the UI yet but storage is effective. You can see how the data was loaded with associated files under the "uploaded file" section with file entitled: "2019-04-22_18:29:35_paula_tissue_sample_fix_arua.xls"
There you have 3 consecutive measurements for root softness on the same plant.
I worked on this implementation with @nickmorales

**Comment by titima15** [comment]
@bauchetg Thanks for the feedback. Yesterday we discussed with violet to get more info about the nature of her data. She is going to use Filedbook for data collection and we suggested tissue sample level for replications.

**Comment by titima15** [comment]
After discussing in details with Violet who requested this feature, she actually will collect data from different samples (not different values from the same sample). We already have tissue sample data level in place.
