### ISSUE TITLE
Implement a generation advancement tool

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#2866]
Expected Behavior 
--------------------------------------------------------------------------
An important feature for breeders is to track generation advancement of populations (F1,F2, F3....)
A useful feature would be to include automatically this F level incrementation to progenies generated from cross/population. It usually goes from F1 -> F8.
A further feature would reflect the generation level in the pedigree tree

For Bugs:
---------

**Comment by lukasmueller** [comment]
Implement a generation advancement tool that takes a list of plots and offers the options:
1) to automatically create new accessions, based on a naming scheme, that reflect the generation number, and associated seedlots with the specified amount of seed from that plot
2) to generate new seedlots, with the specified amount of seed, referencing the accession grown on that plot

**Comment by lukasmueller** [comment]
Discussion with Guillaume: On trial detail page, a new section should appear called "Seed Increase" which would look for a trait called 'selected line' which would show all the lines with 'selected line' set to 1 and the ability to generate seedlots with a new generation identifier.

**Comment by bauchetg** [comment]
The set of seedlots generated out of a list of harvested plot can be grouped as a "work task" and can be followed quickly after by a second task (ie: nursery harvesting is often chieved in sequences, over several days).
Having set of seedlots grouped as a work task (or other term) would help to transfer information to other teammates for example.
idea: perhaps these seedlots can be created through a transaction and validated later once harvested seeds will weighted or barcoded for ex.

**Comment by lukasmueller** [comment]
should create another ticket for the work task idea, closing this one.
