### ISSUE TITLE
in all servers, install libcurl4-openssl-dev

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#287]
In R > 3.2, installing R packages is by default from https repos.  For this, we need libcurl4-openssl-dev or equivalent debian package installed in all servers with the latest R.

(Or installing some R packages such as Curl need libcurl4-openssl-dev or equivalent package.)

**Comment by lukasmueller** [comment]
ran aptitude update; aptitude install libcurl4-openssl-dev on the following systems:
cassavabase.org
solgenomics.net
cassava-test.sgn.cornell.edu
sgn-test.sgn.cornell.edu
yambase.org
yambase-test.sgn.cornell.edu
sweetpotatobase.org
sweetpotatobase-test.sgn.cornell.edu
musabase.org
musabase-test.sgn.cornell.edu
zeabase.sgn.cornell.edu
my localhost ;-)
Please run it on your localhost too.
