### ISSUE TITLE
Invalid Plots when uploading phenotype data from Fieldbook App

### ISSUE THREAD

**Issue by afpowell** [solgenomics/sgn#2875]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

Encountered on Cassavabase

#### Steps to Reproduce

Attempt to upload data that has been exported from Fieldbook on the Fieldbook Tools page fails due to 'Invalid Plots' at the verification step. The files used in Fieldbook were using layout files directly from Cassavabase, so it is unexpected that they wouldn't pass verification.

**Comment by titima15** [comment]
@afpowell @lukasmueller Which fieldbook version are you using? If it is a new version, there is a bug in that new version.  Many users have the same problem. They just fixed the bug in the latest one.

**Comment by titima15** [comment]
The user has to update the fieldbook.

**Comment by afpowell** [comment]
The last update in the Play Store is March 9-10, and I installed this version last week.

**Comment by trife** [comment]
I released an updated version earlier this week, but I'm not sure if this bug was addressed. I don't know what could be causing this issue on the Field Book side, but if you have ideas or identify the issue, I'll get it fixed asap.

**Comment by afpowell** [comment]
This is addressed by PR #2939
