### ISSUE TITLE
recent genotype data still has missing values

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#288]

**Comment by lukasmueller** [comment]
Not sure if this is a bug or a feature.... I guess downstream analyses must be able to deal with a certain level of missing data?

**Comment by bauchetg** [comment]
I guess you are talking about imputed datasets here. Could this have something to do with chromosomes data discarded according to the current setting filtering script?

**Comment by bellerbrock** [comment]
Exactly, NAs in the current dosage data come from the process of merging
the dosage data from individual chromsomes into a single file. If an
accession was filtered out of the dosage files for some chromsomes but not
the rest, it is kept, but the missing chromosome dosage values are filled
in with NAs.

I'm not sure what is best, but the alternatives would be to either not
filter out accessions from the imputation process in the first place, or to
filter them out from every chromosome. Issak, what makes the most sense to
you?

On 13 November 2015 at 15:36, bauchetg <notifications@github.com> wrote:

> I guess you are talking about imputed datasets here. Could this have
> something to do with chromosomes data discarded according to the current
> setting filtering script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solgenomics/sgn/issues/288#issuecomment-156465608>.
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868

**Comment by isaak** [comment]
If there are missing values, I will have to impute them on the fly. But considering the size of the genotype data now, it is time consuming. 

What are you filtering out now? Criteria?

About removing accessions or markers with missing values, we will have to be cautious and transparent about the criteria used. 

What criteria are Jean-Luc group  using to filter the genotype data? I at least can use their standard when modeling. But may be keep all data in the database, since different people, who download the data for their analyses, might use different filtering criteria.

**Comment by bauchetg** [comment]
Hello Isaak,
We released a new dataset (including all previous ones) based on v6 built, I send you the link to get the data and criterias for filtering.

**Comment by bauchetg** [comment]
Fixed.
-Dataset "cassava_subset_15094_allchr.snps_noNAs.txt"  
-Available here:
/export/species/Manihot_esculenta/gbs/IGDbuildNewWithV6/genotypeFiles_VCFformat_filtered_imputed/filtered_imputed_allKcovered_15094accessions_set/dosage_files.
-Extra bash script to be added to the GBS repo.
