### ISSUE TITLE
Problem with synonyms in Accession Usage search

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2882]
A lot of my data is historical and some of the entries eventually get variety names or abbreviations, so I have many accessions with synonyms. Is breedbase designed to treat accessions and synonyms as equivalent in all search functions, trial uploads and tools etc.? I've added synonyms and run some test searches and the database doesn't seem to treat synonyms as synonymous, but I don't know if these are bugs or if I'm misunderstanding how the database treats/uses synonyms. For example, if I do an accession usage search with a certain accession name I get 6 trials, but If I search with it's synonym I get no trial data. I expected the result to be the same for both searches.

**Comment by nickmorales** [comment]
The synonyms are intended to point back to their accession in every case.
Its possible not every query or tool is respecting this.
Most of the uploads should respect this already (field trials, VCF files, etc)
