### ISSUE TITLE
Blast for short 30bp sequences not working

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/sgn#2934]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
fixed in d9e7248a8644b486815420f88c147fbff3065ee3. An additional parameter, "word size", was added to the interface that allows, in combination with a higher evalue, to match shorter sequences. This was also added to the InSilicoPCR tool.
