### ISSUE TITLE
Failure creating fieldbook file.

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#2945]
Expected Behavior 
--------------------------------------------------------------------------
This is the error message:

DBD::Pg::st execute failed: ERROR:  invalid input syntax for integer: "[70727,70691,76587,76580,70681,76615]" at /home/vagrant/cxgn/cxgn-corelibs/lib/CXGN/Chado/Cvterm.pm line 376.

For Bugs:
---------

**Comment by afpowell** [comment]
I was just able to successfully create a trait file by selecting a single trait. I still got the error attempting from trait list.

**Comment by titima15** [comment]
@afpowell I'm on PTO, sorry I wouldn't be able to help during this time.

**Comment by chris263** [comment]
Problem solved.
