### ISSUE TITLE
Error message when managing trials and from analysis tools

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2952]
I have my trait ontology, locations, accessions, pedigrees, and all my trials and trial data etc. loaded into my breedbase instance. No problems loading the data into the database; however, when I navigate to the trial page I get a notification that an error has  occurred. I see this error message in the error log:

```
breedbase_db    | 2020-05-29 12:52:40.942 UTC [59] ERROR:  materialized view "traits" has not been populated
breedbase_db    | 2020-05-29 12:52:40.942 UTC [59] HINT:  Use the REFRESH MATERIALIZED VIEW command.
breedbase_db    | 2020-05-29 12:52:40.942 UTC [59] STATEMENT:  SELECT trait_id, trait_name FROM public.traits WHERE trait_id IS NOT NULL ORDER BY 2
breedbase_web   | Goto URL = 
breedbase_web   | NOW LOGGING IN USER janedoe
breedbase_web   | FOUND: 41
breedbase_web   | criteria_list=$VAR_DUMP1 = [
breedbase_web   |                'traits'
breedbase_web   |              ];
breedbase_web   | dataref=$VAR_DUMP1 = {};
breedbase_web   | queryref=$VAR_DUMP1 = {};
breedbase_web   | target_table=traits
breedbase_web   | QUERY: SELECT trait_id, trait_name FROM public.traits WHERE trait_id IS NOT NULL ORDER BY 2
breedbase_web   | DBD::Pg::st execute failed: ERROR:  materialized view "traits" has not been populated
breedbase_web   | HINT:  Use the REFRESH MATERIALIZED VIEW command. at lib/CXGN/BreederSearch.pm line 153.
breedbase_web   | cannot open file /home/production/public/static_content/folder/entire_jstree_html_trial.txt at lib/SGN/Controller/AJAX/Trials.pm line 72.
breedbase_web   | readline() on closed filehandle $fh at lib/SGN/Controller/AJAX/Trials.pm line 75.

```
None of the trial analysis tools seem to work either, I just get a message that an error has occurred. I'm using the latest docker image (v10).

**Comment by ch728** [comment]
An issue with my trait ontology seemed to be causing problems. Something about a duplicated "VARIABLE_OF" in the CVTERM table.  I loaded in two ontology files and I think the second ontology I loaded may have caused this problem. After deleting the duplicate term from the CVTERM table the error went away. But the analysis tools (anova and correlations) available when you go the trial page still don't work. Seems to be something with the Slurm configuration.

**Comment by nickmorales** [comment]
Ive seen this problem many times too when loading obo file ontologies from backend scripts. I usually do an "update cvterm_relationship set type_id=CVTERM_ID1 where type_id=CVTERM_ID2" and then delete CVTERM_ID2. It would be great to turn the obo upload into an online process and to fix this problem

**Comment by lukasmueller** [comment]
Chris, could you solve your issue with the slurm configuration?

**Comment by ch728** [comment]
The heritability, PCA, correlation, and clustering tools seem to work fine on the trial analysis page, but the ANOVA tool keeps saying "There is no anova output for the datasete." I  don't think it's a Slurm problem.  It's strange to me that the anova would fail but the heritability tool works. I assume they are fitting the same model on the R end?

**Comment by lukasmueller** [comment]
Hi Chris,

Yes, I guess that means that slurm works. Maybe Isaak can comment on the ANOVA issue. I copy him here.

cheers, Lukas

**Comment by isaak** [comment]
The heritablity and ANOVA are based on different models and scripts. But as to the ANOVA failure, could you check the content of a file something like anova-[trial_id]-[trait_id]-err-XXXXX in the anova/tempfiles folder?

**Comment by ch728** [comment]
Okay, I assumed the anova and heritability tool were both fitting a model like lmer(trait ~ (1|block) + genotype)  for RCBD. This is the output from one of my anova runs:
Warning messages:
1: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'phenoAnalysis' 
2: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'phenoAnalysis' 
3: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'phenoAnalysis' 
Read 6 items
Read 3 items
pheno file: /home/production/tmp/127.0.0.1/Agriplex_550/solgs/cache/phenotype_data_225.txt
traits file: /home/production/tmp/127.0.0.1/Agriplex_550/anova/tempfiles/anova_traits_file_225-MowYf
metadata file: /home/production/tmp/127.0.0.1/Agriplex_550/solgs/cache/phenotype_metadata.txt
Read 40 items
Warning message:
In fread(phenoDataFile, header = TRUE, sep = "\t", drop = dropCols,  :
  na.strings[3]==" " consists only of whitespace, ignoring. Since strip.white=TRUE (default), use na.strings="" to specify that any number of spaces in a string column should be read as <NA>.
Read 0 items

**Comment by isaak** [comment]
Yes, the anova tool is fitting the model above for RCBD. The heritability is fitting the genotypes as random (Chris can say more about the heritability). 

Looks like there is problem extracting the trait data from the phenotype file. Is the log stopping at the 'Read 0 items'?

Could you post, here, a screenshot of the acronyms table, after running the correlation?

**Comment by ch728** [comment]
Yes, the log stops at "Read 0 items". This seems to happen for all traits that I have tried. I'm running the tool  under the analysis tab on the trial page and I don't see an acronym table. I haven't specified any acronyms, but I notice that some of my traits seem to be linked to acronyms like "YA" and "RA". I am not sure where these are coming from. See below screenshots in the correlation table.
![correlation_table](https://user-images.githubusercontent.com/36375878/86612422-b8291380-bf75-11ea-96ab-540509e48ee4.png)

**Comment by isaak** [comment]
![image](https://user-images.githubusercontent.com/163702/86628008-8346ac00-bfc9-11ea-8ffb-3212744c0a9a.png)

How recent is your checkout of the codebase? You may need to update your sgn, and R_libs repos.

**Comment by ch728** [comment]
I'm using the v10 Docker image, but I will upgrade to v11 soon. Maybe that will fix the problem?

**Comment by isaak** [comment]
That would be a good start...

**Comment by ch728** [comment]
Okay, I'm all up to date I think. SGN version is sgn-278.0-5-g33794b0e9 and R_lib version rlibs-002-9-g055a8a0c. The error message looks the same. I don't see any acronyms in the acronym table, although my yield and ratoon yield traits have been converted to acronyms in the correlation plot.
![Screenshot from 2020-07-06 22-30-17](https://user-images.githubusercontent.com/36375878/86697467-6a93c180-bfdc-11ea-82df-c2d5a2c15256.png)

**Comment by isaak** [comment]
Any clues in the /var/log/sgn/error log?

We can also do co-debugging on Zoom?

**Comment by ch728** [comment]
I'm not seeing anything that points to an answer in error.log. I could Zoom sometime in the afternoon this Thursday. Would that work for you?

**Comment by isaak** [comment]
Monday or Tuesday, ideally before 18:00 CET, would work for me.

**Comment by ch728** [comment]
Unfortunately early next week won't work for me. I can do near the end of the week or into the week after.

**Comment by dwaring87** [comment]
@isaak we're also seeing the same error when trying to run an ANOVA from the trial detail page (There is no anova output for this dataset).  The PCA works and we get acronyms displayed on the axes but the acronym table below that is empty.

I've looked through some of the temp files and the phenotype_data file looks good but the anova_traits_file is empty and the phenotype_metadata file just has a header row.

**Comment by lukasmueller** [comment]
Has this been fixed? Please update the issue or close it.

**Comment by ch728** [comment]
Hasn't been fixed quite yet. Fixed one problem, but there still seems to be some bug related to trait names/acronyms.

**Comment by ch728** [comment]
@dwaring87 pulling the latest code seems to fix this issue, at least for me. Closing for now.
