### ISSUE TITLE
Warning/error with pedigree viewer tool

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2954]
The pedigree viewer tools seems to work most of the time, but I'm seeing this warning message repeated many times in the error log.
`Use of uninitialized value $return_status in numeric eq (==) at lib/SGN/Controller/AJAX/BrAPI.pm line 211.
`
Sometimes the pedigree won't load and I get an error message on the page. The error message seems to occur with newer lines that have very deep pedigrees. I'm using the v10 docker image.

**Comment by ch728** [comment]
Okay, I actually can't seem to reproduce the error myself. I don't remember which accession caused the issue, but If I come across the error again I will provide you with the pedigree. It is still taking a really long time to load pedigrees into the viewer and it some cases the pedigree never loads and it's stuck saying "Loading...".  The pedigree string will show up, but the interactive tree never loads. I'm not seeing any error messages in these cases though. Is this normal? Is there something I need to configure or a specific web browser I should use?

**Comment by MFlores2021** [comment]
takes a bit of time but it gets loaded. is this slow in your VM also? do you have a lot of data? I will compare performance in our server and local.

**Comment by ch728** [comment]
I am not sure if it's a lot of data, but I have  ~32,500 accessions with pedigree data. The pedigree for a given accession tends to be very deep, going back around 15 generations. I am running the system on a VPS with 8 cores and 8G RAM.

**Comment by ch728** [comment]
Loading the pedigrees when running the system locally on my laptop instead of the server seems to work fine....

**Comment by MFlores2021** [comment]
the server can have some other process running in parallel sometimes, it can result in delay also.

**Comment by lukasmueller** [comment]
So should we close this ticket?

**Comment by ch728** [comment]
Yeah, I think so

**Comment by ch728** [comment]
Looking back at this, the problem was that I had changed the brapi_require_login to 1 at some point. When I switched this back to 0 the pedigree tool and a bunch of other errors were resolved.
