### ISSUE TITLE
Adding a new genotyping facility

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2955]
Is there a way to add a new genotyping facility to the database?

**Comment by lukasmueller** [comment]
I don't know, will check! :-)

**Comment by nickmorales** [comment]
We can make this a conf key. Right now it’s just hard coded in the select that shows up

**Comment by ch728** [comment]
That would be dope. It would be nice to have that conf option for field management factors as well.

**Comment by lukasmueller** [comment]
Good idea. Let’s create a ticket for that as well!

cheers
Lukas

**Comment by titima15** [comment]
Done. Close via 33794b0
