### ISSUE TITLE
Tissue samples page doesn't list samples

### ISSUE THREAD

**Issue by MFlores2021** [solgenomics/sgn#2974]
Expected Behavior 
--------------------------------------------------------------------------
Tissue samples page should show a tissue samples list. Currently is is showing only trials involved. No way to see samples without downloading first.

For Bugs:
---------

**Comment by titima15** [comment]
Manage tissue sample page lists trials that have tissue samples. All of the tissue samples in each trial are in the trial details page.

**Comment by titima15** [comment]
Each trial can have a large number of tissue samples, I think it's not a good idea to display all of the samples in one page. Users can use the link for trial detail page to check tissue samples in each trial.
