### ISSUE TITLE
Clean old trial out of CASS-base database

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#298]
CASS-base is a copy of Cassavabase, but it should not have the trials from Cassavabase (just the accessions and other metadata).

**Comment by nickmorales** [comment]
that means to delete everything in the project table?

**Comment by lukasmueller** [comment]
In a sense, yes. But the trials themselves also need to be removed. There is a script (I think it is called delete_trials.pl) that will do that.

**Comment by nickmorales** [comment]
Ok this is in progress, but the script is slow and will take several days to finish

**Comment by nickmorales** [comment]
also moved cxgn_cass to db5 and applied patches
