### ISSUE TITLE
Download Phenotype or genotype from search wizard not working

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#2983]
Expected Behavior 
--------------------------------------------------------------------------

There ins't an error message, just not working.

For Bugs:
---------

**Comment by nickmorales** [comment]
Please be sure that all db patches have been run when updating the sites. The patches in 00125 added analyses into the wizard so lack of them being run may be causing this.

**Comment by chris263** [comment]
Yeah, it was my first thought.  I ran all db patches last weekend but still not working. Maybe should I try again?

**Comment by nickmorales** [comment]
on which database is this a problem?

**Comment by chris263** [comment]
both db4.sgn.cornell.edu and db5.sgn.cornell.edu

**Comment by chris263** [comment]
It is working now after updating the site and running all patches. But still taking a long time for download the data
