### ISSUE TITLE
Make field management factors configurable in the sgn_local.conf with a appropriate default in sgn.conf

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#2988]
Expected Behavior 
--------------------------------------------------------------------------

Make field management factors configurable in the sgn_local.conf with a appropriate default in sgn.conf.

Currently, the management factors are hard-coded in a pull down menu on the trial create page (I think?)

For Bugs:
---------

**Comment by titima15** [comment]
Done. Close via 214ce1b
