### ISSUE TITLE
Implement analysis of variance of traits between trials (locations or years)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#299]

**Comment by lukasmueller** [comment]
variance of traits in different locations, years, or treatments

**Comment by bauchetg** [comment]
Nearly there, still implementing reshape components

**Comment by lukasmueller** [comment]
ANOVA & Heritability

**Comment by lukasmueller** [comment]
create branch topic/anova for this issue

**Comment by lukasmueller** [comment]
First implementation should only cover one trial...
branch topic/solgs/anova

**Comment by lukasmueller** [comment]
This was implemented by Isaak a while ago. Closing this ticket.
