### ISSUE TITLE
Errors after upgrading to new Docker image

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2991]
I have noticed that whenever I upgrade to the newest breedbase docker image my current database usually breaks (I get a lot of error messages) and I end up having to reload all my data into a fresh version. For example, I upgraded from v10 to v11 and now I am getting an error on the trial page about not being able to refresh trial jstree html and an error about not being
able to load trial data. Is there a better way/best practice for upgrading the system?

**Comment by nickmorales** [comment]
there are database patches (db patches) that need to be run on the database to match the code base. you can use the run_all_patches.pl script here https://github.com/solgenomics/sgn/tree/master/db 
for best practices, the Docker should run this script on start-up of the Docker service

**Comment by ch728** [comment]
Good call! Works now.
