### ISSUE TITLE
Error using GWAS tool

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#2997]
I'm able to load a dataset into the GWAS tool, but I get an error message when I press select dataset. See attached screenshots showing the webpage message and the error log.

![Screenshot from 2020-07-09 20-01-00](https://user-images.githubusercontent.com/36375878/87102472-03fee580-c220-11ea-9840-ee67568ab274.png)

![Screenshot from 2020-07-09 20-04-28](https://user-images.githubusercontent.com/36375878/87102465-ffd2c800-c21f-11ea-8250-d7efbc2a281c.png)

**Comment by afpowell** [comment]
Fixed by PR #3006
