### ISSUE TITLE
gene links in JBrowse should point to the locus page

### ISSUE THREAD

**Issue by noefp** [solgenomics/sgn#301]
When clicking on a gene in Jbrowse links to the search function and is very slow to get to the locus page.

The link should point to the locus page or the genome feature directly.

**Comment by nmenda** [comment]
gene model names in jbrowse have version number . For linking to the locus page the version needs to be removed. This takes care of it https://github.com/solgenomics/sgn/commit/faca3e3aefbb7d4ec224a8e44d2729308240b24b

will update the target URL in the jbrowse conf file after the site update
