### ISSUE TITLE
installing R packages in R > = 3.2

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#302]
R >= 3.2 defaults to downloading packages from https mirrors. Even though, installing debian package libcurl4-openssl-dev is supposed to enable that, in our servers it does not. As it is, trying to install an R package from the R command line will give you something like this:
-----------------
 install.packages('rgl')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) : 
  unsupported URL scheme
Warning: unable to access index for repository https://cran.r-project.org/src/contrib
Warning message:
package ‘rgl’ is not available (for R version 3.2.2) 
-----------------

Until we figure out a solution, workarounds are:
1. you choose an http mirror instead of an https mirror 
2. Or add  'options(download.file.method = "wget")' to the /etc/R/Rprofile.site file and continue to use an https mirror.

**Comment by lukasmueller** [comment]
This was completed by Isaak.
