### ISSUE TITLE
Split genotyping information into genotype props for different chromosomes

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3033]
Expected Behavior 
--------------------------------------------------------------------------

Currently, the genotype prop represents an entire genome, which leads to issues when genome are large because large genomes may exceed the storage capacity of a jsonb field in postgres. The solution is to store each chromosome separately in a genotypeprop, which should be all associated with a single genotype entry.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Clay to add automatic splitting of vcf files into chromosome level files in the upload process
add chromosome information to genotype prop as a top level chromosome_number key

**Comment by ClayBirkett** [comment]
https://github.com/solgenomics/sgn/commit/1fc3c12319a57f90206f9a558d59f370b5bc4072
