### ISSUE TITLE
Enable upload of LIMS ID with a measurement into breedbase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3055]
Expected Behavior 
--------------------------------------------------------------------------

Enable upload of LIMS ID with a measurement into breedbase, using an extra column in the excel sheet for upload

For Bugs:
---------

**Comment by lukasmueller** [comment]
store the LIMS ID as an nd_experimentprop

**Comment by lukasmueller** [comment]
add this field to the "Detailed" upload format

**Comment by chris263** [comment]
This pull request https://github.com/solgenomics/sgn/pull/3311 close this ticket
