### ISSUE TITLE
Rename the genotype table in the phenome schema

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3066]
Expected Behavior 
--------------------------------------------------------------------------
rename it to phenome_genotype

For Bugs:
---------

**Comment by lukasmueller** [comment]
created a branch topic/fix_genotype_table and added a dbpatch that will rename phenome.genotype to phenome.phenome_genotype

**Comment by nmenda** [comment]
need to merge branches in cxgn-corelibs, phenome, and cview
