### ISSUE TITLE
Tables which display accessions take a long time to load.

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#3101]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
Found this problem in the search page and breeding program detail page, seems to be specific to accessions.

**Comment by lukasmueller** [comment]
The table on the Breeding Program page definitely has an issue... The general search could be faster as well.

**Comment by lukasmueller** [comment]
Stock search crashes for certain pages, see also Brapi issue
