### ISSUE TITLE
Does breedbase validate vcf uploads against protocol specification?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3107]
So, when I upload a vcf with a new protocol (marker set) I am asked by the walk through to define a protocol. Then for subsequent uploads of vcfs genotyped with the same marker set I select the defined protocol. Currently, I validate the vcfs (marker order, ref/alt designation, marker number, info fields etc.) before I upload. I was wondering if breedbase performs any of these checks against the defined protocol? In other words, does breedbase validate vcf uploads against the protocol specification?

**Comment by nickmorales** [comment]
Would a good validation be to check if the markers defined in the secondly uploaded VCF are exactly the same (REF, ALT, INFO, etc.) as the markers defined in the firstly uploaded VCF?

**Comment by ch728** [comment]
Yes, I think that would be very useful if that's not what's happening when defining a gentoype protocol. I don't expect the vendor to provide us with inconsistent vcfs but it could happen, and it would be nice to know breedbase checks on upload. Imagine if the ref/alt  changed in one year? GS based on the resulting dosage file would be disastrous.
