### ISSUE TITLE
Cassavabase BrAPI Server Error

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3109]
When trying to retrieve germplasm records via BrAPI on cassavabase, one of the pages of results will always return a "Server Error".  

Using the `/germplasm?pageSize=500` endpoint will work for all pages except page 17.

Page 16 works:
https://cassavabase.org/brapi/v1/germplasm?pageSize=500&page=16 

Page 17 fails:
https://cassavabase.org/brapi/v1/germplasm?pageSize=500&page=17

Page 18 works:
https://cassavabase.org/brapi/v1/germplasm?pageSize=500&page=18

Maybe there's a record with a special character that's causing the BrAPI formatting to fail?

**Comment by MFlores2021** [comment]
Problematic accession Alemao-Aracruz

**Comment by dwaring87** [comment]
@MFlores2021 @lukasmueller is there any update on a fix for this issue?
