### ISSUE TITLE
Genotype plate bulk upload

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3114]
I was wondering if there were any plans to enable bulk upload of genotype plates? For a given genotyping project we usually have around 40-50 plates of tissue, so it becomes very cumbersome to upload one plate at a time. Also, if we choose to generate the plates from within Breedbase using a list of tissue samples we have to create a list separately  for each plate as well. Having an option for a bulk upload of multiple trials from an Excel spreadsheet and/or a list would be very useful.

**Comment by ch728** [comment]
I need to test it still, but I think the sampling trial concept essentially provides this functionality

**Comment by bauchetg** [comment]
Hi @ch728, I am looking for the sampling trial functionality you mentioned, it is already accessible?

**Comment by ch728** [comment]
Yes, if you scroll down on this page https://www.cassavabase.org/breeders/samples/ you will see the section for creating sampling trials. I ended up not going the sampling trial route. Instead we used this script https://github.com/solgenomics/sgn/blob/master/bin/load_genotyping_plates.pl to bulk upload the plates on the back-end.

**Comment by MFlores2021** [comment]
this was addressed here https://github.com/solgenomics/sgn/pull/3763
