### ISSUE TITLE
Connecting Field Book and Breedbase through BrAPI

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3117]
Is there something special that needs to be configured on the Breedbase end for the Field Book BrAPI integration? I am able to connect to my BreedBase instance and the authentication process shown below works.

![authentication_screen](https://user-images.githubusercontent.com/36375878/97217096-23a12600-179d-11eb-9633-4eb934e07700.png)

However when I try to pull in the field layouts I get the BrAPI authorization error show below and I am prompted to login again. Re-logging in does not solve the problem.

![deny](https://user-images.githubusercontent.com/36375878/97217296-7084fc80-179d-11eb-841c-81a2da7a05d6.png)

**Comment by ClayBirkett** [comment]
I was able to use the Field Book App correctly just last week. Are you a curator on the database you are using? Are you using the latest v4.5

**Comment by ch728** [comment]
Yes, I have curator privileges on the database and I am using v4.5 of the FieldBook app. Did you have to setup anything in your sgn_local.conf for it to work?

**Comment by ClayBirkett** [comment]
The problem could be because your website has a second level of authentication in addition to the breedbase authentication. You might be able to allow access by IP address of local network (tablet) to get around this problem.

**Comment by nickmorales** [comment]
If you have an nginx password or something like that running on top of the website, you can try passing the nginx username and password in the URL request like https://username:password@mysite.cornell.edu

In the future maybe fieldbook should pass such passwords in with the Authorization header? That is the better approach https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by ch728** [comment]
@ClayBirkett I do have a nginx password setup. Trying the suggestion of @nickmorales  doesn't not eliminate the problem unfortunately.

**Comment by ch728** [comment]
So I modified my ngnix.conf to allow the brapi calls through without the second level of authentication. Now I can import traits but not trials for some reason. I get this same error when trying with Cassavabase as well.

![Screenshot from 2020-10-26 15-04-03](https://user-images.githubusercontent.com/36375878/97348471-91645500-1864-11eb-95fe-8141d80140dd.png)

**Comment by ch728** [comment]
I had to switch the nginx config back otherwise it is possible to search our data via brapi without logging into our breedbase instance. There doesn't seem to be a way to allow FieldBook to interact with Breedbase and have our data be secure. We can't have this on our production database :(

**Comment by nickmorales** [comment]
In the configuration file (sgn_local.conf) there is a key called brapi_require_login and when it is 1 the brapi calls require a key called access_token to contain a valid login token. not sure if this is all set to work fully though with fieldbook

**Comment by ch728** [comment]
hmm, okay. Something like that would be nice! Either that or change things on the FieldBook side to pass the authentication through. Something I could ask the Fieldbook folks about.  I tried messing with the brapi_require_login key before and it prevented the brapps built into Breedbase, like the pedigree viewer, from working properly.

**Comment by ch728** [comment]
I am closing this issue. It was not technically a breedbase issue. The problem was due to the ngnix password being incompatible with how brapi does authentication. The solution is to configure ngnix so it doesn't enforce password authentication on location ~/brapi. Instead, the brapi_require_login key should be set to 1 for protecting the /brapi calls. The remaining issue with loading the plots into FieldBook was because FieldBook has a one minute time out and /brapi/v1 calls where taking longer than a minute.
