### ISSUE TITLE
Install JBrowse2 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#3140]
Expected Behavior 
--------------------------------------------------------------------------
https://jbrowse.org/jb2/

For Bugs:
---------

**Comment by lukasmueller** [comment]
What new features does Jbrowse 2 have? What would be cool would be comparative features...

**Comment by nmenda** [comment]
https://solgenomics.net/jbrowse2/

See here the Jbrowse2 features compared to Jbrowse1 
https://jbrowse.org/jb2/features/

Jbrowse2 is installed, currently the Eggplant V4.1 genome is loaded 
The only issue for us may be the inability to create stable URL links to specific assemblies and locations
