### ISSUE TITLE
add planting date to plot for musabase, as plants are sometimes replaced (gap filling)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3145]
Expected Behavior 
--------------------------------------------------------------------------
Requested by Rony and Violet
The planting date can be added as a trait (trait needs to be added to the ontology)
Usually the same genotype is planted again, so no need to change that

For Bugs:
---------

**Comment by chris263** [comment]
There is a pull request for that https://github.com/Planteome/CO_325-banana-traits/pull/48.

**Comment by nmenda** [comment]
We should avoid adding traits for dates, these are normally stored as properties (projectprop, can also be stockprop if needed)

**Comment by nmenda** [comment]
The following date terms should be obsolete 
https://github.com/Planteome/CO_325-banana-traits/commit/b8110e662d395a271121167882079f2f3902f77c

**Comment by nmenda** [comment]
we have a 'date of' term in the time ontology, need to have a better way of using date terms 
https://musabase.org/cvterm/77475/view

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/blob/bc350e9378bd9cc3725b27214da4f5752691b174/ontology/cxgn_time.obo#L544

**Comment by nmenda** [comment]
I can also see duplications in TIME ontology terms, 
we have 'post harvesting' in musabse https://github.com/solgenomics/sgn/blob/bc350e9378bd9cc3725b27214da4f5752691b174/ontology/cxgn_time.obo#L530

and 'after harvest' in sweetpotatobase 
https://sweetpotatobase.org/tools/compose
https://sweetpotatobase.org/cvterm/78111/view

**Comment by bellerbrock** [comment]
Hey @naama for the terms that look duplicated, maybe we can reorganize them like this?

```
[Term]
id: TIME:0000076
name: "exact stages"
def: "." []
is_a: TIME:0000000

[Term]
id: TIME:0000080
name: at planting
synonym: "PLT" EXACT []
def: "planting stage:
is_a: TIME:0000076

[Term]
id: TIME:0000077
name: at flowering
synonym: "FLW" EXACT []
def: "flowering (shooting is here equivalent to flowering) stage"
is_a: TIME:0000076

[Term]
id: TIME:0000078
name: at harvest
synonym: "HVT" EXACT []
def: "harvesting stage"
is_a: TIME:0000076

[Term]
id: TIME:0000477
name: "relative stages"
def: "." []
is_a: TIME:0000000

[Term]
id: TIME:0000478
name: after planting
synonym: "AftPlt" EXACT []
def: "" []
is_a: TIME:0000477

[Term]
id: TIME:0000481
name: before flowering
synonym: "AftPlt" EXACT []
def: "" []
is_a: TIME:0000477

[Term]
id: TIME:0000482
name: after flowering
synonym: "AftPlt" EXACT []
def: "" []
is_a: TIME:0000477

[Term]
id: TIME:0000479
name: before harvest
synonym: "BfrHvt" EXACT []
def: "" []
is_a: TIME:0000477

[Term]
id: TIME:0000480
name: after harvest
synonym: "AftHvt" EXACT []
def: "" []
is_a: TIME:0000477
```

The exact terms would work on their own, the relative terms would be used in combination with a dayy, week, or month time term.

**Comment by nmenda** [comment]
'planting date' and 'harvest date' are available in the phenotyping template, need to use these fields and not create a new ontology ID 
Those date values will also be used for calculating derived traits in the number of days by calculating the diff between a post-composed 'date of' trait and the plot/plant planting date
