### ISSUE TITLE
Display a table with an accession average for each trait on trial detail page

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3149]
Expected Behavior 
--------------------------------------------------------------------------
As requested by Rony and Violet
Currently, summaries are always by plot. Accessions planted on several plots/replicates should be averaged.

For Bugs:
---------

**Comment by nickmorales** [comment]
On the trial detail page under Phenotype Summary Statistics, you can select to see the values for individual plots or plants, or you can see it grouped by accession.

![image](https://user-images.githubusercontent.com/7028512/98695581-caaac380-2340-11eb-99cc-9a6d57f9a88e.png)

**Comment by lukasmueller** [comment]
But the accession is shown multiple times in column 1. It should only be there once and the average displayed for the entire trial? Maybe I am missing something?
