### ISSUE TITLE
BrAPI implementation

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#315]
http://docs.brapi.apiary.io/#

**Comment by nickmorales** [comment]
Authenticate
```/brapi/v1/token?grant_type=password&username=USERNAME&password=PASSWORD&client_id=CLIENT_ID```

Germplasm Search by Name (matchMethod: wildcard or exact. wildcard takes * or % for many character matching and ? for single character matching). **Include not Implemented**. Pagination Done
```brapi/v1/germplasm?name=*mo?re%&matchMethod=wildcard&include=&pageSize=1000&page=10```

Germplasm Details by GermplasmDbId. Pagination Done.
```brapi/v1/germplasm/{id}```

Germplasm Details List by StudyDbId. Pagination Done
```brapi/v1/studies/{studyId}/germplasm?pageSize=20&page=1 ```

Germplasm Pedigree. **Notation not implemented**. Pagination Done.
```brapi/v1/germplasm/{id}/pedigree?notation=purdy```

Germplasm MarkerProfiles... **Not Sure If Implemented Correctly**.
```brapi/v1/germplasm/{id}/markerprofiles```

List of Studies. Pagination Done
```brapi/v1/studies?programId=programId&pageSize=1000&page=10```

**Comment by bauchetg** [comment]
all brapi issues are now tracked here; https://github.com/plantbreeding/API/issues
