### ISSUE TITLE
Define file format for high dimensionality phenotype uploads

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3164]
Expected Behavior 
--------------------------------------------------------------------------

File format plus sample data

For Bugs:
---------

**Comment by aco46** [comment]
Here is a sample expression file. It contains two genotypes with 5 tissue sample each. CSV file format is not of the formats accepted here, so I saved it as tab delimited format.

This is just one use case of expression output. Most cases would have replications. We should think about this while writing the loader.
 
[Expression_sample_input_file.txt](https://github.com/solgenomics/sgn/files/5539850/Expression_sample_input_file.txt)

**Comment by ljbrzozowski** [comment]
[LCMS_data_for_testing_loader.zip](https://github.com/solgenomics/sgn/files/5570069/LCMS_data_for_testing_loader.zip)

There are three files for sample input:
1) Metadata_StudyDescription - this is metadata related to experimental design, chemical analyses and consistent with what is requested for other metabolomics databases 
(2) Metadata_CompoundAnnotations - annotation of chemical data, InChi key, RT, mass
(3) LCMS_data - sample phenotypes where the first column is genotype names

**Comment by ljbrzozowski** [comment]
Here is raw plot-level data file too that includes experimental design metadata (rows, columns, batch, +). This was used to calculate the blups that are in the LCMS_data file above (file #3) 

[QCRFSC_LCMS_2018_LC.03metadata_and_abundance_all.csv.zip](https://github.com/solgenomics/sgn/files/5575781/QCRFSC_LCMS_2018_LC.03metadata_and_abundance_all.csv.zip)

**Comment by ljbrzozowski** [comment]
Here is the plot-level data with experimental design metadata (row, column, batch +) that was used the calculate the blups in file 3 (above)
[QCRFSC_LCMS_2018_LC.03metadata_and_abundance_all.csv.zip](https://github.com/solgenomics/sgn/files/5575789/QCRFSC_LCMS_2018_LC.03metadata_and_abundance_all.csv.zip)

**Comment by aco46** [comment]
High Dimensional Phenotyping Data Storage File Format

Dataset upload should include  the below components and spreadsheet file formats.
1.	Sampling (tissue samples) experiment trial upload: metadata and plate layout associated to tissue sampling. 
2.	Phenotyping and protocol metadata: captures metadata associated with sample processing and study description. Also captures in details metadata associated with spectra wavelength (in the case of NIRS), genome features/genes (in the case of transcriptomics) and metabolites for metabolomics data upload.
3.	Phenotype matrix: includes matrix of phenotypes along with matching tissue sample names from an already existing sampling trial in the database.

As an example, the phenotyping metadata spreadsheet for Transcriptomics would contain columns such as transcript_name, chromosome, start_position, end_position and gene annotation description. This is also same for metabolomics with compound annotation metadata.

Users should be able to compare protocols before deciding to use an already existing protocol or a new protocol during uploads. A plugin that compares could be an R script or other ways that such comparison can be made.

During uploads, the database should be able to verify if phenotype matrix column number is similar to the number of columns expected for a specific device (in the case of NIRS), number of genes (in the case of transcripts and genome versions) and specificities associated with metabolomics.

As much as possible unifying the upload pipeline across NIRS, Transcriptomics, and Metabolomics would be a good approach to follow.

**Comment by ljbrzozowski** [comment]
[database_metadata.xlsx](https://github.com/solgenomics/sgn/files/5717732/database_metadata.xlsx)

Here is a list for the drop down menus for setting up a metabolomics protocol.

**Comment by lukasmueller** [comment]
Idea: Use sample preparation ontology  to describe sample used in experiments, see https://cassavabase.org/tools/compose/

**Comment by lukasmueller** [comment]
For describing metabolites, we have used ChEBI in the past

**Comment by ljbrzozowski** [comment]
Here is an updated list for metabolite metadata
[database_metadata.xlsx](https://github.com/solgenomics/sgn/files/5858553/database_metadata.xlsx)
