### ISSUE TITLE
Implement web interface for the high dimensionality data

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3165]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by nickmorales** [comment]
I think I'll change the NIRS upload interface to be a generic "high-dimensional" phenotype upload interface

**Comment by nickmorales** [comment]
@aco46 i think we should add a tab in the workflow about defining the sample names. @lukasmueller maybe we should allow people to define a "samples plate layout". It could be pretty much the same as the genotyping plate, but would allow people to store any metadata they have for their samples. We can make the "genotyping plate" more generic to handle samples.
