### ISSUE TITLE
Download for high dimensionality phenotypic data

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3166]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Also make it compatible for NIRS data?

**Comment by aco46** [comment]
Jean-Luc mentioned in the last meeting that the expectation regarding metabolomics phenotype download would be two spreadsheets (phenotype matrix & metabolites description spreadsheets).

**Comment by nickmorales** [comment]
closed by #3279
