### ISSUE TITLE
Add sample_unity and treatment to the nirs upload tool

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#3170]
Expected Behavior 
--------------------------------------------------------------------------
Sample prep should have the same options as in "object" at post composed traits. Treatment should the same as "attribute".

https://cassavabase.org/tools/compose/   

For Bugs:
---------

**Comment by lukasmueller** [comment]
potentially needs more discussion?

**Comment by chris263** [comment]
Solved with new post compose traits options
