### ISSUE TITLE
Field map/layout orientation error/customization

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3175]
Expected Behavior 
--------------------------------------------------------------------------

The current field map set up does not not allow the selection of the starting point of plot number if you create or if you upload an already existing trial.
This result in:
-a lack of flexibility and usage while creating the trial in breedbase.
-in the case of the upload of an already existing trial, the plot numbering turn to be incorrectly displayed.

Having the ability the starting point of the plot numbering in the design step (ie: bottom left, top left, etc..) would solve the problem and/or offer post trial creation customization on trial map display

These elements were previously identified in #1803 
For Bugs:
---------
incorrect display of coordinate in field map when row col info are provided at trial upload

**Comment by aco46** [comment]
Fixed @ #3356
