### ISSUE TITLE
Marker set filter not working

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3180]
The Marker Set Filter option under the Related Genotype Data tab on the wizard page does not seem to be working. An example of what my marker set looks like is below. I expected this to subset the data to chromosome 1, but data from all chromosomes are returned.  Is there something I am doing something wrong? It seems like the purpose of Marker Sets is to allow the user to have pre-defined filter settings and/or  markers subsets from a genotyping protocol? 

![Screenshot from 2020-11-19 20-43-20](https://user-images.githubusercontent.com/36375878/99747656-fa786a80-2aa8-11eb-97fc-b89879d1f96f.png)

**Comment by lukasmueller** [comment]
Need to finalize the next-gen marker search
