### ISSUE TITLE
Issue with BrAPI export from FieldBook

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3182]
I'm having issues exporting data from FieldBook to Breedbase. The error is shown in the terminal screenshot below
![Screenshot from 2020-11-19 22-05-27](https://user-images.githubusercontent.com/36375878/99753206-d1a9a280-2ab3-11eb-92dd-8f44eb6c0917.png)
.

**Comment by MFlores2021** [comment]
Seems like breedbase was working with variable_db_id. And Fieldbook only pass trait_name now. @trife did you make any changes here?
@bellerbrock

**Comment by trife** [comment]
Yeah that looks like what's happening but I don't see any obvious changes that would have resulted in that happening. @ch728 can you look at the Field Book database with an SQLite viewer and verify that the external_db_id in the traits table populated correctly?

**Comment by ch728** [comment]
@trife amd @MFlores2021  it looked fine to me. Right now I'm testing fieldbook against a sandbox breedbase instance with some toy data. If it helps with debugging you are welcome connect to it at http://breedbase.southcentralus.cloudapp.azure.com/. The login is the default "janedoe" and "secretpw".

**Comment by trife** [comment]
I traced this all the way back to the brapi java library and still have no idea why it's storing the trait name and not the OVDbId. @brapicoordinatorselby any thoughts?

**Comment by MFlores2021** [comment]
@trife It seems like breedbase variable id is like that. we need to fix it in our side

**Comment by BrapiCoordinatorSelby** [comment]
hahahaha @MFlores2021 beat me to it. 
I can confirm Field Book is working correctly. The variableDbId value coming from Breedbase when imported is the same as what gets exported back to Breedbase.

**Comment by trife** [comment]
Ah ok. I thought we were pulling OVDbId the whole way and looking at [one](http://breedbase.southcentralus.cloudapp.azure.com/brapi/v1/variables/79186/) of @ch728 examples, it looks to be formatted correctly on the breedbase side and the `name` is getting pulled instead.

**Comment by BrapiCoordinatorSelby** [comment]
@trife where did you get that URL `http://breedbase.southcentralus.cloudapp.azure.com/brapi/v1/variables/79186/`? Where did you get 79186? nothing in BrAPI returns that value as far as I can tell. @MFlores2021 how does that endpoint work with 79186, but the response returns a different variableDbId?

Field Book uses `brapi/v1/studies/{studyDbId}/observationvariables` when downloading traits attached to a study. 
OR it uses `brapi/v1/variables` when importing traits directly.
Right now, both those endpoints return something like 
`"observationVariableDbId": "alkaliSpreadValue_koh-ord|LSU_01:0000059"` 
(which looks like an accidental concatenation between name and ID on the Breedbase side)

Field Book never uses `brapi/v1/variables/{observationVariableDbId}` like you have above, but in theory they should all be returning the same variableDbIds.

**Comment by trife** [comment]
It was in the URL when browsing to that trait via the front end so I assumed it was the internal_id even though the 79186 doesn't display anywhere in the returned object. Maybe it's the internal_internal_id?

**Comment by MFlores2021** [comment]
> @MFlores2021 how does that endpoint work with 79186
79186 is the observationVariableDbId in breedbase

I fix that in our code. And now it's saving in breedbase correctly. But in fieldbook I get "ERROR missing observation in response". What response fieldbook suppose to get back?

**Comment by BrapiCoordinatorSelby** [comment]
@MFlores2021 it is making the V1.3 call `PUT /studies/{studyDbId}/observations` 
[Docs Here](https://brapi.docs.apiary.io/#reference/study/studies/put-studies-observations-by-studydbid)
It is sending a list of new observation objects, and it is expecting to get back a list confirming that upload was successful. It is comparing the `observationUnitDbId` and the `observationVariableDbId` of what was uploaded vs what the confirmation response says.
Maybe this one more place where the `observationVariableDbId` is coming back wrong?

**Comment by MFlores2021** [comment]
@BrapiCoordinatorSelby Got it. I think response format is incorrect
