### ISSUE TITLE
Giovanni's feedback on eggplant blast and ftp site on solgenomics.net

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3202]
Expected Behavior 
--------------------------------------------------------------------------
Issues reported by Giovanni:

Dear Lukas,

today I tried to do a blastp on the eggplant proteome v3. When I tried to go from the output to the corresponding eggplant protein, the link didn't work. Same for the CDS, when I did a tblastn. I did the same on tomato, and it worked.  Also, the “bulk download" FTP site has links for  N. benthamiana, S. tuberosum, S. lycopersicum, but not eggplant (the FTP is reachable only via the eggplant genome page). Finally, in the eggplant FTP I didn’t find a protein and CDS multifasta, which I find very useful (this feature seems to be missing also in other genomes). Could you please fix these details? Lorenzo can provide you any files that you’re missing.

GG

For Bugs:
---------

**Comment by nmenda** [comment]
BLAST works for me

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/commit/81de9b924c3e8b1f4cf8abadade62f4711b4eeaa

working on fixing the blast matched sequence info pop-up window

**Comment by nmenda** [comment]
#3237
