### ISSUE TITLE
password protect genotype protocol detail page

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#3225]

**Comment by lukasmueller** [comment]
fixed with 76c8a32e100bc09d6b408a6d96a6695afe0e2531

**Comment by ClayBirkett** [comment]
What is the reason for this commit? Is it for protecting data or is there a performance problem?

**Comment by lukasmueller** [comment]
Hi Clay, the problem was that indexers and bots were hitting this page. It is a slow page to load and could bring down the server. We also need to make this page more efficient.
