### ISSUE TITLE
Add Tohru's genomes to SGN

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3229]
Expected Behavior 
--------------------------------------------------------------------------
See Tohru's email

For Bugs:
---------

**Comment by nmenda** [comment]
created an ftp account for Tohru
He needs to upload the genome assembly and annotation files

**Comment by nmenda** [comment]
add publication 
https://academic.oup.com/dnaresearch/advance-article/doi/10.1093/dnares/dsaa029/6104860

README files from Tohru

**Comment by lukasmueller** [comment]
Is this completed?
