### ISSUE TITLE
Include an accession  meta-data download?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3236]
It would be nice to have the option to download accession meta data, specifically the info in the editable_stock_props.

**Comment by dwaring87** [comment]
I had started working on this a little while ago but it doesn't use the editable_stock_props key.  I could update it to use the config stock props and make a PR.

**Comment by ch728** [comment]
It would be nice if it could use the editable_stock_props key variables as well. I  have a number of extra meta-data fields that I added using the key.
