### ISSUE TITLE
trials list link in manage locations page goes nowhere

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#324]
if you click on the number of trials link in a breeding location, the link does not lead to anywhere. 
https://cassavabase.org/breeders/locations

**Comment by bauchetg** [comment]
Location deletion option is available only for trials which are not assigned to a breeding program.
The option is not functionnal.
From Prasad: Assigning a breeding program to a location would be more informative

**Comment by lukasmueller** [comment]
Hi Guillaume,
this is a feature. It should only be possible to remove locations when there are no trials associated with them.

**Comment by lukasmueller** [comment]
To create a link, we either need a /breeders/location/{id} page, or link to the trial page with that location selected. However, the trial search is implemented as a pure data tables gizmo, and does not take any URL parameters, so this would have to be added to the search first.

**Comment by pvnsprasad** [comment]
Dear Dr. Lukas,

Actually we were not able to Delete the location even when there are not trials associated with them.

Thanks
Prasad

**Comment by lukasmueller** [comment]
Ah, ok! That *is* a bug.

cheers
Lukas
