### ISSUE TITLE
More feedback in multi trial upload working modal

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3245]
Expected Behavior 
--------------------------------------------------------------------------

Requested by Russell from NCSU. He says multi-trial uploads take a long time and it is hard to tell whether they are working during the long wait. He'd like more user feedback in the working modal, like a progress bar indicating the upload is working on trial 5/10 then 6/10, etc.

Similar feedback would be helpful in other places like phenotype and accession uploads.

For Bugs:
---------

**Comment by ramierop** [comment]
Just checking in, I still would like this. Bryan can you pick this back up? Thanks!!

**Comment by lukasmueller** [comment]
implemented a background upload.
