### ISSUE TITLE
Make trial type a configurable key

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3247]
Would it be possible to make trial type a configurable key:value?

**Comment by lukasmueller** [comment]
Could you expand on this idea? An example would be good... :-)

**Comment by ch728** [comment]
I would like to be able to add new terms to the drop-down menu for trial type when designing a trial  like "Second Stage Testing" or "Regional Trial". Could trial_types be added  as a  key in sgn_local.conf so that the terms are editable like editable_stock_props or cross_properties are?

**Comment by lukasmueller** [comment]
trial types are stored as cvterms, there is an ontology for those. So you can add as many terms there is needed (cv is called project_properties).

**Comment by lukasmueller** [comment]
Hi Chris, not sure if the above comment solves your problem. Let me know and is yes, I will close this ticket. If not, we could add more keys to the config file, but I think that would make it a bit unwieldy, having this iinfo in two places.

**Comment by ch728** [comment]
Yes,I was able to add additional trial types.
