### ISSUE TITLE
Pedigree Viewer is Very Slow

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3259]
Expected Behavior 
--------------------------------------------------------------------------

On the Stock Detail Page, the interactive pedigree viewer is very slow to load.

One example: https://oat.triticeaetoolbox.org/stock/97779/view takes ~50 seconds to load.

Once the initial parents are displayed, I tried displaying the descendents ~~but gave up after 5 minutes when it was still loading~~ and after ~7 minutes it displayed the 10 children.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe the BrAPI calls "parents" and "children" need to be sped up???
