### ISSUE TITLE
Create a historical tree visualization tool to capture all trials linked 

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#3267]
Expected Behavior 
--------------------------------------------------------------------------

It will be important to follow all trials linked in forward breeding to create reports and check the progress.

For Bugs:
---------

**Comment by bauchetg** [comment]
Hi Chris, good idea!  #1817 and #1416 may have some useful info to your project.

**Comment by chris263** [comment]
This request solves the issue https://github.com/solgenomics/sgn/pull/3564
