### ISSUE TITLE
seedlot boxes not searchable?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3274]
Expected Behavior 
--------------------------------------------------------------------------

Are seedlot boxes searchable? On current seedlot search (Manage -> Seedlots) it does not show the "box" stock prop among search fields. This could be very useful for inventory search purposes.
<img width="734" alt="Screen Shot 2021-01-14 at 2 45 35 PM" src="https://user-images.githubusercontent.com/12039071/104598693-2b26eb80-5677-11eb-8c0c-bf4bc94af826.png">

For Bugs:
---------

**Comment by lukasmueller** [comment]
Hi Guillaume, isn't location the box part?

**Comment by bauchetg** [comment]
Hi Lukas, multiple boxes can be store in a single location

**Comment by lukasmueller** [comment]
OK, great point, we'll make it searchable!
________________________________

**Comment by lukasmueller** [comment]
this issue is related: #3427. Combined with this issue.

**Comment by dwaring87** [comment]
Fixed by #3681
