### ISSUE TITLE
Cluster submission problem? Many analysis tools failing without user feedback in sweetpotatobase

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3276]
Expected Behavior 
--------------------------------------------------------------------------

Both the Heritability and Mixed Model tools run endlessly on sweetpotatobase. Same thing for the 
Phenotypic correlation analysis (Pearson), ANOVA, Phenotypic heritability analysis, and Quality Control Tool (st4gi) tools on the trial detail page.

Some error log details after trying to run the mixed model tool:
```
Start _submit_cluster_job
JOB RUN CREATED: sbatch -o /dev/null -e /dev/null --export=PATH,PERL5LIB -N 1 /tmp/cxgn_tools_run/job_RcZo3E/cmd
Running it...
sbatch: error: Batch job submission failed: Unable to contact slurm controller (connect failure)
Done...
CLUSTER_JOB_ID = 
COMMAND: sbatch -o /dev/null -e /dev/null --export=PATH,PERL5LIB -N 1 /tmp/cxgn_tools_run/job_RcZo3E/cmd  
CXGN::Tools::Run error running `sbatch`: 
[error] Caught exception in SGN::Controller::AJAX::MixedModels->run "CXGN::Tools::Run: failed to submit cluster job, after 4 tries"

```

For Bugs:
---------

**Comment by isaak** [comment]
Slurm may not be set up on spbase properly. Jobs (the db queries) that run on the spbase server are failing.

When was the last time any of the analyses worked on the site?

**Comment by lukasmueller** [comment]
I fixed the settings in slurm. There was an issue with the SelectTypeParameters setting in /etc/slurm-llnl/slurm.conf, which was unset (it should be set to CR_CPU or CR_CORE). (it also depends on the SelectType parameter).

**Comment by lukasmueller** [comment]
Isaak confirmed that it works now. Thanks! :-)
