### ISSUE TITLE
HIDAP link broken on sweetpotatobase

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3277]
Expected Behavior 
--------------------------------------------------------------------------
[https://apps.cipotato.org/hidap_sbase/](https://apps.cipotato.org/hidap_sbase/) - Page not found

For Bugs:
---------

**Comment by lukasmueller** [comment]
I seem to remember that they run HIDAP on a VM at BTI, but I am not sure whether that was still the case later... The VM is still running ( I think on vm-04. )
