### ISSUE TITLE
in breeder search an error occurs if default genotyping protocol not set in sgn_local.conf

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#328]
Caught exception in SGN::Controller::AJAX::HTMLSelect->get_genotyping_protocols_select "The default genotyping protocol: "undefined(set this in sgn_local.conf)" in sgn_local.conf doesn't match any protocols in the database at /home/production/cxgn/sgn/bin/../lib/SGN/Controller/AJAX/HTMLSelect.pm line 107."

**Comment by bellerbrock** [comment]
make sure a default_genotyping_protocol is set for the fixture local.conf file. 
For bases other than cassavabase, I'll make it possible to set the default to N/A if no genotyping protocols exist yet, and have it stop generating an error or displaying the filtering option.
