### ISSUE TITLE
protocols (genotyping) should not enforce a specific stock type source

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3281]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe the allowed stock_types should be a list

**Comment by ch728** [comment]
Couldn't agree more with this, it would make GS implementation easier. Our training data comes from genotyped plots, but our prediction set might be seedlings that only have plant ids,,They all need to be on the same genotyping protocol for the SolGS tool to work.
