### ISSUE TITLE
Newly added editable stock props break search output display

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3284]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------
After adding new props to editable_stock_props in conf file, when I try to add them to search output display I get a datatable warning and a log error, ex:

$VAR_DUMP1 = [
               'market_type'
             ];
[error] CXGN::Stock::Search::_refresh_materialized_stockprop(): DBI Exception: DBD::Pg::db do failed: ERROR:  must be owner of extension tablefunc at lib/CXGN/Stock/Search.pm line 659
Something to do with refresh_materialized_stockprop(\@stockprop_view)
Is this related with some web usr permissions?
Do I need to re-run a specific dbpatch after adding editable props?

Newly added editable stock props would show correctly on the associated accession page, no problem here.

![Screen Shot 2021-01-20 at 3 58 39 PM](https://user-images.githubusercontent.com/12039071/105194199-9ff79b00-5b39-11eb-9780-a7208f046b80.png)

This was previously described in #3105 #3106 and addressed in #3129. 
I am on tag 290.0

**Comment by lukasmueller** [comment]
The dbpatch needs to be run and the views need to be updated. To refresh the views, go into psql and type:
```
refresh materialized view materialized_stockprops;
```

**Comment by lukasmueller** [comment]
The issue was that the Search attempts to update the stocks materialized view but does not include the 'editable_stock_props' in the process, and the process breaks. I have added another parameter to the CXGN::Stock::Search project called 'editable_stock_props' that can be used to feed additional stock props (usually by calling $c->config->{editable_stock_props} into the object. The object will then combined default hard coded props with the custom props and regenerate the materialized view based on that list. The branch is /topic/fix_stock_props_search

**Comment by lukasmueller** [comment]
There is a pretty severe issue with the stock props search. The stock prop search uses a materialized view of stockprops that is checked against the cv called stock_properties, factually not allowing any props that are not in stock_properties to be in the materialized view. It stores the cvterm_id of each stock prop in the materialized view, maybe this should be simply changed to the prop name?

**Comment by lukasmueller** [comment]
Maybe it is easier to add the custom stockprops to the database?

**Comment by bauchetg** [comment]
The error remains shall I switch existing stockprops as suggested? Or is there some changes since?

**Comment by ch728** [comment]
Just commenting to bump this issue up. It would be really useful to be able to search accessions by editable stock prop.

**Comment by lukasmueller** [comment]
Noted! This is an important issue. Need to bump up!


________________________________
