### ISSUE TITLE
Add seedlot_name to trial_layout brapi call. 

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#3292]
Expected Behavior 
--------------------------------------------------------------------------
Guillaume requested the addition of seedlot_name to fieldMap. But seedlot has not been captured in the trial_layout brapi call that is used by fieldMap view display. 

For Bugs:
---------

**Comment by bauchetg** [comment]
Thanks for bringing the issue Alex.
Seedlots would be super useful to have on the field map at planting stage!

**Comment by lukasmueller** [comment]
Need to talk to Peter Selby to add seedlot to the fieldmap call.

**Comment by MFlores2021** [comment]
Closed here #3334
