### ISSUE TITLE
Add Coffea humblotiana to SGN

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3296]
Expected Behavior 
--------------------------------------------------------------------------
Files from Romain Guyot

For Bugs:
---------

**Comment by lukasmueller** [comment]
Hi Naama, Romain Guyot's email is:

romain.guyot@ird.fr

cheers, Lukas

**Comment by lukasmueller** [comment]
Add to SGN test for now, then update SGN when paper is on line

**Comment by nmenda** [comment]
genome files are in the FTP site. Emailed Romain and asked to give a green light to put this up on the live site

**Comment by nmenda** [comment]
added genome page and blast db
Need to display both once the publication is out
