### ISSUE TITLE
install data.table R package

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#330]
installed it on cassavabase, cassava-test, solgenomics, sgn-test. 

Elsewhere, or locally, please install if you run solGS or solQTL.

A complete list of R dependencies is: https://github.com/solgenomics/sgn/blob/master/R_files/DESCRIPTION

**Comment by isaak** [comment]
To avoid this manual installation, we should make Rob's script for installing R dependencies during the application build work...

**Comment by lukasmueller** [comment]
installed on my local vm ;-)
