### ISSUE TITLE
Dataset creation pipelines for specific tools so that they are guaranteed to work

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3301]
Expected Behavior 
--------------------------------------------------------------------------
Preselect datatypes in the wizard ?? 

For Bugs:
---------

**Comment by dwaring87** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dataset Creation Pipeline](https://trello.com/c/Y5ojXBoA/28-dataset-creation-pipeline)
