### ISSUE TITLE
Error on add new stock page

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#331]
![github_issue_05](https://cloud.githubusercontent.com/assets/7028512/11544594/ade6e78e-9910-11e5-951f-c40f3fc789d4.png)

**Comment by nickmorales** [comment]
shouldn't this page only show the stock details form and not everything else?

**Comment by lukasmueller** [comment]
Yes, because adding something to what does not exist yet doesn’t work anyway… Does the error occur in any case?

**Comment by nickmorales** [comment]
it occurs whenever you go on to /stock/0/new

**Comment by nickmorales** [comment]
fixed with de562b0bfbc67879d797ffbfdb7298b878e5b4c5
