### ISSUE TITLE
Clone ordering system for Musabase (and other dbs :-)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3317]
Expected Behavior 
--------------------------------------------------------------------------
Clone ordering workflow:

 * breeder generates list of clones (using accession names) in the database
 * breeder navigates to plant material order tool (to be implemented)
 * the database stores the request and sends an email to the appropriate person (lab manager) with a link to the request.
   * stock or population ids to order based on the list
   * shipping address
   * account information for payment
   * estimated cost
   * estimated shipping date
 * lab manager approves the request, and can update the status of the order
 * lab manager uses btract to manage field operations. Downloads data from Musabase to Btract.
 * breeder can login and view the status
 * account and cost information can be specified for each order
 * after the breeder has received the clones, the breeder can acknowledge and dismiss the ticket
 * maximum number of plants per order?

For Bugs:
---------

**Comment by lukasmueller** [comment]
implement in the same way as "Catalog" feature (see that ticket), Implement catalog at the same time :-)

**Comment by lukasmueller** [comment]
Note as a reminder: To dump DBIx::Class objects for a specific schema in postgres, use:
```dbicdump -o dump_directory=./new_people_lib  -o db_schema='sgn_people'  CXGN::People::Schema  'dbi:Pg:database=cxgn_fixture;host=breedbase_db' postgres postgres```

(note the db_schema option... :-) )

**Comment by titima15** [comment]
Done. Closed via 52d7600

**Comment by lukasmueller** [comment]
DBIx::Class schema dump explained in this ticket!
