### ISSUE TITLE
Orientation of field layout display is confusing

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3321]
The first plot starts at the top left, which is not very intuitive. It's like looking at the field from behind and working the plots down toward you instead of standing at the foot of the field working up left to right. Would be less confusing if the first plot started at the bottom left and worked up. See below.

BreedBase default:
![confusing_breedbase_default](https://user-images.githubusercontent.com/36375878/106937693-11178080-66ec-11eb-9a17-bdf4f5b0ab71.png)

More natural default:
![natural_orientation](https://user-images.githubusercontent.com/36375878/106937762-268caa80-66ec-11eb-8268-fbd2db3d78a2.png)

**Comment by bauchetg** [comment]
@ch728 see  #3175

**Comment by aco46** [comment]
fixed @ #3356
