### ISSUE TITLE
Spaces in spreadsheet name leads to infinite spinning wheel of doom

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3322]
When a file is uploaded with spaces in its name for uploading an existing field trial BreedBase get's stuck on the loading wheel modal and doesn't throw an error, but I can see the error on the server. An error should be raised to the user in this case.

**Comment by lukasmueller** [comment]
I assume this is the phenotype upload? 

This should not error out - it should handle filenames with spaces correctly. Which upload format are you using (CSV, phenotype excel, phenotyp excel with images ... etc.?)

Should be a simple fix... :-)

**Comment by lukasmueller** [comment]
Chris - if you could copy the error you get in the log that might help as well...

**Comment by bellerbrock** [comment]
@ch728 Was it the multi trial upload where you encountered this problem? If so then it's fixed in PR #3665
I also checked the single trial upload where file name errors are reported as expected, and the phenotype spreadsheet upload where spaces in filenames apparently are allowed.

**Comment by ch728** [comment]
Yeah this was trial upload. So I will close this issue. Thanks!
