### ISSUE TITLE
Wizard trial queries show discrepancies (part2)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3327]
Expected Behavior 
--------------------------------------------------------------------------
Some sql query joins in the wizard may not be fully equivalent when they should be, see example below: if you swap trait and trial selection order, the final output can be quite different:
<img width="1252" alt="Screen Shot 2021-01-30 at 9 46 27 AM" src="https://user-images.githubusercontent.com/12039071/107189938-6e604a00-69ea-11eb-8372-37e9b8c7a610.png">
<img width="1241" alt="Screen Shot 2021-01-30 at 9 45 12 AM" src="https://user-images.githubusercontent.com/12039071/107189945-715b3a80-69ea-11eb-84c6-01773263fb2f.png">
ie: cyanide scoring at CIAT gives 11 years of data in the first case but 26 years in the second

follows previous issue #1457
For Bugs:
---------

**Comment by lukasmueller** [comment]
Hi Guillaume, I don't understand the query because the trials are different... (not sure why, but with different trials in the list it should give a different result ???)

**Comment by bauchetg** [comment]
Hi Lukas, to me these two queries should give the same results: 
Q1: CIAT -> all trials from CIAT -> HCN trait -> associated years 
Q2: CIAT -> HCN trait -> associated trials -> associated years 
The criterias are identical, applied to the same breeding progam, just the trait and trial order is changed, how can it give such a different number of years associated??

**Comment by bellerbrock** [comment]
@bauchetg Seeing this confused me too, but I just took a look at it with Lukas and Nick and here's what's going on with the underlying queries. Long story short this is expected. The different order in query 1 means the trials are not filtered by the trait, so years like 2020 where CIAT had a trial but did not measure HCN (and somewhere else another program did) end up in the result. 

Here's what's going on under the hood:

When you select years in the 4th panel of **query 1** it calculates the intersect of 3 sets of years:

**All years for which CIAT has loaded phenotypic data:** (40 years) {1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021}
**All years related to _1476 trials_:** (40 years) {same as above}
**All years in which HCN has been measured, regardless of program:** (28 years) {1986 1993 1994 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020}

resulting in this set: (26 years) {1986 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020}

When you select years in the 4th panel, **query 2** intersects 3 sets of years:

**All years for which CIAT has loaded phenotypic data** (40 years) {same as query 1}
**All years in which HCN has been measured, regardless of program** (28 years) {same as query 1}
**All years related to _155 trials_**: (11 years) {1986 1997 1998 1999 2000 2001 2002 2003 2004 2005 2012}

resulting in this set: (11 years) {1986 1997 1998 1999 2000 2001 2002 2003 2004 2005 2012}
