### ISSUE TITLE
Phenotype Download: Shifted Columns

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3331]
Expected Behavior 
--------------------------------------------------------------------------

The phenotype download (from the Search Wizard or the Trial Detail Page) will have shifted columns if there is a comma in the trial description.  All of the columns are quoted but the trial description column is double quoted (if it contains a comma or not).

Example with comma in trial description:
<pre>
"studyYear","programDbId","programName","programDescription","studyDbId","studyName","studyDescription","studyDesign","plotWidth","plotLength","fieldSize","fieldTrialIsPlannedToBeGenotyped","fieldTrialIsPlannedToCross","plantingDate","harvestDate","locationDbId","locationName","germplasmDbId","germplasmName","germplasmSynonyms","observationLevel","observationUnitDbId","observationUnitName","replicate","blockNumber","plotNumber","rowNumber","colNumber","entryType","plantNumber","plantedSeedlotStockDbId","plantedSeedlotStockUniquename","plantedSeedlotCurrentCount","plantedSeedlotCurrentWeightGram","plantedSeedlotBoxName","plantedSeedlotTransactionCount","plantedSeedlotTransactionWeight","plantedSeedlotTransactionDescription","availableGermplasmSeedlotUniquenames","Grain plumpness - 5.0/64 thin - %|CO_350:0005050","Grain protein content - percent|CO_350:0000161","Grain yield - g/m2|CO_350:0000260","Heading date - Julian day|CO_350:0000270","Lodging severity - 0-9 Rating|CO_350:0005007","Plant height - cm|CO_350:0000232","Test weight - g/L|CO_350:0000259","notes"
"2020","4382","Uniform Oat Performance Nursery","The Uniform Oat Performance Nursery","4764","UMOPN_2020_Carrington",<strong>""Uniform Mid Season Oat Nursery 2020 Carrington, ND""</strong>,"Alpha","","","","","","","","49","Carrington, ND","97779","OGLE","","plot","507036","UMOPN_2020_Carrington-PLOT_101","1","1","101","","","test","","","","","","","","","","","","13.0","300","184","3.00","63","386.4",""
"2020","4382","Uniform Oat Performance Nursery","The Uniform Oat Performance Nursery","4764","UMOPN_2020_Carrington",<strong>""Uniform Mid Season Oat Nursery 2020 Carrington, ND""</strong>,"Alpha","","","","","","","","49","Carrington, ND","101822","IL13-6046","","plot","507003","UMOPN_2020_Carrington-PLOT_102","1","1","102","","","test","","","","","","","","","","","","15.2","193","177","2.00","56","248.0",""
</pre>

Example without comma in trial description:
<pre>
"studyYear","programDbId","programName","programDescription","studyDbId","studyName","studyDescription","studyDesign","plotWidth","plotLength","fieldSize","fieldTrialIsPlannedToBeGenotyped","fieldTrialIsPlannedToCross","plantingDate","harvestDate","locationDbId","locationName","germplasmDbId","germplasmName","germplasmSynonyms","observationLevel","observationUnitDbId","observationUnitName","replicate","blockNumber","plotNumber","rowNumber","colNumber","entryType","plantNumber","plantedSeedlotStockDbId","plantedSeedlotStockUniquename","plantedSeedlotCurrentCount","plantedSeedlotCurrentWeightGram","plantedSeedlotBoxName","plantedSeedlotTransactionCount","plantedSeedlotTransactionWeight","plantedSeedlotTransactionDescription","availableGermplasmSeedlotUniquenames","Crown rust severity (plot) - 0-9 Rating|CO_350:0005030","Grain plumpness - 5.0/64 plump - %|CO_350:0005049","Grain plumpness - 5.0/64 thin - %|CO_350:0005050","Grain yield - g/m2|CO_350:0000260","Groat content (machine dehulled) - percent|CO_350:0000162","Groat oil content - percent|CO_350:0000163","Groat protein content - percent|CO_350:0000164","Heading date - Julian day|CO_350:0000270","Lodging severity - 0-9 Rating|CO_350:0005007","Plant height - cm|CO_350:0000232","Snapback - 1-9 snapback scale|CO_350:0000217","Test weight - g/L|CO_350:0000259","Thousand grain weight - g|CO_350:0000251","notes"
"2020","4382","Uniform Oat Performance Nursery","The Uniform Oat Performance Nursery","4740","UEOPN_2020_Beresford",<strong>""Uniform Early Oat Performance Nursery""</strong>,"RCBD","1.524","3.9624","","","","2020-April-01","2020-July-16","40","Beresford, SD","103337","SD160070","","plot","502453","UEOPN_2020_Beresford-PLOT101","1","1","101","","1","test","","","","","","","","","","","4.5","53.7","5.6","446.8564905","67.3","4.94","17.17","162","","71.12","3","419.3","33.7",""
"2020","4382","Uniform Oat Performance Nursery","The Uniform Oat Performance Nursery","4740","UEOPN_2020_Beresford",<strong>""Uniform Early Oat Performance Nursery""</strong>,"RCBD","1.524","3.9624","","","","2020-April-01","2020-July-16","40","Beresford, SD","201748","IL15-5271","","plot","502441","UEOPN_2020_Beresford-PLOT102","1","1","102","","2","test","","","","","","","","","","","7.2","7.4","9.4","348.6894231","68.9","5.66","18.72","162","0","66.04","1","442.5","30.3",""
</pre>

Removing the double quotes (and keeping the single quotes) around the trial description fixes the problem.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Closed by Clay's merged branch #3341
