### ISSUE TITLE
Manage Seedlots page visualization

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3333]
Expected Behavior 
--------------------------------------------------------------------------
Seedlots are usually obtained from a set of harvested plots and are an intermediate step to prepare the next field seed drilling.
Often the seed preparation task is splitted into batches across teamates/projects over several weeks/months.
These batches do no necessarily exactly match the initial source trial or next cross experiment but are more organized on practical/logistical aspects.
Having a similar visualization tree/folder structure  on http://flaxbase/breeders/seedlots/ page as for trials,crosses and genotyping plates would give more flexibility in organizing/structuring work based on labor/time requirements for example.

For Bugs:
---------

**Comment by titima15** [comment]
Done via cbb7d54

**Comment by titima15** [comment]
@bauchetg Hi, I implemented list details page which you can use to aggregate different seedlots. On the list dialog (seedlots list type), you will see a link for list details page. List details page shows seedlot name, content and other info for each seedlot
