### ISSUE TITLE
Barcode Server Error

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3346]
Expected Behavior 
--------------------------------------------------------------------------

The Manage > Barcodes page (`/barcode`) crashes with a Server Error on all of our instances with the message:
```
[error] Caught exception in SGN::Controller::Barcode->index "read_file '/home/production/cxgn/sgn/../cassava/documents/barcode/tools.def' - open: No such file or directory at lib/SGN/Controller/Barcode.pm line 41."
```

https://github.com/solgenomics/sgn/blob/8ed971f39d2f967172dbf43078a0ac51aa6913a8/lib/SGN/Controller/Barcode.pm#L41

The Barcode controller is trying to load a hard-coded file from the cassava mason repo that we don't have.  [The file](https://github.com/solgenomics/cassava/blob/master/documents/barcode/tools.def) is specific to cassava traits. 

Is this something new that we need to create for each of our crops?

For Bugs:
---------

**Comment by lukasmueller** [comment]
It looks like this info should be read from the database. Is this a cache file?
