### ISSUE TITLE
Allow Curator to Edit Trial Details

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3347]
Expected Behavior 
--------------------------------------------------------------------------

My account has curator privileges, but if I try to edit the details of a trial I get an error message if my account is not associated with the breeding program of the trial.  Is this by design?

My suggestion for editing trials:
- curator can edit any trial
- submitter can edit a trial of a breeding program they are associated with
- user cannot edit trial

For Bugs:
---------

**Comment by lukasmueller** [comment]
Curator should be able to modify anything so that should be fixed.
