### ISSUE TITLE
move site-specific images to img dirs in mason repos

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3350]
Expected Behavior 
--------------------------------------------------------------------------

At the moment site-specific logos and other images are stored in the sgn img directory, which makes it difficult to deploy a new breedbase image and customize it via a mason repo alone. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe better to store site specific images in the database?

**Comment by lukasmueller** [comment]
Or, set static_content to the mason repo in sgn_local.conf

**Comment by dwaring87** [comment]
For our instances, we have the `static_content_path` key set to a directory in our mason repo and store our site-specific images there.  But that only works if you're not using anything in the default static content directory.

**Comment by lukasmueller** [comment]
Should be mounted from the site specific mason into the docker at the right place. This is already standard practice.
