### ISSUE TITLE
marker search from nd_protocolprop 

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3351]
Would like to search for markers in any protocol, not just mapped markers. The query I use takes about 15 sec (too slow). If I include a protocol_id in the query the response drops to less than 1 sec.

takes 15 sec
select s.key , s.value->>'name' as alias ,s.value->>'chrom' as lg_name ,s.value->>'pos' as position, s.value->>'ref' as ref, s.value->>'alt' as alt from nd_protocolprop, jsonb_each(nd_protocolprop.value) as s
WHERE type_id = 84975 AND s.value->>'name' like 'S1A_1000%';

takes 300 msec
select s.key , s.value->>'name' as alias ,s.value->>'chrom' as lg_name ,s.value->>'pos' as position, s.value->>'ref' as ref, s.value->>'alt' as alt from nd_protocolprop, jsonb_each(nd_protocolprop.value) as s
WHERE type_id = 84975 AND s.value->>'name' like 'S1A_1000%' AND nd_protocol_id = 74;

Is there a quicker way to search for a marker in any protocol?
Is there a better way to index the nd_protocolprop table to improve performance? The table is already indexed by type_id and nd_protocol_id

**Comment by nickmorales** [comment]
If you are querying for marker name strings it might be faster to use the nd_protocolprop type_id of 'vcf_map_details' and then search over the 'nd_protocolprop.value->marker_names' JSON array.

**Comment by ClayBirkett** [comment]
I got this query to work that runs quickly
select nd_protocol_id from nd_protocolprop WHERE 'IWA1375' IN (SELECT jsonb_array_elements_text(nd_protocolprop.value->'marker_names') where type_id = 76698);

**Comment by ClayBirkett** [comment]
I have this feature working on [https://wheat.triticeaetoolbox.org/search/markers](url). I'v changed search page, /marker/view_byname, and the mason page so that it displays results from nd_protocolprop. I would like to improve the code by eliminating the cgi script and replacing it with asynchronous ajax. The queries can take upto 10 or 15 sec if the marker is in several protocols.

**Comment by lukasmueller** [comment]
hi Clay, I think this ticket can be closed after the merge yesterday?
