### ISSUE TITLE
Breedbase changes all dates stored per plot to the trial  

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#3360]
Expected Behavior 
--------------------------------------------------------------------------

All trials have option to store planting date and harvest date. Also, is possible store dates per plot using upload pheno (detailed format). However, when extracting dates from breedbase, all plots dates are changed to the trial planting date.

For Bugs:
---------

**Comment by chris263** [comment]
For instance, the trial 201775DMPEA_cere in cassavabase should have 3 different dates stored in different plots. But, when extracting the pheno, only shows one date.
 - Should we create a trait "planting" and then compose with "days after planting"? It might be confusing, though.
 - Or keep date stored per plot and allow extract different dates for the same trial.

**Comment by nmenda** [comment]
see further discussion about handling date-formatted traits here #3323

**Comment by nmenda** [comment]
Updated the cxgn time ontology, can now use date_of for post-composing date terms with agronomy management traits (planting, harvesting, flowering, weeding - available now in banana and cassava and can add to other crops as needed) 
This is to be used just for the convenience of collecting date format in the field. 
 Best practice is to have derived traits measured in number of days, and calculate the values from 2 date fields prior to phenotyping file uploading
