### ISSUE TITLE
Location NOAA station edit reports invalid id when noaa_ncdc_access_token config variable is not set 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3372]
Expected Behavior 
--------------------------------------------------------------------------
Tried saving the Clinton, NC station id `GHCND:USC00311881` in sweetpotatobase, but got the error message `The NOAA NCDC authorization token may not be valid! We could not verify your NOAA StationID. Please contact us!`

The id itself is from https://www.ncdc.noaa.gov/ and should be valid. [In the code](https://github.com/solgenomics/sgn/blob/7b5bcd94199385eea1503ee680958e31f9f53e42/mason/breeders_toolbox/location_map.mas#L423) it looks like the problem is that the `noaa_ncdc_access_token` is not set. It'd be better to check if the access token is defined before using it, and fail if it's not. It'd also be helpful to describe (maybe in the docs?) how to get/create a noaa access token.

For Bugs:
---------

**Comment by nickmorales** [comment]
Yes good point, the NOAA token can be created here
https://www.ncdc.noaa.gov/cdo-web/token . They are pretty robust access
tokens.
Here is some documentation on the API
https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation

Your station id looks like it will work
https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USC00311881/detail

**Comment by bellerbrock** [comment]
Awesome, thanks @nickmorales !
