### ISSUE TITLE
BrAPI /brapi/v2/studies?studyType=genotype does not return expected data

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3377]
The studyType=genotype call returns all phenotype trials
It looks like the code is trying to return a "field trial" of type "genotype_trial" but doesn't work.
I expected this call to return a list of genotype protocols
I would like to get this to work so that the Flapjack program can retrieve genotypes calls using BrAPI

**Comment by lukasmueller** [comment]
Investigate if genotyping related calls are sufficient for the use case.

**Comment by lukasmueller** [comment]
Not sure what the call should return... Should it return field trials that have genotyped data, or should it return genotyping trials (essentially genotyping plates in Breedbase)???
