### ISSUE TITLE
Replace deprecated Digest::SHA1 with Perl core Digest::SHA

### ISSUE THREAD

**Issue by nathanweeks** [solgenomics/sgn#3378]
lib/SGN/Contoller/Bulk.pm (and a few legacy/unused modules?) uses the [apparently-unmaintained](https://rt.cpan.org/Public/Bug/Display.html?id=81102) Digest::SHA1 for sha1_hex():
https://github.com/solgenomics/sgn/blob/9172968f76ca315ab5e75eea8db166de3d8907b0/lib/SGN/Controller/Bulk.pm#L6

In particular, no debian/ubuntu package exists for Digest::SHA1. 

[Digest::SHA](https://perldoc.perl.org/Digest::SHA) from perl core looks like a drop-in replacement.

**Comment by lukasmueller** [comment]
Fixed via dfe6353aa45664a6e257f37a6a14a02075da6714
