### ISSUE TITLE
Pedigree viewer only shows a maximum of 10 progeny

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3379]
Expected Behavior 
--------------------------------------------------------------------------
Pedigree viewer only shows a maximum of 10 progeny. 

Example:
https://musabase.org/stock/65475/view

But:
select cvterm.name, stock.uniquename, child.uniquename, count(*) from stock join stock_relationship on(stock.stock_id=subject_id)  join cvterm on stock_relationship.type_id = cvterm.cvterm_id join stock as child on(child.stock_id=stock_relationship.object_id) where stock.stock_id=65475 and cvterm.name='female_parent' group by cvterm.name, stock.uniquename, child.uniquename;

retrieves 972 rows (half of which are pedigrees, the other half are cross)

Maybe a pagination issue in BrAPI? 

For Bugs:
---------

**Comment by bauchetg** [comment]
Hi Lukas, that s a feature involving speed gain and display i believe, see #2523 
A proposed solution can be found here in #3178 
Ideally the viz should at least let the user know that more than 10 progenies are available
