### ISSUE TITLE
Phenotype download not working in Cassavabase for certain trials (but works in other databases)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3382]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by chris263** [comment]
Some trials with data, but download not working:
https://cassavabase.org/breeders/trial/8659?format=
https://cassavabase.org/breeders/trial/8660?format=
https://cassavabase.org/breeders/trial/8658?format=

**Comment by lukasmueller** [comment]
For some reason, the materialized view needed to refreshed with:
```REFRESH MATERIALIZED VIEW materialized_phenotype_jsonb_table```
