### ISSUE TITLE
Trial Layout incorrect row/col if empty plots

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3384]
Expected Behavior 
--------------------------------------------------------------------------

The Trial Layout displayed on the trial detail page has incorrect/shifted row and/or column headers if there are empty plots in the layout.  The plots are displayed in the correct location but the row and/or column index numbers displayed on the sides are either missing or shifted.

**Examples:**

Correct layout downloaded as Excel file:
![1213_file](https://user-images.githubusercontent.com/7526014/110495008-19cfed80-80c2-11eb-8623-3adbf934d31c.png)

Incorrect column numbers (1-5 at the end):
![1213_layout](https://user-images.githubusercontent.com/7526014/110495091-2a806380-80c2-11eb-8fdb-2c142adf7bbd.png)

Correct layout downloaded as Excel file:
![1322_file](https://user-images.githubusercontent.com/7526014/110495369-6fa49580-80c2-11eb-8d5d-ed44b59c850b.png)

Missing columns 4-5
Rows 1-4 added between 13 and 14 and missing row 16
![1322_layout](https://user-images.githubusercontent.com/7526014/110495421-7e8b4800-80c2-11eb-989c-75dc56f465ba.png)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Not sure if this is a problem of the download or the field viewer? It seems it is the latter?

**Comment by dwaring87** [comment]
The storage in the database and the download to the Excel file is correct.  The problem is with the row/col headers in the website display.
