### ISSUE TITLE
data timestamp download broken?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3385]
Expected Behavior 
--------------------------------------------------------------------------
For Bugs:
---------

#### Steps to Reproduce

Breedbase timestamp upload follows the following format:
<img width="511" alt="Screen Shot 2021-03-10 at 9 16 18 AM" src="https://user-images.githubusercontent.com/12039071/110597794-4dbe1800-8181-11eb-9bab-a786773dcea8.png">

Here an example of an uploade trial data file
<img width="956" alt="Screen Shot 2021-03-10 at 9 08 01 AM" src="https://user-images.githubusercontent.com/12039071/110596865-2155cc00-8180-11eb-96dc-fa5586787ac7.png">

However download output only gives the ontology terms including data but  does not return timestamps, here an example:
<img width="912" alt="Screen Shot 2021-03-10 at 9 19 00 AM" src="https://user-images.githubusercontent.com/12039071/110598101-aab9ce00-8181-11eb-838f-29fb3dcc1a35.png">

Is there an error in the input data? Or is the timestamps download (tested from wizard and trial page) just broken?

**Comment by lukasmueller** [comment]
Good point... there may be another download for the timestamps? I will check.

**Comment by lukasmueller** [comment]
Just checking, is your example from the Manage->Downloads page?

**Comment by titima15** [comment]
Fixed via 13bd312
