### ISSUE TITLE
Field Trials page is also showing some Genotyping projects

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#3401]
Expected Behavior 
--------------------------------------------------------------------------

https://cassavabase.org/breeders/trials is showing genotyping projects. I was expecting to see geno projects only at https://cassavabase.org/breeders/genotyping/

![Screen Shot 2021-03-18 at 9 15 26 AM](https://user-images.githubusercontent.com/51970212/111632243-a9fce980-87ca-11eb-9dd9-2322c84a13d3.png)

For Bugs:
---------

**Comment by lukasmueller** [comment]
I think we decided that this is actually a feature.

**Comment by lukasmueller** [comment]
dupliate of #3436
