### ISSUE TITLE
Quotes in CXGN::Dataset::File downloads break Mixed Model and potentially other tools

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3404]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Solgwas tool fixed in e17a183b4232306736f4fd2ff69971c10a41b0ed and f67cc0d777ce0ee8758ad4ef6add7d8988eb3cbf.
Heritability and Stability tools fixed in 6441f73990b2700fc4a2ec0f58e1a0e0472bed63.
Mixed model tool fixed in e3db5d83e9533185456951e5c88b039aa60c9996. This also adds the quotes parameter to CXGN::Dataset::File.

**Comment by lukasmueller** [comment]
Note: Brapi calls don't seem to be affected...

**Comment by ClayBirkett** [comment]
I don't see why the quotes would break the other tools. Would a better fix be using the same command when reading the file in the R-script? Most of the R-scripts use read.table so changing mixed_models.R to use read.table might fix the problem.
