### ISSUE TITLE
Upload new version of eggplant genome

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3418]
Expected Behavior 
--------------------------------------------------------------------------
As requested by Giovanni Giuliano.

For Bugs:
---------

**Comment by nmenda** [comment]
Eggplant_V4_Pangenome uploaded
Lorenzo needs to let us know when the data can go live

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/3521
