### ISSUE TITLE
Accents in stock names are wrong when downloading pedigree from the Manage->Download page

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#3430]
Expected Behavior 
--------------------------------------------------------------------------
Accents in stock names are showing wrong when downloading pedigree from the Manage->Download->Download Pedigree (/breeders/download).
For example: 
ROCHDALE GOLD-DORÃE instead of ROCHDALE DORÉE 
MYSTÃRE instead of MYSTÈRE

For Bugs:
---------

**Comment by lukasmueller** [comment]
This is a UTF-8 issue! Will fix this asap.

**Comment by lukasmueller** [comment]
Pull request created #3433
