### ISSUE TITLE
Dealing with duplicate genotypes

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3453]
I was curious how BreedBase handles genotype data that is for the same accession on the same genotyping protocol. Every year we genotype all yield plots from the first rep of all trials and we genotype with the same SNP set. This generates lots of duplicate data for checks and accessions that were genotyped the previous year or the same year across trials.  Technically the lines are changing slightly each year with selfing and also we want to be able to track seedlot contamination/planting errors, so the duplicate data are useful but It doesn't seem like there is a way, on the user facing side at least, to manage the duplicate genotypes. Breedbase allows duplicates to be uploaded, but I'm not sure which version is being returned on download. It would be useful if there was a concept of a preferred duplicate that could be returned by default, but all duplicates were retained because we need a record for identifying mixups/contamination. Having the option to merge duplicates via consensus would also be useful.

**Comment by lukasmueller** [comment]
I have to check this - in the download, everything should be downloaded, but in tools like solGS, one will be selected over the other, I think it is just the most recently loaded. Consensus merging is something not yet implemented, as it can generate lots of problems (merging wrong stuff etc), so it has to be done in a very controlled way.

**Comment by ch728** [comment]
Defaulting to returning everything makes sense to me. I don't think it is currently doing that, but that would be desirable. Knowing the rules for what is selected in solGS/GWAS would be helpful and having some ability to set the preferred duplicate for these pipelines would also be useful I think.

**Comment by isaak** [comment]
In solGS, the first result returned from the query is used. Adding the 'preferred copy' concept sounds also good idea.

**Comment by lukasmueller** [comment]
OK, will check the download and make sure it downloads everything...

**Comment by ch728** [comment]
@nickmorales  from the wizard seems ideal to me. Good idea to have it as an option, some users probably just want one genotype returned. Last question: would there be something appended to the genotype name so that the user knows the versions of the genotype? Like "accession_name_dbid" or something like that maybe? In the immediate term I think the download all option will solve the duplicate genotype problem. Long term a "preferred copy" concept would be a useful feature, I think.

**Comment by nickmorales** [comment]
@ch728 ok, in the case where duplicates are returned, it can append the unique database genotype_id to the column header name. would that be good?

**Comment by ch728** [comment]
Sounds good to me!

**Comment by nickmorales** [comment]
@ch728 unfortunately, there was a bug when uploading duplicate genotypes in the same protocol. Only the most recent genotypes were actually stored. The pull request will fix that and includes an option on the wizard to download including duplicate genotypes.

**Comment by ch728** [comment]
Gotcha, glad you found the bug! I think this will benefit others too. This will be useful for integrating into the flapjack-gobii QC/Pedvar tool in future as well https://excellenceinbreeding.org/event/webinar-tool-demo-gobii-genomics-data-management . The tool already supports BrAPI and can work with duplicates, it would be a matter of being able to transfer datasets via BrAPI to the tool I think.
