### ISSUE TITLE
Plots not loading correctly in Geo Field Layout 

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3455]
This is a screenshot showing part of the layout:
![Screenshot_2021-04-06_13-35-32](https://user-images.githubusercontent.com/36375878/113755370-3e79ae00-96de-11eb-9170-c8a874af7dc0.png)

This is what I see in the app:
![Screenshot_2021-04-06_13-35-46](https://user-images.githubusercontent.com/36375878/113755057-ddea7100-96dd-11eb-85da-23e2b86366bb.png)

Also, a problem in general is that BreedBase puts the (1,1) coordinate in the top left which makes no sense for how a field is laid out in practice. First plot is bottom left..  I don't think anyone who regularly walks a field would position the plots according to the BreedBase default.

**Comment by MFlores2021** [comment]
Hi Chris, do you have a trial id and site? It will be useful since we can get a sense which is the desirable plot layout and which plots types are missing.  do the plots are linked to plants?

**Comment by ch728** [comment]
Those plots do not have plants, but the spatial layout was altered after the trial was designed. Unfortunately, the site is private and behind a password. I will check a couple of examples and see if I can find a pattern in what is working and what isn't. I could also provide the BrAPI JSON if that helps.

**Comment by ch728** [comment]
I've looked at couple examples where the spatial grid wasn't modified and it doesn't look wonky like the example I showed, but only ten plots are being shown over the whole area. I know the default page size is 10 for BreedBase BrAPI calls, maybe something related to this?

**Comment by MFlores2021** [comment]
I couldn't reproduce that error. Please can you check the brapi json response in the browser webtools?  I don't think it's page size since fieldmap request default page size is 1000 but I want to make sure what response you have.

**Comment by ch728** [comment]
Strangely, I cannot reproduce this error either. It seems to work now... I'll let you know if it the problem pops up in a different context again, but I guess I can close this for now .
