### ISSUE TITLE
Issue uploading FB field layouts including previously scored phenotypic data

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#3456]
Expected Behavior 
--------------------------------------------------------------------------
When generating a fieldbook layout from breedbase using the "Include summary of overall accession performance (for a list of traits)" option 
<img width="1078" alt="Screen Shot 2021-04-06 at 10 48 54 AM" src="https://user-images.githubusercontent.com/12039071/113767883-7bb26000-971f-11eb-9e60-a3138c9d4617.png">
and transfering it to Fieldbook's "field_ import" folder the file cannot be loaded as a filed layout it seems. No particular error message is provided in Fieldbook.
 For a single stock row/trait column, data structure looks like: "Avg: 69.167 Min: 50.000 Max: 100.000 Count: 4 StdDev: 21.667", maybe a parsing issue from Fieldbook? Or is there a different way to do it?

Here an example file downloaded from "Manage" -> "Fieldbook app" from cassavabase:
[CBbase_FBK_layout_2021-04-06_20.GS.C2.UYT.36.setA.IB.lgfmt.xls.zip](https://github.com/solgenomics/sgn/files/6267103/CBbase_FBK_layout_2021-04-06_20.GS.C2.UYT.36.setA.IB.lgfmt.xls.zip)

Is this a known problem? @trife @lukasmueller 
For Bugs:
---------

**Comment by trife** [comment]
Not sure what the issue is- I'm able to import the attached file into Field Book without any errors.

**Comment by lukasmueller** [comment]
The column labelled cassava brown streak disease leaf incidence 6-month evaluation\|CO_334:0000209 contains some strange data... Should that be there?
--

**Comment by lukasmueller** [comment]
Could you resolve this issue?
