### ISSUE TITLE
Remove plant entries from 4 trials in musabase

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#3467]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
2020 Triploid crossing Block 4 Strip 3          (project_id = 605)         360 plant entries
2020 females  Block 5 strip 5                        (project_id = 608)         252 plant entries
2020 Tetraploid crossing Block 5 Strip 7      (project_id = 609)         270 plant entries 
2020 Tetraploid crossing Block 5 Strip 2      (project_id = 611)          520 plant entries

**Comment by lukasmueller** [comment]
Opened the trial detail page for each trial, and copied the list of associated plants from the trial design section into a file. Then ran the bin/delete_stocks.pl script on each file.

**Comment by lukasmueller** [comment]
Needed to regenerate trial cache after running the script. For each trial, need to go to the detail page, scroll to the bottom, open "trial status" and then open "Field design" section. This will regenerate the cache. Maybe cache regeneration could be made less cryptic (button on detail page?)

**Comment by lukasmueller** [comment]
Also need to remove the trial_has_plant_entries from projectprop.
