### ISSUE TITLE
Paging does not work for search requests

### ISSUE THREAD

**Issue by chaneylc** [solgenomics/sgn#3473]
search/studies is not paging correctly
--------------------------------------------------------------------------
```POST https://www.cassavabase.org/brapi/v2/search/studies```

returns a search request id: DslHHaWJjKkJW2TO

```GET https://www.cassavabase.org/brapi/v2/search/studies/DslHHaWJjKkJW2TO```

The GET to the search request id only returns 10 results. 
```json 
"pagination": {
      "currentPage": 0,
      "totalCount": 10,
      "totalPages": 1,
      "pageSize": 10
    }
```

Furthermore, you can specify a pageSize
```GET https://www.cassavabase.org/brapi/v2/search/studies/DslHHaWJjKkJW2TO?pageSize=5```
But this will only change the response list size if the pageSize is less than 10.

Expected results should match a normal GET, ```GET https://www.cassavabase.org/brapi/v2/studies``` will return 5104 studies that are paged correctly. search/studies should have the same paging functionality.

At a quick glance this also seems to fail for search/programs. I'm guessing it does not work for all search calls.

For Bugs:
---------

### Environment 
cassavabase

#### Steps to Reproduce
steps included in description

**Comment by lukasmueller** [comment]
I have observed the same on the people call
