### ISSUE TITLE
Multi-trial upload fails with error about undefined project_owner_id

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3480]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

Encountered on spbase.org while it was on tag sgn-295.1. Disappeared after reverting to tag 294.0

**Comment by chris263** [comment]
It is also affecting genotyping plates upload.

**Comment by bellerbrock** [comment]
@chris263 . yep. That's also fixed in the pull request
