### ISSUE TITLE
Synonyms not checked when uploading accessions?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3490]
I don't understand how breedbase allows this to happen:

![duplicate](https://user-images.githubusercontent.com/36375878/115442977-a8b34800-a1e0-11eb-988c-a43d08abfe9b.png)

When the Uniquename with RU was uploaded shouldn't the system have checked the synonyms against existing unqiuenames and existing synonyms and made sure there wasn't a match? Breedbase validates the uniquenames, but doesn't check the synonyms?

**Comment by lukasmueller** [comment]
It checks the synonyms for the fuzzy search, but not the synonyms in the list validation. It is recommended to use the fuzzy search for import.

**Comment by lukasmueller** [comment]
A good idea would be to add another section similar to the adjust case feature (not merged yet) to pull in the right name if a synonym was encountered

**Comment by ch728** [comment]
Okay, that would be good. Our technician introduced this error when uploading new accessions from an excel sheet. She uploaded the accession with the RU as new unique name with the synonym a 192L116 not realizing 192L1166 was already in the database as a unique name. It would be good to have some warning about this.

**Comment by ch728** [comment]
Really what the technician should have done is add the RU as a synonym for the existing 192L1166 accession.

**Comment by lukasmueller** [comment]
Looks like Excel upload should be tightened down a little bit more, thanks for this info.
