### ISSUE TITLE
VCF output of wizard has empty genotypes

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3505]
When downloading genotype data in VCF format I am getting empty genotypes. These should be "./." when there is not measurement. This problem occurs when there are more than one projects in a genotype protocol. If the markers in each project are not identical then the missing marker is left empty. The empty cells cause TASSEL to fail and is not a valid VCF file.

For Bugs:
---------

**Comment by lukasmueller** [comment]
merged in pull request #3518
