### ISSUE TITLE
Materialized view refreshes too slow

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3506]
Expected Behavior 
--------------------------------------------------------------------------
The materialized views refresh too slowly on Cassavabase.
Possible solution: Split out phenotypic and genotypic related materialized views and update them separately.

For Bugs:
---------

**Comment by nmenda** [comment]
need to write a script instead of the refresh_materialized_views postgres function 
Update matviews.currently_refreshing for each row as it gets updated.

**Comment by nmenda** [comment]
another issue is the matviews table is a mess, does not contain all the mv_names and some names are duplicated. Fix this in a db patch, or hardcode the mv names in the refresh script to match the refresh_materialized_views postgres function

**Comment by bellerbrock** [comment]
Closed by PR #3580
