### ISSUE TITLE
Upgrade Devel VMs to postgres 9.4 using the back ports

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#351]

**Comment by lukasmueller** [comment]
As root:

Add the PostgreSQL Apt Repository

create a Debian sources list file (e.g. pgdg.list)

1
nano /etc/apt/sources.list.d/pgdg.list
add the following line and save the file

1
deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main
Import the repository signing key

1
2
wget https://www.postgresql.org/media/keys/ACCC4CF8.asc
apt-key add ACCC4CF8.asc
Update the package lists

1
apt-get update
Install PostgreSQL as usual

1
apt-get install postgresql

Finally, upgrade using pg_upgrade. The posgres wiki has good documentation, follow the instructions for upgrading to version 9.2 and later.

**Comment by bellerbrock** [comment]
Done on my VM

**Comment by aco46** [comment]
Done on my VM

**Comment by noefp** [comment]
Done on my VM

**Comment by lukasmueller** [comment]
Done on my VM!

**Comment by nickmorales** [comment]
Done!

**Comment by phosmani** [comment]
Done!

**Comment by isaak** [comment]
Done.

**Comment by MFlores2021** [comment]
Done
