### ISSUE TITLE
Field Book brapi v2 study import does not give traits of collected observations

### ISSUE THREAD

**Issue by nickpalladino** [solgenomics/sgn#3513]
Expected Behavior 
--------------------------------------------------------------------------
Using Field Book with Breedbase as the host BrAPI server and using brapi v1, Field Book will pull in traits for any existing collected data points in the study. When using brapi v2, Field Book doesn't pull in any traits even if there are existing data points in the study. It looks like this is due to the studyDbId query parameter not being implemented for the GET /variables endpoint.

**Comment by MFlores2021** [comment]
GET /variables doesn't have studyDbId parameter implemented either in brapi v1 or v2. Maybe something else is missing?

**Comment by nickpalladino** [comment]
@MFlores2021 Field Book uses `GET /studies/{studyDbId}/observationvariables` for v1.3. For v2 it uses GET /variables.
