### ISSUE TITLE
Computing derived traits

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3516]
I have two traits that are dates: emergence date and heading date. We have a derived trait days to heading, which is the days between these two dates. I see there is a Derive Trait Phenotypes option on the trial detail page, but I'm not sure how to use this feature. Can this feature be used to get days to heading in my example? Do I have to upload a formula with https://github.com/solgenomics/sgn/blob/master/bin/load_trait_formula.pl ? What sorts of formulas are supported?

**Comment by ch728** [comment]
Thanks! That example helps a lot. For our maturity traits we measure the day of emergence as a date in FieldBook and the date of flowering. Then the days to flowering is the days between those to dates, so if we had 5-10-21 for emergence and 5-15-21 for flowering, the days to flowering would be 5.  Can BreedBase find the difference between dates or will that lead to a problem?

**Comment by ch728** [comment]
I'm also wondering why trait_formula isn't an option under trait properties on the trait detail page.

**Comment by aco46** [comment]
If the trait definition is captured in the trait Ontology, the description (not necessarily trait_formula) should automatically show up in the trait ontology page.
