### ISSUE TITLE
Adding external database links for accessions

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3517]
I would like to add Grin and other database links for our accessions. I see there is a space on the accession details page to add this information, but I don't see a way to add it. Is there an easy way to do this/some backend perl script?

**Comment by nmenda** [comment]
@ch728 you should probably add stock_dbxref 
Some version of this 

https://github.com/solgenomics/Phenome/blob/master/bin/loading_scripts/one-offs/load_tgrc_wild_acc.pl

**Comment by ctucker3** [comment]
Poking in here because I chanced upon this when creating an issue. @MFlores2021 External references have been added to germplasm in brapi from what I can see. Are these displayed on the front end? That would be an easy way to add your database links if so.

**Comment by ch728** [comment]
That would be a lot easier than having to modify a one-off Perl script to do it (which I haven't been able to do successfully yet)!

**Comment by lukasmueller** [comment]
Can we consider this as resolved?

**Comment by ch728** [comment]
yes

**Comment by MFlores2021** [comment]
Yes. The brapi POST /germplasm stores external references and you can check it in the stock page Additional Info
