### ISSUE TITLE
Refactor uploads to make them faster

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#352]
Uploads should separate the process of uploading, validation and database load. An overview page for each user with the status of each upload, and optional email notification, should also be available.

**Comment by lukasmueller** [comment]
http://github.com/solgenomics/sgn/lib/SGN/Controller/AJAX/Trial.pm: upload layout
http://github.com/solgenomics/sgn/lib/SGN/Controller/AJAX/PhenotypesUpload.pm: upload phenotypes (maybe outdated?)
http://github.com/solgenomics/sgn/lib/SGN/Controller/AJAX/Fieldbook.pm: Fieldbook data upload

**Comment by nickmorales** [comment]
phenotype spreadsheet, fieldbook, and datacollector phenotype files are faster. trial upload is faster. more info can be found in the branch merge in this commit. 1db9e03e31db874ffdf7242b1a8fabed91ae59fa
