### ISSUE TITLE
boxplotter is too slow on Musabase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3532]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Also, season/year, study and other queries don't seem to work right. It always downloads all the traits (=> slow).

**Comment by lukasmueller** [comment]
Upgrade to BrAPI 2.0 also

**Comment by MFlores2021** [comment]
@lukasmueller Do you have any specific example to test?
