### ISSUE TITLE
Genotype download from protocol page has format problem

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3534]
When downloading genotype data for an accession on the protocol page the output does not have the GT data in the first field. This does not match the specifications for VCF file format and causes error in TASSEL program. The download works correctly in wizard.

**Comment by lukasmueller** [comment]
Hi Clay, I was under the impression that this has been fixed...

**Comment by ClayBirkett** [comment]
No, not fixed yet.

**Comment by ClayBirkett** [comment]
fixed by pull request https://github.com/solgenomics/sgn/pull/3612
