### ISSUE TITLE
genotyping plate problem with source observation 

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#3546]
Expected Behavior 
--------------------------------------------------------------------------

The genotyping plate is not showing the source observation unit. This problem is also present in the download formats.

As reported by Prasad:

Used to show:
![image](https://user-images.githubusercontent.com/7028512/119734217-a62fb800-be48-11eb-9fba-09c74a06f607.png)

Now shows:
![image](https://user-images.githubusercontent.com/7028512/119734235-ad56c600-be48-11eb-9da0-8674c9ae58af.png)

For Bugs:
---------

**Comment by chris263** [comment]
Hi Nick and Lukas... Prasad still reporting problems with source visualization.

**Comment by nickmorales** [comment]
@chris263 you will need to "refresh" the layout by opening the "check plate design" section at the bottom:

![image](https://user-images.githubusercontent.com/7028512/120368469-1c686a80-c2e0-11eb-88ae-91e35b587bc7.png)

We could potentially write a database patch to run this on every plate automatically

**Comment by lukasmueller** [comment]
May need to update the site...

**Comment by lukasmueller** [comment]
Seems fixed now on production.
