### ISSUE TITLE
Memory error on test sites

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3554]
Expected Behavior 
--------------------------------------------------------------------------

![Screenshot from 2021-06-02 15-50-12](https://user-images.githubusercontent.com/11297346/120543481-586ffe00-c3ba-11eb-98dd-d3482fc9018d.png)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe need to run memtest on db4?

**Comment by lukasmueller** [comment]
Server crashed and can't be rebooted. Closing ticket.
