### ISSUE TITLE
refresh_matviews.pl does not handle password parameter correctly

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3568]
I get an error when I try to run the 'Update Wizard' from Wizard. It looks lie the db password in our system has a special character that will not pass as a perl argument.

bin/refersh_matviews.pl

**Comment by lukasmueller** [comment]
Add single quotes around the password when script is called

**Comment by ClayBirkett** [comment]
I tested the code with single quotes and it fixed one error but still did not run. Now it is not appending my basepath. I think the quoting was required because bin/refresch_matview.pl switched from getopts::std to getopts::Long. I haven't figured out why basepath is not working yet.

**Comment by ClayBirkett** [comment]
The problem was because of a file system permission error so I don't believe any code change is needed
