### ISSUE TITLE
BrAPI v2 error posting observations from Field Book

### ISSUE THREAD

**Issue by nickpalladino** [solgenomics/sgn#3592]
Posting observations from Field Book using BrAPI v2 should work, instead get the following error:

```
Use of uninitialized value $user_type in string ne at lib/CXGN/BrAPI/v2/Observations.pm line 245, <$fh> line 1.
Use of uninitialized value $user_type in string ne at lib/CXGN/BrAPI/v2/Observations.pm line 245, <$fh> line 1.
Use of uninitialized value $user_type in string ne at lib/CXGN/BrAPI/v2/Observations.pm line 245, <$fh> line 1.
````
Looking at ` lib/SGN/Controller/AJAX/BrAPI.pm` sub _authenticate_user, there is a conditional check for the login and populating the user_type which is not being satisfied. For BI deployments, we've been using this in our sgn_local.conf:

```
brapi_require_login 0
brapi_GET any
brapi_POST any
brapi_PUT any
```
We don't currently login to breedbase from BI, but Field Book does when linked directly with breedbase. Since the POST observations endpoint checks user_type to allow posting, it seems you need to be logged in whereas other POST endpoints don't. Not sure how we want to handle that.

**Comment by MFlores2021** [comment]
Observations and few others endpoint required to store the user who submitted the request in Breedbase as well as users needs to have curator / submitter rights (not in all endpoints but Observations) and it works the same as the UI.  
-The error shown above should be handle with a error message, sorry.
-Will add a $force_authentication in the observation endpoint  so it always will require login. I think Fieldbook App requires login anyways right?
Does it sounds good to you?

**Comment by nickpalladino** [comment]
ya, so I guess in BI we'd have to do a breedbase login which we don't currently do. @ctucker3 @timparsons

**Comment by ctucker3** [comment]
> ya, so I guess in BI we'd have to do a breedbase login which we don't currently do. @ctucker3 @timparsons

In our fork we have a default brapi user config for running breedbase as a backend server, so we should be able to continue using that. We should probably get a proper solution for that at some point though.
