### ISSUE TITLE
Upload multi trial with load_cxgn_multi_trials.pl

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#3594]
Expected Behavior 
--------------------------------------------------------------------------

The script to upload multi trial in Phenome/bin/loading_scripts/load_cxgn_multi_trials.pl is not working.

For Bugs:
---------

**Comment by nmenda** [comment]
@chris263 can you paste the error you are getting? It looks like a database-specific issue from my end

**Comment by bellerbrock** [comment]
@naama @chris263 could it be related to #3623?
