### ISSUE TITLE
cassavabase FTP site not loading

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#3610]
ftp://ftp.cassavabase.org -- pops up 'choose an application...' dialog, after choosing firefox, displays blank page.

**Comment by lukasmueller** [comment]
do you access it through a browser?

**Comment by suryasaha** [comment]
Working on Chrome with edited settings. Will not work on Firefox :-(

**Comment by bellerbrock** [comment]
@isaak Is it just a typo in the url? Works fine for me on firefox.

![ftp-firefox](https://user-images.githubusercontent.com/11297346/125316556-3a28e680-e306-11eb-9039-db5090acd6a7.png)
