### ISSUE TITLE
trait list validation is not working 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#3614]
Expected Behavior 
--------------------------------------------------------------------------
This is a js issue 
from the browser console 

caught TypeError: Cannot read property 'length' of undefined
    at CXGN.List.validate (List.js:44)
    at validateList (List.js:119)
    at HTMLInputElement.onclick ((index):1)

For Bugs:
---------

**Comment by titima15** [comment]
@nmenda @lukasmueller list validation works only for accessions. Not working for other list types including traits, plots, plants and tissue samples

**Comment by titima15** [comment]
I'm working on the issue now

**Comment by lukasmueller** [comment]
fixed
