### ISSUE TITLE
missing materialized views

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3617]
some of the wizard functions do not work because of missing materialized views

accessionsxgenotyping_projects
genotyping_projectsxtraits
genotyping_projectsxtrial_designs

select column 1 genotype protocol
select column 2 genotype project
unable to select accessions or anything else in column 3

For Bugs:
---------

**Comment by lukasmueller** [comment]
Should be implemented as a new patch to generate "normal" views

**Comment by dwaring87** [comment]
Original matview definitions are here: https://github.com/solgenomics/sgn/blob/master/db/00114/AddGenotypeProjectSearchTables.pm
