### ISSUE TITLE
Multi trial upload fails with big stack trace if trial type is not specified 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3623]
Expected Behavior 
--------------------------------------------------------------------------
![multi_upload_error](https://user-images.githubusercontent.com/11297346/125855197-6c73274f-a662-4b02-a38e-0d514ab09070.png)

Trial type used to be optional, looks like that changed in [a recent update](https://github.com/solgenomics/sgn/commit/684e37ee36497d95bc3543cc636a5c4d5e4f38f6). The parser and user documentation should be updated to reflect that it is required.

For Bugs:
---------

**Comment by ctucker3** [comment]
This was switched back to optional in https://github.com/solgenomics/sgn/pull/3575/files. Are you still having issues?

**Comment by bellerbrock** [comment]
@ctucker3 good call, I saw it before the latest release tag was deployed to sweetpotatobase. Let me confirm that it's fixed now and then close this

**Comment by bellerbrock** [comment]
Yep, looks fixed. I can't reproduce the error anymore after updating sweetpotatobase to sgn-304.1. Closing this one.
