### ISSUE TITLE
BrAPI store additionalInfo json with observations

### ISSUE THREAD

**Issue by nickpalladino** [solgenomics/sgn#3626]
@MFlores2021 I would like to be able to store the additionalInfo json along with the brapi observation data. Just wanted to start a conversation here and see if it's something you want in the main codebase?

**Comment by MFlores2021** [comment]
do you have any particular info you want to store?

**Comment by nickpalladino** [comment]
@MFlores2021 It's dependent on the dataset. For some context we have a number of instrument datasets for blueberry where we want to store both raw values and computed averages. For the raw data there is the value for the quantity being measured and there is additional metadata associated with the measurement we would like to capture. One instrument dataset we have is a discrete analyzer where we get different measurements like Sucrose content. For each measurement we have instrument specific metadata properties: Errors, Dilution 1 +, Man. dil. 1 +, and Sample type that we would like keep.

**Comment by MFlores2021** [comment]
Implemented here #3687

**Comment by nickpalladino** [comment]
Awesome, thanks @MFlores2021!
