### ISSUE TITLE
Synonyms no longer being matched in multi-trial upload

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3639]
Using newest docker image (v0.28) , and I noticed multi trial upload is no longer matching synonyms. For example, if the accession Cypress has 17L1003 as a synonym and 17L1003 is used as a name in the multi-trial upload file then the uploader will throw an error that 17L1003 is not in the database as a uniquename or a synonym.

**Comment by lukasmueller** [comment]
Discussion: Synonyms would seem to be useful (David & Bryan). Opposing view: Synonyms create problems, as they can be duplicated. However, duplicated synonyms are flagged by the web interface.

**Comment by ch728** [comment]
Is this an implementation or a bug fix? The uploads have always supported synonyms, it was already implemented and support for synonyms is implied in the error message itself: "not in the database as a uniquename or a synonym".  I  don't think the system is very usable without synonyms. It's the nature of a breeding program that early lines get variety names and other synonyms as they progress through the breeding pipeline. People designing future trials aren't going to want to use experiment codes, they will want to use the variety name or another synonym once they exist.  Nobody remembers the old codes.  Just need to add a check for uniqueness for the synonyms ( I think already in place on the web interface but not in the accession sheet uploads), and preferably, an easy way to choose the preferred name of the existing synonyms for use in views.

**Comment by lynnjo** [comment]
At Buckler Lab, we rely on synonyms being recognized when loading trials.  We have many cases in the historical data where sometimes the accession looks like "04FL833801" and sometimes it includes donor initials e.g. "JH04FL833801".   We'd like them to be recognized as the same accession.

**Comment by lukasmueller** [comment]
How about single trial uploads? Maybe single trial upload should only allow uniquenames and not synonyms?

**Comment by lynnjo** [comment]
What would be the rational for supporting synonyms for multi-trial uploads but not  single trial uploads ?  In both cases, shouldn't the accession_name on the trial form be valid if it matches either an existing accession_name or accession synonym?

**Comment by ch728** [comment]
Yeah, I feel like all uploads should check against the uniquename and synonyms. I also have found synonyms essential for dealing with historical data and in cases where collaborators use different codings for the same line.  As I mentioned before, synonyms are also inevitable in a breeding program. I know there is a variety name field in the accession list upload, but this isn't matched on upload either so I add the variety name as a synonym. Then people complain that the new variety name added as a synonym is not used in views, the old uniquename is. This lead to field technicians trying to change the uniquename using the web interface and adding the old uniquename as a synonym, which the system allows but leads to strange behavior. Maybe the concept of the uniquename should be retired? There is an underlying database id that is unique, right? Isn't every text name technically a synonym? Instead of a uniquename, I think what most people really need is  a preferred name that is used in views and downloads. All names should be checked for uniqueness, synonyms map to a common db id , and then have the option to change the preferred name to any of the synonyms.

**Comment by lynnjo** [comment]
We don't use variety as a synonym because it cannot be a synonym for multiple accessions.  For example, we have many accessions that derive from B73, so they all get B73 as a variety (and sometimes multiple values for the variety when they are crosses).  This (hopefully) would allow us to pull everything related to B73 for some future analysis.  But if we're analyzing a particular accession, we only want JH04FL833801 and its synonym 04FL833801.

**Comment by ch728** [comment]
I see. We don't mess with trying to  keep track of derived lines from a variety or off-types, so it's always a one-to-one for us. I'm not trying to advocate for treating the variety field as a synonym. I'm just trying to make the case that some synonyms don't come until many years later in the breeding pipeline (like a variety name in our case) and it is desirable to set the name that is used in the database to the new name while maintaining a record of the old name that was initially entered into the system during early trials. I would like to see breedbase retain the concept of synonyms and possible add the feature of a preferred name.

**Comment by lynnjo** [comment]
Chris - I agree.  We need synonyms in breedbase

**Comment by ch728** [comment]
@lukasmueller  I am looking at the accession page closely now and I see in addition to there being a variety stock property there is an "add released variety" button up top. Is this new? I don't recall seeing this in earlier versions. Does adding the released variety name change the name that is in views and downloads to the released name? If so, then the feature I'm looking for already exists!

**Comment by nmenda** [comment]
@ch728 yes, the 'released variety name' was added in the last year or so. It does not change the unique name of the accession, but these can be identical.

**Comment by dwaring87** [comment]
Also related, the trial design tool does not work if a synonym is used in the accession list.  The trial design tool wizard will validate the list when it is first selected (if a list contains an accession name that is completely missing it will display an error immediately after selecting the list, but does not show an error if the list contains a synonym name).  The trial design will fail if an accession is used after the randomization is complete and the trials are being created with an error "Error validating trial design: The following name is not in the database: {synonym}".

**Comment by dwaring87** [comment]
It's also worth noting that if the trial design tool fails at this point, it creates a project entry for the trial (essentially an empty trial) and the name cannot be used for the actual trial if the problem with the list is fixed since the name is already used.  The trial doesn't show up on the website and the only way to remove it is directly from the database.

**Comment by ch728** [comment]
@dwaring87 related to https://github.com/solgenomics/sgn/issues/3291 it seems.

**Comment by dwaring87** [comment]
@ch728 Yes, I think it's the same core issue.  If the trial creation fails for any reason the original project entry still exists when it should be removed.

**Comment by lynnjo** [comment]
hi all - Have decisions been made regarding synonym processing for trials?   I have 4 NAM trials that are currently blocked from loading due to use of synonyms for the accession_name field.  Will breedbase allow synonyms as per the documentation, or do we need to re-process our data to remove synonyms?  Thanks

**Comment by lukasmueller** [comment]
Hi Lynn,

Naama is currently working on it. The idea is to bring synonym upload back for the multi trial search for loading of historical data.

thanks and cheers
Lukas
________________________________

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/3709
