### ISSUE TITLE
Updating plot accession creates confusion given plot name

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3649]
Say you have an accession in a plot, MPA_173, the plot name is 21RYT_CNRRS-rep1-MPB_173_61 . When planting, you notice you don't have enough seed so you plant MPA_274 in that plot instead and update the accession for that plot to MPA_274. Now the accession in that plot is MPA_274, but the plot name is not updated in the system and  remains as 21RYT_CNRRS-rep1-MPB_173_61. The issue is Breedbase doesn't update the plot name when the accession is switched, and since the accession name is part of the plot name it leads to confusion. Either accession should not be part of the name (not required to make the plot name unique anyways) or the system should update the plot name when the accession is changed.

**Comment by lukasmueller** [comment]
If the trial is generated using Breedbase, the plot names should not contain the accession names. However, if an accession is changed, the plot name should be checked and made consistent.
