### ISSUE TITLE
Fix FTP browser access

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/sgn#3660]
Expected Behavior 
--------------------------------------------------------------------------

Users should be able to access the FTP sites with their browser. They can only access via an FTP client now as both Firefox and Chrome have deprecated it

For Bugs:
---------

### Environment 
ftp://ftp.cassavabase.org/

#### Steps to Reproduce

Access FTP site from latest Firefox, Chrome, Safari and IE
ftp://ftp.cassavabase.org/

**Comment by lukasmueller** [comment]
add this section to /etc/nginx/sites-enabled/sgn-forward-https  (or similar name of course): 
```
location /ftp {
           root /export/prod/public;
           autoindex on;
           autoindex_exact_size off;
           autoindex_format html;
           autoindex_localtime on;
       }

```

**Comment by lukasmueller** [comment]
This has been done for solgenomics.net, cassavabase.org, fernbase.org, musabase.org, sweetpotatobase.org.
