### ISSUE TITLE
Add New Cross Type: Reselection

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3662]
Expected Behavior 
--------------------------------------------------------------------------

As requested by a wheat breeder:

> It would be nice if the cross type within pedigree for accessions had an option for reselection, so that I could add this accession from which the new accession has been reselected.  I'm doing this with "self" right now- but it isn't quite the same thing.

For Bugs:
---------

**Comment by ch728** [comment]
I have thought about asking for this same thing. In our program we have derived lines or mutations in lines that are selected on and right I treat them as selfs. Having this cross type would make sense, but not sure how to best represent it in a pedigree though.

**Comment by ch728** [comment]
For example, we have an accession like Cypress_Irradiated. Right now it is in the system as a self (Cypress/Cypress). It is not technically a self, so it would be nice to indicate that, but as far as representing it correctly in the pedigree I still think it needs to be Cypress as both parents.

**Comment by titima15** [comment]
Which term would you like to use?

**Comment by ch728** [comment]
Reselected as suggested seems okay to me. Derived seems like it would also work. I think both have the potential to confuse breeders, but as long as it's clear in the documentation it probably doesn't matter too much.

**Comment by titima15** [comment]
We also have "sib" cross type.

**Comment by ch728** [comment]
Yeah, I don't think that term really captures the reselected concept. Reselected is more similar to the concept of a sport or roguing maybe. I don't know what the best option is though.

**Comment by titima15** [comment]
Between "reselected" and "derived", "reselected" seems to be clearer. If you all agree with the term "reselected", I can add this new cross type.

**Comment by ch728** [comment]
Sounds good to me and  that is the term @dwaring87 's stakeholders wanted too.

**Comment by dwaring87** [comment]
I think "reselected" would be more clear than "derived".  Thanks @titima15!

**Comment by titima15** [comment]
How should we describe "reselected" in one sentence?

**Comment by dwaring87** [comment]
Fixed by #3672
