### ISSUE TITLE
No user feedback when validate button is click in list manager

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3667]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bellerbrock** [comment]
@lukasmueller Yes. Thought it'd be a simple fix, but for some reason I can't explain a working modal won't display even when you  add one. Despite the fact that it works in every other context I've tested in the list manager.

**Comment by ch728** [comment]
Not sure if this is related https://github.com/solgenomics/sgn/issues/3792 . Noticing this with many buttons, not just the list manager.

**Comment by bellerbrock** [comment]
Lukas and I figured out that the issue is the asynch list functions locking the UI before the working modal can display. Refactoring them to be synchronous solves the problem
