### ISSUE TITLE
There is no heritability output for this dataset

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3669]
I notice this message sometimes when running heritability analysis on a trial page. When I look at the error file for the tool I see "Error: grouping factors must have > 1 sampled level. Execution halted" .  It shouldn't be possible to calculate the broad-sense heritability for some of our traits because some traits are un-replicated. Wondering if these un-replicated traits are the root of the issue?

**Comment by lukasmueller** [comment]
I think that's correct, you essentially compare distributions when calculating heritability, so one would not be enough?

**Comment by lukasmueller** [comment]
We should probably add a better error message.

**Comment by ch728** [comment]
Yeah, I think that might be an issue, but after looking closer it sometimes does report a heritibility for traits with no reps... Some of the traits are replicated so it seems like it should output heritabilities for the traits that it can and NA for traits that it can't instead of nothing for all traits or something clearly wrong. Maybe indicating that NA means not enough replication to get a broad-sense heritability. The tool also reports a Ve in addition to Vg and Verror. I am confused how it is calculating Ve for trials that are not multi-environment trials.

**Comment by lukasmueller** [comment]
Hi Chris,

I found some issues with the Heritability tool, which I will correct in the next release. I found that it crashes for most datasets and some other issues. So you should try to use it again after that

**Comment by chris263** [comment]
Hi Lukas,

I can see that there is a problem with post composed traits. It might be the problem.
I can check that during the weekend.

Cheers

Chris

On Sep 9, 2021, at 11:23 AM, Lukas Mueller ***@***.***> wrote:

﻿

Hi Chris,

I found some issues with the Heritability tool, which I will correct in the next release. I found that it crashes for most datasets and some other issues. So you should try to use it again after that

**Comment by lukasmueller** [comment]
This was fixed in 58df152daf51158120287fb44ae5363661db1bae.
