### ISSUE TITLE
speed to load trial data incredibly slow

### ISSUE THREAD

**Issue by lynnjo** [solgenomics/sgn#3686]
Expected Behavior 
--------------------------------------------------------------------------
I have about 12 trials in a breedbase instance.  Of these, 7 have 6028 plots or more.  It takes several minutes.  Once that is loaded and I click on "Phenotype Summary Statistics" to verify which phenotypes have been loaded for the trial, it takes over an hour.  I"m never sure if it is still working or has timed out - the GUI just spins and I don't see any errors in the docker log output.

For Bugs:
---------

#### Steps to Reproduce

I can provide a dump of my db is that would help.  Otherwise it is strictly Search -> Field Trials -> (select a trial with lots of plots) -> Phenotype Summary Statistics

**Comment by lukasmueller** [comment]
Hi Lynn, could you provide the database so that I could take a look what's going on here?

**Comment by lynnjo** [comment]
Hi Lukas - I just shared a link with your from dropbox.  (to your Cornell email).  Let me know if you don't receive the email or have problems accessing the db.  Thanks!

**Comment by lukasmueller** [comment]
I think the new version of the fieldviewer had more optimized data loading. Please re-open if that's not the case.

**Comment by lynnjo** [comment]
Thanks. We'll check this out once we get back to it and upgrade to a newer
load.
