### ISSUE TITLE
clear files in /export/prod/tmp/ on server startup

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#369]
--clean up cached and temp files from the site cluster shared dir  in /export/prod/tmp

**Comment by lukasmueller** [comment]
This is not a good idea, because /export/prod/tmp are used by many different hosts.

**Comment by isaak** [comment]
There is a directory in the /export/prod/tmp/ specific to each host where only solGS stuff is saved (at least so far), eg. for the production site is /export/prod/tmp/cassavabase.org/, for cassava-test is cassava-test.sgn.cornell.edu. You can get this directory from $c->site_cluster_shared_dir.

**Comment by lukasmueller** [comment]
I think there is a setting for doing that in sgn_local.conf, if you set to 1 it will delete the server specific tmp files.
