### ISSUE TITLE
Heritability tool on Trial Detail page ( breeders/trial/###) pulls in data from other trials?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3690]
Expected Behavior 
--------------------------------------------------------------------------
User expects that the heritability tool available on trial page will report heritability for that trial only.

For Bugs:
---------

Ve is reported in addition to Vg and Vresid. How can a Ve be reported for a single trial? The tool must be pulling data from other experiments, perhaps experiments from trials in the same folder that have overlapping accessions. I understand Breedbase keeps track of multi-environment trials by putting trials in the same folder at trial design, but still, doesn't make sense to have the tool on the Trial detail page pull this data in. Also, we have a folder ,  2021, that has singe location trials in it and they should not be assumed to all be apart of the same experiment by a tool.

### Environment 

Docker V29 Trial Detail page ( breeders/trial/###)

**Comment by chris263** [comment]
This pull request  https://github.com/solgenomics/sgn/pull/4547 solves it
