### ISSUE TITLE
Add new tomato genomes (from Zach and Sanwen) to SGN

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3719]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
(from Zach and Sanwen)

**Comment by nmenda** [comment]
46 genomes from Sanwen
https://solgenomics.net/ftp/genomes/TGG/

Do not load yet BLAST and JBrowse and annotations
