### ISSUE TITLE
Create a role to retrieve common cvterms used in the code-base

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#372]
The codebase is littered with code to retrieve cvterms. It would be easier to have a role for the web application that can retrieve cvterms.

**Comment by lukasmueller** [comment]
This is probably better implemented using a Model than a Role. Implemented via 9a60edf065dd56457d7ead89f050e8876dada5b6 and e4c4e2465b35a3a8fcdb3af73f17840a674312f8.

**Comment by bellerbrock** [comment]
related to #53 data repo, which naama may need to implment first

**Comment by nmenda** [comment]
cc975b68c501561b23cab05b240eef1623492470
