### ISSUE TITLE
BrAPI pagination issue

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3724]
I am not sure if I really understand the issue, but I found it while using the brapir-v2 R package, see description of the issue here https://github.com/mverouden/brapir-v2/issues/1

**Comment by MFlores2021** [comment]
Breedbase default pageSize = 10 to improve performance.Although BRAPI default value is 1000
brapir-v2 R package sets pageSize=1000 to fix issue. Issue closed here mverouden/brapir-v2#1
