### ISSUE TITLE
Change "GBS Genotype " to  "Genotype"

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3732]
On the /breeders/download page:
![Screenshot from 2021-09-23 07-23-24](https://user-images.githubusercontent.com/36375878/134498970-dff492b5-50c0-4ee7-8b96-0e33864b423c.png)

Since not only data from GBS are loaded into breedbase,  I think it would make more sense to have it say "Download Genotype".

**Comment by lukasmueller** [comment]
Fixed in 3b2b206f1e8558bcccbc2967402c4165a51167cd.
