### ISSUE TITLE
Add image analysis usage tracker

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3744]
Expected Behavior 
--------------------------------------------------------------------------

Requested by Solomon. Should be added at the bottom of the image analysis page, and available to be retrieved and displayed on an external site.

Something like this:
![example_activity_display](https://user-images.githubusercontent.com/11297346/135126480-7f18b3be-a769-4720-a103-f4da690b4810.png)

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe add a file in the log (?) directory
