### ISSUE TITLE
Add seedlot names and image db ids to brapi/v2/observationunits get request

### ISSUE THREAD

**Issue by npanitz** [solgenomics/sgn#3746]
Expected Behavior 
--------------------------------------------------------------------------
Currently, to retrieve seedlot names or image db ids, one must make a get request to the seedlots or images brapi endpoints for every observation unit. For the fieldmap feature, making a get request for each observation unit will take a very long time with larger trials. The v1 studies endpoint managed to query all this data for all observation units in just one get request. Can these data be added to the observationunits get request?

For Bugs:
---------

**Comment by lukasmueller** [comment]
Need to schedule a meeting with Peter to discuss adding this metadata.
