### ISSUE TITLE
/analyze/phenotypes/ broken 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#378]
https://cassavabase.org/analyze/phenotypes/ -- error 404...resource not found...

**Comment by bellerbrock** [comment]
Hi Issak, I had to add this link to the toolbar mason file in the cassava
repo while we work on the code for the new analyze phenotypes page on a
branch in the sgn repo. I didn't realize the change would be pulled to the
live site so soon!  I guess we could disable that link for now, revert to
the previous commit in the cassava repo, or just wait for it to be fixed
when topic/analyze_phenotypes_page gets merged.

On 28 December 2015 at 08:52, Isaak Y Tecle <notifications@github.com>
wrote:

> https://cassavabase.org/analyze/phenotypes/ -- error 404...resource not
> found...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solgenomics/sgn/issues/378>.
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868

**Comment by bellerbrock** [comment]
topic/analyze_phenotypes_page is still being implemented, so solved this by just getting rid of the link for now
