### ISSUE TITLE
Page unresponsive after clicking download button

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3792]
We have noticed this issue for pretty much every download or verification button. The button is clicked, nothing appears to be happening, but if we wait long enough eventually the button starts loading and a file is returned.  People often think the download isn't working and click off the page prematurely. Is there a way to improve this so that a modal comes up right when the button is clicked?

![image (1)](https://user-images.githubusercontent.com/36375878/139878784-83a1314c-7095-40bf-99c0-066a2f1a67e6.png)

**Comment by lukasmueller** [comment]
I think this was fixed via 67600b9a93a510a565406de1408642f694d305c5.
