### ISSUE TITLE
Issue uploading intercross file

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3819]
Created a crossing experiment for testing using v35 Docker image.

![Screenshot from 2021-11-17 11-57-17](https://user-images.githubusercontent.com/36375878/142246574-bc66b2c8-0208-4b6c-8a18-51d3584ac07c.png)

But when I upload my test Intercross file I get the following message.

![Screenshot from 2021-11-17 11-57-00](https://user-images.githubusercontent.com/36375878/142246605-e9415267-ef72-4436-884d-6257bb754124.png)

See Intercross file is attached. Note, this is not a file produced by Intercross. I made it.
[intercross_test.csv](https://github.com/solgenomics/sgn/files/7556522/intercross_test.csv)

**Comment by titima15** [comment]
problem with the file.
