### ISSUE TITLE
Create Wizard tutorial video

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#382]

**Comment by bauchetg** [comment]
Added a screen video to download including login, list management and search on cassavabase:
http://www.slideshare.net/solgenomics/cassavabase-video-wizard-search-and-list-management-demo?related=

**Comment by bauchetg** [comment]
From workshop: Existing video needs update

**Comment by bauchetg** [comment]
covered with https://solgenomics.github.io/sgn/
