### ISSUE TITLE
P-Rep Trial Design

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3822]
Expected Behavior 
--------------------------------------------------------------------------

Does the partially replicated design type still work in the interactive trial design tool?

The design type requires the DiGGer R package, which is not included in the R_libs with the rest of the R packages
The version of DiGGer currently available for download requires R version 4.0+
Breedbase uses R version 3.6, so the DiGGer package is not compatible

Which version of DiGGer was the trial design tool written to use?

For Bugs:
---------

**Comment by lukasmueller** [comment]
An older version of DiGGEr was available, but I think we don't have access to it. It was unclear if the DiGGer code is actually licensed as an open source package.

**Comment by dwaring87** [comment]
@lukasmueller do you know what version of DiGGer the trial design works with?  It's not open source, but here is the license: http://www.nswdpibiom.org/austatgen/files/software/downloads/FreewareLicense.html

**Comment by bellerbrock** [comment]
We could also explore other R packages for producing P-rep design. I've been using the [blocksdesign](https://cran.r-project.org/web/packages/blocksdesign/index.html) package to implement [doubly-resolvable row-column designs](https://github.com/bellerbrock/TrialDesigns/blob/main/TrialDesignOptions.Rmd) and it may have what's needed.

**Comment by lukasmueller** [comment]
Hi Bryan, that would be great...
