### ISSUE TITLE
List passes validation but is invalid for download

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3830]
I created a list by adding accessions from a trial to a list, and of course the list passes validation because it was created within breedbase.

![Screenshot from 2021-11-18 14-46-29](https://user-images.githubusercontent.com/36375878/142486413-cae3ff82-6368-42b9-88f3-7fe0bcde80e4.png)

![Screenshot from 2021-11-18 14-41-59](https://user-images.githubusercontent.com/36375878/142486087-2ed75a27-42cf-4d86-9c2c-69a1d670116b.png)

Yet when I use this list to try and download data I get:
![Screenshot from 2021-11-18 14-42-13](https://user-images.githubusercontent.com/36375878/142486113-60cf25fc-4a05-4887-bb52-02bb8fa5c20b.png)

**Comment by lukasmueller** [comment]
Could you share the list so that I can also see it?

**Comment by lukasmueller** [comment]
Fixed via d674e75e1a96b87a131f59b31405637e4794ed98.
