### ISSUE TITLE
Label designer crashes when certain plot lists are submitted

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3848]
Expected Behavior 
--------------------------------------------------------------------------
as reported by Prasad.

Plot list in Cassavabase:

2021-20.GS.C5.CE.820.IB-rep1-TMS20F1007P0007_118
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1007P0016_117
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1037P0003_126
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1048P0012_116
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1056P0061_99
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1061P0009_141
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1062P0021_105
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1062P0024_144
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1089P0003_161
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1116P0032_164
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1126P0002_203
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1126P0007_201
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1144P0007_204
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1147P0003_168
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1158P0079_183
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1167P0010_187
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1179P0001_208
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1182P0043_215
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1193P0005_211
2021-20.GS.C5.CE.820.IB-rep1-TMS20F1233P0012_407

As reported by Prasad, the feature normally worked, but not with this specific plot_list. The plots in the list may be missing some specific metadata that is present in other plots. When the tool tries to append metadata to the label, it fails. 

For Bugs:
---------

**Comment by bellerbrock** [comment]
closed via 6b7d9a789e1b934a53183240a8b022adbfbf0552
