### ISSUE TITLE
Genotyping protocol: delete not working

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#3851]
[error] SGN::Controller::AJAX::GenotypingProtocol::genotyping_protocol_delete_GET(): DBI Exception: DBD::Pg::st execute failed: ERROR:  permission denied for table genotype [for Statement "DELETE from genotype WHERE genotype_id IN (148887,148888,148889,148890,148891,148892,148893,148894,148895,148896,148897,...

**Comment by lukasmueller** [comment]
Need to give the table the delete permission for web_usr

**Comment by lukasmueller** [comment]
Hi Titima, would you like to take a look at this one? It might just be a permission issue, in that case it could be closed as we should just assign correct permissions (it doesn't seem to be wrong in most databases)

**Comment by titima15** [comment]
@lukasmueller I don't this issue is caused by any bug in the codes. I have been using this deletion function a few times during these past few days. It works fine.

**Comment by titima15** [comment]
This issue is database specific
