### ISSUE TITLE
Loading phenotypes by subplots observationunit not working correctly

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3878]
I am able  to load the phenotypes using subplot as the observationunit. I am also able to download the phenotype from the trial after loading. However, on the trial detail page I see this:
![Screenshot from 2021-12-20 10-03-53](https://user-images.githubusercontent.com/36375878/146788687-cc07dd61-68d8-4ae2-b4f4-f3f374860a39.png)
![Screenshot from 2021-12-20 10-06-54](https://user-images.githubusercontent.com/36375878/146788698-0697cc0e-b174-400c-bd39-a843d418d95d.png)

**Comment by lukasmueller** [comment]
Hi Chris, did you select subplots from the Display dropdown menu?

**Comment by ch728** [comment]
Ah, didn't notice that! That fixes the issue with displaying the data, but it still shows "No Phenotypes" under Trial Status which is a little confusing.

**Comment by lukasmueller** [comment]
Yes, that count should be fixed... will look into it.

**Comment by lukasmueller** [comment]
Maybe display a section with associated phenotype counts for subplots, plants, and plots?

**Comment by alockrow** [comment]
Hi Chris, would you mind providing example data that you've had this issue with? Thank you!
