### ISSUE TITLE
Modify behavior of list download

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3883]
When the download button is pressed to download a list

![Screenshot from 2021-12-21 13-41-40](https://user-images.githubusercontent.com/36375878/146981948-3a5874ec-584b-4c4d-a4b3-80a5342f979f.png)

The a new tab is opened with the list in the browser. I think it would be more desirable to have the list download as a file. This behavior can be achieved by right clicking and selecting "save link as" currently, but many users may not realize this.

**Comment by lukasmueller** [comment]
Good idea!
