### ISSUE TITLE
Link between Accessions and Breeding Programs

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#3891]
Expected Behavior 
--------------------------------------------------------------------------

Am I correct in understanding that there is no direct link between an Accession and a Breeding Program in the database?

This came up when a breeder tried to use the Search Wizard to find all Accessions that are associated with their Breeding Program and only 2 out of their 100+ Accessions in the DB showed up.  This is because their Accessions have almost all been used in a Trial performed by a different Breeding Program.

It looks like when you select a Breeding Program and then Accessions in the Search Wizard it will list all of the Accessions from Trials from that Breeding Program, regardless if the Accessions in those Trials are actually associated with that Breeding Program.  We have a large number of Trials performed by a Breeding Program that contain a mix of Accessions from multiple Breeding Programs (cooperative nursery trials, etc).

We add the Breeding Program in the organization field to Accessions, but this does not seem to be a direct link to a Breeding Program and is not used in the Search Wizard.

Does the Accession upload do any verification on the organization field to ensure it is an existing Breeding Program name?

Would it be possible to create a direct link between Accessions and Breeding Programs and/or have the Search Wizard use the organization field for the link between the two?

For Bugs:
---------

**Comment by lukasmueller** [comment]
maybe add a new stockprop that contains a breeding program ID foreign key

**Comment by lukasmueller** [comment]
I think this was solved with the stockprop "organization" ? Please re-open if not!
