### ISSUE TITLE
d3 upgrade to recent version

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3900]
Expected Behavior 
--------------------------------------------------------------------------

use branch topic/d3_upgrade

For Bugs:
---------

**Comment by isaak** [comment]
Mason templates loading d3 (v3 and v4)

- [ ] mason/solgs/population/selection_trait.mas
- [ ] mason/solgs/population/trait.mas
- [ ] mason/solgs/selection/combined/selection_trait.mas
- [ ] mason/solgs/tools/kinship/plot.mas
- [ ] mason/solgs/tools/correlation/correlation.mas
- [ ] mason/solgs/tools/correlation/genetic_correlation.mas
- [ ] mason/solgs/tools/pca/plot.mas

- [ ] mason/breeders_toolbox/drone_imagery/standard_process_raw_images.mas
- [ ] mason/breeders_toolbox/program/traits.mas
- [ ] mason/breeders_toolbox/breeder_search_page.mas
- [ ] mason/breeders_toolbox/trial/trial_create_dialogs.mas
- [ ] mason/breeders_toolbox/trial/field_trial_from_field_trial_linkage.mas
- [ ] mason/breeders_toolbox/trial/phenotype_summary.mas
- [ ] mason/breeders_toolbox/trial/phenotype_heatmap.mas
- [ ] mason/breeders_toolbox/manage_drone_imagery.mas
- [ ] mason/breeders_toolbox/db_stats.mas
- [ ] mason/breeders_toolbox/radargraph.mas
- [ ] mason/breeders_toolbox/radargraph.mas
- [ ] mason/breeders_toolbox/manage_odk_data_collection.mas

- [ ] mason/search/stocks_graphicalfiltering.mas
- [ ] mason/stock/index.mas

- [ ] mason/pedigree/stock_pedigree.mas

- [ ] mason/page/detail_page_2_col_section.mas

- [ ] mason/tools/label_designer/design_label.mas
- [ ] mason/tools/label_designer/save_and_download.mas
- [ ] mason/tools/label_designer/select_layout.mas
- [ ] mason/tools/label_designer/label_designer_modals.mas

- [ ] mason/tools/solgwas/index.mas

- [ ] mason/tools/qualityControl/qualityControl.mas
- [ ] mason/tools/graphicalfiltering/index.mas

- [ ] mason/tools/heritability/index.mas
- [ ] mason/tools/heritability/heritability.mas
- [ ] mason/tools/stability/index.mas

- [ ] mason/tools/boxplotter.mas
- [ ] mason/tools/fieldmap.mas
- [ ] mason/tools/available_seedlots.mas
- [ ] mason/tools/trial_comparison/index.mas

**Comment by isaak** [comment]
All solGS tools upgraded to d3 v4: #4725

**Comment by lukasmueller** [comment]
There is still an issue with the geo field viewer, but that has a separate ticket.
