### ISSUE TITLE
Error uploading cross families

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3902]
Expected Behavior 
--------------------------------------------------------------------------

![Screenshot from 2022-01-10 15-15-49](https://user-images.githubusercontent.com/11297346/149198581-12c87e8d-da97-4199-bd79-99f6de2d8650.png)

For Bugs:
---------

**Comment by titima15** [comment]
@bellerbrock could you please include the file that you tried to upload and got the error? Thanks

**Comment by bellerbrock** [comment]
[19GRKNfamilynames.xls](https://github.com/solgenomics/sgn/files/7856885/19GRKNfamilynames.xls)

@titima15 no problem, here's the file. From what I can tell the upload fails because some of the crosses are missing female_parent relationships. '19GRKN_CaromexXNC05-0198' for example. No idea how that happened though, seems like it shouldn't be possible

**Comment by titima15** [comment]
In this case, there's noting wrong with the adding family function then. I don't know what's going on with the female_parent relationships, it shouldn't happen at all and I haven't seen this issue with other database.

**Comment by titima15** [comment]
I remember that you had similar problem on SPbase (some rows were missing from the relationship table). It's database specific issue, not the codes.

**Comment by bellerbrock** [comment]
I'll check for patterns in the missing stock_relationship ids to see if anything jumps out.

If the original problem was caused by deletion and re-upload of stocks like Beauregard, then let's check to ensure that stock deletion has sufficient safeguards, and isn't orphaning crosses by removing parent relationships without warning.

**Comment by bellerbrock** [comment]
So I'm not seeing any clear patterns in missing stock relationship ids. The largest gap is 648214 to 991436, but most gaps are a single missing id. The missing female parent relationships for 19GRKN crosses are are linked to Beauregard, Caromex, or Resisto, so seems curation of those 3 stocks is the issue.

**Comment by bellerbrock** [comment]
Best guess at this point is that some manual curation of CIP accessions inadvertently deleted the parent relationships.

In any case it is now fixed. I restored the parent relationships with some [sql insert statements](https://gist.github.com/bellerbrock/ef10474b2f457e2877ec94a71b583ab6), then uploaded the family names.
