### ISSUE TITLE
Pedigree view not loading

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3903]
The pedigree visualization gets stuck on loading, but the great grandparents load instantly below as a string.

![Screenshot from 2022-01-12 16-26-16](https://user-images.githubusercontent.com/36375878/149224034-b6592c52-07cf-482c-8131-b92c27c1550c.png)

**Comment by MFlores2021** [comment]
can you share a link for a specific example? ... also you can check on the web developer tools if the get the proper brapi data

**Comment by ch728** [comment]
The database is behind a password wall. Not sure about the development tools. 
I will follow up in slack.

**Comment by lukasmueller** [comment]
Discussion with Mirella: We need to redesign the progeny call in BrAPI. It needs to have a depth parameter (default = 1) that will add progenies of progenies etc. such that repetitive BrAPI calls are not necessary. They are too slow when there are hundreds of progenies with in turn hundreds of other progenies. 

We have a discussion about this with Peter Selby on Monday.

**Comment by titima15** [comment]
Prasad also reported this problem. The loading takes a long time. In his case, pedigree string doesn't show any info.

**Comment by lukasmueller** [comment]
Need to move to the new BrAPI call in version 2.1.

**Comment by MFlores2021** [comment]
related #1839

**Comment by MFlores2021** [comment]
Improved at https://github.com/solgenomics/BrAPI-Pedigree-Viewer/pull/14

**Comment by lukasmueller** [comment]
Can we close this ticket?

**Comment by lukasmueller** [comment]
I am closing this issue as the backend has been revised to the new BrAPI 2.1 calls that are much faster. Please re-open if this assessment is incorrect!
