### ISSUE TITLE
Cross-Site Scripting (XSS) > Stored > Non-Privileged User to Anyone

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#3908]
USDA did a security scan of Breedbase and found XSS vulnerability. When you visit the page now you get a javascript pop up saying "This is a XSS vulnerability"

To Create Stored XSS:
1) Login and visit https://tcap.pw.usda.gov/accession_usage.
2) Browse to the page of any accession (Example: https://tcap.pw.usda.gov/stock/98795/view)
3) Scroll down to "Related stocks" and Click "Create New Seedlot"
4) Enter XSS payload as new seedlot Name value.
5) Fill rest of required params with arbitrary values and click "OK" to create stored XSS.

**Comment by lukasmueller** [comment]
Need to filter out '<script>' and '</script>' from input?

**Comment by lukasmueller** [comment]
Need to check authorization and limit to submitter & curator

**Comment by ClayBirkett** [comment]
https://metacpan.org/pod/HTML::StripScripts
https://metacpan.org/pod/String::Clean::XSS
HTML::Entities::encode($text)

https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html
