### ISSUE TITLE
Streamline code for different folder types in the manage menus

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3919]
Expected Behavior 
--------------------------------------------------------------------------
The folders on the manage pages can have different types, but there is also a type that is shown on every manage page, but these are not really functional. 

By default, each manage page should create a folder of the proper type for that page (cross folder vs trial folder vs genotoyping folder etc). The selection of different types on the folder create dialog should be removed.

The folders (especially in Cassavabase) need to be curated to have the right type.

For Bugs:
---------

**Comment by bellerbrock** [comment]
related #3861

**Comment by titima15** [comment]
Done via 7858347
