### ISSUE TITLE
Sort alphabetically in list type and crossing experiment dropdowns

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#3926]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
@lukasmueller @alockrow The part about sorting crossing experiment dropdown lists is not relevant anymore. I already changed the crossing experiment dropdown list to crossing experiments by breeding program in the branch that I will merge soon.
