### ISSUE TITLE
Adding additional accession info not working

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3934]
On /breeder/accessions I click on "Add Accessions or Upload Accession Info". After I load the file I see this:

![Screenshot from 2022-02-04 07-20-38](https://user-images.githubusercontent.com/36375878/152529415-6f736159-130a-485a-a411-371efd23995f.png)

but when I click Continue the box disappears and the new information is not added. We are trying to add info on grain_type which is an accession stock property in our database (see attached file). 
[22 WGP CL entry list - grain type.xls](https://github.com/solgenomics/sgn/files/8002975/22.WGP.CL.entry.list.-.grain.type.xls)

**Comment by lukasmueller** [comment]
It looks like you  system is again on a development branch that hasn't been updated with new merges... If it's ok, I will put it back on the major production tag, where this should work.

**Comment by ch728** [comment]
Ah, okay, yes please feel free to do that. Thanks!

**Comment by ch728** [comment]
This works now! I think the real issue was that I had un-checked the fuzzy search box. This box must be checked in order to get the update accession info option.
