### ISSUE TITLE
Enable deletion of identifiers generated with identifier generation tool

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4005]
Expected Behavior 
--------------------------------------------------------------------------
as requested by Prasad

For Bugs:
---------

**Comment by lukasmueller** [comment]
enable the list manager to edit this string. Maybe a specific list detail page like for seedlots?

**Comment by titima15** [comment]
The owner can delete the whole set of identifiers by using the list dialog. No need to implement any new delete function. Already discussed with Prasad.
