### ISSUE TITLE
Clean up xen virtual machine hosts

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4013]
Expected Behavior 
--------------------------------------------------------------------------
Not sure about these vms:

vm-03: 
sweetpotatobase-reload.sgn.cornell.edu
hidap2.sgn.cornell.edu

vm-04:
debaser.sgn.cornell.edu (Something that Trushar has set up?)

vm-07:
kelp.sgn.cornell.edu
ptools-citrusgreening-ubuntu.sgn.cornell.edu
cassavabase-gobii.sgn.cornell.edu

For Bugs:
---------

**Comment by ClayBirkett** [comment]
You can remove kelp.sgn.cornell.edu
