### ISSUE TITLE
Trial delete runs incompletely when plots have images

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4019]
Expected Behavior 
--------------------------------------------------------------------------

Trial delete removes the trial but not the plots and returns with an ugly error when plots have images

For Bugs:
---------

**Comment by lukasmueller** [comment]
Combine with phenotype delete search

**Comment by lukasmueller** [comment]
undo the stock_image entry only.
Uploads of images should check it that md5sum is already present and not re-upload anything for that image

**Comment by lukasmueller** [comment]
fixed via #4042
