### ISSUE TITLE
"Upload Spatial Layout" does not update field layout

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4061]
Expected Behavior 
--------------------------------------------------------------------------

Uploading a file with the plot coordinates does not update the displayed field layout.

From the Trial Detail Page:

- Initially, the trial does not have a spatial layout and "This experiment does not have spatial layout info!" is displayed in the Field Layout section
- Upload a tab-delimited .txt file with plot_name, row_number, and col_number using the "Upload Spatial Layout" button
- The file is processed and the message "The trial coord upload finished with no errors." is displayed
- Refresh the page
- The Field Layout section now says "This experiment has spatial layout info uploaded!", but the displayed field layout is the same (does not reflect the plot coordinates in the uploaded file)

For Bugs:
---------

**Comment by dwaring87** [comment]
It looks like the materialized_phenotype_jsonb_table isn't refreshed after the upload

**Comment by npanitz** [comment]
Yes, I figured that was probably it. I will have it refresh the mat view
and refresh the cache and that should fix it.
