### ISSUE TITLE
Add the histogram tool as an analysis option with dataset input

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4069]
Expected Behavior 
--------------------------------------------------------------------------

The histogram is a popular tool, but right now it can only show a single trial's worth of data on a trial detail page, or a whole breeding program's worth of data on breeding program detail pages.

For Bugs:
---------

**Comment by lukasmueller** [comment]
There is the boxplotter tool that can already to that!

**Comment by lukasmueller** [comment]
Currently a dataset introspection tool is in development, we could add the histogram to that page as an alternate view (currently it uses a scatterplot which is used for outlier detection and selection)
