### ISSUE TITLE
Download accession properties producing some funky files

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4086]
Downloading accession properties from /breeders/download produces a pretty messed up file.  The population field is full of random accession names (maybe progeny?) and the other fields have a ton of duplication. See attached. Also, only 3 accessions, but notice it is a 2 MB file :octocat:  .
[download_accessions_xcyep.xls](https://github.com/solgenomics/sgn/files/8674831/download_accessions_xcyep.xls)

**Comment by lukasmueller** [comment]
Wow, that is funky!

**Comment by ch728** [comment]
This can be reproduced in cassavabase by downloading the Accession Properties for the public list IITA-NaCRRI-40-clones. So it appears to be a problem with the download itself and not a specific database.
