### ISSUE TITLE
NIRS uploader device type doesn't show for new protocol

### ISSUE THREAD

**Issue by afpowell** [solgenomics/sgn#4108]
Expected Behavior 
--------------------------------------------------------------------------

When user tries to create new NIRS protocol in the workflow, the device selection dropdown is not present (only shows up when you come back to it).

For Bugs:
---------

### Environment 

The error was encountered on cassavabase.org

**Comment by lukasmueller** [comment]
I was under the impression that this had been fixed...?

**Comment by afpowell** [comment]
Closed by #4271
