### ISSUE TITLE
Implement overview table for all crosses

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4109]
Expected Behavior 
--------------------------------------------------------------------------
Add a functionality that shows all the crosses (in a data table) and that is also downloadable.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe this can be implemented by using the code of the crossing experiment specific data table and simply leaving out the experiment specific constraint in the query?

**Comment by titima15** [comment]
Done via c4a3a31
