### ISSUE TITLE
Pedigree doesn't load due to BrAPIjs pagination bugs 

### ISSUE THREAD

**Issue by MFlores2021** [solgenomics/sgn#4112]
Expected Behavior 
--------------------------------------------------------------------------

Pedigree doesn't load due to BrAPIjs pagination issues. When pedigree returns more than 10 

Problematic code 
https://github.com/solgenomics/sgn/blob/fa71ea5d93af1bb277ec1e34b20c74d779a936d4/js/source/legacy/brapi/BrAPI.js#L2537

Related to https://github.com/solgenomics/BrAPI-js/issues/20

Pagination should be checked with another brapi tools as well.

For Bugs:
---------

#### Steps to Reproduce

(https://cassavabase.org/stock/40137/view
https://cassava-test.sgn.cornell.edu/stock/40137/view)

**Comment by darekbienkowski** [comment]
That commit should solve a problem. 
https://github.com/solgenomics/sgn/pull/4120
