### ISSUE TITLE
Dataset detail page and outlier filtering

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#4116]
Feature request
create a page to manage datasets
name, description, contents, delete, make public, make private
this feature would enable the addition of a description for datasets which could include a publication
another nice option would be ability to allow external link to a dataset detail page

**Comment by lukasmueller** [comment]
The dataset introspection page also implements outlier filtering, as explained in #3800 .

**Comment by lukasmueller** [comment]
Deleting #3800 as a duplicate of this ticket.

**Comment by lukasmueller** [comment]
For a good description of the outlier filtering feature, see #3454 .

**Comment by lukasmueller** [comment]
Closing this as a duplicate of #3454 and #3800.
