### ISSUE TITLE
GWAS fails

### ISSUE THREAD

**Issue by ClayBirkett** [solgenomics/sgn#4118]
using R4.2 the solgwas tool fails

using a simple example from rrBLUP 4.6.1
scores <- GWAS(pheno,geno,plot=FALSE)
Error in mixed.solve(y, X = X2, Z = Z, K = K2, return.Hinv = TRUE) : 
  K not positive semi-definite

I believe this is because of LAPACK 3.10.0
The code works correctly on my mac but fails on debian so appears to be platform dependent
Does solgwas work on other systems that have be upgraded?

**Comment by ClayBirkett** [comment]
I found that if I uninstall 3 openblas libraries that it fixes the errors running GWAS in rrBLUP.

**Comment by ClayBirkett** [comment]
Also doesn't work with R-4.2.1 which has updated LAPACK and fixed OpenBLAS. Temporary fix is to remove openBLAS packages, apt-get remove libopenblas0, but probably needs to recompile Rlib

**Comment by lukasmueller** [comment]
Does this work now with the new R4.2 library?

**Comment by ClayBirkett** [comment]
I tested using libopenblas with R-4.3.0 and it still crashes running GWAS. So we should not add these libraries back
