### ISSUE TITLE
Look at Fieldbook support for barcodes and implement in Cassavabase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#413]

**Comment by lukasmueller** [comment]
Does the field book support 2D barcodes?

**Comment by aco46** [comment]
Field book supports 2D QR codes.

**Comment by aco46** [comment]
Add user options for nursery and  trial barcode creation.

**Comment by aco46** [comment]
Merged to master here d2ebed296fac40b3f57e1ea09b454ec44479bf57
Could no get the QRbarcode to work for now but will look into it again.
I intend adding additional field information to each plot's barcode in an up coming commit.

**Comment by aco46** [comment]
merged to master via 083050f0782a21f5456cc15a1f6fe51108c48c45

prints field information for each plot if plot option is checked.
prints male and female if nursery option is checked.
