### ISSUE TITLE
Phenotype download does not download all the traits when trials are combined

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#4132]
Expected Behavior 
--------------------------------------------------------------------------

maybe only common traits are downloaded? (that's on the wizard and download page I believe)

For Bugs:
---------

**Comment by bellerbrock** [comment]
@aco46 is there a particular environment or set of trials where you have see this happen?

I've tried replicating it in Sweetpotatobase, in both the wizard and manage trials page, using a set of trials that measured distinct traits (16PURNIRS, 14ADYT0008CUN, 14DISE209HFLNO7). With those trials at least all the data seems to download just fine [phenotype.csv](https://github.com/solgenomics/sgn/files/8920117/phenotype.csv)
.

**Comment by tphickey** [comment]
I've had this issue when downloading as an xls and reaching the maximum column IV (256). CSV worked for me though.

**Comment by lukasmueller** [comment]
Duplicate of #4209. Closing this issue.
