### ISSUE TITLE
BrAPI should not use materialized views

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4133]
Expected Behavior 
--------------------------------------------------------------------------
Most downloads etc should not use materialized views. Only things that are interactive, such as the wizard, should rely on materialized views.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Will require speed improvements for native queries, let's revisit ideas like #3089 to improve speed

**Comment by lukasmueller** [comment]
Need to create a list of which method (native vs materialized) which brapi call use

**Comment by MFlores2021** [comment]
Related #2629
