### ISSUE TITLE
Soil data associated on the trial level

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4141]
Expected Behavior 
--------------------------------------------------------------------------
as requested by Eder

For Bugs:
---------

**Comment by lukasmueller** [comment]
Example file provided by Eder:
[Soil analysis BR.UYT.21.PP1.xlsx](https://github.com/solgenomics/sgn/files/8919986/Soil.analysis.BR.UYT.21.PP1.xlsx)

**Comment by lukasmueller** [comment]
Also store at the block level.

**Comment by titima15** [comment]
Done via d4e5f33
