### ISSUE TITLE
Change the defs of the DBIx::Class objects for the Metadata database

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#4145]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
Got this warning message when running dbpatch:
"DBIx::Class::Storage::DBI::insert(): Missing value for primary key column ‘metadata_id’ on MdMetadata - perhaps you forgot to set its ‘is_auto_increment’ attribute during add_columns()? Treating ‘metadata_id’ implicitly as an autoinc, and attempting value retrieval at /home/vagrant/cxgn/cxgn-corelibs/lib/CXGN/Metadata/Metadbdata.pm line 1408
DBIx::Class::Storage::DBI::insert(): Missing value for primary key column ‘dbversion_id’ on MdDbversion - perhaps you forgot to set its ‘is_auto_increment’ attribute during add_columns()? Treating ‘dbversion_id’ implicitly as an autoinc, and attempting value retrieval at /home/vagrant/cxgn/cxgn-corelibs/lib/CXGN/Metadata/Dbversion.pm line 556"

**Comment by lukasmueller** [comment]
Note this is in the cxgn-corelibs repo. Fixed in topic/fix_auto_increment_warnings in that repo and corresponding pull request.
