### ISSUE TITLE
Allow curators to edit program description and name

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4151]
Expected Behavior 
--------------------------------------------------------------------------

A request from Bert. Looks like [SGN/Controller/AJAX/BreedersToolbox.pm](https://github.com/solgenomics/sgn/blob/9e1d7f679d1b53852a0e688718da14320768c4d9/lib/SGN/Controller/AJAX/BreedersToolbox.pm#L42) and [CXGN/BreedersToolbox/Projects.pm](https://github.com/solgenomics/sgn/blob/9e1d7f679d1b53852a0e688718da14320768c4d9/lib/CXGN/BreedersToolbox/Projects.pm#L454) only implement program create and delete, no update.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Caveat, need to change also corresponding role in sp_role
