### ISSUE TITLE
Add tissue type options in sampling trial workflow

### ISSUE THREAD

**Issue by jmh579** [solgenomics/sgn#4159]
For metabolomics and transcriptomics studies, it is expected that results will vary across different tissue types, so it is important to support a wide variety of tissue types in Breedbase if we want to handle these types of experiments. Current tissue types are limited for Breedbase sampling trials and more options (seed, fruit, etc) are needed.  

#### Steps to Reproduce
Within the "Sampling trial workflow", if the user selects "I need to design a completely new sampling trial", the drop down menu for "Optional Tissue: (If used the same tissue for all samples)" only has three tissue types ("Leaf", "Root", "Stem"). This is also a limitation for sampling trials uploaded as excel files. From the info box for sampling trial upload: "tissue_type (must be either leaf, root, or stem)".

#### Suggested change
**This drop down menu should be expanded to include seed, fruit, etc.** The Plant Ontology has many other tissue types/organs/structures that may also be useful to users.

**Comment by aco46** [comment]
Current implementation is not limited to root, stem and leaf tissue types. I have indicated that fruit and seed tissues can also be used. Other tissue types can also be reflected as options.
