### ISSUE TITLE
Phenotype uploading page does not refresh automatically after uploading a xls spreasheet

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#417]
After uploading your phenotypes and updating the wizard search, the confirmation of uploading page status remains till you refresh manually the page by login off and in again (refresh the page only does do it).
https://cassavabase.org/breeders/phenotyping/

**Comment by nickmorales** [comment]
I'm not able to see the error you're talking about? Once you refresh the page you should be able to upload a new file
