### ISSUE TITLE
Sweetpotatobase runs out of memory and crashes during phenomatrix construction of large downloads

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4170]
Expected Behavior 
--------------------------------------------------------------------------
Happens when trying to download all trial data for Peru-CIP program in sweetpotatobase.org via the wizard

Based on the error log output the crash must be during phenomatrix construction, lib/CXGN/Phenotypes/PhenotypeMatrix.pm between [line 273](https://github.com/solgenomics/sgn/blob/d1fc50fb925be4c304ebb4dd66d2c31ee62182cc/lib/CXGN/Phenotypes/PhenotypeMatrix.pm#L273) and [line 365](https://github.com/solgenomics/sgn/blob/d1fc50fb925be4c304ebb4dd66d2c31ee62182cc/lib/CXGN/Phenotypes/PhenotypeMatrix.pm#L365)

Lukas and I tried increasing the server RAM from 24GB to 48GB, but it still crashes

For Bugs:
---------

**Comment by lukasmueller** [comment]
added more RAM (100G) and now it works... closing this for now but the data should not be completely handled in RAM is it is done now for calculating the transpose of the data.
