### ISSUE TITLE
Implement custom plot naming for other designs

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4175]
Expected Behavior 
--------------------------------------------------------------------------

Currently, the plot custom naming button only works for complete block. IITA would like to use the same custom naming for alpha lattice and augmented (really with all the designs).

Custom naming is : Year (as prefix) - trial name - replication - accession name - plot number

Example: C1.C2.C3.C4.40.UYT.IB-rep1-TMS18F1307P0077_101

Maybe allow specification of different custom formats for different breeding programs?

For Bugs:
---------

**Comment by aco46** [comment]
Close via PR #4182
