### ISSUE TITLE
Combined image/phenotype upload does not connect phenotypes to images

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4177]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bellerbrock** [comment]
Currently the only images that are linked to phenotypic scores are ones uploaded via spreadsheet with attached zipfiles. The phenotypic scores from images analysis are stored along with the output image, but they are not currently linked back to the original image(s) they came from.

One way to fix this - store the phenotypic score, link it to the analysis output image through nd_experiment and additional linking table, then link the output image to the original image through and image to image linking table. also link the output image to nd_protocol/ the image analysis version. How does that sound?

**Comment by bellerbrock** [comment]
related to this is the problem of sorting images by type (root cross section, leaf, full plant, etc), to see what is suitable for a given analysis. A more formalized tag system where image tags are required could help.
