### ISSUE TITLE
Add ploidy Levels to phenotype download when available.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#4179]
Expected Behavior 
--------------------------------------------------------------------------
As a follow-up to the discussion in #748, ploidy levels column should be added to the phenotype download spreadsheet when available. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
A new more general ticket was added for the download of more attributes. See #4318. Closing this ticket and transfering assignee to new ticket.
