### ISSUE TITLE
"414 Request-URI Too Large" errror in wizard phenotype download when many trials / accessions selected

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4198]
Expected Behavior 
--------------------------------------------------------------------------

Not sure what the best solution is. Maybe switch to a BrAPI style POST request with parameters in the body that returns a result ID, then a GET request with the result ID?

For Bugs:
---------

**Comment by lukasmueller** [comment]
maybe convert to post?

**Comment by lukasmueller** [comment]
related issue #3795
