### ISSUE TITLE
Accession loading based on lists broken

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4201]
Expected Behavior 
--------------------------------------------------------------------------
Accession loading based on lists gives an error.

Accessions can be loaded using excel files as a temporary workaround.

For Bugs:
---------

**Comment by darekbienkowski** [comment]
A bug is probably particular for a given list or database. The problem cannot be reproduced on basic workflow, docker environments, or cassava base-test websites.
I will close the issue now. If there are more details about a situation, we should reopen it to fix it.
