### ISSUE TITLE
Can't display other language correctly

### ISSUE THREAD

**Issue by huiyn** [solgenomics/sgn#4207]
Expected Behavior 
--------------------------------------------------------------------------
I am localizing the website to Chinese, most of the pages work fine like below.

<img width="1387" alt="Screen Shot 2022-08-29 at 15 30 35" src="https://user-images.githubusercontent.com/83797018/187147690-292f3d16-15e2-462c-aef1-ccb8d43b764d.png">

For Bugs:
-------------------------

But some pages are garbled

<img width="1387" alt="Screen Shot 2022-08-29 at 15 32 08" src="https://user-images.githubusercontent.com/83797018/187147954-1b4d77e4-78fa-453b-b51a-275748b4616e.png">

This only happens when the URL ends with a .pl file
<img width="112" alt="Screen Shot 2022-08-29 at 15 44 39" src="https://user-images.githubusercontent.com/83797018/187150454-cad9213a-1f72-4f1b-9cf8-6a3cf9f02e6e.png">

English all works fine, only Chinese on the page is garbled.

After some search, I think this is something about code in cgi-bin folder, I tried to add "use utf8;" in some files but not working.
I don't know if I am correct, but I think all the .pl files are code from the old mod_perl project, and mod_perl doesn't support utf8 well.

Any ideas on how to solve this issue?

**Comment by lukasmueller** [comment]
Hi, thanks for the amazing work to translate to Chinese! 

We should have replaced all of these pages by now, but it didn't quite happen 100%. For the about page, I think there is an alternate mason page as well that you should probably link to. How many pages have you seen that are still around that are based on the old mod perl? They are usually simple pages that can be replaced easily with mason pages.

**Comment by lukasmueller** [comment]
Did you create the Chinese version in its own mason repo? That would be the ideal way of doing it. Also, will you make it avaialble to other users?

**Comment by lukasmueller** [comment]
For the display in the cgi-bin files, the problem may occur because most of the content is read in from files. The filehandles need to be opened as utf-8 encoded filehandles, such as open(my $F, "< :encoding(UTF8)", $filename) ...

**Comment by lukasmueller** [comment]
Hi Huiyn, if that suggestion didn't work let me know, otherwise I will close this ticket. Thanks again for letting us know.

cheers
Lukas
