### ISSUE TITLE
Error when creatig a field design on Cassavabase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4208]
Expected Behavior 
--------------------------------------------------------------------------
FromPrasad: We got error on cassavabase when trying to design the trial (Alpha lattice) for multiple locations
[11:12](https://muellerlab.slack.com/archives/D0CHK5E94/p1661440348137029)
I checked the error log it was showing  “package ‘agricolae’ was built under R version 4.1.2  Error in alpha$book : object of type ‘closure’ is not subsettable Execution halted” message

For Bugs:
---------

**Comment by bellerbrock** [comment]
similar to #4146

Updating to R 4.2 fixed it but then caused problems with the NIRS upload outlier visualization. I think what worked best was reinstalling agricolae and any other individual packages that give errors

**Comment by lukasmueller** [comment]
Need to upgrade R version to 4.2 for all dependencies.

**Comment by darekbienkowski** [comment]
I added a branch for Debian 11 with R version 4.2. Packages were built on Debian 11 with R 4.2 based on 4.1.2 libs on a day 08/30/2022, with a full dependencies flag. 

https://github.com/solgenomics/R_lib/tree/topic%2Fdebian_bullseye_R4.2

**Comment by MFlores2021** [comment]
Test the new version and it will be ready to close the issue

**Comment by lukasmueller** [comment]
Seems to have solved the issue, closing this ticket.
