### ISSUE TITLE
Create auditing system

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4237]
Expected Behavior 
--------------------------------------------------------------------------
Implement backend that can track changes to the database

For Bugs:
---------

**Comment by lukasmueller** [comment]
possibilities: 
* have a specific _history table for each data type
* have a stand-alone audit table (maybe with json data?)

**Comment by lukasmueller** [comment]
Add audit table in metadata schema?
implement the auditing information transparently in each second level database object?

**Comment by lukasmueller** [comment]
other possible implementation: keep log in a file

**Comment by afpowell** [comment]
after discussing a bit, a solution involving triggers for specific tables and jsonb seems reasonable - something like the following? https://elephas.io/audit-logging-using-jsonb-in-postgres/

**Comment by bellerbrock** [comment]
From the ticket meeting discussion about the triggers + jsonb solution:
Let's make sure the change records in the audit log include an insert date so they can be deleted once they are a year or two old.

**Comment by afpowell** [comment]
For future ref, it looks like the example in the link above includes the timestamps for each record
