### ISSUE TITLE
add a new stock type, "vector", to improve representation of transgenic lines

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#424]
The vector would have a male_parent relationship with the transgenic line, and the female_parent would be the original untransformed line.

May also need a stock_property "transgenic", and "T1", "T2" to indicate generation. The transformed line would still be a stock of type "accession".

**Comment by nickmorales** [comment]
db patch adds these new cvterms af1e0f41f89291648f30a752571d1b81d8250ea1

**Comment by nickmorales** [comment]
122e5549df3ef5136655ab7e9da039b463d78148
