### ISSUE TITLE
Add cross type option to handle female parent mixes

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4255]
Expected Behavior 
--------------------------------------------------------------------------

Sometimes errors during crossing, seed handling, or seedling harvest cause mixes where there is more than one possible female parent. It's not possible to represent this with the current cross types, it'd be helpful to add a 'mix' type that can identify possible parents.

For Bugs:
---------

**Comment by ramierop** [comment]
I also would like to see this feature implemented. We had some selections from 2023 where we know what the females may be, but due to time and quality of plants, they were bulked at transplanting. Is there a way that would be appropriate to do that currently? Or would I just have to upload accession only?
@titima15 @chris @bellerbrock

**Comment by titima15** [comment]
@ramierop This can be done by having those females in a population, then using that female population as female parent. Right now, we allow using population only for male parents (for open pollination), but I can add using population for female parent option. Would this approach work for you?

**Comment by ramierop** [comment]
@titima15 That would work fine. What kind of time would we be looking for that to get implemented?

**Comment by titima15** [comment]
@ramierop  If you need to use this feature soon, I can assign this ticket to myself and start working on it on Tuesday. It should be done by next week. Also, what's the cross type name you would like to use for this option? We should add a specific cross type for this option.  How about male parent for this type of cross? A male accession or male population?

**Comment by ramierop** [comment]
I would like to get this data in quickly. Next week would be fantastic!

A name like bulked-population would be good.

I would keep the male population options the same maybe.

In our situation we have a combination of mixed open pollinated plants and
paired cross plants. I'm open to suggestions on how to name them so it is
clear what it is.

**Comment by titima15** [comment]
@ramierop How about "bulked-females" to make it clearer. For this "bulked-females" cross type, female parent would be a population and male parent can be either a population or an accession. Would these criteria cover everything for your usage?

**Comment by titima15** [comment]
@ramierop Actually, we have a cross type called "bulk", I will modify that bulk cross type to include your use case.

**Comment by ramierop** [comment]
I think that sounds good.

**Comment by ramierop** [comment]
@titima15 just wanted to check in and see how this cross type option for bulks was going? Is there anything you need from me?

**Comment by titima15** [comment]
@ramierop I am done with the modification. However, I would like to check some details and test it first. You have 2 options: bulk_open and bulk cross types. For bulk_open cross type, you can use female population and male population or unknown male. For bulk cross type, you can use female population and male accession. I will let you know once the site is updated (I plan to update by Friday).

**Comment by titima15** [comment]
Done via #4787

**Comment by ramierop** [comment]
@titima15 I will check on this soon and give you an update after.
