### ISSUE TITLE
Add Spreadsheet::XLSX to the local-lib repo

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4260]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by darekbienkowski** [comment]
We also need 
Excel::Writer::XLSX.

**Comment by darekbienkowski** [comment]
Done - both modules added

https://github.com/solgenomics/perl-local-lib/tree/topic/debian_bullseye
