### ISSUE TITLE
Heritability Tests Fail

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4265]
Expected Behavior 
--------------------------------------------------------------------------

The `unit_mech/AJAX/Heritability.t` tests fail on our local machine.  It looks like the hard-coded file paths in the test:

https://github.com/solgenomics/sgn/blob/e4937d5dd3a7174c4195b10febc7b21cd0cb8442/t/unit_mech/AJAX/Heritability.t#L62

don't match the path to the files on our server (we don't have a `static` directory on our system).

```
RDATA: $VAR1 = {
          'h2Table' => '/documents/tempfiles/heritability_files/h2_download_gNhjl_h2File.png',
          'figure4' => '/documents/tempfiles/heritability_files/h2_download_gNhjl_figure4.png',
          'figure3' => '/documents/tempfiles/heritability_files/h2_download_gNhjl_figure3.png',
          'dummy_response' => '1'
        };

#   Failed test 'figure 3 created'
#   at /home/production/cxgn/sgn/t/unit_mech/AJAX/Heritability.t line 62.

#   Failed test 'table created'
#   at /home/production/cxgn/sgn/t/unit_mech/AJAX/Heritability.t line 64.

...

 /home/production/cxgn/sgn/t/unit_mech/AJAX/Heritability.t                             (Wstat: 512 Tests: 10 Failed: 2)
  Failed tests:  9-10
  Non-zero exit status: 2
```

For Bugs:
---------

**Comment by darekbienkowski** [comment]
It can be connected with GWAS

**Comment by dwaring87** [comment]
I just checked the heritability tool on the websites again and the images are loading on cassavabase (maybe I just didn't wait long enough before) but they're not showing up on our instance.

The issue might have to do with the `tempfiles_subdir` key in the conf file which is set to `/static/documents/tempfiles`.  We don't have a `/static/` directory in our Docker image.  Does this exist on the VMs?  Is it a symlink to the static directory in the sgn repo?

**Comment by dwaring87** [comment]
It looks like updating the R_libs repo to use the 4.2 branch fixes the tests and most of the issues we were seeing (thanks @darekbienkowski).

We still occasionally get some runs of the heritability tool to not display the image of the heritability table, but that seems to be more an issue with the data going into the analysis (ie if the trials only have one block).

PR #4274 fixes a small typo which caused some runs to fail (depending on the input data) and returns error messages from the R script to the website.
