### ISSUE TITLE
Allow uploading biochemical data with NIRS template

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#4304]
Expected Behavior 
--------------------------------------------------------------------------
requested by Karima - they need to have the biochemical/phenotyping data associated with the NIRS data. 
If this is uploaded using the phenotyping template it cannot be traced back to the NIRS experiment.

Need to find a way to upload and  represent the phenotype data with the NIRS dataset. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
The question is how do you create the dataset after upload. Having two uploads for the two different types of data does not seem to be a huge barrier?
