### ISSUE TITLE
educational breedbase DB

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4306]
Expected Behavior 
--------------------------------------------------------------------------

Peter Kulakow suggested a breedbase DB dedicated for educational purposes, which can possibly be used by students.

For Bugs:
---------

**Comment by lukasmueller** [comment]
great idea. We could call it demo.breedbase.org.

Let's discuss I and will set it up.

**Comment by isaak** [comment]
Ideally, it would be good to load it with a variety of data that can be used to demo all the features in the code base. And also make all the features visible on the menus.

**Comment by lukasmueller** [comment]
Create a demo version of each database with less data for faster demos

**Comment by lukasmueller** [comment]
The site is available at demo.breedbase.org
It runs as a docker from vm-05
