### ISSUE TITLE
FieldBook app multi users 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4307]
Expected Behavior 
--------------------------------------------------------------------------

A participant in the BreedBase workshop (ISTRC) asked if more than one users from different devices could use the FieldBook app to collect data on the same trial.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Yes, it is possible, but it has to be coordinated I think. For example, different devices could be used to collect data about different phenotypes. It would be difficult to upload information when more than one device has data about the same phenotype. Maybe we should add a brief section about this to the manual?

**Comment by isaak** [comment]
Great. Does the data from the different devices need to be aggregated before loading to the DB? or Can it uploaded in parts from the different devices?

**Comment by isaak** [comment]
Multiple users collecting data on the same trait, and then having options on how to process that, may be useful. For example, for traits (e.g., disease scoring) that you make subjective judgements, averaging the trait data from the multiple evaluations can be a solution to achieve more accurate data.
