### ISSUE TITLE
genotype download does not work from wizard

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4313]
Expected Behavior 
--------------------------------------------------------------------------

The following error is encountered when trying to download genotyping information from the wizard (we selected protocols as well as genotyping projects)

Attribute (protocol_id_list) does not pass the type constraint because: Validation failed for 'ArrayRef[Int]|Undef' with value [ undef ] at /home/production/cxgn/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Object.pm line 24

         Moose::Object::new('CXGN::Genotype::Download::VCF', 'HASH(0x55ab07282920)') called at lib/CXGN/Genotype/DownloadFactory.pm line 56

         CXGN::Genotype::DownloadFactory::instantiate('CXGN::Genotype::DownloadFactory', 'VCF', 'HASH(0x55ab07282920)') called at lib/SGN/Controller/BreedersToolbox/Download.pm line 1063

         SGN::Controller::BreedersToolbox::Download::download_gbs_action('SGN::Controller::BreedersToolbox::Download=HASH(0x55ab003891a0)', 'SGN=HASH(0x55ab0727d690)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 358

         Catalyst::Action::execute('Catalyst::Action=HASH(0x55ab00a6ef18)', 'SGN::Controller::BreedersToolbox::Download=HASH(0x55ab003891a0)', 'SGN=HASH(0x55ab0727d690)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060

         eval {...} at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060

         Catalyst::execute('SGN=HASH(0x55ab0727d690)', 'SGN::Controller::BreedersToolbox::Download', 'Catalyst::Action=HASH(0x55ab00a6ef18)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 353

         Catalyst::Action::dispatch('Catalyst::Action=HASH(0x55ab00a6ef18)', 'SGN=HASH(0x55ab0727d690)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Controller.pm line 170

         Catalyst::Controller::_ACTION('SGN::Controller::BreedersToolbox::Download=HASH(0x55ab003891a0)', 'SGN=HASH(0x55ab0727d690)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 358

         Catalyst::Action::execute('Catalyst::Action=HASH(0x55ab00a6aee0)', 'SGN::Controller::BreedersToolbox::Download=HASH(0x55ab003891a0)', 'SGN=HASH(0x55ab0727d690)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060

For Bugs:
---------

**Comment by alockrow** [comment]
Unable to replicate issue: successfully downloaded genotyping information from multiple datasets. Closing for now; will reopen if a dataset is identified that throws this error.
