### ISSUE TITLE
For trial creation, allow consecutive plot numbers for CRD design

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4316]
Expected Behavior 
--------------------------------------------------------------------------
add a checkmark that allows to select option to create consecutive plot numbers instead of plot increases by 1000's etc.

In lib/CXGN/TrialDesign/Plugin/CRD.pm should call function convert_plot_numbers should only be called if the block should be represented in the plot number.

For Bugs:
---------

**Comment by lukasmueller** [comment]
standardizing plot names by breeding program feature related to this ticket

**Comment by bellerbrock** [comment]
@lukasmueller  [This](https://github.com/dauglyon/textTemplater) is the templating tool David was working on that I mentioned. The idea at the time was to use it to allow each program to define a standard trial name template and plot name template according to their naming conventions

**Comment by lukasmueller** [comment]
duplicate of more general issue #4390
