### ISSUE TITLE
tag release note

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4324]
Expected Behavior 
--------------------------------------------------------------------------

It would nice to revive the old practice of making tag release notes, so sites can be updated with all the necessary repos and db patches anytime by anyone.

For Bugs:
---------

**Comment by bellerbrock** [comment]
Just looked it up in an old gist I had, the -c flag is how we used to include info about dependencies

`../sgn-devtools/make_release_tag -M -c "dependencies: patch db/00061 and db/00062"`

**Comment by lukasmueller** [comment]
Thanks for the command :-)

This is the SOP now.

**Comment by isaak** [comment]
github also has a release notes feature: https://github.com/solgenomics/sgn/releases/new
