### ISSUE TITLE
Some wizard phenotype downloads never complete in Cassavabase

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4326]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

Cassavabase

#### Steps to Reproduce

Has been happening for about a month. Prasad sees the problem when trying to download data for these 4  accessions specifically : IITA-TMS-IBA070337, IITA-TMS-IBA011368, IITA-TMS-IBA011371, IITA-TMS-IBA120008

Looking at the error log and pg_stat_activity, it seems related to the new treatment retrieval query. It uses observation unit ids and placeholders, the queries remain active but don't take up many resources and never finish. May be exceeding the query length, a solution could be to modify the query to just use trial ids, then filter the results by the observation unit ids afterwards.

**Comment by lukasmueller** [comment]
Create temp table with identifiers to join to, instead of using in (...) operator, which can exceed query length.
