### ISSUE TITLE
Accession search very slow in Cassavabase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4345]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
Maybe also don't retrieve all the accessions in the database?

**Comment by lukasmueller** [comment]
add a config key that prevents the empty search from happening, so that it can be fine tuned for each database

**Comment by nmenda** [comment]
search page does not submit empty search now at loading. 
Recent pull request should take care of slowness related to multiple joins.
