### ISSUE TITLE
Necrosis image analysis

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4358]
Expected Behavior 
--------------------------------------------------------------------------

I would be informative to display the image prediction model metrics (e.g., accuracy) on the page. (Francisca, TARI) 

For Bugs:
---------

**Comment by solomonnsumba** [comment]
@bellerbrock  http://unet.mcrops.org/api/  updated to include the information requested here. The info parameter contains all this information. Please update accordingly within the database interface.
<img width="1430" alt="Screenshot 2023-02-07 at 04 31 21" src="https://user-images.githubusercontent.com/4299350/217125593-fe6ff20a-7277-41ac-a22f-82db5da26bd2.png">

**Comment by bellerbrock** [comment]
Thank you @solomonnsumba!

Now breedbase just needs to display the addtional returned info along with the analyzed images and scores

`
{
               'trait_value' => '0.00',
               'info' => {
                           'publications' => 'https://arxiv.org/abs/2005.03367',
                           'model-version' => 'v.3.1',
                           'parameters' => {
                                             'epochs' => '217',
                                             'batch-size' => '4',
                                             'images' => '3428'
                                           },
                           'architecture' => 'Unet-256',
                           'data-access' => 'https://doi.org/10.1016/j.dib.2020.106170',
                           'ref-table' => 'https://virologyj.biomedcentral.com/articles/10.1186/s12985-014-0216-x',
                           'results' => {
                                          'IOU' => '0.931',
                                          'Dice' => '0.964',
                                          'trained' => '12/2022'
                                        },
                           'info' => 'Model version 3.1 trained in 12/2022. Image input size changed from 128 to 256 pixels'
                         },
               'trait_name' => 'CBSDpct | CO_334:0002078',
               'image_link' => 'http://unet.mcrops.org/static/api_results/TDr8902474_replicate3_plot41_01ATDrAB9596s_image3_1_2020-10-12-10-26-19.png',
               'image_name' => 'TDr8902474_replicate3_plot41_01ATDrAB9596s_image3_1_2020-10-12-10-26-19.JPG'
             };
`
