### ISSUE TITLE
Add trait ontology export in obo format

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4380]
Expected Behavior 
--------------------------------------------------------------------------

To complement the obo loading script, it would be very useful to be able to export a database's trait ontology in obo format

For Bugs:
---------

**Comment by lukasmueller** [comment]
This requested by BI OnRamp (Keo)

**Comment by chris263** [comment]
I am turning this ticket to "Critical" because there are few databases with missing obo file. This feature will be very important to solve the problem.
