### ISSUE TITLE
Additional information to trial 

### ISSUE THREAD

**Issue by pa279** [solgenomics/sgn#4399]
Expected Behavior 
--------------------------------------------------------------------------

Add reporting info (type of analysis to be conducted, objective, ...) to the trials for easy sharing with biometricians 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Trial creation dialog should have input fields for "Trial Purpose" or something like that... would that cover it?

**Comment by Sri-2023** [comment]
Yes, we have an option called "Description" that allows us to include our objective, analysis of this study, and experimental design as part of the trial creation process. However, there is a limit of 250 characters.
Here is an exmaple:
![Screenshot from 2023-10-04 15-35-12](https://github.com/solgenomics/sgn/assets/122313818/ddeb16fa-cd4b-45d2-9ece-3373fb236c0d)

**Comment by Sri-2023** [comment]
:-)
