### ISSUE TITLE
links from trial search results to trial detail pages 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#440]
-- on cassava-test

--Caught exception in SGN::Controller::BreedersToolbox::Trial->trial_info "Can't call method "cvterm_id" on an undefined value at lib/CXGN/Trial.pm line 1101."

--the trial page is broken: e.g. https://cassava-test.sgn.cornell.edu/breeders/trial/128

**Comment by aco46** [comment]
You need to run a db patch in 00052.

    On Wednesday, March 30, 2016 10:02 AM, Isaak Y Tecle <notifications@github.com> wrote:
 

 -- on cassava-test--Caught exception in SGN::Controller::BreedersToolbox::Trial->trial_info "Can't call method "cvterm_id" on an undefined value at lib/CXGN/Trial.pm line 1101."—

**Comment by isaak** [comment]
Thanks, Alex.
