### ISSUE TITLE
Heritability analysis broken

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4402]
Expected Behavior 
--------------------------------------------------------------------------

-- There is a bug in the r script.

Error in if (md[i, 1]/nrow(phenoData) > 0.6) { : 
  missing value where TRUE/FALSE needed

Occurs here:
https://github.com/solgenomics/sgn/blob/master/R/heritability/h2_rscript.R#L81

For Bugs:
---------

**Comment by chris263** [comment]
Hi Isaak, could you try this branch? https://github.com/solgenomics/sgn/tree/topic/fix_h2

**Comment by isaak** [comment]
Fixed #4424
