### ISSUE TITLE
In vitro maintenance trial

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4405]
Expected Behavior 
--------------------------------------------------------------------------
Create an in vitro maintenance trial that essentially represents a collection of "seedlots" that can have different statuses associated with it

For Bugs:
---------

**Comment by titima15** [comment]
This one is overlap with #4362 tissue culture inventory tool

**Comment by titima15** [comment]
This tool should support data collected by using fieldbook.

**Comment by lukasmueller** [comment]
The issue is that fieldbook cannot dynamically add or remove "plots" from a trial

**Comment by lukasmueller** [comment]
Conclusion: in an in vitro trial, all operations are carried out on the premises of a research lab which usually has wireless internet. We can therefore update in vitro records directly in the database. 

Implementation started in topic/invitro_regeneration_trial

Support for QR code reading directly from the webpage: https://github.com/LazarSoft/jsqrcode

**Comment by titima15** [comment]
Done via #4864
