### ISSUE TITLE
Depositing new genotyping in the yam base

### ISSUE THREAD

**Issue by pa279** [solgenomics/sgn#4408]
Expected Behavior 
--------------------------------------------------------------------------
The same genotypes sequenced with the same genotype protocol and under the same project should have a way of storing the vcf file rather than returning "genotype xxx has been genotype under protocol A" 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Has this problem been resolved? Can we close this ticket?

**Comment by pa279** [comment]
Yes Please Lukas,
Cheers,
Agre

From: Lukas Mueller ***@***.***>
Date: Thursday, May 18, 2023 at 3:35 PM
To: solgenomics/sgn ***@***.***>
Cc: Agre, Paterne (IITA) ***@***.***>, Assign ***@***.***>
Subject: Re: [solgenomics/sgn] Depositing new genotyping in the yam base (Issue #4408) Newsletter / Marketing

Has this problem been resolved? Can we close this ticket?
