### ISSUE TITLE
add time stamp information in downloaded traits 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#443]
Enable the download of the time stamps from the tablet when downloading phenotypic data/trials.
When available, Planting and harvesting date cvterm data should there too

**Comment by lukasmueller** [comment]
Upload and download needs to support time stamps. Field book timestamps need to be used for storing timestamps (not use the upload time, but the collection time is hugely important!!!)

**Comment by nickmorales** [comment]
takes care of upload b9eddc1b5e99643ea573e14068cd0caad53e0adb
