### ISSUE TITLE
Creating seedlots from trial summons spinning wheel of doom

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4431]
Trying to create seed lots for a field trial, but it is stuck on the spinning wheel of doom. Doesn't seem to be working.

![Screenshot from 2023-02-08 08-31-48](https://user-images.githubusercontent.com/36375878/217544848-9c640241-1fac-406f-93a7-51819d0bb70e.png)

This is a very small field trial.

**Comment by dwaring87** [comment]
@ch728 I created this tool and can look into this a bit more.  Can you check the server error log to see if there are any error messages displayed when you try to load the trial?

**Comment by ch728** [comment]
I didn't see any errors in the log; however, I realized that I have two trials that have tissue samples associated with them and those appear to be the only trials where the issue occurs. The tool seems to work with the other trials (at least the spinning wheel goes away and I have the option to continue, but I didn't follow through).

**Comment by lukasmueller** [comment]
Hi David, have you been able to reproduce this issue? Could this ticket be closed?
