### ISSUE TITLE
running analyses on musabse

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4453]
Expected Behavior 
--------------------------------------------------------------------------

Analyses jobs are not getting submitted to the analysis (cluster) server:

From the error log:
sgn.psgi: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
sgn.psgi: error: fetch_config: DNS SRV lookup failed
sgn.psgi: error: _establish_config_source: failed to fetch config
sgn.psgi: fatal: Could not establish a configuration source
Child process 450407 exited with status 1

For Bugs:
---------

**Comment by lukasmueller** [comment]
Analyses work now after installing correct slurm config file, but seem to be run on localhost instead of remote slurm host (according to config in sgn_local.conf)
