### ISSUE TITLE
Error when associating pictures to a trait from the ontology

### ISSUE THREAD

**Issue by pa279** [solgenomics/sgn#4470]
Expected Behavior 
--------------------------------------------------------------------------
Server Error
Our apologies, there was an error processing your request.

An error report has been sent to the development team. Feel free to contact the [development team](https://yambase.org/contact/form), if the problem persists, and we will keep you informed of our progress in resolving it.

For Bugs:
---------

**Comment by lukasmueller** [comment]
Could you send me an image so that I can test it?

**Comment by lukasmueller** [comment]
OK, I used a test image :-) 

I think the issue is fixed. The issue was that the image directory had inconsistent ownership. Fixed using 
```
sudo chown -R www-data:production /export/prod/public_yambase/images/image_dir/
```

**Comment by lukasmueller** [comment]
The image cannot be a pdf. This is stated incorrectly on the upload page. Should be removed.
