### ISSUE TITLE
Rep/Bloc overlapping in the yamBase

### ISSUE THREAD

**Issue by pa279** [solgenomics/sgn#4474]
Expected Behavior 
--------------------------------------------------------------------------
Please have a look at this trial 
https://yambase.org/breeders/trial/1255 
Three reps but all the 3 Rep are overlapping 

For Bugs:
---------

**Comment by bellerbrock** [comment]
I see what you're saying, the combination of row and column number should be unique for each plot, but looking at the layout file, each combination is duplicated three times [1255_layout.csv](https://github.com/solgenomics/sgn/files/11021163/1255_layout.csv)

There is no data loaded for the trial, so the easy fix is to delete it and re-upload a fixed layout file.

I wonder how it got this way though, the upload code is written to check for postion uniqueness in both [single](https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Trial/ParseUpload/Plugin/TrialExcelFormat.pm#L395) and [multitrial](https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm#L611) uploads. @pa279 do you know how this trial was loaded? If it was loaded through the web interface there must be some sort of error in those upload checks.

**Comment by bellerbrock** [comment]
Ok I just checked the single and multi trial uploads. They both throw warnings for overlapping plots as expected.
![warnings](https://user-images.githubusercontent.com/11297346/226621913-4f34d659-b247-498d-adab-bff744148ef1.png)

Someone must have overridden the warnings when uploading this trial.

**Comment by bellerbrock** [comment]
Ok, closing this issue. Fixed trial has been uploaded here: https://yambase.org/breeders/trial/1312
