### ISSUE TITLE
Cannot search for seedlots in Wizard

### ISSUE THREAD

**Issue by alockrow** [solgenomics/sgn#4500]
Expected Behavior 
--------------------------------------------------------------------------

If you try to search for seedlots in the wizard (/breeders/search), it hangs indefinitely and gives the following error: 

```
DBD::Pg::st execute failed: ERROR:  permission denied for view seedlots at /home/production/cxgn/sgn/bin/../lib/CXGN/BreederSearch.pm line 160.

[error] Caught exception in SGN::Controller::AJAX::BreederSearch->get_data "DBD::Pg::st execute failed: ERROR:  permission denied for view seedlots at /home/production/cxgn/sgn/bin/../lib/CXGN/BreederSearch.pm line 160."
```

For Bugs:
---------

**Comment by dwaring87** [comment]
I think this error might show up if the owner of the `seedlots` view is not `web_usr` (or whichever postgres user you're using for the website to connect to the db)

```
SELECT viewowner FROM pg_views WHERE viewname = 'seedlots';
```

**Comment by lukasmueller** [comment]
Hi David, would your ownership correction script fix this? I just confirmed that this is a problem on other sites as well. A dbpatch might be the more sustainable solution.

**Comment by dwaring87** [comment]
This would be the relevant part of the script:

```
ALTER TABLE public.seedlots OWNER TO web_usr;
```

You can check first to see if that fixes the problem.  Otherwise, you can try running the [whole script](https://github.com/TriticeaeToolbox/loading-scripts/blob/master/sql/web_usr_grants.sql) to see if there are other permissions problems.  I just updated it last week since we had a problem with a different table.

**Comment by bellerbrock** [comment]
[Found this typo](https://github.com/solgenomics/sgn/blob/f66e42f5892bab37d82eae2a0950d25e125623c1/db/00149/AddMissingSeedlotViews.pm#L291) in the latest patch that recreates the seedlot view, that might be the only issue.

**Comment by lukasmueller** [comment]
I also ran the ```ALTER``` statement manually on all the major databases, so we should be set for now.
