### ISSUE TITLE
`merge_stocks.pl` script fails due to `stock_allele` associations

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4512]
Expected Behavior 
--------------------------------------------------------------------------
If the 'bad' stock has associated loci stored in the `stock_allele` table, the merge script will fail when trying to remove the 'bad' stock:

```
Delete merged stocks ( -x option)...
Deleting stock WI_X8177-1 (id=106664)
An ERROR occurred (DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  update or delete on table "stock" violates foreign key constraint "stock_allele_stock_id_fkey" on table "stock_allele"
DETAIL:  Key (stock_id)=(106664) is still referenced from table "stock_allele". at ./merge_stocks.pl line 118
). Rolling back changes...
```

For Bugs:
---------

**Comment by dwaring87** [comment]
More details:

In this particular case, the CXGN::Stock merge function failed to merge two stocks because they had different pedigrees, but the merge script still tries to delete the 'bad' stock from the database.

Should the merge script exit with an error if the merge function fails?  Or should it skip the failed merge (and not attempt to delete the stock) and continue with the rest of the merges?

**Comment by bellerbrock** [comment]
[Here's the patch](https://github.com/solgenomics/sgn/blob/36637db6e326c51e2c0cb8361cb3f8190986585c/db/00158/AddCascadeDeletes.pm) that added missing cascade deletes. Looks like it didn't touch stock_allele table though.
