### ISSUE TITLE
Phenotype download from accession page doesn't work

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4515]
When I go to download data from an accession page

![Screenshot from 2023-04-25 12-22-50](https://user-images.githubusercontent.com/36375878/234342039-8abf0949-33a0-46d1-89f0-d3c3c9d4bf2b.png)

I get this error

![Screenshot from 2023-04-25 12-22-56](https://user-images.githubusercontent.com/36375878/234342015-2ad8fcb6-6e5f-4eb3-855c-3d533fbde32f.png)

**Comment by lukasmueller** [comment]
Fix in preparation via #4517.
