### ISSUE TITLE
Fix issues on accession and trial detail pages

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#452]
Is the plot list on the accession detail page really useful?
The trial list is loading too slowly (several minutes)
The trial list should be moved closer to the top of the page.
On plot detail page, the trial list should also appear.

**Comment by lukasmueller** [comment]
Add how many times this accession has been used (# plots) and in which years and locations.

**Comment by bellerbrock** [comment]
last issue, On plot detail page, the trial list should also appear. has been moved to ticket #459

**Comment by bauchetg** [comment]
Show accession popularity through a graph of trial in which its been involved over years
