### ISSUE TITLE
trial deletion is not deleting plots

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4525]
Expected Behavior 
--------------------------------------------------------------------------

Trial deletion from the trial detail page is not deleting associated plots. (Prasad).

For Bugs:
---------

**Comment by lukasmueller** [comment]
In the test database, the deletion works. What was the trial id of the reported trial? I can then check the deletion process of that trial in an old database dump.

**Comment by isaak** [comment]
@pvnsprasad may remember...

**Comment by lukasmueller** [comment]
Could not reproduce... closing this issue for now, re-open if it re-occurs.
