### ISSUE TITLE
accession download only working one trait at a time

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4530]
Expected Behavior 
--------------------------------------------------------------------------

The download dialog collapses the section with the trait select by default, which is confusing. When expanded, it says to select 'none' to download all traits. But none is not showing as an option.

![dropdown](https://user-images.githubusercontent.com/11297346/236867417-168d2d86-7a5f-40f5-9492-32b33c3e5e66.png)

For Bugs:
---------

**Comment by darekbienkowski** [comment]
https://github.com/solgenomics/sgn/pull/4533
