### ISSUE TITLE
Create an option to store pdf or docx in accession details page

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4549]
Expected Behavior 
--------------------------------------------------------------------------

Currently, there are two options to store literature in accession's detail page (publications or ontology). In some cases there are local information about the accession that would be important to be stored.

![image](https://github.com/solgenomics/sgn/assets/51970212/fc4746bf-d80c-48c1-ae63-d5c4e031eefb)

For Bugs:
---------

**Comment by lukasmueller** [comment]
The trial detail page I think has a feature to upload any file to it, so this could use the same code

**Comment by lukasmueller** [comment]
How far along is this feature? I think there are a lot of use cases where this could be useful...

**Comment by MFlores2021** [comment]
Duplicated #3804

**Comment by lukasmueller** [comment]
Hi Chris, I am assigning this to critical because many people ask for it. Could we have a look during the Monday Openthon to finish it asap?
