### ISSUE TITLE
the /stock/{id}/datatables/traitlist AJAX call often crashes

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#456]
May be due to bad data in the database for certain traits.

**Comment by bellerbrock** [comment]
stock id 39629 is causing problems

**Comment by nickmorales** [comment]
this should fix it 4dfca45ba162786292a8d3f6b051fd499de61953

**Comment by nickmorales** [comment]
that commit is in cxgn-corelibs repo https://github.com/solgenomics/cxgn-corelibs/commit/4dfca45ba162786292a8d3f6b051fd499de61953
