### ISSUE TITLE
Seedlot upload needs to support for removing the amount

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4575]
Expected Behavior 
--------------------------------------------------------------------------
Currently, the upload resets the weight/count to the value by creating a transaction that results in that weight/count
This is useful. 
Need to implement a checkbox that will subtract that count/weight

For Bugs:
---------

**Comment by lukasmueller** [comment]
It may already exist!

**Comment by alockrow** [comment]
Currently you can add or subtract weight or number of seeds from a seedlot under Manage/Seedlots: Add New Transaction. Is this sufficient or should this functionality also be available in the upload section? 
![image](https://github.com/solgenomics/sgn/assets/26778258/d8dbd445-f90b-4f82-9054-f7c61dea5a49)

**Comment by lukasmueller** [comment]
Is this part of the uploads that Titima implemented? If so, it can be closed.
