### ISSUE TITLE
A BrAPI v1 call generating error 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4578]
Expected Behavior 
--------------------------------------------------------------------------
Argument "" isn't numeric in addition (+) at lib/CXGN/BrAPI/v1/Germplasm.pm line 134.
Argument "" isn't numeric in addition (+) at lib/CXGN/BrAPI/v1/Germplasm.pm line 134.
Argument "" isn't numeric in addition (+) at lib/CXGN/BrAPI/v1/Germplasm.pm line 134.
Argument "" isn't numeric in addition (+) at lib/CXGN/BrAPI/v1/Germplasm.pm line 134.
CXGN::Stock::Search search start

For Bugs:
---------

**Comment by MFlores2021** [comment]
@isaak I couldn't replicate the error but I think #4606  will fix it. 
Please can you review and confirm?

**Comment by isaak** [comment]
The error occurred in cassavabase and I happened to see in the log. I did not know what was causing it. But I came across it at least on two occasions (different days). I will keep an eye if it recurs.
