### ISSUE TITLE
Remove duplicate CXGN::Genotype::Search

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#4587]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by titima15** [comment]
Please check pull request #3988

**Comment by ClayBirkett** [comment]
Can you describe the problem in more detail? What is being duplicated?

**Comment by titima15** [comment]
Please see the pull request #3988. In addition in to the modification in lib/CXGN/Genotype/Search.pm, there is a new file (Search.pm), which is a copy of lib/CXGN/Genotype/Search.pm

**Comment by titima15** [comment]
closed via 8352055
