### ISSUE TITLE
On plot detail page, the trial list should also appear

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#459]

**Comment by bellerbrock** [comment]
jbrowse and pedigree sections should be hidden and trial list section that doesn't work should simply be the trial name

**Comment by nickmorales** [comment]
trials will now show up on stock detail page for all stock types https://github.com/solgenomics/cxgn-corelibs/commit/9ea523c52d9072ca8ca04e26b76f4e767cf484b5

**Comment by bauchetg** [comment]
Trial type contain duplicates in the list like:
Preliminary Yield Trial
Preliminary Yield Trial_s_ 
etc...
