### ISSUE TITLE
Does breedbase have support for repeated measures?

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4601]

**Comment by lukasmueller** [comment]
Hi Chris, sorry for the late reply. Currently, the recommended way to take repeated measurements is to post-compose a trait with the time ontology. This will create a new term for each timepoint. In most cases, likely you would like to compare a timepoint to the other equivalent timepoints, so this scheme is good for that use case. Sometimes you would like to draw growth curves etc, so measurements with associated timestamps would be the best. Currently, we are working on implementing that. Let me know if you have any other special use cases in mind.

**Comment by ch728** [comment]
Hi Lucas, I am interested in disease progress (disease scores over time) and repeated measures of yield in vegetables like zucchini. Timestamp associated with the measurement is really what I am interested in for both.  It is implemented in FieldBook, so we started using that feature. I will keep an eye out for when it is implemented in Breedbase so we can store the data in the database.

**Comment by lukasmueller** [comment]
Hi Chris,

The values are stored in the database when you use fieldbook, but I think currently they are not correctly retrieved. We can definitely work on that if that's a feature you actively use.

cheers
Lukas
________________________________

**Comment by jeanlucj** [comment]
The Triticeae Toolbox (T3) has users who would like to be able to retrieve phenotypes in "long format" with the time stamp.  The format would include columns that identify the observation unit (trial, plotID, accession, ...), a column specifying the trait, a column with the time stamp, and a column with the trait value.  Only one trait value per row of output.  And a time stamp for each row of output.  If all time stamped values can be retrieved from the database and put into that format, that would be nice.
The behavior of the GUI would be that the phenotype download dialogue would have a checkbox for if you wanted data downloaded in "long format".  If you checked that, you would get what I describe above.  Else you would get the usual matrix that is the default now.
Thanks!
