### ISSUE TITLE
Label Designer: Support more than one Trial

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4604]
Expected Behavior 
--------------------------------------------------------------------------

We've received a number of requests for the label designer to be able to print plot-level labels for more than one trial at once.

The input source could be either a list of plots or a list of trials.

The labels should then be printed in a user-defined sort order:
  - trial name
  - plot number
  - row position
  - col position

For Bugs:
---------

**Comment by dwaring87** [comment]
I've started working on this in the [topic/label_designer_improvements](/TriticeaeToolbox/sgn/tree/topic/label_designer_improvements) branch

**Comment by lukasmueller** [comment]
Didn't we merge something related to this? Can this ticket be closed?

**Comment by dwaring87** [comment]
This will be fixed once PR #4623 is merged.  I'll have to merge master into the feature branch to see if the tests will pass now that the Docker image has been updated.
