### ISSUE TITLE
link weather db to cassavabase

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#461]

**Comment by bellerbrock** [comment]
Working on this, one caveat is that it requires cross origin resource sharing to retrieve locations from weather.rtbbase.org/rest/locations. 

To enable this, I've updated the apache2 server conf for rtbbase.org to enable mod_headers, and then added 'Header Set Access-Control-Allow-Origin "*"' to the weather.rtbbase.org virtualhost in the /etc/apache2/sites-availaible/default conf file. This way it's possible to retrieve the locations with weather data available before displaying a link on trial detail pages.

**Comment by lukasmueller** [comment]
Link needs to be updated as we have moved rtbbase to https it should work now.

**Comment by lukasmueller** [comment]
I think this is not yet working correctly... Could this be moved up in the priority queue?
