### ISSUE TITLE
Create a field view with multiple trials

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4611]
Expected Behavior 
--------------------------------------------------------------------------

Currently, it is only possible to view one trial per location. The idea here would be to provide the visualization of all trials in a specific area (farm). It would also allow the creation of "field management factors" for the area (this would include all trials in that area).

Then, it should generate view like that:

![Screenshot from 2023-08-04 12-29-02](https://github.com/solgenomics/sgn/assets/51970212/cd914543-ffd8-4f81-b576-934fe3b99b6b)

For Bugs:
---------

**Comment by dwaring87** [comment]
This is something we've been wanting for T3 as well.  I worked on the plot map on the trial detail page so it can display plots from more than one trial *if the row and col positions are unique across trials* (ie trial 1 starts at row 1, trial 2 starts at row 10, etc).  Right now we don't have any way of linking the individual trials together into the same physical field, so it doesn't know which additional trials to pull from the DB.

**Comment by chris263** [comment]
Maybe, if create an way to store geo coordinates for the 4 corners in each trial (In this case they don't need to store coordinates for all plots). Then, if possible adjust rows and columns inside those coordinates.
The second point is about management factors. If there is an way to add management factors per locations (including many trials) it will help.

**Comment by MFlores2021** [comment]
fixed in https://github.com/solgenomics/sgn/pull/4620
