### ISSUE TITLE
Genotyping List Inconsistencies

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4649]
Expected Behavior 
--------------------------------------------------------------------------

In the List Manager:

- You can create a list of type "genotyping_trials" - are these genotyping protocols or projects?
- A list of genotyping projects fails validation
- A list of genotyping protocols also fails validation

In the Search Wizard:

- If you select an existing list of genotyping projects or protocols you get an error: "List is not of an appropriate type."
- If you create a list of genoyping projects or protocols directly in the Search Wizard - the list type is set to "null" and the lists do not work if you try to use them later (same error as above) 

For Bugs:
---------

**Comment by titima15** [comment]
genotyping trials are genotyping plates (we should change the name). No list type for project and protocol

**Comment by titima15** [comment]
Just wanted to be sure,  your 'genotyping experiment' is the 'genotyping project', right?

**Comment by jeanlucj** [comment]
Yes, that's right.  Thanks.

**Comment by lukasmueller** [comment]
fixed in #4657.
