### ISSUE TITLE
Histogram is crashing when management factors are present

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4663]
Expected Behavior 
--------------------------------------------------------------------------

If management factors are added to a field trial, then histogram crashes.

The trial with no management factors:

![Screenshot from 2023-09-20 14-25-19](https://github.com/solgenomics/sgn/assets/51970212/01a7f502-4444-4325-a39a-b93afd64795f)

After adding management factors: 

![Screenshot from 2023-09-20 14-28-02](https://github.com/solgenomics/sgn/assets/51970212/f6be2e9c-172f-485a-9a49-7d65ca4399a9)

For Bugs:
---------

**Comment by isaak** [comment]
Hi Chris, could you share a link to a trial where this happens?

**Comment by chris263** [comment]
Hi Isaak, this is happening in a few trials in citrusbase. I was able to reproduce the error locally, we just have to add a management factor to a existing trial. (The trial must have pheno data in plot level and then create management factors also in plot level).

**Comment by chris263** [comment]
https://citrusbase.breedinginsight.net/breeders/trial/218?format=

**Comment by chris263** [comment]
This pull request solves the problem https://github.com/solgenomics/sgn/pull/4719
