### ISSUE TITLE
Add xlsx format option to pedigree upload

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#4671]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by ch728** [comment]
This would be very helpful! Explaining to staff the difference between an "Excel file" and a tab-delimited file can be very difficult. Also would improve user experience to have a consistent file type for uploads. I believe this is one of the few tab-delimited uploads left in the system.

**Comment by titima15** [comment]
@ch728 I will change priority for this ticket to high. Hopefully I can start working on it early next week.

**Comment by dwaring87** [comment]
@titima15 Have you started working on this?  If not, I've started working on a [Generic Data File Parser](https://github.com/solgenomics/sgn/issues/4975) that would support csv, tab-delimited, and excel files that could be used for the different file uploads.

**Comment by titima15** [comment]
@dwaring87 Yes, I'm working on it and it's almost done. However, If you are going to finish that File Parser soon. We can use that for pedigrees as well.

**Comment by dwaring87** [comment]
@titima15 Sorry, I should have started this sooner!  The file parser is working now, I've just updated the locations upload as an example (in the topic/generic_file_parser branch).  Would you like me to convert the pedigree upload to this or would you like to give it a try?

**Comment by titima15** [comment]
@dwaring87 No problem. Yes, I would like to give it a try. I will be traveling Monday and Tuesday. I will take a look after I get back. Thanks.

**Comment by dwaring87** [comment]
@titima15 Great, here is the [Location upload](https://github.com/solgenomics/sgn/blob/topic/generic_file_parser/lib/CXGN/Location/ParseUpload/Plugin/LocationsGeneric.pm) I just converted if you want to use that as an example.  Let me know if you have any questions using it.

**Comment by titima15** [comment]
Done via #5037
