### ISSUE TITLE
Add static text to a label in LabelDesigner

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4682]
Expected Behavior 
--------------------------------------------------------------------------
Add the ability to add static text to a label in LabelDesigner

For Bugs:
---------

**Comment by dwaring87** [comment]
You can currently do this with the "Create Custom Field" function and not adding a variable

**Comment by lukasmueller** [comment]
Amazing!
________________________________

**Comment by lukasmueller** [comment]
Closing this ticket.
