### ISSUE TITLE
Error in additional file - Accession details page

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4699]
Expected Behavior 
--------------------------------------------------------------------------

![image](https://github.com/solgenomics/sgn/assets/51970212/76fd7ee2-3427-4e5f-9317-18afe754cb6e)

It is not showing additional files.

For Bugs:
---------

**Comment by darekbienkowski** [comment]
Is the system/server updated for that merge? ( I don't have access to it.)

[#4688](https://github.com/solgenomics/sgn/pull/4688)

This means:
- merged branch
- updated solgenomics/Phenome
- updated all db_patches with 00179
- the system is rebuilt and reloaded

I cannot replicate bug / problem on docker 0.90 with cxgn_fixture
Everything works fine on master with docker 0.90 and cxgn_fixture.

![Screenshot from 2023-10-20 13-25-06](https://github.com/solgenomics/sgn/assets/7416921/240c5432-e3fd-4ef2-9549-1b22e2533ee2)

![Screenshot from 2023-10-20 13-25-17](https://github.com/solgenomics/sgn/assets/7416921/927d59ed-7441-45d3-89ea-399f353d9396)

![Screenshot from 2023-10-20 13-25-28](https://github.com/solgenomics/sgn/assets/7416921/e771f7b0-9a68-43e0-9957-6bde68bed741)

**Comment by chris263** [comment]
I updated all patches in cassavabase.org, it solved the problem.
