### ISSUE TITLE
Zero values are stored the same as undef values in trait uploads

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#470]
Zero values need to be represented as 0 whereas undef values need to be undef (currently both seem to be undef) in trait uploads

**Comment by bauchetg** [comment]
Trait value handling, example: 	cassava mosaic disease incidence 1-month evaluation for 2015-GSpyt88IB trait with 0 value are not displayed (showed as missing). See ontology
https://cassavabase.org/chado/cvterm?action=view&cvterm_id=70743
Works fine in: 12geneticgainUB

**Comment by nickmorales** [comment]
values with 0 are being stored as 0 and empty values are just not stored at all.
if you check the histogram, you will see the 0 values.
if you click download trait data, it is writing the 0's as empty though, so i can fix that.

Where did you notice this?

**Comment by nickmorales** [comment]
I think there are issues with the phenotype download because it only returns one value for each trait and plot (even if there are many) and it writes 0 as empty.

**Comment by lukasmueller** [comment]
Hi Nick,
it should retrieve all the values, and report zero as zero... Should be an easy fix?

**Comment by nickmorales** [comment]
Hi Lukas
Is the phenotype download the only place this has been seen?

**Comment by nickmorales** [comment]
printing of 0 values in phenotype download fixed here fac34c287275545bbce6016040703cdd3d992f6f
