### ISSUE TITLE
Ontology browser page should include pictures of scale/measurements when available

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#471]

**Comment by lukasmueller** [comment]
Ask Peter for images for cassava

**Comment by nmenda** [comment]
Peter says they need to assign someone. I'm following up with him

**Comment by bellerbrock** [comment]
For sweetpotatobase, this is the book with descriptors and keys that the community says they use:

http://www.bioversityinternational.org/uploads/tx_news/Descriptors_for_sweet_potato_Descripteurs_pour_la_patate_douce_Descriptores_de_la_batata_263.pdf

**Comment by bauchetg** [comment]
I got the list of descriptors and pictures from Ismail for disease evaluation and general cassava characterisation forward this to you Naama

**Comment by nmenda** [comment]
both files are PDF, we will have to extract the images from them

**Comment by nmenda** [comment]
for now I'm extracting images from the PDFs and will have them stored in metadata.md_image_cvterm 
will need a db patch for this and ajax div in chado/cvterm.mas
