### ISSUE TITLE
outlier cutoff slider step size

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4710]
Expected Behavior 
--------------------------------------------------------------------------

-- the outlier cutoff slider step size is now 0.5. It would add more flexibility in deciding outlier cutoff, if it is smaller, e.g. 0.2 - 0.25. It will allow a cutoff at ~2.7 STD from the mean, which is equivalent to the common 1.5*IQR approach.

-- add the 1.5*IQR option

For Bugs:
---------

**Comment by lukasmueller** [comment]
fixed in #4767
