### ISSUE TITLE
Trial detail page download format change

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#472]
Field trial download gives just plot_ID and phenotypes whereas the wizard gives a full informations set. We should align the trial page output on the wizard output
-sort phenotype according to ontology number and instead of the trait full name we may display the synonym and the CO term.
-generally  outputs should include trait data + trial metadata (trial info and traits correspondance (syn-full name-trait code). This could be one single file with different sheets (data+ metadata)

**Comment by nickmorales** [comment]
trial download now uses the _extended function fac34c287275545bbce6016040703cdd3d992f6f
