### ISSUE TITLE
QBMS: data download from cassava 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4723]
Expected Behavior 
--------------------------------------------------------------------------
From Xiaofei (CIAT):

We have been using QBMS to download data from CassavaBase, which facilitates the standardization of the data analysis pipeline. 

After a while, when I came back to re-run the code, I encountered the errors below. 

I updated all my packages. The problem was not fixed. 

I am using macOS Ventura version 13. I did not find the solution after google searching and chatGPT. 

Can you please help me out?

> library(QBMS)
> # Cassava BreedBase server

> set_qbms_config(https://cassavabase.org/brapi/v1/calls/,
 path = "", time_out = 300, no_auth = TRUE,
page_size = 10000,
engine = "breedbase")
> # list supported crops in the current bms server

> list_crops()

Error: 'synchronise' is not an exported object from 'namespace:async'

For Bugs:
---------

**Comment by isaak** [comment]
Resolved by installing a missing R package: `remotes::install_github("r-lib/async")`

**Comment by lukasmueller** [comment]
Does this have to be installed on the user's computer or the server?

**Comment by isaak** [comment]
On the user's computer.
