### ISSUE TITLE
Genotype Protocols are not showing up in Wizard when filtering per Projects

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4736]
Expected Behavior 
--------------------------------------------------------------------------

Wizard > Breeding Program > Genotype Projects > Protocols

There is a protocol associated with the project soybase_nov2023. However, it is not showing up in wizard. I've refreshed the view.

![Screenshots02](https://github.com/solgenomics/sgn/assets/51970212/b39f17ea-2972-432b-b575-79943eb25e54)

For Bugs:
---------

**Comment by isaak** [comment]
Running refresh_matviews.pl (from the cli) seems to fix the hung up call (in the cassava sites at least) from the web interface and fix the issue...
