### ISSUE TITLE
sort brapi studies call results by most recent

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#4752]
Expected Behavior 
--------------------------------------------------------------------------

Right now it the studies seem to be sorted by name, in ascending order. Showing the most recently created trials first (which could be done by sorting by descending DbId for example) would be helpful at least for users importing fields to fieldbook.

For Bugs:
---------

**Comment by MFlores2021** [comment]
@bellerbrock  I added the sort by feature to studies call.  You should be able to pass sortBy studyDbId as parameter for the study.
