### ISSUE TITLE
Show only phenotyping trials in Manage Trials tree

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#476]
No crosses or genotyping trials

**Comment by bellerbrock** [comment]
Hey Nick, I noticed this problem during the workshop, and one of the participants, Ernest, reported it too. We made crosses, and they all showed up in the trial tree and confused people. 

Do think it is something we can fix before the next workshop this coming Wednesday?

**Comment by bellerbrock** [comment]
Oh, and here's an example on sptest: 
![screenshot from 2016-05-27 17 42 59](https://cloud.githubusercontent.com/assets/11297346/15616446/5b190060-2433-11e6-933d-2ae127f2dde5.png)

**Comment by nickmorales** [comment]
that should be an easy fix. i think i can do it before wednesday

**Comment by bellerbrock** [comment]
Awesome, thanks Nick!

On 27 May 2016 at 17:53, Nick Morales <notifications@github.com> wrote:

> that should be an easy fix. i think i can do it before wednesday
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/solgenomics/sgn/issues/476#issuecomment-222211933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKxiQp5cOUEiRiXEksYHAhh3kPlH2Mnnks5qFy-igaJpZM4IcNNs>
> .
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868
