### ISSUE TITLE
Phenotype data cannot be overlaid on fieldmap

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4760]
Expected Behavior 
--------------------------------------------------------------------------

Fieldmaps are back but phenotypes cannot be overlaid on the map

When selecting a trait, the javascript fails with the following error:

jQuery.Deferred exception: d3.scale is undefined value@https://ingredion-corn.breedbase.org/js/build/chunk.ac98bc6c0881d6509918.js:1:54381

For Bugs:
---------

**Comment by isaak** [comment]
fixed #4762

**Comment by darekbienkowski** [comment]
solved
