### ISSUE TITLE
Pedigree Viewer: Scaled Too Small

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4771]
Expected Behavior 
--------------------------------------------------------------------------

We have some instances where the pedigree viewer is off-center and too small

![image](https://github.com/solgenomics/sgn/assets/7526014/5e5376bc-bcb1-4a6b-874c-9e015b141818)

![image](https://github.com/solgenomics/sgn/assets/7526014/a631f6ce-03fd-4843-b5d1-61aa232ab78a)

For Bugs:
---------

**Comment by darekbienkowski** [comment]
https://github.com/solgenomics/sgn/pull/4798
