### ISSUE TITLE
SGN: user profile page is blank

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#4776]
Expected Behavior 
--------------------------------------------------------------------------

![image](https://github.com/solgenomics/sgn/assets/163702/8dfeb1f6-c5e1-4f5a-a40b-7186335d163d)

For Bugs:
---------

**Comment by lukasmueller** [comment]
It works for me... what does the error log say when you open it?

**Comment by lukasmueller** [comment]
Could you figure out what causes this in your instance? I think it might be a section on that page, such as analyses or background jobs, that could affect the display of the page.

**Comment by isaak** [comment]
Nothing helpful in the sgn error log or my browsers.

**Comment by lukasmueller** [comment]
Is this still an issue?

**Comment by isaak** [comment]
Since, nobody else has reported this, may be it is something about my setting....
