### ISSUE TITLE
Population details page doesn't have information about accessions in the population

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#4786]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by bellerbrock** [comment]
https://github.com/solgenomics/sgn/blob/8a8955f8935977dc237e0303651bc58f5acfe896/mason/stock/index.mas#L288 Could add population to the type_names checked in this line, but showing the contents in a dedicated uncollapsed section would be even better.

**Comment by titima15** [comment]
Done via #4947
