### ISSUE TITLE
Add new trial types

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4803]
Expected Behavior 
--------------------------------------------------------------------------
Requested trial types:
Stage 1
Stage 2
Stage 3
Stage 4
First Clonal
Second Clonal

For Bugs:
---------

**Comment by lukasmueller** [comment]
The trial types can be individually tailored to the group using a specific instance. Some trial types should not be changed as the system relies on them for displaying information, such as genotyping_trial

**Comment by lukasmueller** [comment]
Add these terms to sugarcanebase

**Comment by chris263** [comment]
Trail types added successfully!
