### ISSUE TITLE
sugarcanebase, citrusbase: disallow new user accounts for web interface

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4814]
Expected Behavior 
--------------------------------------------------------------------------
there is a setting for that to send it to curator accoutn for confiirmation

For Bugs:
---------

**Comment by dwaring87** [comment]
These are the setting in the config file that can be used to send the confirmation emails to one or more admins instead of the users:

```
user_registration_admin_confirmation 1      # when enabled, the new user confirmation message will be sent to the address(es) below instead of the user
user_registration_admin_confirmation_email  # a comma-separated list of email addresses to send new user confirmation messages to, when the above is enabled
```

The users won't be able to sign in until the accounts are confirmed

**Comment by chris263** [comment]
Thanks @dwaring87 !
