### ISSUE TITLE
Upload genotyping data into Cassavabase

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4819]
Expected Behavior 
--------------------------------------------------------------------------
As requested by Prasad

Submission 18 DArTseqLD: [https://www.dropbox.com/t/7rRmj0FjRlDJYGKH](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Ft%2F7rRmj0FjRlDJYGKH&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847045259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=I452DFqUof2Pavnf5rQ434IsHJpWXqr3drCxzXjnIuY%3D&reserved=0)
        These are mainly CET 1600 (TMS 21 series)
        Intertek order form : [https://www.dropbox.com/scl/fi/xbp4a3do7o5lo66h5uyyr/Intertek-Order-form-SNP-Genotyping-Services..xls?rlkey=c28nkp2mjdd4seasl61k8drcd&dl=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2Fxbp4a3do7o5lo66h5uyyr%2FIntertek-Order-form-SNP-Genotyping-Services..xls%3Frlkey%3Dc28nkp2mjdd4seasl61k8drcd%26dl%3D0&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847053800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xOBxe0h9umQhVxvdL5872dbTSOq42WyP3Jsr321sd1g%3D&reserved=0)

 

    Submission 20 DArtSeqLD: [https://www.dropbox.com/t/IVFcOAwNdUZlkNPq](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Ft%2FIVFcOAwNdUZlkNPq&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847060415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=dO%2BeOFKN8XHrX4PnnNR70%2F7C1W0HxYyX4PkrqYI3N78%3D&reserved=0)
        These are fresh market product profile trials in Abuja (22SeedlingNurseryAB, 22.PD.PYT.12.AB and 22.PD.PYT.12.AB)
        Intertek order form : [https://www.dropbox.com/scl/fi/vjqh2c6atdw9a01i10e1f/Intertek-Order-form-SNP-Genotyping-Services_IITA_Oct22_16-plates.xls?rlkey=bggrv9uijg0e7e31e8po7id31&dl=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2Fvjqh2c6atdw9a01i10e1f%2FIntertek-Order-form-SNP-Genotyping-Services_IITA_Oct22_16-plates.xls%3Frlkey%3Dbggrv9uijg0e7e31e8po7id31%26dl%3D0&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847066249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZEGJKBX%2FhMwdGL7%2BJ9OX9M8BBLFEzmCNrxBgHibYXU4%3D&reserved=0)

 

    Submission 23 DArtSeqLD: [https://www.dropbox.com/t/u2zCVDa8QdGB16F8](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Ft%2Fu2zCVDa8QdGB16F8&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847071661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2%2B00xb2OESsZ9gnYtlSFJW8dPIYa0Y7pKERU6dELkFI%3D&reserved=0)
        These are HarvestPlus population (Seren’s trials)
        Intertek order form : [https://www.dropbox.com/scl/fi/se33mvrjk65bszsvmg4co/Intertek-Order-form-SNP-Genotyping-Services.xls?rlkey=bcrnxmh4d3hhz0djc78kcqbns&dl=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2Fse33mvrjk65bszsvmg4co%2FIntertek-Order-form-SNP-Genotyping-Services.xls%3Frlkey%3Dbcrnxmh4d3hhz0djc78kcqbns%26dl%3D0&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847076677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=X2IC5eyE7MhzJ59q8jHtGm%2Fmol19%2BA45FrFVMzd7%2Fw8%3D&reserved=0)

 

    Submission 25 DArTSeqLD: [https://www.dropbox.com/t/kwUcS93FXV6TkLGx](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Ft%2FkwUcS93FXV6TkLGx&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847081770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4ZG%2F3WqNWKTxzyJRfwXJcX8cFNRsVBFtifUSfv%2F1CBw%3D&reserved=0)
        These are mainly 22.GS.C7.CE.1360.IK (TMS22) + 23.GS.C8.SN.IB (TMS23)
        Intertek order form: [https://www.dropbox.com/scl/fi/sgetax7dmux6pk82rihcf/Intertek-Order-form-SNP-Genotyping-Services.xls?rlkey=ikgk056m1b81ht3dxerxecqco&dl=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2Fsgetax7dmux6pk82rihcf%2FIntertek-Order-form-SNP-Genotyping-Services.xls%3Frlkey%3Dikgk056m1b81ht3dxerxecqco%26dl%3D0&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847088528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=lLzBb2M6R1rs6pQPvlCdJfY8Dj%2F2l1qRYDZvyvsAxTE%3D&reserved=0)

 

    Submission26 DArTseqLD: [https://www.dropbox.com/t/u8XaJEE0rnbYvNNh](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Ft%2Fu8XaJEE0rnbYvNNh&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847094478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=s97fjRPfPxY53hX0VA2gVS1qeVfuYQlYnwAr%2BGentes%3D&reserved=0)

a.      These are mainly continuation of submission 25 i.e., 22.GS.C7.CE.1360.IK (TMS22) + 23.GS.C8.SN.IB (TMS23) and some Harvest plus trials.

b.     Intertek order form: [https://www.dropbox.com/scl/fi/qgfadxu5jdo8tgby6b7si/Intertek-Order-form-SNP-Genotyping-Services.xls?rlkey=lvju4le1dln053yzzsgfl7mj0&dl=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2Fqgfadxu5jdo8tgby6b7si%2FIntertek-Order-form-SNP-Genotyping-Services.xls%3Frlkey%3Dlvju4le1dln053yzzsgfl7mj0%26dl%3D0&data=05%7C02%7Clam87%40cornell.edu%7C6c0f4d8dc4a9498e715b08dc2e0d0a98%7C5d7e43661b9b45cf8e79b14b27df46e1%7C0%7C0%7C638435881847099955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=K21pMjIU%2B%2FpS6uSCjwXWSN%2FFgZqc4jJKVDIe7oEIbx4%3D&reserved=0)

For Bugs:
---------

**Comment by isaak** [comment]
All uploaded.
