### ISSUE TITLE
Make sure all data (such as archive dirs etc) have been transferred

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4823]
Expected Behavior 
--------------------------------------------------------------------------
For the onramp hosting, make sure all the auxiliary file-based data is also transferred

For Bugs:
---------

**Comment by chris263** [comment]
Maybe we should quickly walk through this. I am not sure which archive should I transfer. The aws server is very clean.

**Comment by chris263** [comment]
All files are transferred!
