### ISSUE TITLE
In move trial to a folder, alphabetize the list of folders and the list of trials

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4831]
Expected Behavior 
--------------------------------------------------------------------------
On the manage trials page, when moving a trial to a folder, the lists are not alphabetized. It's difficult to find the trials/folders because of that. As reported by Valerie.

For Bugs:
---------

**Comment by titima15** [comment]
Trials already sorted, need to fix only folders. Done, included in tracking tool
