### ISSUE TITLE
Solgenomics contact form not working

### ISSUE THREAD

**Issue by Sri-2023** [solgenomics/sgn#4840]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
The token in GitHub had to be renewed. 
A way to check whether the authentication works:
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: token <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/issues/ISSUE_NUMBER/comments \
  -d '{"body":"Me too"}'
