### ISSUE TITLE
Create Seedlots from a trial  with "plot_name"

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4843]
Expected Behavior 
--------------------------------------------------------------------------
Currently:

Options to create a template for a seedlot are: trial_name, accession_name, plot_number,  rep, block, index

@titima15 , would be possible to add plot_name? 

![seed_lots](https://github.com/solgenomics/sgn/assets/51970212/452f8ac1-b0ab-4e1f-bb15-1f57f2cbbe6d)

For Bugs:
---------

**Comment by titima15** [comment]
This was implemented by @dwaring87

**Comment by dwaring87** [comment]
Yes, I can take a look at this.  One thing to note, you won't be able to use just the plot name since you can't have two stocks (plot and seedlot) using the same name.
