### ISSUE TITLE
reconstruct obo file from cvterm tables and allow curator to download

### ISSUE THREAD

**Issue by keocorak** [solgenomics/sgn#4850]
Feature request: 

Script to reconstruct obo file from species ontology terms in cvterm tables. Additionally, add radio button to front end ontology tab that allows user/curator to download file. 

@bellerbrock and I were discussing this the other day related to issues tracking down the original obo files for sugarcane and citrus bases

**Comment by chris263** [comment]
Hey Keo, there is already a ticket for that: https://github.com/solgenomics/sgn/issues/4380 
Maybe we should close this to avoid duplications?

**Comment by keocorak** [comment]
You're right, sorry I checked for duplicates but missed it
