### ISSUE TITLE
Existing synonyms are removed when uploading existing accessions

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/sgn#4852]
Expected Behavior 
--------------------------------------------------------------------------

When uploading an accession template containing previously stored accessions, any previously stored synonyms will be removed and only the ones in the template will be stored.

This is a change in behavior.  Previously, when uploading existing accessions, any existing synonyms will be kept and new ones will be added.

The deletion is here in the `CXGN::Stock::Accession->store()` function:
https://github.com/solgenomics/sgn/blob/330872458b44691a473cf954726dbfa186d15f01/lib/CXGN/Stock/Accession.pm#L422-L427

For Bugs:
---------

**Comment by nmenda** [comment]
add a function for replacing the existing synonyms or appending the synonyms from the file
