### ISSUE TITLE
Add new genotype facilities

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4871]
Expected Behavior 
--------------------------------------------------------------------------
This request to add new genotype facilities comes from blueberry breeders at NCSU.

These are the names of the requested facilities.
AgBiotech
ArborScience
AgriPlex
RapidGenomics(LGC)
NCState_GSL
UC-Davis-Genome-Core

If more information is needed to add them, let's keep it posted here.

For Bugs:
---------

**Comment by kristenlkoehler** [comment]
Is any additional information needed for this?

**Comment by MFlores2021** [comment]
@chris263 customized  facilities can be added to the blueberry server in the sgn_local.conf using `genotyping_facilities` keyword
