### ISSUE TITLE
Add an option to upload multiple images at once

### ISSUE THREAD

**Issue by Sri-2023** [solgenomics/sgn#4872]
Expected Behavior 
--------------------------------------------------------------------------

![image](https://github.com/solgenomics/sgn/assets/122313818/671b2f47-69c1-42b5-9231-2dbb91fc997d)

For Bugs:
---------

**Comment by ch728** [comment]
FYI, I don't think this is an issue anymore. It's currently possible to select multiple images from that interface and upload them all at once.
![image](https://github.com/user-attachments/assets/129f43ce-851f-4b57-ac86-b1c65f04a9a7)

**Comment by Sri-2023** [comment]
Am closing this ticket, as we already have this feature in BB !!!
