### ISSUE TITLE
create a copy of sugarcane datanbase without the current trials

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4873]
Expected Behavior 
--------------------------------------------------------------------------
contact: Keo

For Bugs:
---------

**Comment by lukasmueller** [comment]
Has this been done?

**Comment by chris263** [comment]
Not yet, can we work on that tomorrow at our meeting?

**Comment by lukasmueller** [comment]
Done! The website is called sugarcane-industry.breedbase.org and the database is on db9, called cxgn_sugarcane_florida (we should change this to match!).
