### ISSUE TITLE
fieldbook phenotype file does not download immediately when file is created

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#488]
Or if the file is not supposed to be downloaded immediately, redirect user to /fieldbook page where the file is downloadable from

**Comment by bauchetg** [comment]
fromtrial detail page, the "create fieldbook spreadshhet" should point to the "manage", "fieldbook" page while creating the spreadsheet. Adding spinning wheel.

**Comment by bellerbrock** [comment]
Nice fix!

On 31 May 2016 at 15:53, Nick Morales <notifications@github.com> wrote:

> Closed #488 <https://github.com/solgenomics/sgn/issues/488> via f58358e
> <https://github.com/solgenomics/sgn/commit/f58358e8287e0ad075c0dd3123268bc32b57b358>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solgenomics/sgn/issues/488#event-677213408>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKxiQg53TS1Bu6c2DMDwEZGx_2-t_kUfks5qHFl2gaJpZM4IiNrL>
> .
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868
