### ISSUE TITLE
fix user trait addition issues

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4891]
Expected Behavior 
--------------------------------------------------------------------------
When user trait addition is enabled (in sgn_local.conf) it errors out when users are trying to add a new term

For Bugs:
---------

**Comment by chris263** [comment]
It freezes when adding method. Also it is not allowing to choose an existing method.

![Screenshot from 2024-04-16 20-35-53](https://github.com/solgenomics/sgn/assets/51970212/6853723e-a82f-4284-bf4e-fb925d7c314d)

**Comment by chris263** [comment]
![Screenshot from 2024-04-16 20-36-16](https://github.com/solgenomics/sgn/assets/51970212/7adc8525-3f39-4f0d-961a-99f397b79612)

**Comment by nmenda** [comment]
Duplicate 
#4996 

This is a technical issue, user needs to load new method ontology first if one does not exist yet in  the database
