### ISSUE TITLE
In BrAPI call for image, replace empty string with null or empty list

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4893]
Expected Behavior 
--------------------------------------------------------------------------
Compatibility with new geojson update.

https://docs.google.com/presentation/d/1Wq-GKE5ox5b1htS9_nevrmlZtlioBnpBtS7gUePiNdI/edit#slide%3Did.g2cb0690f604_0_50&seq=3

For Bugs:
---------

**Comment by ahulsekemp** [comment]
[Click here for slide details](https://docs.google.com/presentation/d/1Wq-GKE5ox5b1htS9_nevrmlZtlioBnpBtS7gUePiNdI/edit#slide=id.g2cb0690f604_0_50)
