### ISSUE TITLE
Onramp bases are not loading field layout

### ISSUE THREAD

**Issue by chris263** [solgenomics/sgn#4900]
Expected Behavior 
--------------------------------------------------------------------------
These are the main messages:

lib/CXGN/BrAPI/v2/ObservationUnits.pm line 120

[error] CXGN::Trial::TrialLayoutSearch::search(): DBI Exception: DBD::Pg::st execute failed: ERROR:  function regexp_replace(stockprop, unknown, unknown, unknown) does not exist

For Bugs:
---------

**Comment by lukasmueller** [comment]
removing the option brapi_ou_order_plot_num 1 from sgn_local.conf fixes the field layouts.
Created anohter issue for the brapi_ou_order_plot_num 1 setting.
