### ISSUE TITLE
Add seedlot description when uploading seedlot

### ISSUE THREAD

**Issue by LaetsCode** [solgenomics/sgn#4905]
Expected Behavior 
--------------------------------------------------------------------------
Currently the seedlot upload format contains a description field, to fill in the transaction description. It would be useful to add the seedlot description in usable fields when batch uploading seedlots, would that be possible ?

For Bugs:
---------

### Environment 
Flaxbase

**Comment by titima15** [comment]
@LaetsCode Thanks for letting us know. Yes, description in the seedlot upload file should be stored as seedlot description as well. There is a bug there. I will fix it asap.

**Comment by titima15** [comment]
@LaetsCode After the site is updated, you should be able to see seedlot description from the description column. For newly created seedlots, seedlot description will be used as the first seedlot transaction description as well.

**Comment by LaetsCode** [comment]
Great, thank you @titima15 !
