### ISSUE TITLE
protocol detail page crashes for certain old protocol entries

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4917]
Expected Behavior 
--------------------------------------------------------------------------
On the fixture:

/breeders_toolbox/protocol/2

crashes

For Bugs:
---------

**Comment by titima15** [comment]
@lukasmueller @isaak I know what's going on with those protocols. I will fix and include the fix in the edit pull request.

**Comment by titima15** [comment]
Fixed in pull request #4913
