### ISSUE TITLE
fieldbook file upload

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#492]
reported by Trushar: on the production site (yambase)…2016-UB-UPT under folder Demo ....on verification there is an error saying has less than 2 lines

**Comment by nickmorales** [comment]
If you could send me the field book file he is using I could check this

**Comment by bauchetg** [comment]
This was due to the a misuse of "table" format instead of "database" format from FieldBook export  by the user. The upload is up to date with latest Fieldbook version (3.2.4 version)
