### ISSUE TITLE
Notes (as a trait) imported through Excel cannot contain spaces or special characters

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4925]
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

**Comment by Sri-2023** [comment]
this works!, can you specify in which DB this issue is occurring?

![Screenshot from 2024-07-04 22-17-47](https://github.com/solgenomics/sgn/assets/122313818/2c3caf39-0079-400e-8dae-e394c54acff8)

**Comment by lukasmueller** [comment]
Could the upload detect the encoding of the Excel file and give an error if not UTF-8?

**Comment by lukasmueller** [comment]
This is an issue of spreadsheet encoding I think, closing the issue. (The spreadsheet needs to have UTF-8 encoding).
