### ISSUE TITLE
People search does not work on sweetpotatobase (data table error)

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#493]

**Comment by lukasmueller** [comment]
The sgn_people schema was added to the dbsearchpath in the sgn_local.conf on the sweetpotatobase.org server.

**Comment by bellerbrock** [comment]
wow, that was fast! Thanks Lukas. The workshop is going very well, that was the first issue we encountered and we used it as an example of when to use the contact form. I just added sgn_people to the dbsearchpath in the sgn_local.conf for sweetpotatobase-test too

**Comment by lukasmueller** [comment]
Great! Let me know how things develop! 
Greetings to everyone.

cheers
Lukas
