### ISSUE TITLE
Upgrade R in non-docker systems

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#4943]
Expected Behavior 
--------------------------------------------------------------------------

- [x] Cassavabase
- [x] cassbase
- [x] Musabase
- [x] MusabaseQUT
- [x] Sweetpotatobase
- [x] Yambase
- [x] SGN
- [x] Cluster
- [ ] and related test servers
- [x] Cassava-test
- [x] Musabase-test -- can't ssh to it.
- [x] Sweetpotatobase-test
- [ ] Yambase-test -- is it on docker???
- [x] SGN-test
- [x] Cluster-test

For Bugs:
---------

**Comment by isaak** [comment]
-- On all the checked systems: R upgrade to 4.4; R_libs set to topic/debian_bullseye_R4.4.

--MusabaseQUT has ssh authentication issues
--musabase-test...seems to be down. Can' ssh to it...it is not responsive.
--yambase-test...not sure if it is on docker or not...

**Comment by lukasmueller** [comment]
Updated R in Musabasequt
yambase-test is docker-based 
musabase test is up and updated
