### ISSUE TITLE
 Existing Seedlot to Unspecified Seedlots/Plots Transactions  Not Working

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4965]
![image](https://github.com/solgenomics/sgn/assets/36375878/dbb2414e-9ecb-450e-8234-6670f62f9671)

Notice the description mentions a "to_seedlot_name" field that is not included in the template header. The field wouldn't make sense for this type of transaction. I get the below error when I upload the attached file.

![image](https://github.com/solgenomics/sgn/assets/36375878/802e95d7-7ac5-4eae-bcac-a21f46e77d53)

[2024-06-04_seedlot_update.xlsx](https://github.com/user-attachments/files/15570947/2024-06-04_seedlot_update.xlsx)

**Comment by titima15** [comment]
@ch728 Hi, sorry for the mixed-up. Actually, the column "operator_name" should comes before "transaction_description".  If you switch the 2 columns, it should work even with the current version. I will fix the file format info and the required columns info asap. Thanks for letting us know.

**Comment by ch728** [comment]
It worked after swapping the columns, thanks @titima15!

**Comment by titima15** [comment]
Fixed seedlot spreadsheet info via #4966
