### ISSUE TITLE
Plots with crosses instead of accessions aren't shown in field map

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#4979]
The plots with accession are shown the plots with crosses are blank. When I download the trial info all the plots are there. I

![image](https://github.com/solgenomics/sgn/assets/36375878/15a5875a-180b-4c99-bf2c-19596cd899e0)

**Comment by titima15** [comment]
Done via #4981

**Comment by titima15** [comment]
Fixed via #4984
