### ISSUE TITLE
adding subplots as seedlots source

### ISSUE THREAD

**Issue by LaetsCode** [solgenomics/sgn#4987]
Expected Behavior 
--------------------------------------------------------------------------
When creating seedlots through the "upload seedlots" in the interface, there is the possibility to add a source, like a plot in a trial. But when using subplots, it doesn't recognize the source. Would it be possible to add the use of subplots as seedlots source please ?

For Bugs:
---------

### Environment 

Flaxbase, based on Breedbase v1.21

**Comment by lukasmueller** [comment]
This could be solved by naming the seedlots in a systematic way. But the proposed functionality is something that would be valuable.
