### ISSUE TITLE
include trial data comparison tool to folder page

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#499]

**Comment by nickmorales** [comment]
should display comparative plot(s) for trials in the folder that had the same designs, accessions, and measured traits.

**Comment by lukasmueller** [comment]
a trial comparison tool was implemented in /topic/analyze_phenotype_page, but it does not yet work with folders.  Should we merge the tool at this point?

**Comment by isaak** [comment]
I vote for merging it for the limited functionality to has and upgrade it as we go...

On the R script side, it is designed to compare upto 4 trials. However, creating >2  trials dataset creation is buggy.

Speed is also an issue, at least adding 'working dialog' might help.

**Comment by dauglyon** [comment]
covered by #1614
