### ISSUE TITLE
Missing Manage --> Tissue Samples Field

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#4995]
Expected Behavior 

The user should be able to navigate to a page for managing and creating new tissue samples for trials. 

### Actual Behavior

Option completely missing in CitrusBase and SugarcaneBase. 

--------------------------------------------------------------------------

For Bugs:
---------

**Comment by lukasmueller** [comment]
The manage tissue sample option has been added to sugarcanebase and citrusbase. Let me know if there are others that need it.
