### ISSUE TITLE
Unable to Create Trait in CitrusBase

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#4996]
Expected Behavior 

The curator functionality to add traits is enabled in CitrusBase. Clicking on the "Add a New Observation Variable to the Database" button at the bottom of the Trait Search Page opens up a pop-up for adding observation variable, trait name, method, scale and submitting new trait. 

### Actual Behavior

On the Method Page of the pop-up box, there is not an option for select a Method Ontology Name and adding a new method does not work (error pops up that you must do either every time you click "Go to Next Step". Not able to completely walk through steps and add trait. 

--------------------------------------------------------------------------

For Bugs:
---------

### Environment 

CitrusBase

#### Steps to Reproduce

See above. 
<img width="1196" alt="Screenshot 2024-07-02 at 2 51 59 PM" src="https://github.com/solgenomics/sgn/assets/8751385/c8177f11-75af-4691-b5b5-d632475ca0cd">

**Comment by nmenda** [comment]
to have the 'method ontology' select box populated there needs to be a row in the cvprop table with a 'method_ontology' type_id linking to the cvterm_id of your method ontology in the cvterm table.

**Comment by nmenda** [comment]
@hkmanching when you try to store a new ontology what error message do you get? You need to have a  'curator' account to add a new 'method' ontology from the dialog

**Comment by hkmanching** [comment]
I am a curator in CitrusBase. The attachment shows what I see when I try to walk through the process. 

[MethodOntologyProblem.pdf](https://github.com/user-attachments/files/16089743/MethodOntologyProblem.pdf)

**Comment by hkmanching** [comment]
Sorry, that pdf doesn't display what it should. Fixing now.

**Comment by hkmanching** [comment]
@nmenda 

[MethodOntologyProblem.pdf](https://github.com/user-attachments/files/16089817/MethodOntologyProblem.pdf)

**Comment by nmenda** [comment]
@hkmanching in the 'method' step, it looks like there is no pre-loaded 'method ontology' in citrusbase. 
What happens when you add a new method ontology? ON the 'method' page click first on 'Need a new ontology? Click here first' button

**Comment by hkmanching** [comment]
Okay. I think I figured out what I was doing wrong. However, in that process I added some things that need to be changed. Could you change the name of "CITRUS:0000240: Chlorosis of canopy estimation as a percentage." to "CITRUS:0000240: ChlorPer"

**Comment by hkmanching** [comment]
@nmenda it looks like there are actually 2 traits that were created (not sure why). "CITRUS:0000240" and "CITRUS:0000242". Also, when I create a trait file for these, it sets the default value to 50, but I did not set a default value for this. So, need to delete "CITRUS:0000242" and change name of "CITRUS:0000240" to ChlorPer, please.

**Comment by nmenda** [comment]
@hkmanching 
https://citrusbase.breedinginsight.net/cvterm/79411/view

Please email me if you need more help with citrusbase!
