### ISSUE TITLE
implement phenotype averages

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#50]
Add averages of phenotypic measurements depending on field layout type. The averages should be stored as a separate trial. Code interfacing with trials should not have to be changed to use the 'average' trial.

**Comment by lukasmueller** [comment]
Isaak and Bryan to work on this. Implement a CXGN::Trial function that gives a hash of accessions and their phenotypic value averages. This is related to issue #

**Comment by lukasmueller** [comment]
Create a section on the trial detail page with averages calculated on the fly.

**Comment by isaak** [comment]
related: #354

**Comment by nickmorales** [comment]
phenotype summary section calculates statistics on the fly for an accession's plot level measurements 84fd9378bd4608970a1237a3d83b9b5f4cdb5012
