### ISSUE TITLE
Ontology browser: allow trait list creation and export .trt format to "manage" -> "Fieldbook" menu 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#502]
This would  allow the user to create a trait list directly from the trait dictionary and export it to the Fieldbook: 
From Fola: for example trait selection could be done from the ontology browser ticking boxes from a trait search output or from the tree directly.

**Comment by bauchetg** [comment]
We could add two export buttons from the ontology browser:
-" export to field book" : send the .trt to the "manage"-.> " "Fieldbook" trait file section
-"export to list manager": send the list to the list manager menu

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/issues/670

**Comment by lukasmueller** [comment]
Implement a variable search under the search menu, allowing users to select variables for use in a list, implemented in data tables, seems preferable for user friendliness. see (#670).
