### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#5021]
On /breeders/trial/, will this delete images? 

![image](https://github.com/user-attachments/assets/13d16733-3ab7-421f-b399-0ee8abf3d52c)

If not, how do I purge associated images? It seems like images are not treated the same way as other traits; however, I have a lot of different image traits that I collect with Fieldbook. Sometimes I realize a mistake and It's easier to delete the whole trial and phenotypic data and reupload to fix. I worry that images aren't being updated or deleted however.

**Comment by lukasmueller** [comment]
Short answer is no, but it will delete the association of the images with the plot/plants/etc. Technically, images are never deleted. You can delete the database entry of an image, but it will still be on disk.
