### ISSUE TITLE
Crossing manager: Add Suffix to the custom plot naming option 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#503]
Currently while creating a new trial from cassavabase, plot_name are generated without including the accession name.Here are examples:
year_trialname_plotid_accession/clone name 
-For augmented design it has a plot number suffix, like:
2016-2017.GS.C3.IB_1-plot1
2016-2017.GS.C3.IB-plot254
-Same for RCBD.

Trials need to generate a more descriptive plot_name
year_trialname_plotid_accession/clone name

**Comment by bauchetg** [comment]
from Prasad, plot naming should follow this structure:
From Prasad:

-> RCBD: Year + ”-“ + TrialName + “-“ + “Rep” + Repno + “-“ + Accession_name
2016-15ayt10highTCUB-rep1-IITA-TMS-IKN120065
-> Augmented: Year + ”-“ + TrialName + “-“ + “Plantno” + Plotno + “-“ + Accession_name
2016-15clonalevalhighDMIB-plantno438-IITA-TMS-IBA152846

**Comment by lukasmueller** [comment]
Could you clarify with Prasad what the use case was for this? In my opinion, the plot name should just be an identifier and not carry too much meaning...

**Comment by bauchetg** [comment]
We clarified this with Prasad. This is the naming convention at IITA and changes can be made accordingly.

**Comment by aco46** [comment]
@bauchetg: just like Lukas mentioned, the use case was for identifier within the database.

with longer plot names; 
 -part of the plot name only shows above the barcode on the stock page for any accession.
 -while printing barcode for a plot, the barcode becomes smaller.

**Comment by bauchetg** [comment]
Hi Alex, thanks for the note.
-Plot naming allows customization (prefix and/or suffix) by the user but the customization is incorrect (i.e prefix set as suffix). 
-Adding accession name may be discussed but it is widely used already through historical trial plot names (since 2005). IITA request this format to keep historical and new trials from cassavabase in a same format.
Could the issue with barcode be fixed differently?

**Comment by aco46** [comment]
Barcode can be fixed differently.

**Comment by bauchetg** [comment]
fixed here by Lukas:
[4369392](https://github.com/solgenomics/sgn/commit/4369392d87ef9fe2ba019f1bdede6fa4bc89e98d)

**Comment by bauchetg** [comment]
still need a minor change for plot number customization @aco46

**Comment by bauchetg** [comment]
[c6c5799](https://github.com/solgenomics/sgn/pull/1013/commits/c6c5799307b8a918c32a6a77d70c470b6b9cfc54)

[h6ddab77](https://github.com/solgenomics/sgn/commit/6ddab779e903f996887d8b2a162c56d8ed30e292)

[5593aeb](https://github.com/solgenomics/sgn/commit/5593aeb8456ed267b62a757d2789a40a837beb93)

**Comment by bauchetg** [comment]
9fa427a[https://github.com/solgenomics/sgn/commit/9fa427a19dc068bb12e167878b8952f34fecc957](url)
