### ISSUE TITLE
Reroute broken histogram links on Trial Detail page to the Raw Data Histo tool

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#504]
From Ted Carey:

Under Trial detail report, traits assayed has a table of raw data
statistics presented in tabular form. The last column, "more info", has a
little histogram icon which is non-functional.  Histograms are presented by
variable below.  You might want to get rid of this.

**Comment by nickmorales** [comment]
you can use js/SGN/Histogram.js to display the hostogram. just give it an array of values.

**Comment by bellerbrock** [comment]
closed with f2dc814c7ea320f30478f01765dc1655c9c08eee
