### ISSUE TITLE
Fix the indentation of the Phenotype_summary.mas file.

### ISSUE THREAD

**Issue by Sri-2023** [solgenomics/sgn#5043]
Expected Behavior 
--------------------------------------------------------------------------

https://github.com/solgenomics/sgn/blob/master/mason/breeders_toolbox/trial/phenotype_summary.mas

For Bugs:
---------

**Comment by titima15** [comment]
@Sri-2023 are you planning to add or modify any section for that mason? If not, shouldn't just fix indentations.

**Comment by Sri-2023** [comment]
@titima15 yes, am adding an option of start date and end date for the repetitive measurements.

**Comment by titima15** [comment]
OK, If it's not interfering with what you plan to add or modify, we usually don't just fix indentations. We should try to preserve the original author information.

**Comment by Sri-2023** [comment]
Yes, noted.

**Comment by Sri-2023** [comment]
I will close this issue because the problem was not in the master branch file. Instead, it was in this branch (**topic/repetitive_measurements**) only.

**Comment by titima15** [comment]
@Sri-2023 Yes, I know that. That's why I was wondering why you are going to fix that mason file and made that comment.
