### ISSUE TITLE
Report that a pedigree already exisits if a user tries to load a pedigree for an accession that already has one

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#506]
Noticed at the workshop in Ghana and reported by Victor:

In the pedigree upload, the upload fails silently if the progeny accession already has a pedigree loaded. We should fail with an informative message

**Comment by lukasmueller** [comment]
Bryan - is this with the upload of the pedigree file or on the interactive user interface?

**Comment by bellerbrock** [comment]
If I remember correctly, it was with the upload of the pedigree file

On 1 June 2016 at 21:39, Lukas Mueller <notifications@github.com> wrote:

> Bryan - is this with the upload of the pedigree file or on the interactive
> user interface?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solgenomics/sgn/issues/506#issuecomment-223133123>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKxiQiUTYfiFsjty_jFu_ThX0tPWbLqBks5qHfwEgaJpZM4Iovfz>
> .
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868

**Comment by bauchetg** [comment]
Pedigree should not create population folder when it is a unique half-sib (this functionnality should be limited to the polycross design)

**Comment by nickmorales** [comment]
#1133 prompts a message to the user if a progeny already has parents and allows user to redefine the parents by clicking a checkbox.
