### ISSUE TITLE
Add accession properties to inventory.breedbase

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5117]
Expected Behavior 
--------------------------------------------------------------------------

Please add the following accession properties to inventory breed base. Thanks!

1. **GrinGlobal_current** - Indicates whether material has a current record in GRIN Global. Please indicate 1 if yes and empty if otherwise.
2. **GrinGlobal_date** - Date when record was updated in GRIN Global.
3. **Core** - Indicates whether material is part of the core collection. Please indicate 1 if yes and empty if otherwise.
4. **Clean** - Indicates whether material has been cleaned. Please indicate 1 if yes and empty if otherwise.
5. **Cryo** - Indicates whether material has been cryo-preserved. Please indicate 1 if yes and empty if otherwise.
6. **IDType** - Qualifies the type of the name, this could be a cultivar name, or the identifier of the accession provided by the donor.
7. **Lifeform** - Describes the biological form of the material (tree, shrub, etc…)
8. **accession_form_received** - Form accession was received in: budwood, seed, etc…
9. **Source_history** - Free text description of source history.
10. **Source_type** - type of source event
11. **cooperator_first_name** - first name of cooperator who provided material
12. **cooperator_last_name** - last name of cooperator who provided material
13. **city** - city of origin
14. **IPR** - Free text description about accession's intellectual property rights/restrictions
15. **quarantine** - Free text description about accession's quarantine status

For Bugs:
---------

**Comment by hkmanching** [comment]
@lukasmueller thanks for adding those properties! Here is the list of what to add back in from BB original properties and I added a few more, too. 

1. biological status of accession code
2. notes
3. state
4. country
5. pedigree - free text description of pedigree from source, in the case of material received in gene bank.
6. quantity_received
7. acquisition date
8. organization
9. variety
10. PUI
11. web_visible
12. accession number
13. donor
14. donor PUI
15. donor institute
16. location_code
17. released_variety_name

**Comment by lukasmueller** [comment]
Added both sets of accession properties to inventory.breedbase.org in the sgn_local.conf file.
