### ISSUE TITLE
Option to download seedlots with info

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#5126]
Is there a way to download seedlot information from the database using a list? I can't find one. This would be a very useful feature. Basically a download with the information shown in the table.
![image](https://github.com/user-attachments/assets/89bde449-2b82-4f54-aaac-b44b6a61d13d)

**Comment by titima15** [comment]
@ch728 On the List dialog with seedlots list type, you can find a link "Go to List Details Page" on the top left conner. There is a download function there.

**Comment by ch728** [comment]
@titima15  Found it! Thank you
