### ISSUE TITLE
Search by accession property not working

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5128]
Expected Behavior 
--------------------------------------------------------------------------
<img width="1402" alt="Screenshot 2024-09-27 at 9 09 06 AM" src="https://github.com/user-attachments/assets/03f3c27d-3eb4-4e5f-818b-cab10b548864">

When searching by cooperator_last_name in inventory DB, the following error occurs. 

For Bugs:
---------

**Comment by lukasmueller** [comment]
Which site is this? We recently fixed this bug, and I probably just need to update the site

**Comment by lukasmueller** [comment]
It seems to work now
