### ISSUE TITLE
Can't navigate trial tree in manage trials page on a tablet

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#513]
For some users, it's easiest to create and download fieldbook files directly on a tablet. But double clicking on a trial in the trial tree doesn't seem possible on a tablet. Is this fixable, or are there any good ways to get around it?

**Comment by nickmorales** [comment]
It is expecting a double-click in the trialtreefolder.mas , but could
theoretically be made a single click

**Comment by bellerbrock** [comment]
that could work, a single click shouldn't be a problem on a tablet. but
would that mess up the ability to select trials in order to move or
download them?

On 31 May 2016 at 20:06, Nick Morales <notifications@github.com> wrote:

> It is expecting a double-click in the trialtreefolder.mas , but could
> theoretically be made a single click
>
> On Tue, May 31, 2016 at 3:56 PM, Bryan Ellerbrock <
> notifications@github.com>
> wrote:
>
> > For some users, it's easiest to create and download fieldbook files
> > directly on a tablet. But double clicking on a trial in the trial tree
> > doesn't seem possible on a tablet. Is this fixable, or are there any good
> > ways to get around it?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/solgenomics/sgn/issues/513>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AGs_IJ6uzXLEi_pklgAyYGf5X02I8NTiks5qHJJdgaJpZM4Iq5Wy
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solgenomics/sgn/issues/513#issuecomment-222804068>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKxiQha4qkR1qtWhksaQsKltNmZkd-u2ks5qHJTMgaJpZM4Iq5Wy>
> .
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868

**Comment by nickmorales** [comment]
on a tablet you can push and hold on the link until a dialog for "open in a new tab" appears. just need to fix the url for that
