### ISSUE TITLE
Account quick create as an admin doesn't give length requirements

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#514]
When we use 
http://sweetpotatobase-test.sgn.cornell.edu/solpeople/admin/quick_create_account.pl

to create accounts at a workshop, it'd be helpful to include an explicit list of requirements for account creation - username and passwords 7 characters or longer, and not the same as each other.

The 'private' part of the private email field also confuses people

**Comment by lukasmueller** [comment]
This page is really only for curators, so the interface is more bare bones.

Fixed in fe7e4ae4c623957654b3598965d44eb1a2aa1f5b
