### ISSUE TITLE
Track plot ids for the female and known males in a population for an OP cross

### ISSUE THREAD

**Issue by keocorak** [solgenomics/sgn#5146]
Expected Behavior 
--------------------------------------------------------------------------
Some cross types allow the front-end user to track the exact parents used in the cross by selecting the appropriate male and female plots in a trial (ex: biparental, backcross). Others do not, usually when a population is designated as the female(s) and/or male(s) parent (ex: open pollinated, bulk). I'd like the ability to track specific parents, if known, for these types of crosses too. 

I can see a couple ways that this could be implemented, but discussion is probably warranted.

**Comment by titima15** [comment]
What is the advantage of this use case?

**Comment by titima15** [comment]
We can specify female plot/plant and use population name for male. Is this enough?

**Comment by keocorak** [comment]
At minimum, what you specified is definitely helpful. Maybe you can help me think through the second part regarding population names for males. The motivating situation regards a long-lived and clonally propagated perennial species. The breeding group has propagated stocks of the same accession into many different orchards. Because of the potential for somoclonal mutation and/or simple planting errors, they want to be able to associate a population of male parents to a specific trial/location at least. Possibly to exact plots/plants within the orchard, but I need to clarify with them to be sure. They have not planned to create new accessions for propagated clones, but maybe they should? I'm curious to learn what you'd recommend here.

**Comment by titima15** [comment]
@keocorak If you would like to keep tract of population in different trial , you can record that info in the "Additional Parent Info" section. You can record as "Female Source Trial" and "Male Source Trial". This section is in Crossing Experiment details page

**Comment by titima15** [comment]
@keocorak Sure, I will work on this ticket when I have a chance. How soon do you need this?

**Comment by keocorak** [comment]
Not urgently, sometime in the next month or so would be great!

**Comment by titima15** [comment]
@keocorak I just added another ticket for the ability to create a population with a list of plots/plants. This feature will be useful for your open-pollinated use case.

**Comment by titima15** [comment]
Done via #5230
