### ISSUE TITLE
On manage-trial page of sweetpotatobase-test site, folder symbol is used in the instruction, but suitcase symbol is used in trial instead.  

### ISSUE THREAD

**Issue by titima15** [solgenomics/sgn#515]
![screen shot 2016-05-31 at 3 58 08 pm](https://cloud.githubusercontent.com/assets/17749882/15689108/6e2f58dc-274b-11e6-89cf-1bc173f437fe.png)

**Comment by titima15** [comment]
Note: the instruction should indicate that "Double click arrow".  Also the arrow symbol is not clear.

**Comment by titima15** [comment]
On this page, it's confusing when users see folder in the instruction section (left panel), but see suitcase in the right panel.

**Comment by lukasmueller** [comment]
Hi Titima,

the suitcases represent breeding programs and the folders are groups of trials. In the case shown, there is no folder.

cheers
Lukas

**Comment by nickmorales** [comment]
add legend for suitcase image.
