### ISSUE TITLE
New trials not showing up in trial search results

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#516]
For example, there are twelve trials on sweetpotatobase.org, in both the trial tree and wizard. 4 of them were uploaded last week in Ghana, and do not show up in the trial search. This is confusing!

**Comment by lukasmueller** [comment]
for some reason, in the trial search the trial needs an associated trial type in order to show up. This is definitely a bug and a result of a bad join somewhere in the search query.

**Comment by nickmorales** [comment]
somehow related to here https://github.com/solgenomics/sgn/blob/master/lib/SGN/Controller/AJAX/Search/Trial.pm#L73

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/blob/master/lib/SGN/Controller/AJAX/Search/Trial.pm#L73

this query is wrong. It assumes that a trial has either NO projectprops 
OR all of the following:
project year
and 
project_type
and 
project_location

**Comment by nmenda** [comment]
fixed the query, works now with DBIx::Class and CXGN::Trial. Need to check sorting now
