### ISSUE TITLE
Allow addition of trait properties only on variables

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#5161]
Expected Behavior 
--------------------------------------------------------------------------

Currently the trait properties tool works for adding properties for all ontology terms which is confusing, it is easy to accidently add a format for example to a trait, not realizing that the brapi import to fieldbook only checks the format for variables. And then spend an hour trying to figure out why it's not importing with the right format (don't ask me how I know).

For Bugs:
---------

**Comment by lukasmueller** [comment]
This is part of the pull request for #5162.

**Comment by lukasmueller** [comment]
Fixed in pull request #5162.
