### ISSUE TITLE
Barcode tool:  "Excel Sheet Download" and "Download Stock Barcodes" tools fail

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#517]
Reported by Prasad, while creating both outputs give error messages:
"Server Error Our apologies, there was an error processing your request. "
as well:
 the "Lines or Plots:" option could access  the list manager to select plot and lines and/or put by default the plot/accession list from the selected trial in "Project:" 

In Download Stock Barcodes:
"Or Paste From a List" should be changed for a drop down menu of available list and/or list manager access.

In general, t could be more efficient to source the data from the wizard and create the different barcodes outputs from there.

**Comment by aco46** [comment]
close 8c38deac9083edc6fa4e20fc35afa6cfac603cc1
