### ISSUE TITLE
Synonym misspelled under trait page. 

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5176]
Expected Behavior 
--------------------------------------------------------------------------

<img width="780" alt="Screenshot 2024-10-30 at 3 29 07 PM" src="https://github.com/user-attachments/assets/a3756cb0-e3f4-4ddc-8d72-f6bb779181fa">

For Bugs:
---------

**Comment by alockrow** [comment]
Fixed with PR #5179
