### ISSUE TITLE
Modified Augmented Design: Could not calculate design

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#518]
MAD trial design crashes with the information:
"Could not calculate design: Number of block row not specified"

**Comment by bellerbrock** [comment]
In addition to this error (or maybe they're related)  Ismail Rabbi noticed that the dialog doesn't give an option to specify which specific check should be used in all the blocks.

**Comment by bauchetg** [comment]
add split plot and factorial analysis

**Comment by lukasmueller** [comment]
I assume this has been fixed a long time ago (hopefully?)

**Comment by lukasmueller** [comment]
Closing this now as I think this is not an issue anymore. Please re-open if that's not the case.
