### ISSUE TITLE
InventoryBase: Add Option to add "variety" to field book field layout files from a trial. 

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5189]
Expected Behavior 
--------------------------------------------------------------------------

This is currently not an option and "variety" is not considered in the synonym category, which works for accessions that are the same variety, but maybe clonal propagates. 

<img width="1492" alt="Screenshot 2024-11-06 at 11 53 31 AM" src="https://github.com/user-attachments/assets/897c8800-2158-4e1f-8a5b-0e31ee911c66">

For Bugs:
---------

**Comment by afpowell** [comment]
Linked to #5193 - #5193 is a more general case of this ticket

**Comment by hkmanching** [comment]
@lukasmueller this issue doesn't appear to be resolved in InventoryBase even though ticket is closed.
