### ISSUE TITLE
Validation of a list of locus_ids fails

### ISSUE THREAD

**Issue by ryan-preble** [solgenomics/sgn#5198]
Expected Behavior 
--------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/41025064-186f-4f8f-bae2-a16f5387d86f)

For Bugs:
---------

### Environment 

List creation interface

#### Steps to Reproduce

Try to make a new list of locus_ids. Attempt to validate the list, and you will be met with an error.

**Comment by ClayBirkett** [comment]
Do you want a list of locus_id or locus names? It seems to me that locus names would be more useful.

**Comment by ryan-preble** [comment]
> Do you want a list of locus_id or locus names? It seems to me that locus names would be more useful.

I agree that locus names are probably more useful to users. But currently the list creation interface only has locus_ids and markers as options
