### ISSUE TITLE
InventoryBase: Search Wizard does not work when trying to search Traits

### ISSUE THREAD

**Issue by hkmanching** [solgenomics/sgn#5211]
Expected Behavior 
--------------------------------------------------------------------------

On Search Wizard page, selecting traits in the dropdown causes wizard to initiate loading cycle of doom. 

<img width="1046" alt="Screenshot 2024-11-18 at 10 41 05 AM" src="https://github.com/user-attachments/assets/c406ce61-9cf3-40b4-ac5f-86ff02535ea1">

For Bugs:
---------

**Comment by lukasmueller** [comment]
recent ontology loading caused 'VARIABLE_OF' term to be present twice in the cvterm table, which caused this issue. Renamed one of the terms.
