### ISSUE TITLE
Can't create new trials using the Design New Trial tool or uploading existing trials.

### ISSUE THREAD

**Issue by laguem** [solgenomics/sgn#5219]
Expected Behavior 
--------------------------------------------------------------------------
Can't create new trials using the Design New Trial tool or uploading existing trials.
Getting this popup error message:
<server name> says 
An error occured. sorry

For Bugs:
---------

### Environment 
Breedbase docker 1.28 and 1.35 installed on Linux Mint 20 (build on Ubuntu 20)

#### Steps to Reproduce
Go in Manage -> Field Trials -> Design New Trial
Fill all the forms as usual until step 7, Review Design Trial
When clicking Go To Next Step, the regular popup titled Working appears, followed by another popup with this error message: 
<server name> says 
An error occured. sorry

####  /var/logs/sgn/error.log
Here is the relevant part from /var/logs/sgn/error.log:

NOTICE:  relation "logged_in_user" already exists, skipping
NOTICE:  relation "logged_in_user" already exists, skipping
NOTICE:  relation "logged_in_user" already exists, skipping
NOTICE:  relation "logged_in_user" already exists, skipping
Use of uninitialized value $sp_person_id in concatenation (.) or string at lib/SGN/Role/Site/DBIC.pm line 32.
sp_person_id passed to DBIC Schema:  
Setting plot_numbering_scheme to block_based
Use of uninitialized value $calculated_total_plot in numeric ne (!=) at lib/SGN/Controller/AJAX/Trial.pm line 255.
Use of uninitialized value $p_rep_total_plots in numeric ne (!=) at lib/SGN/Controller/AJAX/Trial.pm line 255.
[error] Attribute (submit_host) does not pass the type constraint because: Validation failed for 'Str' with value [ "breedbase_web", "" ] at writer CXGN::Trial::TrialDesign::set_submit_host of attribute submit_host (defined at lib/CXGN/Trial/TrialDesign.pm line 148) line 3
	CXGN::Trial::TrialDesign::set_submit_host('CXGN::Trial::TrialDesign=HASH(0x55fde5482fb0)', 'ARRAY(0x55fdc7c7ebe0)') called at lib/SGN/Controller/AJAX/Trial.pm line 302
	SGN::Controller::AJAX::Trial::generate_experimental_design_POST('SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 358
	Catalyst::Action::execute('Catalyst::Action=HASH(0x55fde591ec28)', 'SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	Catalyst::execute('SGN=HASH(0x55fdebd6d468)', 'SGN::Controller::AJAX::Trial', 'Catalyst::Action=HASH(0x55fde591ec28)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 353
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x55fde591ec28)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 261
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'forward', 'SGN=HASH(0x55fdebd6d468)', 'Catalyst::Action=HASH(0x55fde591ec28)', 'ARRAY(0x55fdebfd6788)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 241
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'SGN=HASH(0x55fdebd6d468)', 'Catalyst::Action=HASH(0x55fde591ec28)', 'ARRAY(0x55fdebfd6788)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 482
	Catalyst::forward('SGN=HASH(0x55fdebd6d468)', 'Catalyst::Action=HASH(0x55fde591ec28)', 'ARRAY(0x55fdebfd6788)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action/REST.pm line 109
	Catalyst::Action::REST::_dispatch_rest_method('Catalyst::Action::REST=HASH(0x55fde591ece8)', 'SGN=HASH(0x55fdebd6d468)', 'generate_experimental_design_POST') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action/REST.pm line 91
	Catalyst::Action::REST::dispatch('Catalyst::Action::REST=HASH(0x55fde591ece8)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Controller.pm line 170
	Catalyst::Controller::_ACTION('SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 358
	Catalyst::Action::execute('Catalyst::Action=HASH(0x55fde591a640)', 'SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	Catalyst::execute('SGN=HASH(0x55fdebd6d468)', 'SGN::Controller::AJAX::Trial', 'Catalyst::Action=HASH(0x55fde591a640)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 353
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x55fde591a640)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 261
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'forward', 'SGN=HASH(0x55fdebd6d468)', '_ACTION') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 241
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'SGN=HASH(0x55fdebd6d468)', '_ACTION') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 482
	Catalyst::forward('SGN=HASH(0x55fdebd6d468)', '_ACTION') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Controller.pm line 134
	Catalyst::Controller::_DISPATCH('SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 358
	Catalyst::Action::execute('Catalyst::Action=HASH(0x55fde591a238)', 'SGN::Controller::AJAX::Trial=HASH(0x55fde4499190)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2060
	Catalyst::execute('SGN=HASH(0x55fdebd6d468)', 'SGN::Controller::AJAX::Trial', 'Catalyst::Action=HASH(0x55fde591a238)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Action.pm line 353
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x55fde591a238)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 261
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'forward', 'SGN=HASH(0x55fdebd6d468)', '/ajax/trial/_DISPATCH') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 241
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'SGN=HASH(0x55fdebd6d468)', '/ajax/trial/_DISPATCH') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 482
	Catalyst::forward('SGN=HASH(0x55fdebd6d468)', '/ajax/trial/_DISPATCH') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Dispatcher.pm line 107
	Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x55fdc5616c48)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2006
	Catalyst::dispatch('SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Plugin/Static/Simple.pm line 85
	Class::MOP::Class:::around('CODE(0x55fdc550d668)', 'SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 166
	SGN::_wrapped_dispatch('SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 97
	SGN::dispatch('SGN=HASH(0x55fdebd6d468)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2412
	Catalyst::try {...}  at /home/production/cxgn/local-lib/lib/perl5/Try/Tiny.pm line 102
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Try/Tiny.pm line 93
	Try::Tiny::try('CODE(0x55fdec854970)', 'Try::Tiny::Catch=REF(0x55fdec8340c0)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst.pm line 2421
	Catalyst::handle_request('SGN', 'env', 'HASH(0x55fdebfaf170)', 'response_cb', 'CODE(0x55fdec858e08)') called at /home/production/cxgn/local-lib/lib/perl5/Catalyst/Engine.pm line 807
	Catalyst::Engine::__ANON__('CODE(0x55fdec858e08)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Middleware/HTTPExceptions.pm line 32
	Plack::Middleware::HTTPExceptions::try {...}  at /home/production/cxgn/local-lib/lib/perl5/Try/Tiny.pm line 102
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Try/Tiny.pm line 93
	Try::Tiny::try('CODE(0x55fdec850618)', 'Try::Tiny::Catch=REF(0x55fdebb79080)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Middleware/HTTPExceptions.pm line 41
	Plack::Middleware::HTTPExceptions::__ANON__('CODE(0x55fdec861390)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Util.pm line 339
	Plack::Util::__ANON__('CODE(0x55fdec864478)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Util.pm line 339
	Plack::Util::__ANON__('CODE(0x55fdec5a06b8)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Util.pm line 339
	Plack::Util::__ANON__('CODE(0x55fdec8336e8)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Util.pm line 339
	Plack::Util::__ANON__('CODE(0x55fdec7c4b00)') called at /usr/share/perl5/Starman/Server.pm line 198
	Starman::Server::dispatch_request('Starman::Server=HASH(0x55fdead95978)', 'HASH(0x55fdebfaf170)') called at /usr/share/perl5/Starman/Server.pm line 298
	Starman::Server::process_request('Starman::Server=HASH(0x55fdead95978)', 'Net::Server::Proto::TCP=GLOB(0x55fdec59ee70)') called at /home/production/cxgn/local-lib/lib/perl5/Net/Server.pm line 72
	Net::Server::run_client_connection('Starman::Server=HASH(0x55fdead95978)') called at /home/production/cxgn/local-lib/lib/perl5/Net/Server/PreFork.pm line 225
	eval {...} at /home/production/cxgn/local-lib/lib/perl5/Net/Server/PreFork.pm line 225
	Net::Server::PreFork::run_child('Starman::Server=HASH(0x55fdead95978)') called at /home/production/cxgn/local-lib/lib/perl5/Net/Server/PreFork.pm line 183
	Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x55fdead95978)', 10) called at /home/production/cxgn/local-lib/lib/perl5/Net/Server/PreFork.pm line 107
	Net::Server::PreFork::loop('Starman::Server=HASH(0x55fdead95978)') called at /home/production/cxgn/local-lib/lib/perl5/Net/Server.pm line 58
	Net::Server::run('Starman::Server=HASH(0x55fdead95978)', 'port', 'ARRAY(0x55fdeada6968)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 10, 'min_spare_servers', 9, 'max_spare_servers', 9, 'max_servers', 10, 'max_requests', 1000, 'user', 'www-data', 'group', 'www-data', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1) called at /usr/share/perl5/Starman/Server.pm line 106
	Starman::Server::run('Starman::Server=HASH(0x55fdead95978)', 'CODE(0x55fdc35cf950)', 'HASH(0x55fdeb0a5290)') called at /usr/share/perl5/Plack/Handler/Starman.pm line 25
	Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x55fdead97688)', 'CODE(0x55fdc35cf950)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Loader.pm line 84
	Plack::Loader::run('Plack::Loader=HASH(0x55fdc33d6530)', 'Plack::Handler::Starman=HASH(0x55fdead97688)') called at /home/production/cxgn/local-lib/lib/perl5/Plack/Runner.pm line 279

**Comment by lukasmueller** [comment]
You may have your the dbhost key twice in your config file

**Comment by laguem** [comment]
Finally found the configuration causing the problem:

I had cluster_host key configured twice
```
cluster_host breedbase_web
cluster_host ""
```
which matches the array in the error messages:

`Validation failed for 'Str' with value [ "breedbase_web", "" ]`

Thanks for pointing me in the right direction.

**Comment by lukasmueller** [comment]
Super! Great debugging! 🙂

cheers
Lukas
________________________________
