### ISSUE TITLE
Adding a new species name to a database

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#5227]
I would like to add some species to my database. I assume I need to write a db patch to do this. What table needs to be modified? Thanks!

**Comment by lukasmueller** [comment]
Hi Chris, you can really just insert it into the public.organism table. 
These are the fields that you need:
      Column      |          Type          | Collation | Nullable |                    Default                    
------------------+------------------------+-----------+----------+-----------------------------------------------
 organism_id      | integer                |           | not null | nextval('organism_organism_id_seq'::regclass)
 abbreviation     | character varying(255) |           |          | 
 genus            | character varying(255) |           | not null | 
 species          | character varying(255) |           | not null | 
 common_name      | character varying(255) |           |          | 
 comment          | text                   |           |          | 
 genbank_taxon_id | integer                |           |          | 
 sgn_organism_id  | integer                |           |          | 
 obsolete         | integer                |           |          | 

Abbreviation would be "S. lycopersicum", genus "Solanum", species "Solanum lycopersium", common_name "tomato and you can look up the genbank taxon id but it is not a required field.

**Comment by ch728** [comment]
Worked! Thank you Lucas.
