### ISSUE TITLE
Users would like the ability to edit lists directly from the add accessions dialogs

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#523]
For example, it would be helpful if, next to the list of accessions that are found in the database, we included the option to click and remove them from the list immediately. And if fuzzy search matches included an 'ignore I'm confident that these accessions are in fact different' option, and an 'update the name in my list to the version already in the database' option.

**Comment by bauchetg** [comment]
Similar suggestions from the musa workshop:
From the list manager, include fuzzy search directly in "validate" step.
This would streamline the process and save a big amount of time when adding accessions.
Similar as above comments: include ability to merge (or maybe an option to synonymize?) the submitted accession found to be redundant with existing ones  in the fuzzy search would make the submission process a lot simpler.

**Comment by lukasmueller** [comment]
The drop down on validate step needs another entry "Add the accession as input..." and it needs to add the name as a synonym if another accession is selected.
