### ISSUE TITLE
Users would like the cross creation dialogue to make 'flower #', 'seed #', and 'progeny #' options more clear.

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#524]
Question from the SP Ghana workshop: What is the difference between 'flower #', 'seed #', and 'progeny #' options ? Keeping track of how successful a cross is can be important.

After much discussion, we agreed that 'flower number' must mean number of individual crosses made, 'seed number' must mean number of seeds set, and 'progeny number' must mean number of viable seeds, or germinated seeds, or even number of progeny that were actually selected out of the seedling nursery. To prevent confusion, it could be helpful to make these definitions more explicit.

**Comment by lukasmueller** [comment]
Maybe add a question mark button for more info?
