### ISSUE TITLE
The trial creation option 'Year(s)' is confusing.

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#526]
From the Ghana SP workshop. Do we support the creation of multiple year trials at one time? If so, in what format should the multiple years be entered?

**Comment by bauchetg** [comment]
Could the creation of GxE project folder from the trial tree page better answer the problem?

**Comment by bellerbrock** [comment]
That might be a good way to organize the trials once they're created. But the question came up when we we're practicing trial creation with this dialogue:
![screenshot from 2016-06-06 13 45 35](https://cloud.githubusercontent.com/assets/11297346/15824118/26838cc8-2bed-11e6-8c5c-63a11dab6477.png)
The demo we were doing was a single trial, but based on the 'Year(s)' option, the participants were wondering if it's possible to enter multiple years, and in doing so create multiple trials at once. I wasn't sure, but I'm guessing this simply means you can enter something like 2015,2016 for a trial that starts in 2015 but ends in 2016? Either way, we should specify how the multiple years should be entered.

**Comment by bauchetg** [comment]
Maybe we could change "Year(s)"as  "Year of planting"  to avoid confusion and maybe add a multi-year option (Interesting use as usually trial plans are made from a year to an other)
"Date of planting" (mm/dd/yy) should be moved ti the trial creation dialogue as an optional (?) mandatory (?) field  (see #420) for further GxE analysis with weather data.
Regarding GxE multiple trials, the multi-location option should be offered too.

**Comment by lukasmueller** [comment]
Maybe we should call it "Year or Season" (our trials are limited to one year or season)
