### ISSUE TITLE
Generation of multi-year and multi-location trials (using same accessions and design type) all at once

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#527]
SP Ghana workshop, users asked for support for generation of multi-year and multi-location trials (using same accessions and design type) all at once.

**Comment by bellerbrock** [comment]
At SP/MUSA Uganda workshop, users asked about the same sort of functionality not just for trial creation, but for trial uploads too.

**Comment by aco46** [comment]
merged via 71aded7332100d642d9b3c98741c4f422f8d9de5
