### ISSUE TITLE
Notify database users of changes

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#530]
From SP Ghana workshop - users have asked for notification when there are changes, whether it's an ontology update, a new feature, bug fix, version # etc. Could be a section on the landing page, or maybe a user email listserv.

**Comment by isaak** [comment]
about mailing lists: any change or feature added in one database may be of interest for other RTB database users. If it is not available on another database, and another database users show interest we can make it available. So, I think, we should make all RTB users aware of changes in one mailing list.

**Comment by lukasmueller** [comment]
Maybe create a mailing list that has the other mailing lists as subscribers?

**Comment by lukasmueller** [comment]
Use the news section to announce new features.

**Comment by lukasmueller** [comment]
Maybe have a common news section for all the sites (just point that section to the same file for all the sites)

**Comment by bauchetg** [comment]
covered by #1105
