### ISSUE TITLE
Automatic refresh of trial tree when a new trial is uploaded or added

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#531]
Users were confused when their newly created or uploaded trials didn't show up in the trial tree on Manage->trials page. If possible, it would be good to make the refresh automatic when a new trial is uploaded or added.

**Comment by bellerbrock** [comment]
Also would be good to implement when folder structure is changed

**Comment by lukasmueller** [comment]
Ticket meeting discussion: People felt that the refresh button is sufficent, maybe add an alert to refresh after an upload. What happens when you add a folder? Or move a trial? Maybe in these cases it should refresh automatically?
