### ISSUE TITLE
Add ability to delete old or duplicate files on fieldbook app and phenotyping page

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#538]

**Comment by aco46** [comment]
Deletion option added for fieldbook layout file. Merged here  364c552a475861ad955cedcf01cdd88497bd2f19 with master.

**Comment by aco46** [comment]
Deletion option added for uploaded phenotype file on the 'Manage Phenotypic Data' page. Merged here 2fb969584f412f6c2b4158bf54ddd42d2b7a3213 with master.
