### ISSUE TITLE
Add additional schemes in cross tool, including NC2 and diallel

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#540]
Request from Doreen at NaCRRI Uganda

**Comment by bauchetg** [comment]
see also #420

**Comment by bellerbrock** [comment]
@titima15 Here are the mating designs I mentioned that some sweetpotato breeders have requested

**Comment by bauchetg** [comment]
@titima You can use agricolae implementation for the NC2 with the function carolina(model,data)

**Comment by lukasmueller** [comment]
Complex schemes can be uploaded using an Excel sheet, so this might not be required.
