### ISSUE TITLE
Trial JBrowse link broken on trial detail page

### ISSUE THREAD

**Issue by trusharshah** [solgenomics/sgn#542]
Please see the sample URL - 

https://www.cassavabase.org/jbrowse_cassavabase/?data=data/json%2Ftrials%2F135&tracks=DNA%2CGene%20exons%2C&cat=Diversity/NEXTGEN/Imputed&highlight=

**Comment by bellerbrock** [comment]
Thanks for the feedback Trushar! I'll take a look a this.
