### ISSUE TITLE
quick search (from magnifying glass in toolbar) is broken on sweetpotatobase-test

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#548]
![screenshot from 2016-06-07 21 17 00](https://cloud.githubusercontent.com/assets/11297346/15874946/4241721e-2cf5-11e6-8a98-86782a03ec3f.png)

**Comment by lukasmueller** [comment]
Seems like a db patch was not run....

**Comment by lukasmueller** [comment]
or just run alter table...

**Comment by bellerbrock** [comment]
needs to be done on sweetpotato, yam and musa sites

**Comment by bellerbrock** [comment]
closed by alter phenome.locus table in musa, yam, and sweetpotato databases to reflect cxgn_cassava. this meant dropping the organism_id column where present, and adding a locus column with:

alter table phenome.locus drop column organism_id;
alter table phenome.locus add column locus varchar(24) default NULL::varchar;
