### ISSUE TITLE
Improve user feedback for trial deletion options

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#552]
Trial deletion works now, but is somewhat confusing. It would be helpful to disable the UI with a working modal while the deletion is running, and to disable pheno and layout deletion if the trial does not have phenos or layout.

**Comment by bellerbrock** [comment]
also to add the option to delete measurements for individual traits, not just all or nothing

**Comment by bauchetg** [comment]
Hi Bryan, a similar ticket was open previously, see: #512
As well for curators it could be useful to have a bulk deletion using the list tool (ex: list of accessions).

**Comment by bellerbrock** [comment]
thanks guillaume, tackling all these improvements at once will make sense.

**Comment by bauchetg** [comment]
from NACRRI: single trait deletion should be possible

**Comment by titima15** [comment]
closed via e23e8a93d7b64635590c2572142c9774ce193442
