### ISSUE TITLE
Improve speed of trial page section that reports accessions, plots, plants

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#555]

**Comment by nickmorales** [comment]
accessions here a7cc5e6e2e6e38bbdaed44f3a05480799fdb6088

**Comment by nickmorales** [comment]
plots 69b60ccff8a8455529a55103e9fa1923751d1028 controls 2d4b938c494a50980a542a27a1e79c8e933f41d3

**Comment by nickmorales** [comment]
speed is improved, but if it is still too slow we may need to use a materialized view
