### ISSUE TITLE
cassava-devel https config 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#590]
The site is accessible after jumping over the following warning...

The owner of cassava-devel.sgn.cornell.edu has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

Report errors like this to help Mozilla identify misconfigured sites

cassava-devel.sgn.cornell.edu uses an invalid security certificate.

The certificate is not trusted because it is self-signed.
The certificate is only valid for cassava-test.sgn.cornell.edu

Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by lukasmueller** [comment]
This is a "feature".
