### ISSUE TITLE
run matviews dbpatches on fixture db

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#596]
-- also this https://github.com/solgenomics/sgn/blob/master/db/00053/GrantPublicMatviews.pm

**Comment by bellerbrock** [comment]
closed with commit [779f566c7e65db73c4f9f850f21e96d44c520c0f](https://github.com/solgenomics/fixture/commit/779f566c7e65db73c4f9f850f21e96d44c520c0f) in fixture repo
