### ISSUE TITLE
add ability to replace specific accessions on the fly in an exisiting trial design.

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#604]
Per request from NC State. In a good fraction of trials they will get to the field and find that they are unable to plant an accession that they had planned to (lack of planting material, for any number of reasons). They would like the ability to swap the planned accession out for a replacement, without having to go back and delete the original trial and upload a new design.

**Comment by bellerbrock** [comment]
Alex is working on this now as part of larger interactive fieldmap improvements

**Comment by aco46** [comment]
merged to master via 03c045cfe93bbb2f25bf1a68c78feb7ee70027e7
