### ISSUE TITLE
Plant based phenotype upload and download: bugs and suggestions

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#612]
Testing the new feature, I got into some minor bugs and a couple of suggestions:

--bugs: 
-in 'Manage' ,'Phenotyping', 'upload phenotypes', including existing plant based trial, validated list of traits and plant level, the upload doesnt work and give an error message: ''An error occurred creating a phenotype file". From the trial detail page, uploading work just fine.
-Uploading plant based phenotypes can be very long for not so large trials (i.e: 100 plots x 5 plants)

--suggestions:
-in 'Manage' ,'Phenotyping', 'upload phenotypes', while selecting the trial from the drop down menu  can be difficult as there are many many trials. An autocomplete search would help.
-On top of having it from the trial detail page, the generate plant entries option could be included from the trial creation page/drop down.
-A great feature to be added: 
automatically/or on demand, generate plot average values from plant based values when available. This will allow user to load data directly from FieldBook, without averaging it "by hand" prior uploading, we could possibly switch to most of the data load on a plant based approach.

**Comment by nickmorales** [comment]
8b784772b913a9195f7f876eeac10df3d8dfcfdf fixes the bug from manage phenotyping page
