### ISSUE TITLE
Simplify phenotyping spreadsheet generation for plant/plot based trial

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#619]
The current process to generate a template has three steps where users are getting confuse: #Current process is:
 From trial detail page, got  to “File” section,  “Uploaded Phenotyping Files”, “Phenotyping Spreadsheets”  click (1)“Upload" go to “File format information” click on (2) “Spreadsheet Format “ then click on (3)“ Create Phenotyping Spreadsheet fro Trial".

#An improved process could be do it in a single  step by adding option (1)"Create Phenotyping Spreadsheet from Trial" menu directly from the "File",  “Uploaded Phenotyping Files”, “Phenotyping Spreadsheets”  section on the trial detail page, next to the current "Upload" option.

**Comment by nickmorales** [comment]
Hi
There is a direct link to create a pheno spreadsheet from the trial detail
page. The button link is directly above the upload button link.

**Comment by bauchetg** [comment]
just realized it ,already addressed!
