### ISSUE TITLE
Same trait(s) uploaded multiple times in a given trial

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#620]
For a given trial, when uploading a phenotypic spreadsheet including a trait previously uploaded,  the upload is notified as successful, but the existing data remains unchanged, except for plots  where data was previously absent.
However, in "trait assayed", the "count" value for the trait reflects the multiple uploads:
https://cassava-test.sgn.cornell.edu/breeders/trial/1875?format=
-> A  notification that a particular trait is been already uploaded could be useful, especially when these are loaded in large batches.
-> While data already exist, Shall we provide users (curators) an option to overwrite -or not- the existing AND overlapping phenotypic data with the new dataset provided?

**Comment by nickmorales** [comment]
Add better notifications to the user when they are adding plot - trait measurements that already exist in the database. Possibly give curators the ability to "overwrite" (aka delete the old measurement and add the new one) the previous measurements with the new measurements.

**Comment by nickmorales** [comment]
@bauchetg  please try it out now. it should have better warnings and has an option to "overwrite" old values.

**Comment by bauchetg** [comment]
@nickmorales It works perfectly, warning messages are displayed when data overlap previous one, thanks!
