### ISSUE TITLE
Limit which terms from the trait ontology can be used to store phenotypes

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#624]
In spbase, most phenos are stored with the composed variables (combined trait+method+scale), but some are stored just with the trait. The wizard also currently retrieves all terms, including traits and variables, from the trait ontology. Maybe this should be limited to only composed variables?

**Comment by bauchetg** [comment]
In some case old trials will need curation and get the  trait variable variable assigned

**Comment by bellerbrock** [comment]
just commited a patch that fixes the trait materialized view used in the wizard. Once run, the wizard will only show composed variables. c3ffdf038368231dd548797a035a4fcf8b897953

we'll still need to handle the phenotypes that are stored with the wrong cvterms.

**Comment by bellerbrock** [comment]
Ok, so there is different work required in each database. In cassavabase and sweetpotatobase, most phenos are stored with the composed variables (combined trait+method+scale). The ones that aren't can simply be fixed by changing the trait ids in the pheno table.

In musabase and yambase all phenos so far are stored with just the trait. Musabase has composed variables loaded, but with acronyms rather than names. Yambase does not have composed variables loaded.

**Comment by bellerbrock** [comment]
Closing this issue. New phenotypes can now only be stored with variables, and most phenotypes that were linked to traits instead have been fixed. The only dbs that need more curation are cassavabase and cassbase, their issues are beeing tracked [here](https://github.com/solgenomics/sgn/issues/2491)
