### ISSUE TITLE
Improve the omni/advanced search from database homepage

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#625]
Comment from several breeders: an "omni" search bar (google like) would be a useful tool.
-> Current search bar from the homepage:
-not very visible (need to click on the magnifying glass icon to appear): need to be constantly displayed
-does not always provide accurate outputs (ex doesn t find some registered user name) or redirects to the accession/trial search (ex search: 'ayt', 'TME' accession) without processing the requested search automatically.
-> Could including a google engine search in the website be a do-able/useful thing?

**Comment by lukasmueller** [comment]
The quick search implements such features, but some of the functionality is broken, such as the connection to stock pages...

**Comment by lukasmueller** [comment]
The web search is present but it is not working.

**Comment by lukasmueller** [comment]
There is a advanced search in the toolbar... Does that need to be on the homepage as well? The advanced search needs to also search locations, breeding programs, trials by name, traits, years, etc.
