### ISSUE TITLE
Field map could be automatically generated using "range value" from field layout instead of requesting "column" information field 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#627]
In field layout template the "range" information field is under utilized.
We can encourage this use by creating the map more systematically: 
-Providing a better definition of the "range" field (=can be equivalent to column) in the template description.
-Inform the user that if this field is informed it will automatically  generate a field map.

Two other element could be considered for the field map:
-Inclusion of the guard rows (ex between blocks) for a better representation
-Representation of subplot information: the field layout has a plant based information (= subplot level) 
- allow a printing output for the field map (ex: pdf)

In general, map generation could be used for many other functionalities (plotting trait values, Selection index, etc...)

**Comment by bauchetg** [comment]
Uploading the field map input is successful but is not displayed
Access time can be be really slow. For example see:
http://musabase-test.sgn.cornell.edu/breeders/trial/234?format=

<img width="926" alt="screen shot 2016-09-01 at 7 56 45 am" src="https://cloud.githubusercontent.com/assets/12039071/18156358/6044d942-701e-11e6-9d7b-831812665504.png">

[field_map_DT_trial.txt](https://github.com/solgenomics/sgn/files/448875/field_map_DT_trial.txt)

**Comment by aco46** [comment]
Thanks for the feedback. Will start working on it today. The file must have been saved in the wrong file format. I re-saved the file in the right format (tab separated) and was able to upload the layout. However, I'll work on making it more user friendly by checking when a wrong file format is used. See the link for the trial: http://musabase-test.sgn.cornell.edu/breeders/trial/234?format=

**Comment by aco46** [comment]
The feature for uploading trial along with field map has been added to trial upload tool and merged to master via bb67efc2b8cf95c4b5ab2a88257c8d60f5d4d9a0
-row_number and col_number are required to be filled in the trial upload template (layout) for the field map to display on the trial detail page of the uploaded trial.

**Comment by aco46** [comment]
View sample layout file (template):
 https://drive.google.com/open?id=0B0FrcaU107T_aktFMkFtU0xZVmM

**Comment by aco46** [comment]
subplot-level information added to field map plot popups via #681

**Comment by aco46** [comment]
-strokes colored for plots with reps and blocks.
-plots with checks are well differentiated with colored plots.
-ligands added for different color code.
committed via c4e7bae9144265ff58414756a429dd35b898c1bd
