### ISSUE TITLE
solanaceae project page broken

### ISSUE THREAD

**Issue by noefp** [solgenomics/sgn#632]
https://solgenomics.net/solanaceae-project/index.pl

https://github.com/solgenomics/sgn/blob/001db97ba69a7e0bbc0872f9ff33d3e037ad9611/mason/projects/solanaceae_project.mas

**Comment by noefp** [comment]
The page was commented out and replaced by a YamBase page. I recovered the previous version

**Comment by suryasaha** [comment]
NCBI tomato genome page has incorrect link.
https://www.ncbi.nlm.nih.gov/genome/?term=tomato#

Submitted ticket to NCBI Case #: CAS-280526-Q1F8D1
The link for the reference genome submitter goes to http://www.sgn.cornell.edu/solanaceae-project/index.html
It should be https://solgenomics.net/solanaceae-project/index.pl
