### ISSUE TITLE
Remove populations as parents from the pedigrees with open cross type. Fix pedigree upload code to not add the population for the open cross type.

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#642]

**Comment by lukasmueller** [comment]
code fixed in 4c5e6b22360b057c45185f768abe9911502ffc5c and 5b492ff77e0079ad918c716b7c37b386a8a13c01

**Comment by lukasmueller** [comment]
Need to fix data that is already loaded.

**Comment by lukasmueller** [comment]
Need to run the SQL statement "delete from stock where type_id=76441 and uniquename ilike '%_open'". Web server may have to be shut down for this to work... ?

**Comment by bauchetg** [comment]
There is no more stock uniquename associated with that statement, can we close this issue?
