### ISSUE TITLE
During phenotype upload check if the trait is a variable

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#644]
Check if it has a variable_of relationship.
Will query variables from materialized view.

**Comment by nickmorales** [comment]
list validation for a trait should fail for non-variables?

**Comment by nickmorales** [comment]
should this check occur on a cvtermprop rather than a cvterm_relationship?
the current system of checking for a cvterm_relationship assumes that the ontology was structured and loaded with variable_of relationships.

**Comment by bauchetg** [comment]
list validation for a trait should fail for non-variables?
In case we have Trait, Method and Scale, failing while using these single  codes  instead of the variable make sense. Maybe it cannot apply for all ontologies we are using? Naama what do you think?

**Comment by nmenda** [comment]
I think cvterm_relationship is better to use. I think cassbase is the only one that does not have this relationship, so maybe consider changing this and add variable_of relationship to the cassbase ontology

**Comment by nickmorales** [comment]
I think yambase also has this issue

**Comment by nmenda** [comment]
yambase right now just has a flat list of variables since we could not wait anymore for CO to get their release ready , but it should have the variable_of relationship when we finally get a working copy

**Comment by nickmorales** [comment]
ok, i changed the cassbase terms to use the variable_of cvterm_relationship.
do we agree then that during upload and trait list validation there will be
a check for the cvterm_relationship?

**Comment by bauchetg** [comment]
I think it is a very good feature

**Comment by nmenda** [comment]
sounds good to me!

**Comment by nickmorales** [comment]
def0b11c3a3dba3e41401405e0da00838194bb72
