### ISSUE TITLE
Uploading images to accession doesn t work

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#648]
When uploading a photograph " [Add new image] "to the "image" section, an error message is displayed when clicking "Store in SGN database":
"Caught exception in SGN::Controller::Image->store "Sorry, can't convert image dece3vTYcv.png to dece3vTYcv.JPG at /usr/local/share/website/cxgn-corelibs/lib/CXGN/Image.pm line 496."

Maybe related to a previous issue (closed)?  stock images are broken #78

**Comment by nickmorales** [comment]
On which server was this? Seems like sudo apt-get install imagemagick would solve this

**Comment by lukasmueller** [comment]
Confirming that imagemagick needs to be installed for this.

**Comment by bauchetg** [comment]
It doesnt work in Musabase live and test sites

**Comment by bauchetg** [comment]
fixed on test site:
-creating  folders image_dir /images/image_files_musa_test
 and image_path /export/prod/public/images/image_files_musa_test
-adding them in  sgn_local.conf
-changing dir permission on /export/prod/tmp/

Live site still has a bug

**Comment by bauchetg** [comment]
closed 

fixed on both live and test site:
static_content_path       /export/prod/public_musabase/static_content
image_dir                 /images/image_files
image_path                /export/prod/public_musabase/images/image_files
