### ISSUE TITLE
manage -> crosses page crashes in cassavabase 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#649]
https://cassavabase.org/breeders/crosses/
404 - not found

**Comment by bellerbrock** [comment]
I think this is related to todays site update - looks like the sgn repo was updated, but we need to do a git pull on the master branch in the cassava specific mason repo

**Comment by bellerbrock** [comment]
done. new link under manage goes to https://cassavabase.org/breeders/nurseries_and_crosses/
