### ISSUE TITLE
Hide accession descendants graph if there are more than a certain number of direct descendants

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#652]
The descendants graph gets too small to invisible when there are too many direct descendants on the graph.

**Comment by lukasmueller** [comment]
Fixed via fd86c4c3859a0c823c0abae838bb0b1f4b2845ca.

**Comment by lukasmueller** [comment]
To do: check also children of children recursively.

**Comment by nickmorales** [comment]
#1486
