### ISSUE TITLE
Creating plant entries in 08uyt16PD2Ib on cassava test throws error

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#654]
Error in /var/logs/sgn/access.log:

 ... creating plants for plot 105...
 ... creating plants for plot 301...
 ... creating plants for plot 213...
 ... creating plants for plot 111...
 ... creating plants for plot 408...
 ... creating plants for plot 209...
 ... creating plants for plot 216...
 ... creating plants for plot 411...
Plant entities created.
An error occurred creating the plant entities. DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "projectprop_c1"
DETAIL:  Key (project_id, type_id, rank)=(359, 77203, 0) already exists. [for Statement "INSERT INTO projectprop ( project_id, type_id, value) VALUES ( ?, ?, ? ) RETURNING projectprop_id" with ParamValues: 1='359', 2='77203', 3='5'] at lib/CXGN/Trial.pm line 1306

**Comment by nickmorales** [comment]
Seems like it was created ok? did you try to create the plant entries twice?

**Comment by bellerbrock** [comment]
Right, it seems this error only occurs if a user tries to add plant entries to a trial where they already exist. Which is normally not even possible; I could only reproduce it by opening two trial detail pages for a single trial at the same time, adding plants entries on one page, then trying to add them again on the second page.

It's probably not a high priority, but I suppose we could make it possible to add additional or delete plant entries from a trial if for some reason there are too many or too few of them.
