### ISSUE TITLE
Add suggested improvements to selection index tool

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#659]
Rename tool in dropdown. (Ranking tool? Rank accessions . . .?)
Add placeholders in select boxes. 
Add remove button so users can remove selected traits. 
Make ability to select additional traits more intuitive by moving trait select to last row in table. 
Add way to save a SIN formula. 
Add ability to save top % or # of ranked accessions to a list. 
Add info section or popup to explain how calculations are done. 
Add ability to rank accessions based on phenotypes from multiple trials of the same type, making sure to include a warning that only raw values are used, and important statistical adjustments may not be taken into account.

**Comment by bellerbrock** [comment]
The ideal implementation for multiple locations and years would be to estimate the BLUP and then apply the economic weight

**Comment by bauchetg** [comment]
We can generate blup values using trial analysis. For Selection index on a location basis , it is common to use standardized values for each trait (trait value -mean)/standard deviation)*coef you want to apply.

**Comment by bellerbrock** [comment]
Good idea, thanks for the additional info Guillaume! 
Another item for the list of fixes/improvements: Issac's feedback here: #666

**Comment by bauchetg** [comment]
Add a list option as export format for the rankings

**Comment by bauchetg** [comment]
-Allow ability to remove trait variables selected to build the selection index
-Scaling  of SI values based accessions should preferentially be done with identified checks in the trial (notification when no check available).
-Allow combination of multiple checks ouputs (performance regarding a particular check is usually related to a particular trait associated to that trait)

**Comment by bellerbrock** [comment]
closed with merge of pull request #710. Merged branch implements:
-placeholders in select boxes. 
-remove buttons so users can remove selected traits. 
-makes ability to select additional traits more intuitive by moving trait select to last row in table. 
-adds ability to save top % or # of ranked accessions to a list. 
-autoreset of whole tool when a new trial is selected

some requested features are still missing, but have been added in a new issue: #717
