### ISSUE TITLE
Add sub-sub plot level info to trial layout for fine phenotyping  on plant organ/plant cycle 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#660]
For musabase and maybe cassbase?
-Set plant based phenotyping as "cycle based phenotyping in musabase"
-A sub-sub plot level may be required: 
Plot/Plant/Organ  for fine phenotyping at plant organ level (ex: first inflorescence, second inflorescence), In banana this would be: Plot/Cycle/plant.
- Uploading historical data (field layouts) on a plant/cycle basis is not possible.

**Comment by lukasmueller** [comment]
My suggestion would be to bake that sub-information into the ontology annotation, using post-composing of terms (first cycle, second cycle could be ontology term etc)

**Comment by bauchetg** [comment]
addressed through musa plant level/post composed ontology  #1497
