### ISSUE TITLE
ability to list accessions by location including ones not necessarly associated to trial data

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#661]
Similar as for #658 , when looking at available germplasm in a given location, all the accessions that are not linked to an experiment are not visible. Should these be optionnaly or systematically displayed?

**Comment by lukasmueller** [comment]
There is no link to a location when it has not been used in trials... Would that be a location where it was collected or observed etc.?

**Comment by bauchetg** [comment]
Yes this usually has to do with germplasm conserved in a particular place without being necessary evaluated, typically a set of genetic ressources in a genebank.
This may need to be adressed through a specific experiment type? to be discussed

**Comment by aco46** [comment]
David is also asking for a similar feature in yambase that has to do with accessions and their sourced locations.

**Comment by nickmorales** [comment]
many stockprops can be linked to an accession. this is configurable in the sgn_local.conf in the editable_stock_props

in sgn by default the options are: organization,variety,donor,donor institute,donor PUI,country of origin,state,institute code,institute name,biological status of accession code,notes,accession number,PUI,seed source,type of germplasm storage code,acquisition date

i can add an option to search over these in the accession search

**Comment by bauchetg** [comment]
@nickmorales, all these field are valuable, the most relevant ones could vary from a crop to an other
I would make them all available in the search menu.
For infos, I think "PUI" stands for permanent unique ID (like in the USDA PI code system)

**Comment by nickmorales** [comment]
#1004 adds a search option in stock search page for properties defined in editable_stock_props
