### ISSUE TITLE
Most trials on cassavabase returns datatable error when viewing assayed traits.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#687]
<img width="944" alt="screen shot 2016-09-30 at 11 54 36 am" src="https://cloud.githubusercontent.com/assets/10618260/18998128/3fb55faa-8705-11e6-8c31-58bbc0a9c4ba.png">

see trial link: https://cassavabase.org/breeders/trial/509?format=

**Comment by nickmorales** [comment]
has to do with: 
$cv = ($stddev /  $average) * 100;

was not checking if $average = 0, and was crashing
