### ISSUE TITLE
Wrong error message while verification of phenotype upload 

### ISSUE THREAD

**Issue by pvnsprasad** [solgenomics/sgn#689]
Verification of phenotype upload gives error message for traits ease of peeling root cortex visual rating 1-7|CO:0000116 and storage root size visual rating 1-7|CO:0000019 for the value 2 which is with in the range.

**Comment by aco46** [comment]
-could you check if the value you have on your file is 2 or 2.0?
-ensure it's 2 and not 2.0

**Comment by pvnsprasad** [comment]
Fola clarified that it should be 3 not 2 for storage root size.
