### ISSUE TITLE
Trial 14.GS.C0.PYT88IK has harvest index values that exceed 1,000,000.

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#694]
cxgn_cassava=# select distinct(project.name) from phenotype join nd_experiment_phenotype using(phenotype_id) join nd_experiment_project using(nd_experiment_id) join project using(project_id) where phenotype_id in (select phenotype_id from phenotype where value !~ '[A-Za-z*./-\,`\n ]+' and value::REAL > 1000000);
##        name       

 14.GS.C0.PYT88IK
(1 row)

**Comment by bauchetg** [comment]
@aafolabi Only found 14.GS.C0.PYT88IB, without such outlir
https://cassavabase.org/breeders/trial/1633?format=
14.GS.C0.PYT88IK doesnt seem to exist anymore
