### ISSUE TITLE
SolGS workshop feedbacks

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#703]
While selecting:
"Select a training population or create a new one using one or more trials" if a single trial is selected, the "combined and run" button doesn t get through. Should send the user to training population page.

Display of frequency distribution:
From Moshood: distribution should be barplot for qualitative traits and histogram for quantitative variable to reflect better the variation

**Comment by bauchetg** [comment]
Graph and figures shoud be downloadable (pdf or jpeg)

**Comment by bauchetg** [comment]
From Peter: while outputting GEBVs by accessions the clone names are incremented of a "1" value

**Comment by bauchetg** [comment]
Accessions with best predictions could be output as a list and thus used with other tools in the db.

**Comment by bauchetg** [comment]
In  " model summary" , "population description",  the heritability value is left as blank when GEBVs are too low.

**Comment by isaak** [comment]
most of them addressed...
