### ISSUE TITLE
list tool and options improvements

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#724]
From the workshop:

-From the list menu: the "combine" option should warn the user when combining different list types, ex: combining an "accession" list with a "trait" list.

-From trial tree:  while using "move trials to folder" a list option would be useful.

-From Crossings: a new list type entitled "cross" or "crossings" would help to manage the hundred or thousands cross that can be generated and distinct them from "trial"

**Comment by nickmorales** [comment]
warning to combine lists: ad316109967d010805214bf1b33d0fc356b966f7

discussed folder list and decided against it. instead made trial list alphabetical c224119862dfbc4e15a31be5105e32c2269fb65a

"crosses" list type added in: ccb5ee7d1326b962e76d54aba6d45e3746ac576a
