### ISSUE TITLE
Add Calendar to cassavabase

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#725]

**Comment by nickmorales** [comment]
https://github.com/solgenomics/cassava/commit/5fb498b8ed8926f5657e388c0180690f683eb2d8

Calendar will show events (planting date, harvest date, etc) for trials that are part of a breeding program that the user has a role in.

**Comment by lukasmueller** [comment]
Move calendar option to menubar next to login name and list icon?

**Comment by nickmorales** [comment]
b21a5725b60772aa0d8a53d0f0b0f75cc972ee07
