### ISSUE TITLE
better file checking during phenotype upload

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#727]
Phenotype upload failure is almost always due to some kind of hidden problem with the file being uploaded. 
The system should return informative error messages instead of silently failing (endless spinning wheel).

**Comment by aco46** [comment]
The option of creating and downloading a phenotype upload template from the trial detail page of a trial has taken care of this ticket. However, if users report any new cases of phenotype upload error, we would use the feed back to fix the error.
