### ISSUE TITLE
List validation on Cassabase often times return error message

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#728]
![screen shot 2016-10-25 at 5 20 21 pm](https://cloud.githubusercontent.com/assets/10618260/19704830/5b43c53c-9ad7-11e6-9c1f-a380095fa2dc.png)

**Comment by lukasmueller** [comment]
This happens usually on Safari because we use sync ajax calls for which Safari only waits 10 seconds. One easy solution: Sped up validation of lists?

**Comment by nickmorales** [comment]
@aco46 Do you know what kind of list this is an issue for? accessions, trials, etc?

**Comment by aco46** [comment]
It's for accessions.

**Comment by nickmorales** [comment]
speed should no longer be an issue when validating accessions, but you can reopen this issue if the problem persists with other lists
