### ISSUE TITLE
On trial page, provide an entry for source trials

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#742]
The trial detail page should have a trial entry specifying the trials the clones came from. Should be implemented using project_relationship.

**Comment by bellerbrock** [comment]
Ok, just to clarify, the idea is to have this displayed in the trial details or design section as a list of one or more source trials? 

Also, it will start out unset for existing trials. Should it be included as an optional or mandatory field in the add or upload trial dialogs?

**Comment by bauchetg** [comment]
Hey Bryan, in most case it should be a unique source trial (multiple may be requested in some cases, ex: GxE experiments).
The source should be part of the trial details, it could be added to the trial creation dialog as an optional field list as well.

**Comment by bellerbrock** [comment]
Implemented by Nick 0c31e562c03c6eb6bcc3bed391211f517e3118bb
