### ISSUE TITLE
create a materialized view for stockprops , decide which props are mandatory

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#743]
we have many stock properties used in the phenotype download 
https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Phenotypes/Search.pm#L194

and in the trial layout object 
https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Trial/TrialLayout.pm#L210

need a view for making the download faster, and to avoid using left joins (some trials do not have all of these properties loaded, and we may not want to load any of these retroactively)
https://github.com/solgenomics/sgn/blob/master/lib/CXGN/Phenotypes/Search.pm#L199

For trial/phenotype data uploading - need to decide which stockprops and projectprops are mandatory (e.g. trial year, plot replicate #) and implement checks in the backend objects (Trial, Phenotype) so the loading scripts fail if these are not loaded.

**Comment by nickmorales** [comment]
These projectprops should be mandatory i think, for all trials in all of the databases:
project year,
project location,
design

**Comment by nickmorales** [comment]
stockprops of interest are:
block_number,
replicate,
plot_number,
is_a_control,
row_number,
column_number
