### ISSUE TITLE
Add a comment 'trait' 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#745]
NCSU is interested in adding a comment 'trait' that is separate, but phenotyped using the fieldbook liek traits in the ontology. It would get stored as the plot description, and plot descriptions could all be pulled into the accession descriptions on the accession detail page.

**Comment by lukasmueller** [comment]
Need to coordinate with Crop Ontology?

**Comment by lukasmueller** [comment]
Maybe not?

**Comment by bauchetg** [comment]
Also requested by the banana group in UG

**Comment by bellerbrock** [comment]
Requested again by NCSU - they want to search all their comments from their clonal evaluation trial last year to see what accessions were described as having high set of roots, based on that they will start making grafts for a new crossing nursery next week

I'm thinking the best way to handle comments may be separate from trait ontologies. Uploaders could include the optional column 'description' in their upload file, and it would be stored as /appended to the stock description. Accession description could import and display subject plot descriptions. Finally a search tool could be added to search across the text of stock descriptions.

**Comment by bellerbrock** [comment]
Mostly implemented in topic/comments_as_descriptions. Comments must be uploaded as 'notes' and are stored as a stockprop for the plot. Stock search in enhanced to make searching across the text of notes more flexible. 

I'm also thinking it may be helpful to add an option to inlcude notes in phenotype file downloads, and somehow associate them to parent accessions. And still considering how best to handle multiple distinct note types. For example NCSU records 3 open-ended text traits - 'Keep Advantages','Why Drop', and then general comments
