### ISSUE TITLE
Add partially replicated design as an additional trial design type/option.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#747]
Asrat has requested the addition of partially replicated design  for use in yam breeding.

**Comment by aco46** [comment]
Partially replicated design (p-rep design) is a design in which all treatment are not replicated equally.

Example (unequal replication):
v = 21 treatments
k = 7 rows
s = 8 columns
7 treatments replicated twice
14 treatments replicated three times
-In other examples, some treatments may be replicated twice while some treatments are  un-replicated.

property
-there is sufficient replication, based on a subset of treatments, to allow a valid estimation of the error variance.

usage
-restricted to early-generation testing in plant breeding where seeds of new candidate lines is usually limited.

software
-CycDesigN (VSN-International, https://www.vsni.co.uk)
-DiGGer (available in R, can.r-project.org)
-'proc optex' in SAS can also be used 

Article for more info on p-rep design.
[CBCS_10_2_5.pdf](https://github.com/solgenomics/sgn/files/744993/CBCS_10_2_5.pdf)

**Comment by bauchetg** [comment]
@aco46: the DiGGer "prd" design function works well on a windows instance, trying to figure out why it doesn ton linux.

**Comment by bauchetg** [comment]
Works fine using "DiGGer_1.0.1_R_x86_64-pc-linux-gnu.tar.gz" package distribution.

**Comment by aco46** [comment]
closed via #1250
