### ISSUE TITLE
Add ploidy information for yam accessions and an option to retrieve accessions in the wizard base on their ploidy levels.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#748]

**Comment by bauchetg** [comment]
see #397 too

**Comment by aco46** [comment]
Forgot there was an existing ticket for that.

**Comment by bauchetg** [comment]
partially addressed (ploidy information upload) through #1514

**Comment by bauchetg** [comment]
Hi Lukas, 
It may be hard to implement in the wizard BUT... :-) :

Having stockprops available in the Wizard would allow their data parsing in a similar way as the current implementation for traits.

Such implementation would grant user the ability to sort their data in (almost) all dimensions: traits+ props
In a selected trial you may have plant material from different source (country, breeders) or types (ie: ploidy, genetic groups, cultivation types, market types).

 Or is there an other (existing) way parsing multiple trial data on a trait+props basis? Can the technical feasibility be assessed ?
