### ISSUE TITLE
Add the concept of seed lot in the database.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#749]

**Comment by lukasmueller** [comment]
Ticket meeting discussion: implement seed tracking as a transactional model with a new entity called seed lot, which is associated to one (generalyy) or possibly more accessions. Seedlots would be a new stock type, and the transactions would be stock_relationships.

**Comment by aco46** [comment]
seed lot stock type should include information about the source and storage location.

**Comment by lukasmueller** [comment]
this is in the topic/seedlot branch.

**Comment by nickmorales** [comment]
40fba981d15da5aabad1f6983d9ef99d1f372d21
