### ISSUE TITLE
news feed

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#752]
the last item is from Dec 2015. No more news???

**Comment by lukasmueller** [comment]
maybe switch to another one?

**Comment by bauchetg** [comment]
maybe we could be replace by:
http://www.nature.com/subjects/plant-breeding.rss
or
https://www.eurekalert.org/rss/agriculture.xml

**Comment by lukasmueller** [comment]
Removed (commented-out) relevant section in index.mas in cassava repo, commit b9a7e86e233318422a3c049df41362dc66c3fa32
