### ISSUE TITLE
folder structure visible from both crosses and field trials sections

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#754]
In "Manage" for both "Crosses" and "Field trials", the folder structure remains visible on both side which can be very confusing as folders created from one side appear empty in the other.
We can keep them as well as their content on both sides by adding a color code and/or make it an optional display ("show trial folders"  and "show crossing folders").

**Comment by nickmorales** [comment]
the thing is as it is right now (i'm not sure if this is a feature), a single folder can contain both trials AND crosses. so "show trial folders" and "show crossing folders" is not really possible. should folders be separated then?

**Comment by pvnsprasad** [comment]
There was a folder called cross demo under IITA breeding program in manage Field trials, I was not successful to delete that  folder from there so i have moved it in to Eastern Africa.

**Comment by pvnsprasad** [comment]
Yes, I think we can use the same folder structure for both, if it is not very confusing.

**Comment by bauchetg** [comment]
So in this case, giving a distinct color/icon to the crossing and trial folders maybe desirable.

**Comment by nickmorales** [comment]
Hi Prasad you could not delete the 'cross demo' folder because it still has lots of crosses in it.

I think I'm confused whether we should allow a single folder to contain both trials AND folders, or should a single folder be designated for only containing trials OR only containing crosses?

**Comment by nickmorales** [comment]
folders which have already been created will need to be set from the folder's page
