### ISSUE TITLE
wizard search for genotyping plate  doesn t give outputs

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#757]
When querying  "trial design" -> "genotyping_plate" the output doesn t give any result. 
Is the corresponding materialized view missing?
There are several genotyping trials available (ie: [https://cassavabase.org/breeders/trial/1741?format=](https://cassavabase.org/breeders/trial/1741?format=))

**Comment by bellerbrock** [comment]
Hmm, good point. Only phenotyping trials are included in the existing views, that's why no results are displayed.
I'm not sure how best to go about it yet, but this could be addressed in the next update along with including actual genotyping scores in JSONB format.

**Comment by lukasmueller** [comment]
I think this has been resolved. Please re-open if not.
