### ISSUE TITLE
Include role management in breeding program creation and deletion functions

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#784]
Many breeding program roles are missing from the the sgn_people.sp_roles table in our breeding databases. Maybe these roles should automatically be created and deleted at the same time as the breeding programs? 

It would also be nice, at the same time, to assign a new program role to whichever account created the program. And to include the assignment of a breeding program role/roles as an option during account creation.

**Comment by bauchetg** [comment]
See as well #753

**Comment by lukasmueller** [comment]
Breeding programs can only be created by curators, they should not be assigned automatically, but roles should be created for each added program.
