### ISSUE TITLE
Can't access trial detail page from "Manage" "Trial"

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#786]
Cant access trial content, It retrieves:

Caught exception in SGN::Controller::BreedersToolbox::Trial->trial_info "Can't call method "cvterm_id" on an undefined value at lib/CXGN/Trial/Folder.pm line 88."
The issue as to do with folder/trial cvterm identification 
In the same commit trialtreefolders.mas was modified.
We could not point the exact problem so we reverted to tag SGN 196 for now on cassava_test

**Comment by bellerbrock** [comment]
Ok, I think what's going on here is that Nick added folder cvterms, and we ran patch 00077 to add them to the dbs. But this error makes it look like the patch wasn't run. Looking at sgn_local.conf, I see why - I ran the patch on sandbox_cassava, but the test site is pointed at a db called sandbox_cassava_b4patch

**Comment by bellerbrock** [comment]
So we need to either run patch 00077 on that db, or change the db to sandbox_cassava

**Comment by bauchetg** [comment]
Thanks Bryan! my bad I switched to this "B4patch" dump to get some trials back

**Comment by bauchetg** [comment]
Closed applying path 00071
