### ISSUE TITLE
wizard large genotyping datasets download fails

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#788]
On cassava-devel, the new v6_june2016 genotyping named "protocol" contains 350,000 SNP. It works well for a single accession, when downloading a whole trial ("13geneticgainIB", >600 accessions) the wizard download times out before finishing "502 Bad Gateway" an give the following
Access log:
(Query)
Decoding genotype data ...Wed Dec 14 03:19:05 2016
Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/share/website/local-lib/lib/perl5/Net/Server/SIG.pm line 72, <$read> line 131.
worker 9573 died unexpectedly with status:1024, restarting
starting new worker 11571
Use of qw(...) as parentheses is deprecated at /usr/local/share/website/ITAG/lib/CXGN/ITAG/Pipeline.pm line 227.
DEPRECATION WARNING: The Regex dispatch type is deprecated.
  The standalone Catalyst::DispatchType::Regex distribution
  has been temporarily included as a prerequisite of
  Catalyst::Runtime, but will be dropped in the future. Convert
  to Chained methods or include Catalyst::DispatchType::Regex
  as a prerequisite for your application.

**Comment by lukasmueller** [comment]
Maybe to due lower RAM setting on the cassava-devel site (production site is way bigger). Could this be tested?

**Comment by bauchetg** [comment]
@lukasmueller 
Similar "502 Bad Gateway" error on production site using the same trial.
The "sprintf" variable is not define in subroutine "get_shared_trials_GET" from lib/SGN/Controller/AJAX/Stock.pm
See enclosed log for more details

[log_seq_download.txt](https://github.com/solgenomics/sgn/files/917385/log_seq_download.txt)

**Comment by lukasmueller** [comment]
Adrian is working on a fix for this, changing the way BreederSearch returns data - instead of loading everything into RAM, use a iterator pattern to get the data.
