### ISSUE TITLE
make fuzzy search outputs downloadable as list 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#789]
related to #523

**Comment by bellerbrock** [comment]
Also related to #800. We could take the fuzzy search output modal from the add accessions workflow, and include it as an advanced option for accession list validation. And make the output downloadable.

**Comment by bauchetg** [comment]
The fuzzy search download option is highly requested by breeders and pathologists to curate their own germplasm informations.

**Comment by nickmorales** [comment]
#1004 fuzzy search output downloadable
