### ISSUE TITLE
move trial to folder function does not work with folders that don't have a projectprop entry with the cvterm for 'folder_for_trials' 

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#799]
Most existing trial folders don't have this prop, and some folders may be used for both crosses and trials. Should all existing folders be given one of these props? Or would it be better/simpler to exclude folders with the wrong prop?

**Comment by bellerbrock** [comment]
a potential implementation of the second fix is in topic/fix_folder_html_selects

**Comment by bauchetg** [comment]
@pvnsprasad @bellerbrock  Moving these trials from the folder moving option does work but does not the other way around, from the trial details page to the folder or from the trial tree page.

Ex:  trial "cassava ibadan 2005/2006" could be moved to "Western Africa", "05_Ibadan" folder

**Comment by nickmorales** [comment]
As it is now, you first have to set the folder to be for trials. It is set
from the folder's page (at the bottom left)
https://cassavabase.org/folder/2782

Once it is set as for trials and/or for crosses, then the folder will
appear when trying to move a trial or cross into it.

Hope that clarifies

On Thu, Jan 5, 2017 at 11:32 AM, Guillaume Bauchet <notifications@github.com

**Comment by bellerbrock** [comment]
Ok, so there is a way to fix this on an individual folder basis by setting the folder 'for trials' from it's folder detail page. 

to make the process easier we could make this same function available on the trial tree page, and allow users to select and modify multiple folders at once.
