### ISSUE TITLE
list tool generates subset list with validated accessions

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#800]
While validating a list of accessions, the list tool provides an option to generate subset list with missing accessions but does not offer a similar option to carry on with validated ones.

Opportunities to improve the display:
-When the list of missing accessions is long, it cannot be displayed properly, see below.
-Element not found could be displayed first, before offering to add missing (or non missing) accessions to a list.
![screen shot 2017-01-04 at 9 51 31 am](https://cloud.githubusercontent.com/assets/12039071/21646455/4a9e30f4-d264-11e6-9ecf-c4be4091bde2.png)

Somehow related to #661

**Comment by bauchetg** [comment]
For accessions, the "validate" step could be tightly linked to the upload  fuzzy search tool by giving two options:
-save them in a separated list (existing).
-load them  directly through the fuzzy search step.

**Comment by nickmorales** [comment]
#1004 validate accession list is more tightly linked to add accession process
