### ISSUE TITLE
wizard list based search rejects stock synonym list

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#805]
Using a validated accession list ("This list passed validation")  as input gives:
 "This lists contains elements that cannot be converted. Not converting list” 
and
 "Unable to retrieve ids from this list."

Maybe some accessions names define as synonyms are not identified by the Accessions2AccessionIds plugin to convert the accession names to ids.

All accessions failing have their name set as a synonym not as stock name:
Query      Actual stock name
I070738	 IITA-TMS-IBA070738
I083724	 IITA-TMS-IBA083724
I090522	 IITA-TMS-IBA090522
I090546	 IITA-TMS-IBA090546
I090574	 IITA-TMS-IBA090574
I090576	 IITA-TMS-IBA090576
I090581	 IITA-TMS-IBA090581
I090590	 IITA-TMS-IBA090590
I100449	 IITA-TMS-IBA100449
I101040	 IITA-TMS-IBA101040

To test see public list "wizard_accession_list_fails"

**Comment by bellerbrock** [comment]
Thanks Guillaume. I'm looking at CXGN::List::Transform::Plugin::Accessions2AccessionIds, and yep, it looks like it assumes list items are the stock uniquename. If we modify it to search using synonyms this problem should be fixed.

**Comment by bauchetg** [comment]
This bug has re-appeared :-(
Now, it would occur for stocks including various special characters (ie: $), such as: IJF*z**A$D
In this case it is no longer a uniquename/synonym issue but rather identification of special characters in wizard list parsing?
The stock example is correctly stored in the stock table, can be validated in list and would give a clean output in the search
