### ISSUE TITLE
phenotype rows with null values 

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#807]
968319 in cassavabase

**Comment by nickmorales** [comment]
older implementations of storephenotypes would save a null value in the phenotype table for any blanks in the supplied phenotype spreadsheet. the last null value was stored 2016-01-28. the current storephenotypes does not store null entries in the database.

**Comment by nmenda** [comment]
should those be deleted? these are not included in the list of traits on the trial/plat/plant levels

**Comment by nickmorales** [comment]
during storephenotypes validation give error if value contains space or is '.' or contains special characters

**Comment by nmenda** [comment]
most of the null values come from IITA trials (about 500 of them) + a handful from NaCRRI and NRCRI

count | project_id |                      name                      |  name  
-------+------------+------------------------------------------------+--------
  1729 |        190 | 11clonal63cpUM                                 | NRCRI
  3783 |        461 | Uganda Cassava Training Population Kasese_2013 | NaCRRI
   389 |        551 | Within Family Prediction Seedling Trial_2013   | NaCRRI
  4104 |        552 | 12nextgen500tp1UM                              | NRCRI
    27 |        603 | 13mlt12yrtUM                                   | NRCRI
     3 |        604 | 13mlt12yrtOT                                   | NRCRI
    26 |        605 | 13mlt12yrtIG                                   | NRCRI
 65436 |       1597 | 13nextgen518tp1UM                              | NRCRI
 19654 |       1598 | 13nextgen518tp1OT                              | NRCRI
 14431 |       1599 | 13nextgen518tp1KA                              | NRCRI
 18306 |       1600 | 13nextgen489tp2UM                              | NRCRI
    40 |       1618 | 13clonal261nr13UM                              | NRCRI
   182 |       1621 | 13mp70popfOT                                   | NRCRI
   598 |       1623 | 13mp259popdOT                                  | NRCRI
    28 |       1625 | 13cmd35gpOT                                    | NRCRI
  1302 |       1626 | 13mp144popdUM                                  | NRCRI
   261 |       1627 | 13cmd60gpUM                                    | NRCRI
    15 |       1628 | 12cmd36gpOT                                    | NRCRI
   347 |       1629 | 12cmd75gpUM                                    | NRCRI
    98 |       1630 | 11cmd48gpUM                                    | NRCRI
   564 |       1632 | Uganda Cassava Training Population Kasese_2014 | NaCRRI
   235 |       1642 | 15cb28cgmUM                                    | NRCRI
  3021 |       1647 | Uganda Cassava Training Population Ngetta_2014 | NaCRRI
 12666 |       1650 | Uganda Cassava Training Population Ngetta_2013 | NaCRRI

**Comment by nmenda** [comment]
Alex thinks some of the null values should have been loaded as '0' 
Look into the original uploaded files

**Comment by isaak** [comment]
What does '0' mean? not measured, as missing value? or is it real observed value?
