### ISSUE TITLE
NRCRI accessions in genotyping trial with no associated breeding prg.

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#808]
Several accessions  from NRCRI do not show up in the wizard although they are involved in a genotyping experiment.
Accessions can be found on live site public list "NRCRI_accessions_withnoBDprogram"
This is probably related with issue #696 and maybe #684

**Comment by bauchetg** [comment]
Actually related to missing materialized views for genotyping trials #757

**Comment by lukasmueller** [comment]
The genotyping trial views have been added so this should be fixed
