### ISSUE TITLE
Should the database synonymizes reciprocally two existing stocks?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#810]
When the name of an existing stock is added to an other existing stock:
"accession B" is a synonym of  "accession A" .
Is the stock relationship table updated reciprocally? 
"accession A" is also added as a synonym of  to "accession B" 
It does not seem like:
![screen shot 2017-01-09 at 6 39 20 pm](https://cloud.githubusercontent.com/assets/12039071/21788349/367cbd7a-d69c-11e6-9d83-b1a6a1d3473a.png)
 Should this be systematic within a given breeding program?
 Across different breeding programs the user could be notified?
related to #586

**Comment by lukasmueller** [comment]
The system should show a notification if a newly entered synonym has already been used as a stock name

**Comment by bauchetg** [comment]
Add automatic fuzzy search output in the accession detail page when adding manually a synonym
