### ISSUE TITLE
curate potential duplicated cassava accessions

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#812]
@aafolabi @pvnsprasad @aco46 

I found potential conflicts between accessions in cassavabase live site with very similar names and would like your help on finding:
a- If they are distinct/duplicated accessions. 
b- If you should leave/merge/delete them (with their related pedigree and phenotypic data)

##1##
"NR010004" (Ed.Peter-Chiedozie/data available) https://cassavabase.org/stock/39550/view AND "NR 010004" (Ed.Peter/data available) https://cassavabase.org/stock/31202/view
##2##
"X00214" (Ed.nocurator/data available/pedigree available) https://cassavabase.org/stock/44204/view AND "00/0214" (Ed.Peter/data available/pedigree available) https://cassavabase.org/stock/9530/view
##3##
"TMS92B00068" (Ed.Peter/data available/pedigree available) https://cassavabase.org/stock/42751/viewAND "TMS-B9200068" (Ed.Peter/data available/pedigree available) https://cassavabase.org/stock/427/view
##4##
"TMS-I4(2)1425" (Ed.Peter/data available/pedigree available) https://cassavabase.org/stock/246/view AND "TMS4(2)1425" (Ed.Alex Ogbonna/nodata/nopedigree) https://cassavabase.org/stock/397093/view
##5##
"NR051653" (Ed.Alex Ogbonna/nodata/nopedigree)  https://cassavabase.org/stock/397084/view AND "5/1653"  (Ed.Peter Kulakow Agbona Afolabi/data available/nopedigree) https://cassavabase.org/stock/28456/view
##6##
"MM96JW1" (Ed.Peter/data available/pedigree available) https://cassavabase.org/stock/1787/view AND  "IITA-TMS-MM96JW1" (Ed.Agbona Afolabi/data available/nopedigree) https://cassavabase.org/stock/75208/view
##7##
"TMS 94/0006" ( Ed.Peter Kulakow Agbona Afolabi Dina Dolapo/data available/pedigree available) https://cassavabase.org/stock/487/view  AND "W 94/0006" (nocurator/data available/pedigree available) https://cassavabase.org/stock/43292/view

**Comment by bauchetg** [comment]
More generally I find a large number of accessions with similar name structure like:
"IITA-TMS-IBA061771" (> 10000s) and  "TMS061771" (>100s).
Are the distinct or the same but different naming between IITA and NRCRI?

**Comment by aco46** [comment]
NR010004 and NR 010004 are the same. They should be merged.

X00214 was only used in a trial in NRCRI but 00/0214 was used in several trials involving IITA. If NRCRI got the material from IITA (not sure though) then they maybe the same. We need to find out the correct name from IITA and then confirm from NRCRI if they are different materials.

TMS92B00068 and TMS-B9200068 should be same. It's an IITA material (hopefully @fola will confirm this).


TMS-I4(2)1425 is associated to IITA trials but TMS4(2)1425 is not associated to any trial. It's a material from IITA. I guess NRCRI may have removed 'I' from the name which stands for Ibadan. TMS4(2)1425 could be made a synonym of TMS-I4(2)1425.

There's every chance that NR051653 might be 5/1653 given that it's not been used in any trial.

**Comment by aafolabi** [comment]
I have not seen any NRCRI clones with prefix "X" before. I think we only need to clarification from NRCRI. However, IBA000214 is a valid IITA clone.

TMS92B00068, TMSB9200068, IITA-TMS-B9200068, IITA-TMS-BAD9200068 are the same.

4(2)1425 is an IITA clone. regardless of how it is been used, let's use the official name IITA-TMS-IBA4(2)1425

IITA-TMS-IBA051653 is a valid IITA clone. Confirm from NRCRI if NR051653 exist.

W94/0006 is not  a valid IITA clone name. IBA940006 (IITA-TMS-IBA940006, IBA940006) is the valid clone.

MM96JW1 and IITA-TMS-MM96JW1 (UG mid altitude clones) can be used synonymously.

IITA-TMS-IBA061771 and TMS061771 can be used synonymously

**Comment by bauchetg** [comment]
@aafolabi @pvnsprasad 
Here is a list of duplicated accession, almost all from NACRRI, this is a conflict between GBS data ID and stock ID.
Just have a look to the five first ones
CPCR27B_30
F10_30_R2
KBH2006_26
KBH2006_26
M_TAI_25
UG14_0021
UG14_0030
UG14_0071
UG14_0074
UG14_0093
UG14_0185
UG14_0223
UG14_0250
UG14_0265
UG14_0302
UG14_0335
UG14_0349
UG14_0441
UG14_0447
UG14_0740
UG14_0747
UG14_0818
UG14_0989
UG14_1016
UG14_1028
UG14_1034
UG14_1192
UG14_1254
UG14_1264
UG14_1318
UG14_1350
UG14_1353
UG14_1385
UG14_1502
UG14_1513
UG14_1539
UG14_1542
UG14_1595
UG14_1659
UG14_1664
UG14_1746
UG14_1800
UG14_1850
UG14_1884
UG14_1896
UG14_1967
UG14_2035
UG14_2061
UG14_2080
UG14_2091
UG14_2095
UG14_2124
UG14_2146
UG14_2159
UG14_2180

**Comment by bauchetg** [comment]
The following list of accessions "TMS" format from NRCRI have an exact equivalent in "IITA-TMS-IBA" format. They may need to be synonymised/merged accordingly.
TMS000203
TMS000210
TMS000338
TMS000346
TMS000354
TMS000355
TMS000364
TMS000388
TMS010034
TMS010040
TMS010046
TMS010085
TMS010090
TMS010093
TMS010098
TMS010103
TMS010131
TMS010134
TMS010169
TMS010903
TMS011086
TMS011097
TMS011115
TMS011206
TMS011235
TMS011331
TMS011368
TMS011371
TMS011412
TMS011413
TMS011442
TMS011560
TMS011610
TMS011663
TMS011731
TMS011797
TMS011807
TMS050024
TMS050100
TMS050125
TMS050127
TMS050128
TMS050186
TMS050231
TMS050251
TMS050286
TMS050303
TMS050311
TMS050327
TMS050473
TMS050741
TMS051274
TMS051553
TMS051570
TMS051599
TMS051600
TMS051601
TMS051625
TMS051626
TMS051631
TMS051632
TMS051636
TMS051646
TMS051652
TMS051653
TMS051654
TMS051658
TMS051740
TMS051814
TMS061771
TMS062426
TMS070481
TMS070525
TMS070539
TMS070553
TMS070576
TMS070614
TMS070620
TMS070632
TMS070649
TMS070675
TMS070749
TMS070756
TMS070808
TMS070824
TMS070835
TMS070874
TMS070952
TMS070962
TMS070974
TMS070982
TMS30555
TMS30572
TMS63397
TMS9102324
TMS920057
TMS920067
TMS920326
TMS930078
TMS940330
TMS950211
TMS950289
TMS950379
TMS960035
TMS961089A
TMS961569
TMS961632
TMS961708
TMS970211
TMS972205
TMS980002
TMS980505
TMS980510
TMS980581
TMS982101
TMS990240
TMS990554
TMS990558
TMS992123

**Comment by bauchetg** [comment]
These other "TMS" from NRCRI do not have IITA-TMS- equivalents yet in the database, but may need some in the future.
TMS070863
TMS30555200GY-12
TMS30555200GY-14
TMS30555200GY-21
TMS30572-7
TMS419
TMS85-10(8411)
TMS870052
TMS892831
TMS911730
TMS920068
TMS920168
TMS92B0068
TMS950414
TMS961413
TMS970057
TMS982123
X.TMS050998
X.TMS051662
X.TMS982132
TMS010128
TMS010632
TMS020018
TMS0330555
TMS050540
TMS050751
TMS050752
TMS051358
TMS051371
TMS051412
TMS070099
TMS070352
TMS070489

**Comment by bauchetg** [comment]
Extra batch of duplication from NaCRRI: 1570 accessions
UG14_X030 and UG14X030  from Kamuli and Lira Farmers trial

**Comment by pvnsprasad** [comment]
[Pedigree_Problems.xlsx](https://github.com/solgenomics/sgn/files/954741/Pedigree_Problems.xlsx)

I have found 89 clones (unique names) that have been duplicated in db, most of them are with _open which are generated during the pedigree upload and with stock type as population, which i think can be removed, so only 09 clones (IITA-TMS-IBA011371, IITA-TMS-IBA011368, IITA-TMS-IBA070539, IITA-TMS-IBA061404, IITA-TMS-IBA061365, IITA-TMS-IBA061679, IITA-TMS-IBA011412, IITA-TMS-IBA070553, SM3360-6) need to be checked.

**Comment by bauchetg** [comment]
extra sets merged:
[Set_1.txt](https://github.com/solgenomics/sgn/files/1081757/Set_1.txt)
[Set_2.txt](https://github.com/solgenomics/sgn/files/1081758/Set_2.txt)
[Set_3.txt](https://github.com/solgenomics/sgn/files/1081759/Set_3.txt)
[Set_4.txt](https://github.com/solgenomics/sgn/files/1081760/Set_4.txt)
[Set_5.txt](https://github.com/solgenomics/sgn/files/1081763/Set_5.txt)

**Comment by wolfemd** [comment]
@bauchetg @pvnsprasad germplasmName "MIGERA" (https://www.cassavabase.org/stock/1774/view) should be merged with IITA-TMS-IBA30572 (https://www.cassavabase.org/stock/5/view)

**Comment by bauchetg** [comment]
Merge 
NAMIKONGA https://cassavabase.org/stock/610859/view (resequencing data)
NamikongaJGI https://cassavabase.org/stock/626691/view (resequencing data)
UG110043 https://cassavabase.org/stock/388968/view (breeding data)
with 
Namikonga https://cassavabase.org/stock/38772/view (breeding data)

**Comment by wolfemd** [comment]
Guillaume asked me to share some documents and comments about C-base data / gemrplasmNames here.

**Master List of GBS samples from each Breeding Program**
https://drive.google.com/file/d/1LYVTvGXPtUFNeHTU7vsjlKThThIQRQ8n/view?usp=sharing

**Comment by wolfemd** [comment]
In the process of making these files, I've taken notes on some naming / curation needs.

Should I put phenotypic trial issues here too? I was thinking just germ plasm-stuff?

**IITA**
- Among the N GBS records==0
IITA-TMS-IBA98I0875
IITA-TMS-IBA98I1081
Both of these examples were listed under “Groups” as being in an ExpCET. The expanded clonal trials are recent and used on GS C1 and C2… the fact that these clones were in those trials suggests they were genomic selection parents and thus must be genotyped. There is a also a "IITA-TMS-IBA981081” with germplasmSynonym “98I1081”… but still no DNA record found

- It would be really useful to put e.g. I000146 as a synonym for IITA-TMS-IBA000146
- There is a block of names like "IBA13:10214:0016”… are these records for the GS_C1
Also a set of “TMS13F”, “TMS14F” and even “TMS15F" which surprisingly don’t get DNA matches…

**NRCRI**
Noticed the following:
germplasmName = “"GCO322P6”
germplasmSynonyms = “GCO322P9”

**Comment by wolfemd** [comment]
Great! Thanks for the update!

**Comment by bauchetg** [comment]
ok Set_6.txt was merged in production

**Comment by bauchetg** [comment]
@pvnsprasad we have about 19 stocks tagged with (2x)  and 135 tagged  (4x) info like:
IITA-TMS-IBA9102324
Is "IITA-TMS-IBA9102324" not the same as "IITA-TMS-IBA9102324(2x)?
