### ISSUE TITLE
ontology trait definition doesn t match actual scale checked when uploading

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#824]
From @pvnsprasad files definition and data checking needs to be harmonized for two traits:
For "root neck length visual rating 0-7|CO:0000022" the actual trait value range checked is 3/5/7
@aafolabi : which one is the right scale? 0-7 or 3/5/7?
ease of peeling root cortex visual rating 1-7|CO:0000116 the actual trait value range checked is 3/7
@aafolabi : which one is the right scale? 1-7 or 3/7?

**Comment by pvnsprasad** [comment]
apical pubescence visual rating 0-7|CO:0000026 value is 1,2 but ontology shows 0,3,5,7
unexpanded apical leaf color visual rating 1-9|CO:0000101, This trait value should be one of 3/5/7

**Comment by aafolabi** [comment]
root neck length visual rating 0-7|CO:0000022" should be scored on a scale of 0, 3 , 5 and 7 as described. 
I think a variable has to be described for ease of peel (1,2,3).
apical pubescence visual rating 0-7|CO:0000026 : The scale of measure remains 0/3/5/7. The field technician used 0/1/2 (0= absent; 1 = Moderate (same as 5) and 2 = Highly Pubescence ( same as 7)without considering the ontology. I think you may have to convert to this scales of measurement.

unexpanded apical leaf color visual rating 1-9|CO:0000101 : It remains 3/5/7/9

The variable names showing "1-9" is at the requirement of the CO guys.

**Comment by aafolabi** [comment]
Ease of peel with scale 1,2 and 3 have been created (CO:0000308). Apical pubescence with scale 0,1,2 also created (CO:0000309). All other variables remain unchanged @bauchetg @pvnsprasad

**Comment by bauchetg** [comment]
apical pubescence visual rating 0-7|CO:0000026 value is actually 0,1,2 but ontology shows 0,3,5,7

**Comment by aafolabi** [comment]
CO:0000309 apical pubescence visual rating 0-2 created.
