### ISSUE TITLE
improve error handling in cross creation tool

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#830]
Cross creation can fail due to a parent not being recognized in the database, and an alert may be triggered, but the working modal still locks the UI. We should improve this error feedback, dismiss the midal, and maybe even copy the add trial tool and verify stock lists when they are selected, before the create cross button is clicked.

**Comment by lukasmueller** [comment]
I assume this has been resolved?

**Comment by titima15** [comment]
Resolved
