### ISSUE TITLE
t/SGN/Model/solGS/solGS.t does not pass using test_fixture.pl. Also should we consolidate tests?

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/sgn#837]
the test does not pass when i run:
perl t/test_fixture.pl t/SGN/Model/solGS/solGS.t

Is this test normally run in another way?

Should we consolidate tests into t/unit/, t/unit_fixture/, and t/selenium2 for easier testing?

The distinction between the three is:
1) t/unit/ covers tests that do not use the database or web services.
2) t/unit_fixture/ covers tests on backend objects that use the database and also covers web catalyst controllers, including ajax controllers. Web service calls can be quickly tested here.
3) t/selenium2/ covers tests on the user interface and is useful for testing javascript. These have fallen out of use because of the recent extreme slowness of selenium.

Then each of the 3 different test types can be run using:
perl t/test_fixture.pl t/unit/
perl t/test_fixture.pl t/unit_fixture/
perl t/test_fixture.pl t/selenium2/  #This requires selenium server running in the background as well

**Comment by isaak** [comment]
Hi Nick,

The solGS related tests are here: https://github.com/solgenomics/sgn/tree/master/t/selenium2/solgs

This will fail (because of the test data in the db): https://github.com/solgenomics/sgn/blob/master/t/selenium2/solgs/combine_trials.t

**Comment by nickmorales** [comment]
the test in t/SGN/Model/solGS/solGS.t is not empty. it seems like it would be a nice test to have in t/unit_fixture/

I consolidated the other tests https://github.com/solgenomics/sgn/pull/855

**Comment by isaak** [comment]
ah, I see that there are old tests from years ago...I will convert them to unit tests. For now, I will comment it out.

**Comment by isaak** [comment]
Done here: https://github.com/solgenomics/sgn/compare/928e1576aa18...d8dd89f96dff
