### ISSUE TITLE
relax trait validation

### ISSUE THREAD

**Issue by nmenda** [solgenomics/sgn#852]
currently adding new traits to a list is validated by checking that the relationship type to the parent is 'variable_of' 
This does not always work for the Solanaceae phenotype ontology in SGN and for CHEBI 

optional solutions
1. add a cvtermprop for allowed traits
2. add a dbprop covering entire ontologies
3. add a conf key to sgn, cassbase, excluding those from the variable_of trait validation
3. add an override function , checkbox in the trait validation pop up, allowing to create lists of traits that are not necessarily variables 
4. edit the ontologies so all traits used for phenotyping, including chebi metabolites, have a 'variable-of' relationship with a parent term

**Comment by nickmorales** [comment]
#862 is an implementation of option 4. during pheno upload there is an option to curators to bypass the variable_of requirement for traits

**Comment by nickmorales** [comment]
@nmenda maybe a conf key (option 3) is most practical. i implemented option 4, but there is still the issue that non-curator users need to be able to validate their trait lists.

**Comment by nickmorales** [comment]
@nmenda It seems that the easiest solution is to continue using the VARIABLE_OF relationship as THE indicator for traits. we just need to enforce this in the database for all trait terms, including for the chebi terms. what do you think?

**Comment by nickmorales** [comment]
seems to have been resolved with post-composing and use of variable_of in uploaded ontologies.
