### ISSUE TITLE
Genotyping trial creation: plate barcode generation

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#858]
@aco46 : An other important item is ability to join barcoding to genotyping trial plate generation, ex:
When generating a genotyping plate, be able to generate and associate a unique barcode with it.

**Comment by bauchetg** [comment]
@lukasmueller @aco46  one option to explore is inclusion of template generation from the coordinate app from KSU: http://www.wheatgenetics.org/research/12-research/software/89-coordinate

**Comment by lukasmueller** [comment]
Use project ID

**Comment by aco46** [comment]
closed via f22f71684eb75674dd4069584c7fe61e42fc7d46 and merged to master via 2bcd27f90ec532059c9efd2e0cf6fec086631315
