### ISSUE TITLE
Add Cv::Cvprop table to fixture and breeding databases

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#861]
As of now it is only available in the cxgn database, but it will be usefulfor handling postcomposing cvs in breeding databases.

**Comment by bellerbrock** [comment]
my mistake, it does exist in our dbs, just for some reason it is in the public schema in cxgn and in the sgn schema in the rest.

@nmenda Do you know if there is an important reason for this? could we move the cvprop table to the public schema in all databases to be consistent?

**Comment by nmenda** [comment]
@bellerbrock cvprop is part of chado, and needs to be in our public schema for all the databases
I'm not sure why it's in the sgn schema for some dbs
