### ISSUE TITLE
Implement new phenotyping feature using barcode labels and scanner.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#867]
Nick, Bryan and I were discussing barcode implementation on our databases. We came up with a new feature that would almost replace the field book in most cases.

The feature should involve the following steps:
- print a unique plot barcode. (the url of a plot specific phenotyping page is encoded to this barcode)
- scan the plot barcode. (you need to be online. you will be directed to a plot phenotyping page)
- There will be dropdown of traits to select what trait you want to phenotype for that plot.
- enter a phenotype value for that plot for selected trait. (you can phenotype for more than one trait 
   for that plot within that page)
- no further action is required the phenotypes are saved automatically for that plot.
- exit that page and scan the next plot to continue phenotyping.

This is definitely an option what exploring and we think breeders would love it.

**Comment by nickmorales** [comment]
We could have a data collection page that could be reached from several end points.
One could be through a barcode URL like you described above.
One could be through a link on the trial detail page. Then the user could just cycle through plots/plants and enter phenotypes directly.
Would enable the user to immediately have access to any analysis tools after they phenotype a field.
