### ISSUE TITLE
fuzzy search output specify accession name status

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#871]
While getting search outputs from the accession list submitted, we can obtain multiple names matching with the database. Some are stock names other are synonyms. T
Could we display this information? (like color code, or simply "stock name", "synonym")

**Comment by bauchetg** [comment]
To check which fuzzy search match may correspond to the query
have ability to copy-paste the fuzzy search outputs (not possible from the drop down it seems).
or 
have hyperlinks that can open the specific stock page would  help to know which close synonym is the one to associate with.
or
download the list (see #789)

**Comment by nickmorales** [comment]
#1004 allows fuzzy result to be downloaded and the fuzzy search output now differentiates synonym matches.
