### ISSUE TITLE
tag accession to the institute it belongs to...

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#875]
This is a known problem and it may have been addressed earlier but can t find related issue or proposed solution.
-Accession could be assign by default to an institute through the stock owner/curator who uploaded it and its affiliation/role in the DB.
-It could help clarifying some cases where accession occur multiple time, loaded by different user especially for germplasm collections and material transfer from IITA to NARS for example.
-Assigning Institutes is less constraining than location and could help differentiate confusing accession naming in the database.
Any other idea?

**Comment by nickmorales** [comment]
3f0158a384b95b22403600f49f9ce6e9e4e51d7b
