### ISSUE TITLE
curate cassavabase user accounts 

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#892]
many duplicates need to be removed

**Comment by pvnsprasad** [comment]
Guillaume, attached is the list of possible user duplicates 
[Cassavabase_Users.xlsx](https://github.com/solgenomics/sgn/files/816606/Cassavabase_Users.xlsx)

**Comment by lukasmueller** [comment]
Fixed all the duplicate role attributions, but a lot of duplicate accounts remain. We need an account merge feature, probably as a back end script.
