### ISSUE TITLE
add fieldbook template specific to crossing experiments (IITA)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#898]
IITA uses a different fiedlbook layout when collecting crossing experiments.
Instead of the usual template:
-plot_id	
-range
-plant
-plot
-rep	accession
-is_a_control

It uses the following:
-SortingNr (= ordered Plot Number in serpentine)
-plot_name ( =plot ID)
-accession
-pedigree
-plot_no
-is_a_control

**Comment by lukasmueller** [comment]
Sent an email to Peter to ask for a sample file as per discussion with Smith at IITA.

**Comment by lukasmueller** [comment]
Is this still needed with Intercross? Maybe we can close this ticket?

**Comment by lukasmueller** [comment]
Titima, can this be considered closed at this point or is this still in the works?

**Comment by titima15** [comment]
We probably can leave this ticket open for now.

**Comment by lukasmueller** [comment]
User should use Intercross app for tracking crossing.
