### ISSUE TITLE
Add support for split plot design

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#916]

**Comment by bauchetg** [comment]
also requested by CNRA for yam, available in agricolae
design.split(trt1, trt2,r=NULL, design=c("rcbd","crd","lsd"),serie = 2,
seed = 0, kinds = "Super-Duper", first=TRUE,randomization=TRUE)

**Comment by nickmorales** [comment]
"splitplot" stocktype implemented in a way similar to "plant" stocktype

**Comment by lukasmueller** [comment]
created branch topic/split_plot_designs

**Comment by nickmorales** [comment]
@lukasmueller should we use topic/split_plot_designs? i don't see it in github

**Comment by nickmorales** [comment]
@bellerbrock is it of interest to collect phenotypes on the "subplot" level? (in a way similar to the plant level)

**Comment by nickmorales** [comment]
#1266
