### ISSUE TITLE
Need for Lattice design (different from  alpha-lattice)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#924]
Current implementation uses alpha lattice:
design.alpha(trt, k, r, serie = 2, seed = 0, kinds = "Super-Duper",randomization=TRUE)

Yam breeding request a lattice type (single or triple).
This can be covered by the design.lattice function from Agricolae:
design.lattice(trt, r=3, serie = 2, seed = 0, kinds = "Super-Duper",randomization=TRUE)

**Comment by aco46** [comment]
close via 1b7a8cca331412bdae681794de85716450567baa
