### ISSUE TITLE
Pedigree download should include pedigree information of multiple generations for an accession.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#935]
David De Koeyer has requested that breeders would want to see pedigree information for multiple generations for any accession if the information is available in the database.

-Current implementation only retrieves the immediate parents of an accession.

**Comment by pvnsprasad** [comment]
Alex, we have currently pedigrees for immediate parents and Grandparents, but Grandparents seems to be not working if we have greatgrandparents. but the pedigree tree shows you the complete pedigree information.


![pedigree](https://cloud.githubusercontent.com/assets/12831484/24552106/1f78a25e-161d-11e7-9fef-a88b832019cd.png)

**Comment by aco46** [comment]
@pvnsprasad : Thanks for the info. What David was referring to is the ability to download not just the immediate parents but grandparents and great grandparents if available while downloading pedigrees using list of accessions.
