### ISSUE TITLE
phenotyping excel sheet does not upload

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#946]
As reported by Rachael. I have the file that she used and ran into problems with. Unfortunately, Github doesn't allow to attach .xls files.

**Comment by nickmorales** [comment]
Hi Lukas can you send me her file through email/slack?

**Comment by bauchetg** [comment]
@nickmorales Here is the file (@lukasmueller git supports .xlsx but not .xls)
[Phenotypes_Final_Arua_Season22014.xlsx](https://github.com/solgenomics/sgn/files/902904/Phenotypes_Final_Arua_Season22014.xlsx)

**Comment by nickmorales** [comment]
File was corrupted.

**Comment by bauchetg** [comment]
[error] Caught exception in SGN::Controller::AJAX::PhenotypesUpload->upload_phenotype_verify_POST "Can't open file  at lib/CXGN/UploadFile.pm line 126."

**Comment by bauchetg** [comment]
@nickmorales I tried to reformat the file, save it again, etc...without success. File is enclosed below
[Phenotypes_Final_Kabarole4.xlsx](https://github.com/solgenomics/sgn/files/911406/Phenotypes_Final_Kabarole4.xlsx)

**Comment by nickmorales** [comment]
this sounds like its due to a file directory not being found. maybe related
to the power outage/ unmounting of drives. what site was this on?


On Mon, Apr 10, 2017 at 4:39 PM, Guillaume Bauchet <notifications@github.com

**Comment by bauchetg** [comment]
Fixed by Nick and Lukas. Error due to power outtage:
trying to save the file to /export/prod/archive/cassavabase/482/spreadsheet_phenotype_upload/2017-04-10_20:44:44_Phenotypes_Final_Kabarole4.xlsx but directory not found
