### ISSUE TITLE
add grafting as cross type in cassava

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#949]
For several flowering experiments grafting is been used (and can be used in other crops), following this format: ParentA (rootstock) and ParentB (scion).

**Comment by bauchetg** [comment]
stock_relationship: scion_of  or rootstock_of 
stock_prop: graft

**Comment by rachealmukisa** [comment]
stock_prop should be one of the 4 grafting methods mentioned in #950

**Comment by nmenda** [comment]
we will store the grafting method in stock_relationship.value 
We do the same for cross types (open, self, biparental)

**Comment by rachealmukisa** [comment]
The types for the grafting experiment are WEDGE, WHIP, NONGRAFTED.

**Comment by nmenda** [comment]
stock type for the graft will be 'grafted_accession'
stock_relationship object = the grafted_accession  subject1 = rootstock subject2 = scion  ; needs to be consistent with the pedigrees - consider modifying for the entire database 

stock_relationship.type_id = rootstock_of, scion_of 
stock_relationship.value stored for subject_id = scion accession, value = wedge or whip

nd_experiment.type_id = grafting_experiment. Will produce one new stock of type 'grafted_accession'

Trials
project.type_id 
 * crossing_trial  - no need for layout , used just for grouping when the plants are used uniquely for crossing
 * grafting_trial
 * pollinating_trial

User interface - for loading grafting experiments add different tabs for each 'crossing' type . 
 * crossing
 * grafting 
 * transformation
Add option to group 'crosses' into a trial (currently can group into a folder only)

**Comment by nmenda** [comment]
pull request
https://github.com/solgenomics/sgn/pull/1152

**Comment by bauchetg** [comment]
@rachealmukisa could you detail the difference between pollinating_trial and crossing_trial?
From what I understand crossing_trial would be for crossing made in crossing block activity and "pollinating_trial" would be for opportunistic crosses done on regular trials? can you confirm?
If so from the database side these two terms could be just one maybe. Just let us know
