### ISSUE TITLE
trial tree doesnt load in cassavabase

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#955]
![Uploading Screen Shot 2017-04-10 at 9.58.30 AM.png…]()

**Comment by aco46** [comment]
It's in all databases. I've seen it in Yambase as well.

**Comment by pvnsprasad** [comment]
It works now in cassavabase.org, I refreshed it.

**Comment by bauchetg** [comment]
Same here, thanks @pvnsprasad

**Comment by aco46** [comment]
Still not working in yam test.
