### ISSUE TITLE
Trial upload error

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#958]
Looks like the temporary directory where uploaded files are called from is not yet mounted.

![upload_error](https://cloud.githubusercontent.com/assets/10618260/24955026/46aeec2c-1f71-11e7-96ff-bde90e7121da.png)

**Comment by nickmorales** [comment]
need to check sgn_local.conf on every site to check the archive path points to /export/prod/archive/SITENAME

**Comment by aco46** [comment]
Added 'archive_path     /export/prod/sgn_archive' to the sgn_local.conf 
-done only for yambase test.
