### ISSUE TITLE
 Breeding program and user roles: some roles missing?

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#959]
@nickmorales 

From Racheal: when trying to move files from the 5CP program to other folders in NACRRI folders, we got this error: "An error occurred trying to associate a folder to the trial."
If I try to move the trial to a different subfolder within the 5CP main folder the same error would occur.
 
After looking at user roles I noticed we only have, these:
 sp_role_id |   name    
------------+-----------
          5 | IITA
          1 | curator
          2 | sequencer
          3 | submitter
          4 | user
          6 | NRCRI
          8 | CIAT
          7 | NaCRRI
          9 | CNRA_PRT

-How other existing programs such as 5CP can be administrated?
-Maybe we  shall have a user role definition for each breeding program when being created?

From the log I get:
[error] Caught exception in SGN::Controller::AJAX::TrialMetadata->get_trial_folder "Can't call method "get_folder" on an undefined value at lib/SGN/Controller/AJAX/TrialMetadata.pm line 289."
Use of uninitialized value in sprintf at lib/SGN/Controller/AJAX/Stock.pm line 1369.

Something to do with the project_parent ID it seems.

**Comment by bauchetg** [comment]
A similar issue appears on musabase-test when assigning a role to a user

[error] Caught exception in SGN::Controller::AJAX::People->add_person_role_GET "Can't call method "check_roles" on an undefined value at lib/SGN/Controller/AJAX/People.pm line 89."

<img width="512" alt="image" src="https://cloud.githubusercontent.com/assets/12039071/25235978/5b210d14-25ef-11e7-9068-cbde35efe0ea.png">

**Comment by bauchetg** [comment]
added a role for "5CP" in cassavabase, maybe a role creation should be a feature when creating a new breeding program?

**Comment by lukasmueller** [comment]
Create new roles when a new breeding program is created.... there was a ticket for that...

**Comment by bauchetg** [comment]
in "sgn_people.sp_person_roles" the "user_type " column include both user roles (curator, submitter, ,etc...) and breeding program/institutes a user if affiliated to.
With the growing number of breeding programs, it may be useful to segregate roles and affiliation in distinct columns so that a user can upload data or can be curator only for a specific program.

**Comment by bauchetg** [comment]
see issue #1131 for follow up
