### ISSUE TITLE
pedigree upload crashes when multiple uniquename(s)

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/sgn#961]
from Prasad:
uploading pedigree file with stock name occurring multiple times gives an error.
Do we expect mutiple stock_id with same uniquename   in stock table? 
like:
cxgn_cassava=# select * from stock where name='IITA-TMS-IBA061679';
 stock_id | dbxref_id | organism_id |        name        |     uniquename     | description | type_id | is_obsolete 
----------+-----------+-------------+--------------------+--------------------+-------------+---------+-------------
   504184 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f
   504183 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f
   504182 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f
   504181 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f
   504180 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f
   504179 |           |             | IITA-TMS-IBA061679 | IITA-TMS-IBA061679 |             |   76441 | f

![screen shot 2017-04-12 at 6 54 04 pm](https://cloud.githubusercontent.com/assets/12039071/24972713/59aebbb6-1fb4-11e7-9559-9748b62345ff.png)
[test_pedigree_error.txt](https://github.com/solgenomics/sgn/files/917464/test_pedigree_error.txt)

**Comment by bauchetg** [comment]
An other example of the same problem when multiple populations are associated to the uniquename:
cxgn_cassava=# select * from stock where uniquename = 'IITA-TMS-IBA011412';
 stock_id | dbxref_id | organism_id |        name        |     uniquename     | description | type_id | is_obsolete 
----------+-----------+-------------+--------------------+--------------------+-------------+---------+-------------
   504138 |           |             | IITA-TMS-IBA011412 | IITA-TMS-IBA011412 |             |   76441 | f
   504137 |           |             | IITA-TMS-IBA011412 | IITA-TMS-IBA011412 |             |   76441 | f
   504136 |           |             | IITA-TMS-IBA011412 | IITA-TMS-IBA011412 |             |   76441 | f
   504104 |           |             | IITA-TMS-IBA011412 | IITA-TMS-IBA011412 |             |   76441 | f
   504097 |           |             | IITA-TMS-IBA011412 | IITA-TMS-IBA011412 |             |   76441 | f
     1281 |           |           5 | TMS-I011412        | IITA-TMS-IBA011412 |             |   76392 | f

Only one accession is there an the rest is population entries (76441)

Mentioned in #1069 by @titima15  as well

**Comment by bauchetg** [comment]
The new pedigree upload process check for an accession name which present twice but would return successful upload even if one parents is actually not associated.
The error log reflects well the problem but this transparent to the user, here is an example:
If we check "T1484" on musabase-test it only shows "Calcutta 4" as parent but not "Zebrina GF" which turns to be twice in the DB.

ARCHIVED: /export/prod/sgn_archive/71/pedigree_upload/2017-08-14_15:36:41_pedigreefileup2.txt
Performing database operations... 
Done.
Accession name (Tjau Lagada) is not a unique stock unqiuename or synonym
Performing database operations... 
Accession name (Zebrina GF) is not a unique stock unqiuename or synonym
Creating pedigree biparental, T1484
Transaction error creating a cross: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "stock_relationship_c1"
DETAIL:  Key (subject_id, object_id, type_id, rank)=(40338, 83177, 76437, 0) already exists. [for Statement "INSERT INTO stock_relationship ( object_id, subject_id, type_id, value) VALUES ( ?, ?, ?, ? ) RETURNING stock_relationship_id" with ParamValues: 1='83177', 2='40338', 3='76437', 4='biparental'] at lib/CXGN/Pedigree/AddPedigrees.pm line 136

**Comment by nickmorales** [comment]
pedigree upload allows "update" of female/male parent. essentially this means deleting the previous female/male parent and linking the new female/male parent indicated in the file.

**Comment by nickmorales** [comment]
@bauchetg was this fixed?

**Comment by nickmorales** [comment]
I helped Violet out today with her upload. the issue was that she was
"updating" pedigrees in the database (their mother and/or father), but she
was not clicking on the "Update pedigree" checkbox.

On Mon, Apr 16, 2018 at 4:21 PM, Guillaume Bauchet <notifications@github.com

**Comment by lukasmueller** [comment]
I am closing this ticket then...
