### ISSUE TITLE
wizard genotype data download format 

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#964]
The headers on the genotype data downloaded from the wizard have formatting issues. Reading it to R  shows the following message:
https://gist.github.com/isaak/c92667640b5bb37469df9f3e591dbf35

hint: the space between the 'Marker' and next header might not be a tab...

**Comment by bellerbrock** [comment]
Hi Isaak, I don't think this is a character issue -  I see only tabs in the header when I show invisible characters in geno download files. 

I'm testing with an example file from the fixture, and haven't been able to reproduce the error with the same command:

```
gt <- fread("6genotypes-p1.txt", na.strings = c("NA", " ", "--", "-", "."))
```

Would it be possible to share the genoDataFile2 reference in your gist, or a list of the accessions it should have genotypes for? My best guess is that the header may get messed up when accessions have multiple genotypes stored.

**Comment by bellerbrock** [comment]
Hi @isaak, I realize I didn't tag you in this before - any chance you could still send me the file you were working with when you encountered this error?

**Comment by bellerbrock** [comment]
Hi @isaak, do you still have that file? I can't work on this issue without reproducing it first.

**Comment by bellerbrock** [comment]
Closing as not reproducible . . .
