### ISSUE TITLE
Enable IITA crossing experiments to be uploaded in bulk

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#970]
The process uses a combination of the Android Fieldbook and Excel sheets, but it is not clear how they work together. Need to clarify.

**Comment by lukasmueller** [comment]
[Template used for crosses.xlsx](https://github.com/solgenomics/sgn/files/925404/Template.used.for.crosses.xlsx)

**Comment by bauchetg** [comment]
This may clarify:
From the enclosed file below

--Inputs (2 files):
1- layout file for the Filedbook:
plot_name
group_number
tag_number

2- Traits file that may contains traits such as:
female
male
bags
no of flowers pollinated
Total no of flowers pollinated
no of fruit set
no of seed

--Output file from FieldBook would contain following columns :
trial
date
female
male
bags
no of flowers pollinated
Total no of flowers pollinated
no of fruit set
no of seed

**Comment by aafolabi** [comment]
Need for a "Pollination" trial type to group nd_experiment.
Ability to add property to nd-experiment after saving
Ability to add number of progenies much later after knowing the number seed germinated.

**Comment by bauchetg** [comment]
@titima15 
I enclose my notes here 
[crossing_tool_discussion.pdf](https://github.com/solgenomics/sgn/files/1183907/crossing_tool_discussion.pdf)
crossing block and seedling nurseries have different templates (included on slide 17)
A seedling nursery ID is specifically generated and should be linked to "plot_name" (you crossing name) from the crossing block.
The naming structure should follow soemthig like:
location-SN-year-plotnumber 
ex: IBASN161001

**Comment by titima15** [comment]
If there are two parts with different IDs (names), the pollination experiments probably will not use cross name then, the cross name will be used for the second part when plant breeders enter progenies.

**Comment by titima15** [comment]
Done. Closed via a0f2873
