### ISSUE TITLE
Duplicate perl package name

### ISSUE THREAD

**Issue by isaak** [solgenomics/sgn#982]
~/cxgn/Phenome/lib/CXGN/Genotype/Search.pm
~/cxgn/sgn/lib/CXGN/Genotype/Search.pm

Depending on the queueing of the libs in one's search path, this causes problems...e.g. not finding object methods...

**Comment by lukasmueller** [comment]
removed duplicate file from Phenome lib in commit 6045fb507c4cf9798f3a74d8aac920699633e4ce.
