### ISSUE TITLE
Error submitting request with contact form.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#984]

**Comment by lukasmueller** [comment]
The contact form now depends on a GitHub access token. This was added in SGN but not in any of the other databases, so the contact form was broken on them. The GitHub access token was added to all the sgn_local.conf sites. (maybe should be added to sgn.conf?)

**Comment by nickmorales** [comment]
Sorry forgot to add that to all the sites. Its not a good idea to add to
sgn.conf since that is essentially a password to a github account

**Comment by aco46** [comment]
Github access token added for yam and cassava test.
