### ISSUE TITLE
Add the ability to delete an image associated with a stock.

### ISSUE THREAD

**Issue by aco46** [solgenomics/sgn#985]

**Comment by nmenda** [comment]
@aco46 do you have an example for a stock where you want to do this ?

**Comment by aco46** [comment]
@nmenda: it should be the actual image associated to a stock. In a situation where a user decides to delete an image, such option should make it possible.

**Comment by lukasmueller** [comment]
It would be preferable that the image association would be removed as the image can be associated with other items, such as organisms, plots, etc.
