### ISSUE TITLE
create new repo for standalone sgn environment

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#995]
The idea is for this to be a pared down version of the development vagrant, but with more extensive documentation for users unfamiliar with sgn. 

BY May 20th the goal is to to have it compliant with [AgBioData DB Recommendations](https://docs.google.com/spreadsheets/d/10xhQJbdeZT6ROOOHSR7YBU6t-KHNhtu-QjN_9PrD68A/edit?usp=sharing)

This would be the first step in the process of making it easy to discover and install an sgn database without extensive in-person support. The next might be adding a demo site and documentation at a central launching page, like rtbbase.org. The end goal is to have something along the lines of what Tripal has [here](http://tripal.info/)

**Comment by bellerbrock** [comment]
Also, a catchy name for the generic sgn/rtbbase environment?

**Comment by nickmorales** [comment]
The Docker deployments accomplish this now
